### ISSUE TITLE
Off (Disabled) Line Icon

### ISSUE THREAD

**Issue by xaviergonz** [Templarian/MaterialDesign#1021]
An Icon that is just basically the " \ " line used for off/disabled icons in order to overlay them over icons that don't support that variant out of the box.

And example of such line can be seen here.
https://materialdesignicons.com/icon/eye-off

**Comment by CoDEmanX** [comment]
The problem here is that it's not just a diagonal line. There's a counter stroke which is subtracted from the underlying icon, and you can't really do that by just stacking multiple icons.

It's possible if your website uses a solid background color however. You would set the color of the counter stroke to the same color. But it doesn't work on any other backgrounds.

With inline SVG code, it might be possible. I think there's some support for clipPaths... 

One final thing to consider: not every "off" line is identical. Some icons require shorter or longer strokes (see e.g. https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-152349331 cast-off), or even slightly different positioning (see https://github.com/Templarian/MaterialDesign/issues/783#issue-114100901 and https://github.com/Templarian/MaterialDesign/issues/820#issuecomment-155521475).

**Comment by Templarian** [comment]
Yea, sorry I'm actually going to advise against this. Please open an issue for any icon you feel needs an off state. As @CoDEmanX explained while we use a template for the slash for consistency there are a lot of icons where the slash is slight modified for a better look.

The webfont accounts for an okay number of users, but I would rather individually design glyphs since many users are consuming the icons in other ways.
