### ISSUE TITLE
Friends Icon

### ISSUE THREAD

**Issue by Darwesh27** [Templarian/MaterialDesign#107]
Icon for friends. There is a multiple accounts icon already there which can be used as an alternative but I guess there could be something cooler.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/account-multiple

That would be the correct one to use. Sometimes adding variants on icons creates confusion when trying to follow the style. Mostly because Material Design relies on geometric shapes.

The lack of finite detail does make the icons ideal for various uses outside of a single use case.
