### ISSUE TITLE
yoga

### ISSUE THREAD

**Issue by bandna22** [Templarian/MaterialDesign#1089]
Icon for Yoga

**Comment by CoDEmanX** [comment]
Google Fit has one as reference (smaller than regular MD icons though)

**Comment by goyney** [comment]
I wouldn't say this is a Google stock icon, because the only place it can be found is in the Fit app and it is this big, white, and in a raster format (I had to invert it to post it here):
![yoga](https://user-images.githubusercontent.com/1015040/48859851-39299c00-ed8d-11e8-9d30-80fc6655779f.png)

I've recreated it as best as I could here:
![image](https://user-images.githubusercontent.com/1015040/48859685-c1f40800-ed8c-11e8-927e-a94966e35e35.png)

[yoga.zip](https://github.com/Templarian/MaterialDesign/files/2605296/yoga.zip)

**Comment by goyney** [comment]
For reference, here is the Google Fit version:
![image](https://user-images.githubusercontent.com/1015040/48975348-06f19600-f03c-11e8-99ba-fe2d8a8d4bc4.png)

[google-fit-yoga.zip](https://github.com/Templarian/MaterialDesign/files/2612828/google-fit-yoga.zip)

**Comment by JamesCoyle** [comment]
We probably wanna use `human` as the base for these:
[![](https://materialdesignicons.com/icon/human)](https://materialdesignicons.com/icon/human)

**Comment by CoDEmanX** [comment]
6dp wide makes it look fat...

![grafik](https://user-images.githubusercontent.com/1309249/63231554-a0da1e00-c21d-11e9-99ed-eaba81557009.png)

and because the body is twisted, it actually makes for sense to have it a bit slimmer:

![grafik](https://user-images.githubusercontent.com/1309249/63231575-1514c180-c21e-11e9-97d8-d7b912a82b69.png)

[yoga3.zip](https://github.com/Templarian/MaterialDesign/files/3513687/yoga3.zip)

**Comment by goyney** [comment]
[![yoga](https://materialdesignicons.com/icon/yoga)](https://materialdesignicons.com/icon/yoga)
