### ISSUE TITLE
add-shadow icon

### ISSUE THREAD

**Issue by andyrooc** [Templarian/MaterialDesign#1119]
graphical editor icon for adding a shadow to a picture/text object

**Comment by CoDEmanX** [comment]
Some experiments:

![shadow](https://cloud.githubusercontent.com/assets/1309249/14412517/d46dcd9a-ff64-11e5-97b7-df69b3ceae10.png) ![shadow2](https://cloud.githubusercontent.com/assets/1309249/14412518/d486b3dc-ff64-11e5-8a3f-c4d3f5b02871.png) ![shadow3](https://cloud.githubusercontent.com/assets/1309249/14412522/d49241ca-ff64-11e5-8584-37ae0171fba3.png) ![shadow4](https://cloud.githubusercontent.com/assets/1309249/14412519/d491b6d8-ff64-11e5-9509-9c1832431f17.png) ![shadow5](https://cloud.githubusercontent.com/assets/1309249/14412521/d49241b6-ff64-11e5-8ce1-e0a9f3a84855.png)
![shadow6](https://cloud.githubusercontent.com/assets/1309249/14412520/d491da82-ff64-11e5-800a-5c08e0cfdf17.png) ![shadow7](https://cloud.githubusercontent.com/assets/1309249/14412523/d493ae5c-ff64-11e5-853c-de3fdfaf7105.png)
![shadow8](https://cloud.githubusercontent.com/assets/1309249/14412524/d4a151b0-ff64-11e5-9323-cc96f3b54627.png) ![shadow9](https://cloud.githubusercontent.com/assets/1309249/14412525/d4ad244a-ff64-11e5-9698-e27687c2deee.png)

**Comment by Templarian** [comment]
[![text-shadow](https://materialdesignicons.com/icon/text-shadow)](https://materialdesignicons.com/icon/text-shadow) [![box-shadow](https://materialdesignicons.com/icon/box-shadow)](https://materialdesignicons.com/icon/box-shadow)

Added a similar `box-shadow`. While I like the 2nd T icon, I was 50/50 on adding it due to it not being flat.
