### ISSUE TITLE
Downhill ski and snowboard icons

### ISSUE THREAD

**Issue by cmunter** [Templarian/MaterialDesign#1156]
Icon request for downhill (alpine) skiing and snowboard

**Comment by goyney** [comment]
#3543 and #3539 duplicate this issue. Typically, I would close those as duplicates since they are newer, but we're trying to maintain individual issues for each icon request and those two issues also have example images in them. Therefore, I'm going to close this one. Please follow those two issues for when they are added. Thanks!
