### ISSUE TITLE
Factories

### ISSUE THREAD

**Issue by kentonbmax** [Templarian/MaterialDesign#1161]
First off, factory smoke stack needs smoke... I know smoke is bad but its a major identifying characteristic. 

I work for manufacturing company currently and would like to see the following:
I would like to see a whole series of factories with small icons in the center, Lightning bolt - factory power, wrench - factory-maintenance, '+'/'-' add/remove site or add factory, and heart factory health. Also need a conveyor with a box on it. Really the conveyor is for worker assembly line. Could also apply the factory sub-icon suggestions above. 

![image](https://cloud.githubusercontent.com/assets/15804484/14469776/3ff5c0fe-00b4-11e6-9614-32b3493d5dfc.png)

more examples
http://cache4.asset-cache.net/gc/521366929-manufacturing-icons-black-series-gettyimages.jpg?v=1&c=IWSAsset&k=2&d=ssPi9roR8ENYA7ixZMvIVCnjZ%2FSpR02KxgVySTGdIbOjpt1B5FebCeQIuDzkFSSV

**Comment by Templarian** [comment]
- This is a very eco-friendly factory. Material Design generally goes for the minimalist side so if it is identifiable without extra details we generally leave it out.
- I like the idea of a box moving across a factory belt (great for first-in-first-out type displays). Any idea what this should be called? `first-in-first-out` `last-in-first-out`.
- I usually try not to add +/- to various icons. This is one of the use cases where it may be too specific.
- `factory-power` actually sounds good to signify a factories' power status.
- Due to the size `factory` + `wrench` might be difficult.

**Comment by kentonbmax** [comment]
My opinion on the factory is the it has windows; I would rather have a solid fill with smoke stack and smoke. Consider how it looks on an orange background. For the conveyor belt, I tend to think they should be named as to what they look like. Makes it easier to find. Ex. Clock, is a clock, wrench is a wrench. I would like to see conveyor  start and stop, and then one with 3 small boxes for running. You could also have a person silhouette behind it to show operator. I agree with the others.

**Comment by goyney** [comment]
Could use `smog` for the smoke stacks icon:
[![smog](https://materialdesignicons.com/icon/smog)](https://materialdesignicons.com/icon/smog)

**Comment by JamesCoyle** [comment]
Im closing this out as I feel our current factory icon should fit most use cases. We try not to add too much detail to any one icon.
