### ISSUE TITLE
Difference between page icons and package icons

### ISSUE THREAD

**Issue by kgram** [Templarian/MaterialDesign#1165]
It seems there is a difference between what icons are shown on https://materialdesignicons.com/ and what icons are included in the available package (1.5.54). Comparing the json from the webpage, yields the following:

The downloaded package has
```
white-balance-irradescent
arrow-collapse
```

Of which the first look like a spelling error.

The webpage has
```
application
arrow-compress
arrow-compress-all
arrow-expand-all
bowl
bridge
buffer
chip
content-save-settings
dialpad
dictionary
format-horizontal-align-center
format-horizontal-align-left
format-horizontal-align-right
format-vertical-align-bottom
format-vertical-align-center
format-vertical-align-top
hackernews
json
lambda
matrix
meteor
sigma-lower
source-branch
source-merge
tune
webhook
white-balance-iridescent
```

Is there a reason for this difference? When downloading the font, one would expect to get all the icons shown on the page. If they are intentionally excluded they should probably be removed from the webpage.

**Comment by PeterShaggyNoble** [comment]
I'd assume that the webfont download isn't updated for every single icon added, rather that it's updated manually after a batch of icons has been added. If you have a look at https://materialdesignicons.com/history, you can see that all the icons that are missing from the webfont download have been added since the 14th of March.

As for the differences in icon names, I'd assume they have also been updated since the webfont was last updated and will be reflected in the next update.

**Comment by kgram** [comment]
Ah, didn't know there was a log available. I assumed the format-icons must be rather old, but that doesn't appear to be the case. Nevermind then :)

**Comment by Templarian** [comment]
There is a bug I'll be fixing soon, it's not showing renames on the history page. Not sure when I broke that, but will need to fix it eventually.

**Comment by PeterShaggyNoble** [comment]
It's also not showing new releases, @Templarian; the last one shown is v1.4.57.

**Comment by Templarian** [comment]
@PeterShaggyNoble Just fixed that. Yea, that's due to me recoding how I build the webfonts (webfonts are built from a separate unicode table now allowing subfont pack generation and version tracking).
