### ISSUE TITLE
Products

### ISSUE THREAD

**Issue by AlirezaAkbarix** [Templarian/MaterialDesign#1186]
An icon that refers to products! It can be used for online shops

**Comment by Templarian** [comment]
Do you have an example (images can be pasted inline). `products` is very general.

**Comment by AlirezaAkbarix** [comment]
No! But you are genius enough to make an icon for any online stores that covers `product` meaning :)

**Comment by AustinPaquette** [comment]
@AlirezaAkbarix I'd personally use a cube for something like this (or a box since is suggests shipping something).

<https://materialdesignicons.com/icon/cube>

Depending on what the product is though a different type of icon may be necessary, your request seems a little to ambiguous since there's so many use cases for what a product may be.

**Comment by Templarian** [comment]
I think that or the `package*` icons could work well for this.
