### ISSUE TITLE
Use "backslashes" on -off icons

### ISSUE THREAD

**Issue by zesik** [Templarian/MaterialDesign#1188]
Hi,

`earch-off` and `headset-off` are using "slashes" instead of "backslashes". I think it might be a good idea if they use "backslashes" like others do for the sake of consistency.

**Comment by CoDEmanX** [comment]
That is on purpose. Important parts of the icons wouldn't be visible the other way around. You wouldn't recognize the microphone in the headset icon anymore, and the land masses in the earth icon would be pretty much erased...
The icons can't be flipped because they need to work as toggle buttons together with their "on" counterparts. It's better to flip the stroke instead, despite the inconsistency.

**Comment by Templarian** [comment]
Yep, as Cody said above this was a conscious decision for these two icons.
