### ISSUE TITLE
Ask for 'checkbox-multiple-marked-circle-outline'

### ISSUE THREAD

**Issue by dGorod** [Templarian/MaterialDesign#1196]
Hello!
First, thank you for great icons!

Austin Andrews draw icons "checkbox-multiple-marked" and "checkbox-multiple-marked-outline".
But they all rectangular and I'm using in app circle variant of checkboxes. Could you, please, add also circle variant of multiple boxes icon? 
Thanks.

**Comment by CoDEmanX** [comment]
We have an alarm-multiple icon, so it's fair to ask for this icon.

It had to adjust the shorter stroke of the checkmark (make it 1px shorter) and also the upper circle opening, so that it lines up with the now shorter checkmark stroke. The "shadow" circle at a 45° angle looks odd though:

![checkbox-multiple-marked-outline-multiple2](https://cloud.githubusercontent.com/assets/1309249/14871242/b89b892a-0ce0-11e6-9aaf-472d8de9401d.png)

I thus used the same positioning as seen in alarm-multiple, and it works really well in the small rendering:

![checkbox-multiple-marked-outline-multiple](https://cloud.githubusercontent.com/assets/1309249/14871241/b89ab5d6-0ce0-11e6-928f-9ecf8fc39165.png)

It looks slightly odd at very large sizes, but not a hindrance IMO:

![checkcircle_xxl](https://cloud.githubusercontent.com/assets/1309249/14871366/b2dc7264-0ce1-11e6-8a0b-b2bf228b2021.png)

**Comment by CoDEmanX** [comment]
The filled version requires a different positioning of the checkmark:

![checkbox-multiple-marked-multiple](https://cloud.githubusercontent.com/assets/1309249/14871556/96a4bc62-0ce3-11e6-89b4-4fcd245d5f31.png) yuck... ![checkbox-multiple-marked-multiple2](https://cloud.githubusercontent.com/assets/1309249/14871558/96a6f338-0ce3-11e6-86ca-9b7142554920.png) much better!

This means the filled and the outline version can't be used for hover effects, as the checkmark would "jump".

We should add the base shapes too of course: ![checkbox-multiple-multiple](https://cloud.githubusercontent.com/assets/1309249/14871559/96a88162-0ce3-11e6-9691-a3e6fa9d6639.png)  ![checkbox-multiple-multiple-outline](https://cloud.githubusercontent.com/assets/1309249/14871557/96a54bf0-0ce3-11e6-8652-bcea9afc0af4.png)

**Comment by Templarian** [comment]
Can you share the files for these. Agreed these would be a nice addition.

**Comment by CoDEmanX** [comment]
I also included icons from other icons for consideration. Their issue numbers are in file names:
https://www.dropbox.com/s/efdjntanj9lozsl/2016-04-28_Conversion.zip?dl=0

**Comment by Templarian** [comment]
In this scenario the hover issue isn't as big of a deal, so included is the one that looks nicer.

[![checkbox-multiple-marked-circle-outline](https://materialdesignicons.com/icon/checkbox-multiple-marked-circle-outline)](https://materialdesignicons.com/icon/checkbox-multiple-marked-circle-outline) [![checkbox-multiple-marked-circle](https://materialdesignicons.com/icon/checkbox-multiple-marked-circle)](https://materialdesignicons.com/icon/checkbox-multiple-marked-circle) [![checkbox-multiple-blank-circle-outline](https://materialdesignicons.com/icon/checkbox-multiple-blank-circle-outline)](https://materialdesignicons.com/icon/checkbox-multiple-blank-circle-outline) [![checkbox-multiple-blank-circle](https://materialdesignicons.com/icon/checkbox-multiple-blank-circle)](https://materialdesignicons.com/icon/checkbox-multiple-blank-circle)
