### ISSUE TITLE
Bomb icon

### ISSUE THREAD

**Issue by gabrielmoral** [Templarian/MaterialDesign#1212]
I would like one like this:

http://iconshow.me/bomb

Thanks!

**Comment by TheManuz** [comment]
Done it!
![bomb_24px](https://cloud.githubusercontent.com/assets/2032334/15361714/ef3a7a9e-1d12-11e6-809d-26e12b90df10.png)
[Bomb_24px.svg.zip](https://github.com/Templarian/MaterialDesign/files/270663/Bomb_24px.svg.zip)

**Comment by Templarian** [comment]
@TheManuz Nice, but can you make it a little more [Material Design](https://www.google.com/design/spec/style/icons.html#icons-system-icons). I think there can be a design that has a 2px fuse or variation that fits.

**Comment by TheManuz** [comment]
I know about the 2dp rule for strokes in Material Design, I made it purposefully of 1dp because i thought i would damage readability. Also, in Material Design specification, on the **optical corrections** section, there is the paperclip example where it uses a 1.5dp stroke.

So i attach a 2dp fuse version and a 1.5dp fuse version. I think the 1.5dp version is the best.
However choose the one that you think is the best.

# 1DP (for reference)
![bomb_24px](https://cloud.githubusercontent.com/assets/2032334/15447805/73550cf8-1f4e-11e6-9957-2b1daeef1367.png)
![bomb_24px 2x](https://cloud.githubusercontent.com/assets/2032334/15447806/76208804-1f4e-11e6-962b-a81d58ab9178.png)
![bomb_24px 4x](https://cloud.githubusercontent.com/assets/2032334/15447807/7836dbb6-1f4e-11e6-97c1-e179b36298fa.png)

# 1.5DP
![bomb_1 5_24px](https://cloud.githubusercontent.com/assets/2032334/15447793/2d4cba94-1f4e-11e6-98d2-8273c1c297c1.png)
![bomb_1 5_24px 2x](https://cloud.githubusercontent.com/assets/2032334/15447795/309399ac-1f4e-11e6-87b0-539d1d147fe7.png)
![bomb_1 5_24px 4x](https://cloud.githubusercontent.com/assets/2032334/15447796/33b6d4dc-1f4e-11e6-8923-b01de196ab3a.png)

# 2DP
![bomb2_24px](https://cloud.githubusercontent.com/assets/2032334/15447817/c5046670-1f4e-11e6-89ad-e91b9c0c9eb9.png)
![bomb2_24px 2x](https://cloud.githubusercontent.com/assets/2032334/15447819/c84db156-1f4e-11e6-8db0-aa331aed21e2.png)
![bomb2_24px 4x](https://cloud.githubusercontent.com/assets/2032334/15447820/cc395cfc-1f4e-11e6-8a9c-b2fc24a1b1d4.png)

# SVG
[Bomb_24px_versions.zip](https://github.com/Templarian/MaterialDesign/files/275826/Bomb_24px_versions.zip)

**Comment by OlsonDev** [comment]
I like the 1.5dp one too. But, what's with the tip of the wick? It has some jaggy on its top left corner.

**Comment by OlsonDev** [comment]
Also guessing the shape would be recognizable without the reflection.

**Comment by TheManuz** [comment]
@OlsonDev I'm not sure if I understood the jaggy you're referring to. However i'm going to remove the reflection. Thinking again it gives the bomb a 3D look, which is not very material.

**Comment by CoDEmanX** [comment]
I added a reflection to https://materialdesignicons.com/icon/kettle because it wasn't very recognizable without. In case of the bomb I'm not sure.

The jaggy part:

![bomb_jaggy](https://cloud.githubusercontent.com/assets/1309249/15464175/01185a4c-20ce-11e6-865a-73a2354ba67c.png)

It could be solved like this:

![bomb1](https://cloud.githubusercontent.com/assets/1309249/15464884/f7a964f2-20d1-11e6-8936-4cc414165535.png) ![bomb1_96](https://cloud.githubusercontent.com/assets/1309249/15464883/f7a8493c-20d1-11e6-8b60-1b4e950cd31d.png)
![bomb2](https://cloud.githubusercontent.com/assets/1309249/15464885/f7aab5b4-20d1-11e6-9caf-5e4b1a6de6fc.png) ![bomb2_96](https://cloud.githubusercontent.com/assets/1309249/15464886/f7af6e6a-20d1-11e6-99bd-e9d0835c61bb.png)

**Comment by TheManuz** [comment]
@CoDEmanX oh, I understand now! That was done purposefully, but I can remove the diagonal cut.

# 1.5DP

- no shine
- no diagonal cut
- sparks are more distant from each other

![bomb_24px](https://cloud.githubusercontent.com/assets/2032334/15465244/f131b848-20d3-11e6-9722-ec89eee14af2.png)
![bomb_24px 2x](https://cloud.githubusercontent.com/assets/2032334/15465259/046c48f6-20d4-11e6-9fd2-68062c1fab09.png)
![bomb_24px 4x](https://cloud.githubusercontent.com/assets/2032334/15465420/b70a5e94-20d4-11e6-85dc-9f2a9cb80ff0.png)

# SVG
[Bomb_24px.svg.zip](https://github.com/Templarian/MaterialDesign/files/277137/Bomb_24px.svg.zip)

**Comment by Templarian** [comment]
[![bomb](https://materialdesignicons.com/icon/bomb)](https://materialdesignicons.com/icon/bomb)
