### ISSUE TITLE
Boat icon (and related)

### ISSUE THREAD

**Issue by becarlos** [Templarian/MaterialDesign#1217]
Would be great to see some icons about Boat, Ship, Vessels, and so on.
- mdi-boat
- mdi-ship
- mdi-vessel

**Comment by CoDEmanX** [comment]
Hm, is it really necessary to distinguish ship and vessel? Anyway, there is an icon called `ferry`, which looks like a ship and is originally called `directions_boat`:

[![ferry](https://materialdesignicons.com/icon/ferry)](https://materialdesignicons.com/icon/ferry)

@Templarian: we could really use some aliases for this one, you can't find it by "ship", "vessel", "boat", "craft", ...

Not sure if the `rowing` icon would work as icon for boat, because there's no boat in the depiction:

[![rowing](https://materialdesignicons.com/icon/rowing)](https://materialdesignicons.com/icon/rowing)

**Comment by Templarian** [comment]
@becarlos If the above `ferry` icon does not work, do you have example of what style you are talking about for this icon?

**Comment by becarlos** [comment]
The `ferry` icon is perfect for what I was looking for!

Thank you all very much for your quick response, it was very helpful!
