### ISSUE TITLE
Add icon hex code to web interface

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#1239]
Would be useful to have the hex code for the icon displayed on the card when you click on an icon. I currently have to use https://cdn.materialdesignicons.com/1.6.50/ and switch between the tabs to search for them which is a little annoying.

**Comment by Templarian** [comment]
Yea, I could write a query to grab the latest version (the backend actually allows subfonting) and display that hex code.

I've been considering adding search to the preview so people could reference the set outside of the website. It's a bit of a work to add, but I think it would be a clean solution for a lot of users just using NPM/Bower.

**Comment by Templarian** [comment]
@JamesCoyle By the way you're added as a collaborator since a day ago. Basically, with great power comes great responsibility and stuff. So yea, always pass it up if you're not sure what to do with an issue (I always read everything anyway). Useful for re-titles of issues, closing duplicates, and such.

**Comment by JamesCoyle** [comment]
Well I'm happy to help out where I can. I don't want to be one of those guys that steps in and tries to take over everything but I do have some ideas of how the project could be improved and would love to discuss them. I don't think this is really the place to talk about it so if you have any better place to talk with contributors that would be useful.
