### ISSUE TITLE
Icons for education area

### ISSUE THREAD

**Issue by CarlosPerezUdabe** [Templarian/MaterialDesign#1274]
#1272 Icons like add task, register attendance, teachers plannings, payments fees, and similars applied to web system about education area.

![image](https://cloud.githubusercontent.com/assets/338885/15906648/63939b06-2d7f-11e6-91fb-a7c6489cea31.png)

**Comment by CoDEmanX** [comment]
Please provide reference images for the requested icons.

As for `task-add`, have a look at #1067

**Comment by CarlosPerezUdabe** [comment]
Maybe like this url

[https://cdn.vectorstock.com/i/composite/16,15/quiz-icon-set-vector-5781615.jpg](url)

**Comment by goyney** [comment]
- Add task - `calendar-check` https://materialdesignicons.com/icon/calendar-check
- Register attendance - `format-list-checks` https://materialdesignicons.com/icon/format-list-checks
- Teachers plannings - Any of the `calendar-*` icons
- Payments fees - Any of the money related icons

It seems like we have icons for all your use cases from your original post. I'm going to close this issue because of that. If you have specific icons you'd like to see along these lines, please create new issues for each icon so we can better address each one. Thanks.
