### ISSUE TITLE
Hammer

### ISSUE THREAD

**Issue by AnthonySmith** [Templarian/MaterialDesign#1323]
Hammer icon to signify a project or work.

![hammer-icon-6](https://cloud.githubusercontent.com/assets/1421157/16440284/4764297c-3d75-11e6-8683-d3094566ebac.png)

**Comment by JapanYoshi** [comment]
![path4156](https://cloud.githubusercontent.com/assets/8707990/17193420/e123dbfa-548d-11e6-9d7b-d341281f665a.png)
![path4157](https://cloud.githubusercontent.com/assets/8707990/17193423/e2bfd1da-548d-11e6-8dd5-6a0b60ed94ff.png)

**Comment by MrGrigri** [comment]
I've used this in a project of mine. 

![hammer 4x](https://cloud.githubusercontent.com/assets/4528551/20225863/ce59b102-a802-11e6-9e0f-e628d65b63bd.png) ![hammer](https://cloud.githubusercontent.com/assets/4528551/20225864/ce5e4186-a802-11e6-8409-f63e2e4abf89.png)

**Comment by JapanYoshi** [comment]
↑ That one doesn't look so Material...

**Comment by JamesCoyle** [comment]
While I like @JapanYoshi's it seems a bit cartoonish. I prefer @MrGrigri's but it could use a bit more improvement to make it feel more material. Perhaps we could create a group of icons for popular tools. `tool-hammer-claw`, `tool-hammer-sledge`, `tool-mallet` etc.

**Comment by MrGrigri** [comment]
Here's an updated version. I changed the thickness of the handle to 2.5px instead of 2px (3px looked too fat) and I changed the claw to be more material-like. I agree with @JamesCoyle, this could be a claw variant. 

![hammer-alt 4x](https://cloud.githubusercontent.com/assets/4528551/20283816/cb6aaa6a-aa77-11e6-8a82-6a5fa59d45c1.png) ![hammer-alt](https://cloud.githubusercontent.com/assets/4528551/20283817/cb6c6df0-aa77-11e6-9f38-c53a29745793.png)

[hammer.zip](https://github.com/Templarian/MaterialDesign/files/590552/hammer.zip)

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/38144625-8f0438d0-3413-11e8-84b9-2270ead17a5f.png)![image](https://user-images.githubusercontent.com/18645219/38144638-9d6928f4-3413-11e8-8de9-bda36e915559.png)
[Download link](https://github.com/Templarian/MaterialDesign/files/1864078/icons.zip)

**Comment by PeterShaggyNoble** [comment]
Those look great, @Croutonix. Could you create a new issue for the `axe` so we can track it separately?

**Comment by Templarian** [comment]
[![hammer](https://materialdesignicons.com/icon/hammer)](https://materialdesignicons.com/icon/hammer)
