### ISSUE TITLE
Add GreenTurtwig as Contributor

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1437]
@GreenTurtwig Need some details... Name, twitter, picture, short description, and as best as you can remember which icons you added so far.
- [x] Add @GreenTurtwig as a contributor.
- [x] Get details for contributor page on the site (twitter, name, photo).
- [x] Assign all icons to contributor. #1435

**Comment by GreenTurtwig** [comment]
All right. :-)  

- Name: Rowan
- Twitter: https://twitter.com/greenturtwig
- Website (if wanted): https://greenturtwig.co.uk
- Image: [avatar.zip](https://github.com/Templarian/MaterialDesign/files/417148/avatar.zip)
- Description: "I make stuff with cats and code <3"
  
And finally icons:
- https://github.com/Templarian/MaterialDesign/issues/1309 Autopilot
- https://github.com/Templarian/MaterialDesign/issues/1422 Linux Distros
- https://github.com/Templarian/MaterialDesign/issues/1435 Bot/Robot
- https://github.com/Templarian/MaterialDesign/issues/1336 Filter Plus
- https://github.com/Templarian/MaterialDesign/issues/1294 Patreon and Hitbox
- https://github.com/Templarian/MaterialDesign/issues/1349 Music Note Plus
- https://github.com/Templarian/MaterialDesign/issues/1423 Nuke
- https://github.com/Templarian/MaterialDesign/issues/1428 Pillar
- https://github.com/Templarian/MaterialDesign/issues/1325 Unshare
- https://github.com/Templarian/MaterialDesign/issues/1311 Watch Vibrate

That's all I can find in my "icons" folder, I'll probably be making more since I (surprisingly) enjoy this. :smile_cat:

**Comment by GreenTurtwig** [comment]
Also I'm getting the hang of Inkscape now, which should be useful. :-)

**Comment by GreenTurtwig** [comment]
Should I add any extra contributions I do to this issue? :+1:

**Comment by Templarian** [comment]
Nah, all the new ones will be assigned going forward now that you're in the database.

**Comment by GreenTurtwig** [comment]
Great. :smile_cat:
