### ISSUE TITLE
Suggestion: Thought / Idea Bubble

### ISSUE THREAD

**Issue by azkaiart** [Templarian/MaterialDesign#1443]
Would love to see a thought bubble, made of the small circles as opposed to the chat bubble.

**Comment by yang3535** [comment]
How about an analog gauge of some kind that would indicate a measurement or analog instrument?

**Comment by JamesCoyle** [comment]
@yang3535 How is that related to this icon request? We already have a gauge icon.

**Comment by yang3535** [comment]
Oops sorry.  When I searched for "gauge", I somehow missed the reply from
the search function - likely because I was using a small window.  Sorry for
the inconvenience.


I am using a gauge icon to represent an A to D converter input, so was
looking for something that communicated an obviously analog idea.  If there
is something better, I couldn't find it.

Thanks for your response.

**Comment by CoDEmanX** [comment]
You could also use a light bulb to represent "idea".

I wonder if a thought bubble should be comprised of 3 ellipses, or two circles and a cloud...

**Comment by JapanYoshi** [comment]
![rect4144](https://cloud.githubusercontent.com/assets/8707990/18417542/a79fcdd0-786e-11e6-995b-3aaa780e9fb0.png)

**Comment by PeterShaggyNoble** [comment]
[![thought-bubble](https://user-images.githubusercontent.com/15157491/36913368-a4578c88-1e41-11e8-8dd9-ec5a78ad9cae.png)](https://materialdesignicons.com/icon/thought-bubble) [![thought-bubble-outline](https://user-images.githubusercontent.com/15157491/36913382-b036b3bc-1e41-11e8-9af6-1dac8a61bbc5.png)](https://materialdesignicons.com/icon/thought-bubble-outline)
