### ISSUE TITLE
grunt-webfont task configuration

### ISSUE THREAD

**Issue by SaleGajic** [Templarian/MaterialDesign#1542]
Hello,
I very much need few more icons for project I am working on. Icons have to be in in webfont since user can choose them by specifying icon name. Since contributions are closed, I forked your repo, added 4 more SVG icons i've designed and generated new webfont using grunt-webfont. New webfont contains my icons, but everything seems to be offset and out of allign. The other problem is that some icons are not complete.

mdi-checkbox-multiple-marked-circle is same as mdi-checkbox-multiple-blank-circle.
![image](https://cloud.githubusercontent.com/assets/9561021/19008802/2411bcbc-876e-11e6-855a-1c2ddf1e1486.png)

I've tried running webfont task with following configuration

``` javascript
module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    // Task configuration.
    webfont: {
        icons: {
            src: 'icons/svg/*.svg',
            dest: 'build/fonts/',
            destCss: 'build/css/',
            options: {
                    font: "Material Design Icons",
                    fontFilename: "materialdesignicons-webfont",
                    autoHint: false,
                    normalize: true,
                //htmlDemo: false,
                syntax: 'bem',
                templateOptions: {
                    font:'materialdesignicons-webfont',
                    baseClass: 'mdi',
                    classPrefix: 'mdi-',
                    types:['eot','woff2','woff','ttf','svg'],
                    order:['eot','woff2','woff','ttf','svg']

                }
            }
        }
    }
  });

  // These plugins provide necessary tasks.
  grunt.loadNpmTasks('grunt-webfont');

};
```

Can you please share your task configuration?
Thanks in advance!

**Comment by Templarian** [comment]
Make sure you build it using the download from: https://materialdesignicons.com/design These are optimized for the webfont's build process. The raw SVG files in the repo can produce defects.

```js
options: {
            engine: 'node',
            types: 'eot,woff2,woff,ttf,svg',
            font: 'Material Design Icons',
            hashes: false,
            autoHint: false,
            normalize: true
}
```

**Comment by SaleGajic** [comment]
I've used SVGs from your link, and now i've got even worse font:
![image](https://cloud.githubusercontent.com/assets/9561021/19071686/9832ed30-8a31-11e6-964c-861ac3e7196f.png)

This was the configuration I used:
```javascript
module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    // Task configuration.
    webfont: {
	    icons: {
			src: 'icons/svg/*.svg',
			dest: 'build/fonts/',
			options: {
						engine: 'node',
						types: 'eot,woff2,woff,ttf,svg',
						font: 'Material Design Icons',
						hashes: false,
						autoHint: false,
						normalize: true
			}
		}
	}
  });

  // These plugins provide necessary tasks.
  grunt.loadNpmTasks('grunt-webfont');

};
```

I guess some parts of configurations are missing because i don't get "mdi" base class and "mdi-" prefix. Also my css doesn't have transformations in the end like ".mdi.mdi-18px", ".mdi-flip-vertical", etc.
Can you please share entire config if it's not a secret. I really need those few extra icons i've created, and without them in font code becomes extremely complicated.

Thanks!

**Comment by Templarian** [comment]
By the way definitely not a secret, that SVG folder output is actually pulled from the font build directory that I use. I just need to find some time to spend debugging this (working to close on a condo, so busy at the moment). Will try and see this weekend if I can debug this in a blank directory from scratch.

**Comment by SaleGajic** [comment]
Great, will you please, when you find a bit of time, share:

- node version you are using for compiling font
- grunt-webfont version
- confirm if the configuration from my previous post is exactly the same as yours / share your whole grunt configuration

I don't see if input is the same, and transformation is the same, how the output can be different.

**Comment by OlivierBoucher** [comment]
+1 on this. I'm also getting weird results, if you could share your config that would be nice 👍

**Comment by outrightlie** [comment]
Hey @Templarian, seems like the documentation for the grunt-webfont task configuration has fallen off your TODO list?

I'm trying to setup grunt-webfont, but I've run into a couple of issues. If you can point me into the right direction I'd be happy to contribute the missing "... explain step by step here..." guide (https://materialdesignicons.com/getting-started).

- The download link https://materialdesignicons.com/design you provided earlier in this thread points to https://cdn.materialdesignicons.com/2.0.46/MaterialDesignIconsDesign.zip and returns a 404 :(
- I can create fonts on a Mac with fontforge with the following options:
options:
```
{
	ligatures: true,
	types: 'eot,woff2,woff,ttf,svg',
	hashes: false,
	autoHint: false,
	normalize: true,
	optimize: false
}
```
- Those options seem to work with the `.ligature-icons` class just fine. (`<div class="ligature-icons">face</div>`). AFAIK the `.ligature-icons` class can be changed to `.material-icons` with custom templates in grunt-webfont, but their documentation is a bit lacking and I have no idea what the template.json should look like. Any pointers? (If I use their template examples I get 'fontPathVariables is not defined' errors)
- The options you provided earlier in this thread do not work for me, since they are missing `ligatures: true`. Is the grunt-webfont config supposed to work without the ligatures option for material icons?
- My setup doesn't seem to work with `engine: 'node'` :(

Thanks a bunch if you have to time to help!

**Comment by Templarian** [comment]
@outrightlie By the I just recently tried to update to the latest and couldn't get the icons to build right (they built, but the actual icons didn't render correctly).

I'm going to go back to trying shortly.

https://github.com/Templarian/MaterialDesign-Site/blob/master/src/content/guide-webfont.md

https://github.com/Templarian/MaterialDesign/issues/2280 To read a little about my failed update/rollback.
