### ISSUE TITLE
Shower, Bath & Toilet

### ISSUE THREAD

**Issue by GRA0007** [Templarian/MaterialDesign#1560]
It would be nice to have a shower and toilet icon for representing a bathroom, i.e for a hotel page.

**Comment by alexefremo** [comment]
![ic_shower_black_24px](https://cloud.githubusercontent.com/assets/3408199/19548938/c0ac5d7e-96ba-11e6-931b-5c64b003fc5a.png)
![ic_shower_black_48px](https://cloud.githubusercontent.com/assets/3408199/19548939/c0bbd20e-96ba-11e6-9dd4-22e6e6294947.png)
![ic_shower2_black_24px](https://cloud.githubusercontent.com/assets/3408199/19548940/c0bd6222-96ba-11e6-8d85-63ef5c4a50b3.png)
![ic_shower2_black_48px](https://cloud.githubusercontent.com/assets/3408199/19548937/c08c455c-96ba-11e6-8b8d-f28088bbe005.png)

**Comment by PeterShaggyNoble** [comment]
[mdi-human-male-female](https://materialdesignicons.com/icon/human-male-female) would be an option that would be universally recognised as representing a bathroom, with [mdi-human-male](https://materialdesignicons.com/icon/human-male) & [mdi-human-female](https://materialdesignicons.com/icon/human-female) for individual facities.

**Comment by daanwintjes** [comment]
maybe something like this: <br>
![bathtub](https://cloud.githubusercontent.com/assets/26581209/24590805/18960ade-17f4-11e7-99be-591ebcbdebf8.png)

**Comment by daanwintjes** [comment]
Maybe something like this:

![bathtub](https://cloud.githubusercontent.com/assets/26581209/24590830/68dc26e0-17f4-11e7-8f51-a3056f0c6610.png)

**Comment by metbril** [comment]
I second a bath, shower and toilet icon, for use with home automation systems like home-assistant. These icons are intend to be used to identify rooms/areas in a house.

**Comment by metbril** [comment]
Any progresss on these?

**Comment by augustin32** [comment]
Bath
![bath24](https://user-images.githubusercontent.com/14167196/30870498-ab7d9ff0-a2ec-11e7-8d67-8e01045ef2b6.png)
![bath36](https://user-images.githubusercontent.com/14167196/30870511-b252cb8e-a2ec-11e7-86dd-192e74f15999.png)
![bath48](https://user-images.githubusercontent.com/14167196/30870514-b3c81424-a2ec-11e7-868d-aaa9281e2010.png)
Shower & Tub
![shower-and-tub24](https://user-images.githubusercontent.com/14167196/30870528-bbd764e4-a2ec-11e7-93c4-2e3fbb5823fb.png)
![shower-and-tub36](https://user-images.githubusercontent.com/14167196/30870530-bd09fdf4-a2ec-11e7-855d-db7af1d3fa9e.png)
![shower-and-tub48](https://user-images.githubusercontent.com/14167196/30870532-be4224e4-a2ec-11e7-9be5-a30de41ea974.png)
Shower
![shower24](https://user-images.githubusercontent.com/14167196/30870537-c31fe348-a2ec-11e7-9d49-c0083c4d47a2.png)
![shower36](https://user-images.githubusercontent.com/14167196/30870540-c4eccf9c-a2ec-11e7-87a9-9c9e0f814a6a.png)
![shower48](https://user-images.githubusercontent.com/14167196/30870543-c6306d14-a2ec-11e7-87ee-1e04288ecb10.png)
Toilet Bowl Front
![toilet-bowl-front24](https://user-images.githubusercontent.com/14167196/30870552-cc941b60-a2ec-11e7-887a-1b731a31b95d.png)
![toilet-bowl-front36](https://user-images.githubusercontent.com/14167196/30870555-cdc5dee2-a2ec-11e7-8966-498a10d95ab7.png)
![toilet-bowl-front48](https://user-images.githubusercontent.com/14167196/30870556-cf84dbd4-a2ec-11e7-87d4-043c7ebd0c6e.png)
Toilet Bowl Side
![toilet-bowl-side24](https://user-images.githubusercontent.com/14167196/30870561-d5d92f12-a2ec-11e7-8839-1b4d22c3b590.png)
![toilet-bowl-side36](https://user-images.githubusercontent.com/14167196/30870563-d6fd3852-a2ec-11e7-87f7-1bec2563f040.png)
![toilet-bowl-side48](https://user-images.githubusercontent.com/14167196/30870567-d879d80c-a2ec-11e7-8b1f-d4df32b02938.png)

[icons.zip](https://github.com/Templarian/MaterialDesign/files/1333839/icons.zip)

**Comment by JapanYoshi** [comment]
Shouldn't the shower icon be a shower head?
![](http://icooon-mono.com/i/icon_12692/icon_126920_256.png)


2017/09/27 午前1:59 "Augustin Ursu" <notifications@github.com>:

Bath
[image: bath24]
<https://user-images.githubusercontent.com/14167196/30870498-ab7d9ff0-a2ec-11e7-8d67-8e01045ef2b6.png>
[image: bath36]
<https://user-images.githubusercontent.com/14167196/30870511-b252cb8e-a2ec-11e7-86dd-192e74f15999.png>
[image: bath48]
<https://user-images.githubusercontent.com/14167196/30870514-b3c81424-a2ec-11e7-868d-aaa9281e2010.png>
Shower & Tub
[image: shower-and-tub24]
<https://user-images.githubusercontent.com/14167196/30870528-bbd764e4-a2ec-11e7-93c4-2e3fbb5823fb.png>
[image: shower-and-tub36]
<https://user-images.githubusercontent.com/14167196/30870530-bd09fdf4-a2ec-11e7-855d-db7af1d3fa9e.png>
[image: shower-and-tub48]
<https://user-images.githubusercontent.com/14167196/30870532-be4224e4-a2ec-11e7-9be5-a30de41ea974.png>
Shower
[image: shower24]
<https://user-images.githubusercontent.com/14167196/30870537-c31fe348-a2ec-11e7-9d49-c0083c4d47a2.png>
[image: shower36]
<https://user-images.githubusercontent.com/14167196/30870540-c4eccf9c-a2ec-11e7-87a9-9c9e0f814a6a.png>
[image: shower48]
<https://user-images.githubusercontent.com/14167196/30870543-c6306d14-a2ec-11e7-87ee-1e04288ecb10.png>
Toilet Bowl Front
[image: toilet-bowl-front24]
<https://user-images.githubusercontent.com/14167196/30870552-cc941b60-a2ec-11e7-887a-1b731a31b95d.png>
[image: toilet-bowl-front36]
<https://user-images.githubusercontent.com/14167196/30870555-cdc5dee2-a2ec-11e7-8966-498a10d95ab7.png>
[image: toilet-bowl-front48]
<https://user-images.githubusercontent.com/14167196/30870556-cf84dbd4-a2ec-11e7-87d4-043c7ebd0c6e.png>
Toilet Bowl Side
[image: toilet-bowl-side24]
<https://user-images.githubusercontent.com/14167196/30870561-d5d92f12-a2ec-11e7-8839-1b4d22c3b590.png>
[image: toilet-bowl-side36]
<https://user-images.githubusercontent.com/14167196/30870563-d6fd3852-a2ec-11e7-87f7-1bec2563f040.png>
[image: toilet-bowl-side48]
<https://user-images.githubusercontent.com/14167196/30870567-d879d80c-a2ec-11e7-8b1f-d4df32b02938.png>

icons.zip
<https://github.com/Templarian/MaterialDesign/files/1333839/icons.zip>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Templarian/MaterialDesign/issues/1560#issuecomment-332246436>,
or mute the thread

**Comment by augustin32** [comment]
It is a shower head, but i didn't pay attention to names.

**Comment by GreenTurtwig** [comment]
It looks like one of those bells you push down for service to me. :-P

**Comment by Templarian** [comment]
[![shower](https://materialdesignicons.com/icon/shower)](https://materialdesignicons.com/icon/shower) [![shower-head](https://materialdesignicons.com/icon/shower-head)](https://materialdesignicons.com/icon/shower-head) [![toilet](https://materialdesignicons.com/icon/toilet)](https://materialdesignicons.com/icon/toilet)

**Comment by goyney** [comment]
`bathtub` added in v6.2.

[![bathtub](https://materialdesignicons.com/icon/bathtub)](https://materialdesignicons.com/icon/bathtub)[![bathtub-outline](https://materialdesignicons.com/icon/bathtub-outline)](https://materialdesignicons.com/icon/bathtub-outline)
