### ISSUE TITLE
Broken glass icon

### ISSUE THREAD

**Issue by ohelal** [Templarian/MaterialDesign#1566]
Would like to request a "glass-broken" icon, to represent damaged items. It could be a vaiant on the wine glass but broken with glass shards flying out of the broken part.

**Comment by Xenomorph99** [comment]
Based on your request, I'm assuming this is the type of imagery you're looking for: ![image](https://user-images.githubusercontent.com/1837101/91868575-1f8bd880-ec32-11ea-846e-cd0dee32c60d.png)

I created 3 options to pick from that illustrate "fragile" or "broken glass". I couldn't use our [glass-wine](https://materialdesignicons.com/icon/glass-wine) icon since it's too narrow to contain the zig zag line even at 1 dps. I tried a 2 dps zig zag line on different shapes, but it's too thick.

- **Option A**  goblet shape similar to standard shipping labels with a 1 dps thick zig zag line.
- **Option B** same shape as option A with a 1.5 dps thick zig zag line.
- **Option C** is closer to the dimensions of [glass-cocktail](https://materialdesignicons.com/icon/glass-cocktail) with a 1.5dps zig zag line on the left.

Personally, I like option B the best since the zig zag line is the most vivid and easiest to read.

![fragile-a](https://user-images.githubusercontent.com/1837101/91872330-fcaef380-ec34-11ea-985b-76a256201791.png)
![fragile-b](https://user-images.githubusercontent.com/1837101/91872331-fd478a00-ec34-11ea-9c33-201a69f7605f.png)
![fragile-c](https://user-images.githubusercontent.com/1837101/91872333-fd478a00-ec34-11ea-87db-bbe4fbef058a.png)

I also created a non-broken "glass-goblet" to match the fragile icons. Not sure if we want to add both of these non-broken icons to the library or just one. We could name one "glass-goblet" and the other "glass-goblet-outline" or "glass-goblet-variant" if we decide to add both.

Either way, we need to include the following aliases where appropriate: _alcohol, bar, broken, broken-glass, cocktail, cup, drink_

![glass-goblet-a](https://user-images.githubusercontent.com/1837101/91872713-64fdd500-ec35-11ea-8b32-939e8fc428f7.png)
![glass-goblet-b](https://user-images.githubusercontent.com/1837101/91872715-65966b80-ec35-11ea-82e8-fc90dd4af366.png)

[fragile-and-goblet-icons.zip](https://github.com/Templarian/MaterialDesign/files/5157308/fragile-and-goblet-icons.zip)

**Comment by temaprint** [comment]
look here a good choice
https://icons8.com/icons/set/broken-glass
<img src="https://img.icons8.com/carbon-copy/50/000000/fragile.png"/><img src="https://img.icons8.com/ios-glyphs/50/000000/fragile.png"/><img src="https://img.icons8.com/plasticine/50/000000/fragile.png"/>

**Comment by JapanYoshi** [comment]
Can you try ``fragile-b`` with one zig instead of two?

**Comment by Xenomorph99** [comment]
Here's what you recommended trying @JapanYoshi. You can see that at 24x24 dps, the break isn't recognizable.

![fragile-d](https://user-images.githubusercontent.com/1837101/97042121-cc494e80-152d-11eb-9f1a-27c011703bbc.png)
[fragile-d.zip](https://github.com/Templarian/MaterialDesign/files/5431299/fragile-d.zip)

Here's some current icons that indicate "broken". They all have large zig zags:

![heart-broken](https://user-images.githubusercontent.com/1837101/97042463-4f6aa480-152e-11eb-97fe-f9e99e682c12.png)
![image-broken](https://user-images.githubusercontent.com/1837101/97042465-50033b00-152e-11eb-9014-235633946070.png)
![trophy-broken](https://user-images.githubusercontent.com/1837101/97042466-50033b00-152e-11eb-8a74-87bacc54d856.png)
![image-broken-variant](https://user-images.githubusercontent.com/1837101/97042468-509bd180-152e-11eb-8d5e-057ea2ae0d96.png)

**Comment by Xenomorph99** [comment]
I recommend we add "fragile-b" as `fragile` and "glass-goblet-b" as `glass-goblet`.

**Comment by JapanYoshi** [comment]
Heart-broken and trophy-broken both have one zigzag. What about adding the same style of zigzag to the goblet?

**Comment by Xenomorph99** [comment]
The stem of the glass is too small and narrow to add the same zig zag shape as `heart-broken` or `trophy-broken`. The only way to add it would be to spread the two sides of the glass apart, but honestly that destroys the meaning. This icon is called “fragile” not “glass-broken”. Look at the screenshot with the red fragile icon examples I posted above from my Google image search. None of them show a shattered glass. This icon is supposed to represent future tense not present tense.

**Comment by goyney** [comment]
[![glass-fragile](https://materialdesignicons.com/icon/glass-fragile)](https://materialdesignicons.com/icon/glass-fragile)
