### ISSUE TITLE
Clover icon

### ISSUE THREAD

**Issue by dfsilva** [Templarian/MaterialDesign#1582]

**Comment by MrGrigri** [comment]
That's a great idea. Here's a quick icon. Maybe instead of clover, it could be 'luck' with an alias of 'clover'.

![clover 4x](https://cloud.githubusercontent.com/assets/4528551/19788127/e94f0d90-9c63-11e6-95e0-b0b59101f3a6.png) ![clover](https://cloud.githubusercontent.com/assets/4528551/19788128/e94f2d48-9c63-11e6-8f84-68dfe6053c19.png)

[clover.zip](https://github.com/Templarian/MaterialDesign/files/557190/clover.zip)

**Comment by JamesCoyle** [comment]
A three leaf variant would probably be a good idea too.

**Comment by Templarian** [comment]
Removed 8 of the extra points.

[![clover](https://materialdesignicons.com/icon/clover)](https://materialdesignicons.com/icon/clover)
