### ISSUE TITLE
world map icon

### ISSUE THREAD

**Issue by Reinbert** [Templarian/MaterialDesign#1643]
As seen here: https://upload.wikimedia.org/wikipedia/commons/1/17/BlankMap-World-noborders.png

For use as a universal map icon, not google related.

**Comment by MrGrigri** [comment]
That would be very hard to do with material. The closest is the earth icon:

![earth](https://materialdesignicons.com/icon/earth)

**Comment by Templarian** [comment]
This is outside of the scope that we can do with this size of icon and style. The suggestion above is your best representation of a globe. We could maybe have a square version/variant?

**Comment by GreenTurtwig** [comment]
How about this:
[earth-square.zip](https://github.com/Templarian/MaterialDesign/files/612884/earth-square.zip)
![puush-linux 2016-11-25 at 09 15 39](https://cloud.githubusercontent.com/assets/15905797/20620090/d893e136-b2ef-11e6-833a-da06737c2ce8.png)
![puush-linux 2016-11-25 at 09 16 03](https://cloud.githubusercontent.com/assets/15905797/20620092/defd4044-b2ef-11e6-9717-1eb4d1184884.png)

**Comment by Reinbert** [comment]
Looks good! Thx for the effort.

**Comment by GreenTurtwig** [comment]
No problem. :smile_cat:

**Comment by Templarian** [comment]
[![earth-box](https://materialdesignicons.com/icon/earth-box)](https://materialdesignicons.com/icon/earth-box) [![earth-box-off](https://materialdesignicons.com/icon/earth-box-off)](https://materialdesignicons.com/icon/earth-box-off)

@GreenTurtwig I assigned the `-off` icon to your account also. 😸 It uses the similar inverse slash as `earth-off` due to the design of the slash.
