### ISSUE TITLE
send-variant

### ISSUE THREAD

**Issue by casesandberg** [Templarian/MaterialDesign#1666]
![image](https://cloud.githubusercontent.com/assets/4633636/20747524/45a1874e-b69f-11e6-8507-73bf948c9cd7.png)

* send-variant

[send-variant-icon.zip](https://github.com/Templarian/MaterialDesign/files/621445/send-variant-icon.zip)

**Comment by casesandberg** [comment]
This is based off Instagrams new send icon:

![image](https://cloud.githubusercontent.com/assets/4633636/20765216/382f2480-b6e6-11e6-9e42-b6b76f099eba.png)

**Comment by Templarian** [comment]
I'm leaning toward rejecting this one. This variation of the send icon is more of a one off "branded" icon rather than a standard representation of the send icon.

Let me know if you feel strongly against this and I'll reopen this. I just think it's well too niche to be included (similar to Twitter's slanted Bell icon).

**Comment by JamesCoyle** [comment]
Is there not already a paper aeroplane available in the iconset? Quite a
few Google apps use one.

**Comment by Templarian** [comment]
@JamesCoyle https://materialdesignicons.com/icon/send

**Comment by JamesCoyle** [comment]
I don't see why we would need an alternative to that.

**Comment by casesandberg** [comment]
Cool, sounds good to me

**Comment by PeterShaggyNoble** [comment]
Those who really want a slanted version could use [mdi-telegram](https://materialdesignicons.com/icon/telegram).
