### ISSUE TITLE
Meditation

### ISSUE THREAD

**Issue by mmokross** [Templarian/MaterialDesign#176]
something ike http://www.flaticon.com/search/guru especially http://www.flaticon.com/free-icon/guru_48213
- [ ] meditation

**Comment by CoDEmanX** [comment]
Links seem down, but the Google Fit meditation icon is actually a good reference:
https://www.dropbox.com/s/nfdi9jr1rbftiey/ic_meditating_gray.png?dl=0

**Comment by goyney** [comment]
I wouldn't say this is a Google stock icon, because the only place it can be found is in the Fit app and it is this big, white, and in a raster format (I had to invert it to post it here):
![meditation](https://user-images.githubusercontent.com/1015040/48861178-fc5fa400-ed90-11e8-896c-d8d979d4bab6.png)

I've recreated it as best as I could here:
![image](https://user-images.githubusercontent.com/1015040/48861891-b3105400-ed92-11e8-9470-3282a9ce825e.png)

[meditation.zip](https://github.com/Templarian/MaterialDesign/files/2605391/meditation.zip)

**Comment by goyney** [comment]
For reference, here is the Google Fit version:
![image](https://user-images.githubusercontent.com/1015040/48975357-402a0600-f03c-11e8-83a2-c47da6e3d39e.png)

[google-fit-meditation.zip](https://github.com/Templarian/MaterialDesign/files/2612829/google-fit-meditation.zip)

**Comment by JamesCoyle** [comment]
Gonna remove the google icon label as its not actually an icon designed for the 24x24 grid. I feel we need to create one that fits better with our current people based icons.

**Comment by MrGrigri** [comment]
I know that in most cases, this can be represented by the lotus flower or spa icon. #3726

**Comment by JamesCoyle** [comment]
We probably wanna use `human` as the base for these:
[![](https://materialdesignicons.com/icon/human)](https://materialdesignicons.com/icon/human)

**Comment by CoDEmanX** [comment]
Same problem as in #1089, but harder to fix. The body can't be 6dp wide:

![grafik](https://user-images.githubusercontent.com/1309249/63231626-b734a980-c21e-11e9-99a7-f84673faa537.png)

4dp looks okay and might be as good as it gets:

![grafik](https://user-images.githubusercontent.com/1309249/63231642-d6cbd200-c21e-11e9-9d18-b665ead557a8.png)

[meditation3.zip](https://github.com/Templarian/MaterialDesign/files/3513689/meditation3.zip)

**Comment by goyney** [comment]
[![meditation](https://materialdesignicons.com/icon/meditation)](https://materialdesignicons.com/icon/meditation)
