### ISSUE TITLE
usage of custom icons as webfont

### ISSUE THREAD

**Issue by csxdotcc** [Templarian/MaterialDesign#1762]
how do i use for example the 'mdi-clipboard-flow' easily in my webpage?
i wanted to use the webfont, woff, file, it works amazingly for the 'standard' icons,
thanks in advance,

**Comment by Templarian** [comment]
The next release is coming out this weekend #1759. You can always use inline SVG (the new website has much better documentation on this, can't wait to release it).

https://materialdesignicons.com/getting-started -> "Inline SVG"

**Comment by csxdotcc** [comment]
i don't get your answer [#1759](https://github.com/Templarian/MaterialDesign/issues/1759).
maybe i should asked, how to get a woff and a css file with all the pretty custom icons too?

**Comment by PeterShaggyNoble** [comment]
If you look at the [history page](https://materialdesignicons.com/history), you'll see that the last release was v1.7.22 - all the icons added to the repository _since_ that release will be available in the _next_ release mentioned in [#1759](https://github.com/Templarian/MaterialDesign/issues/1759).

**Comment by koutsenko** [comment]
Hello.
Can anybody explain how-to build icon webfont subset with webpack?
Thanks.

**Comment by Templarian** [comment]
@koutsenko https://github.com/sapegin/grunt-webfont

Working on the new site to better provide documentation and a easy to reproduce process of building the webfont. Track the issue here: https://github.com/Templarian/MaterialDesign-Site/issues/17

**Comment by koutsenko** [comment]
@Templarian thanks. I'll reverted back to google material icons, because react-mdl have inner dependency in some controls and I dunno how-to to override them. Simply set element's "name" to "" and "className" to "mdi mdi-*" in JSX statements isn't enough for some cases. Since the second version of mdl project is moved to new project "material-components-web", something may changed in the future, but it isn't simple now.
