### ISSUE TITLE
Contribution: various icons

### ISSUE THREAD

**Issue by Croutonix** [Templarian/MaterialDesign#1765]
I made some icons for my needs and some requests I saw: 2 current icons, an electronics icon, json file, network tower, sort by date, sort by size, sort by extension, spark, and 3 wave icons. 
[icons.zip](https://github.com/Templarian/MaterialDesign/files/705954/icons.zip)

I didn't find any precise guidelines so it's possible some of them are wrong, I'll let you judge.

**Comment by MrGrigri** [comment]
These are great ideas, however, I believe that you need to read up on the Material Design standards for icons. We try to follow those.

https://material.io/guidelines/style/icons.html

**Comment by PeterShaggyNoble** [comment]
@Croutonix, did you ever get around to updating these?

**Comment by Croutonix** [comment]
No you can close it.

**Comment by MrGrigri** [comment]
If you ever change your mind, just reopen it.

**Comment by CoDEmanX** [comment]
This is how they look:

![image](https://user-images.githubusercontent.com/1309249/37419736-6e16eae2-27b5-11e8-87cc-968e22807f28.png)
![image](https://user-images.githubusercontent.com/1309249/37419765-7a0c5864-27b5-11e8-8400-f52b1f84f195.png)

- **current_1:** We have an abstract `power` and a physical `power-plug`. Do we really need another icon with a plug + wire, and has the wire to be circle-like?
- **current_2:** `flash` doesn't cut it. I like the idea. Maybe needs a bit grid tweaking?
- **electronics:** Looks pretty much like `memory` to me
- **file_json:** As can be seen in https://github.com/Templarian/MaterialDesign/issues/1240#issuecomment-222284418, the braces alone barely fit while still being legible at 24px
- **network_tower:** we already have `radio-tower`
- **sort_date:** too specific IMO
- **sort_extension:** too specific IMO
- **sort_size:**  too specific IMO
- **spark:** would `flash` suffice?
- **wave_1**: I really like this one, could represent audio waves for instance, maybe like this? ![image](https://user-images.githubusercontent.com/1309249/37432734-af2b8c1c-27d9-11e8-9fe2-0e8971ef8d0f.png)
- **wave_2:** we already have `pulse`
- **wave_3:** we could use this well IMO, because `waves` is not suitable for alternative current
