### ISSUE TITLE
Can light

### ISSUE THREAD

**Issue by kylerw** [Templarian/MaterialDesign#1826]
Using the icons frequently with HomeAssistant (github.com/home-assistant/home-assistant) and it would be nice to have icons like those you find in apps like SmartThings (github.com/home-assistant/home-assistant) so that the icon can match the type of device (can light, fan, sconce, etc)

- [ ] can light
- [x] fan (sort of exists, do you need another style)
- [x] sconce

**Comment by Templarian** [comment]
We've added a ton of icons to help out people using home assistant in the past. If you could make a list of the ones we are missing we'd be happy to try and get them added.

**Comment by 2wheeltraveler** [comment]
Some home automation icons I don't see here that I could use with ActionTiles (tied to smartthings)

- Ballast florescent light like in a garage
- Flood light
- Exterior coach light
- Can light
- Fan (with light)
- Fan (without light)
- Exterior hanging holiday-style light (Edison style hung between trees)
- Christmas tree lights
- Christmas house lights
- Double garage door open
- Double garage door closed

**Comment by PeterShaggyNoble** [comment]
`fan` already exists and sconce lights are covered in #1712. Leaving this open as a request for a (par)can, although it may end up being too similar to `spotlight`.

@2wheeltraveler, please open a new issue for each icon you want to request.

**Comment by dannyhanes** [comment]
Maybe something like this? My photoshop skills are a little rough haha. 
![ceiling-light](https://user-images.githubusercontent.com/3778687/44682329-11869a00-aa11-11e8-8d42-1b6701ba34b6.jpg)

**Comment by goyney** [comment]
That kind of looks like a BBQ. 😆

**Comment by dannyhanes** [comment]
@goyney haha, you're not wrong.

**Comment by GreenTurtwig** [comment]
https://materialdesignicons.com/icon/wall-sconce-flat

**Comment by tom-greene** [comment]
I have created an icon for the recessed/can lights that could be used. I tried to create the preview but I don't know how to do it! Didn't work for me. But I've attached it in hopes someone could do the preview or if it's acceptable, use it in the set.
[recessed-light.svg.gz](https://github.com/Templarian/MaterialDesign/files/3187827/recessed-light.svg.gz)

**Comment by euromem** [comment]
Second the ceiling or can lights icon. Similar to Lutron app...

- [ ] Can or recessed light

- [ ] Pool light

- [ ] Ceiling fan light
Thanks for considering these and doing awesome work folks.
![pool_light_ex](https://user-images.githubusercontent.com/61855017/84518197-f5abc100-ac95-11ea-94f6-93f2dfb3c657.jpeg)
![ceiling_fan_ex](https://user-images.githubusercontent.com/61855017/84518199-f6445780-ac95-11ea-962a-8c9b4c601793.jpeg)
![can_lights_ex](https://user-images.githubusercontent.com/61855017/84518200-f6445780-ac95-11ea-97a8-3a7defc71fc8.jpeg)

**Comment by jefframsey0** [comment]
Recessed light and light groups like this would be awesome. 
![image](https://user-images.githubusercontent.com/67827002/86512202-e966df80-bdcd-11ea-8986-bcfeb8aae79c.png)

**Comment by goyney** [comment]
It should be noted that these have not been added because we *cannot* show perspective.

**Comment by williamobrien** [comment]
OK, so I stumbled across this while looking for a can/recessed light icon. I haven't done one of these before, but tried to follow the guidelines to create an option that could potentially be used? If not, maybe it could be adapted to be used.
![recessed-can-light-final2](https://user-images.githubusercontent.com/6143684/95333363-adcf2c00-087a-11eb-9b7a-bb77029b0d52.png)

**Comment by goyney** [comment]
The problem with that is it either looks like a smashed parking cone or a police siren with the flair coming out of the bottom.

I'm still perplexed on why this one icon everyone wants to be literal on. Icons are contextual and you need to represent a light. The purpose of can lights (IRL) is for them to be hidden away. There's no fixture or style to them, they're just a lightbulb tucked away in a hole. Therefore, a lightbulb seems like the obvious choice to represent these.

**Comment by tom-greene** [comment]
Probably the same reason @goyney that there are the following icons that exist as an icon:

- Car Light
- Car Parking Light
- Ceiling Light
- Coach Lamp
- Dome Light
- Floor Lamp
- Floor Lamp Dual
- Floor Lamp Variant
- Globe Light
- 18 Variants of a light bulb
- Outdoor Light
- Spot Light
- Track Light
- Vanity Light
- 4 Variants of a Sconce

If the icon set was specifically for context, we'd need none of these but an off an on light bulb. Variety makes the world better.

**Comment by goyney** [comment]
My point is that all of those are actual fixtures. A can light's sole purpose is to be hidden away.

**Comment by tom-greene** [comment]
And a recessed light is not an actual fixture that looks completely different than all of these?

**Comment by goyney** [comment]
I mean, the fact that most suggestions for this type of fixture all have to show the internal structure that is hidden behind the ceiling to depict what they are is pretty problematic. The closest thing we have to what these actual look like are the perspective based rings, but that goes against Material guidelines.

**Comment by yapishkahilt** [comment]
The below recessed light icon represents only externally visible parts of such a light. Does it violate Material guidelines because of perspective? I ask because I don't understand the distinction between the perspective in the below icon and that present in a number of existing MDIs such as the server icon. (That icon also happens to show solely the internal structure of the item it represents.) Absent perspective, the server icon would be either a series of horizontal lines if portrayed visually from the side or a black circle if viewed from above. 

I appreciate the MDIs and am not trying to antagonize anyone, I just don't understand how the perspective in something like the below icon differs from the perspective present in many existing MDIs.

![recessed](https://user-images.githubusercontent.com/21110955/111852176-65696f00-88ec-11eb-927e-a03106cdb850.png)

![Screen Shot 2021-03-19 at 7 22 04 PM](https://user-images.githubusercontent.com/21110955/111852282-b4170900-88ec-11eb-9675-15fd537717a1.jpg)

**Comment by goyney** [comment]
We have discussed this issue more internally and voted to break Material Guidelines for this specific use case. Because of its high demand for use in Home Assistant, we've decided to allow its addition.

[![light-recessed](https://materialdesignicons.com/icon/light-recessed)](https://materialdesignicons.com/icon/light-recessed)
