### ISSUE TITLE
file-link, file-mail, file-phone

### ISSUE THREAD

**Issue by victor-perez** [Templarian/MaterialDesign#1849]
[Downloads.tar.gz](https://github.com/Templarian/MaterialDesign/files/765951/Downloads.tar.gz)

* file-link
* file-phone
* file-mail

**Comment by Templarian** [comment]
@victor-perez Can you zip and attach them to your issue above. (drag/drop zip works).

**Comment by victor-perez** [comment]
@Templarian done

**Comment by CoDEmanX** [comment]
Looks too washed out IMO because the link symbol is not pixel perfect:

![image](https://user-images.githubusercontent.com/1309249/38770584-85719016-4015-11e8-97df-7738f005747c.png)

The envelope seems to almost touch the dog-ear. Could be made working with some tweaking I guess:

![image](https://user-images.githubusercontent.com/1309249/38770595-a79d30dc-4015-11e8-97b2-6e27bc176648.png)

This one seems alright. Would it be used to represent VCF files (vCards)?

![image](https://user-images.githubusercontent.com/1309249/38770608-d917b8da-4015-11e8-9402-b66b7e4a735c.png)

**Comment by PeterShaggyNoble** [comment]
Maybe try `file-link` with Google's version of [`link`](https://material.io/icons/#ic_link)?

**Comment by goyney** [comment]
We need to update `file-link` now that Google has updated their link icon.

**Comment by goyney** [comment]
[![file-link](https://materialdesignicons.com/icon/file-link)](https://materialdesignicons.com/icon/file-link)[![file-link-outline](https://materialdesignicons.com/icon/file-link-outline)](https://materialdesignicons.com/icon/file-link-outline)
[![file-phone](https://materialdesignicons.com/icon/file-phone)](https://materialdesignicons.com/icon/file-phone)[![file-phone-outline](https://materialdesignicons.com/icon/file-phone-outline)](https://materialdesignicons.com/icon/file-phone-outline)

`file-mail` doesn't seem to make too much sense, so it was omitted.
