### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by trevex** [Templarian/MaterialDesign#1864]
I installed the Material design icons via `npm install --save mdi` and I am including them via SASS.

However some icon class definitions seem to be missing including `cancel` and `grid-large`. When searching through the `scss` and `css` folder of `node_modules/mdi` no occurrences are found.

Is there a specific reason why they are missing and are intentionally left out or were they simply forgotten?

**Comment by Templarian** [comment]
https://materialdesignicons.com/history Those are just new icons.

We've added a lot of icons in the last few weeks getting ready for the release of Material Design Icons Light. [Preview Here](http://templarian.com/2017/02/11/compare-mdi-to-mdi-light/)

Processing through bug fixes for the next release right now. `1.9.xx` release.

**Comment by matthewrobb** [comment]
@Templarian @PeterShaggyNoble I've seen a few tickets pointing people to here despite this issue being closed. I think a problem worth addressing is that right now if I am looking for an icon and I find it on the website there's a reasonable change it's not in the webfont and there's very little if any documentation to be found detailing the webfont release status, no branches or PRs on the npm/bower repo.

At the very least if an issue sat open in one of the repos so that people having problems can find an easily self surfacing explanation it would likely go a long way to reducing confusion. If there's anything I can do to help let me know!

Is there any way of exposing the "build" process for the webfont to enable those who dare to get out ahead of an impending release if we know what we're working on isn't production bound any time soon?

**Comment by Templarian** [comment]
It's coming with the new site for a more continuous "nightly" release (actually can run it right now, but I don't have any page to host the files it generates yet)!

I'll try and generate and upload a nightly this week for those that want access.

Track it part of #1910

**Comment by Templarian** [comment]
The new site is being built to make releases more transparent. It will specifically let users know what release an icon was added (and which versions it was modified/renamed).

**Comment by RogerPMH** [comment]
In the meantime you might use mdi-block-helper, it's basically the same icon as Google's cancel.
