### ISSUE TITLE
Medieval weapons

### ISSUE THREAD

**Issue by lippekstro** [Templarian/MaterialDesign#1935]
Please icons of medieval weapons (bow and arrow, axes, spears...etc)

- [ ] Bow/Arrows
- [ ] Axe
- [ ] Spear
- [ ] Mace
- [ ] Staff

**Comment by Templarian** [comment]
We added more dice options that will go into `v1.9.xx` and are looking to add more RPG/game related icons so this will probably happen shortly.

**Comment by lippekstro** [comment]
Oh! great.
thanks

**Comment by Xenomorph99** [comment]
How about these? I'm not sure what to call the arrows since they could be confused with pointing arrows.

![bow-arrow](https://user-images.githubusercontent.com/1837101/95399914-8b630000-08c6-11eb-86f4-4d017eed2593.png)
![arrow](https://user-images.githubusercontent.com/1837101/95399909-8a31d300-08c6-11eb-80cf-1805b2dd1966.png)
![arrows](https://user-images.githubusercontent.com/1837101/95399912-8aca6980-08c6-11eb-8fbc-606c52c995f6.png)

![spear](https://user-images.githubusercontent.com/1837101/95399923-8c942d00-08c6-11eb-92cb-7ff96b02f757.png)

![axe-battle](https://user-images.githubusercontent.com/1837101/95399913-8aca6980-08c6-11eb-9540-5e3307bb3c37.png)

![mace](https://user-images.githubusercontent.com/1837101/95399918-8b630000-08c6-11eb-8636-5d4a42958a26.png)

![magic-staff](https://user-images.githubusercontent.com/1837101/95399919-8bfb9680-08c6-11eb-871f-0a1766cbe0fc.png)

[medieval-weapons.zip](https://github.com/Templarian/MaterialDesign/files/5344584/medieval-weapons.zip)

**Comment by GreenTurtwig** [comment]
`arrow-projectile` perhaps

**Comment by hanakin** [comment]
suggest adding a hammer or mallet as well

**Comment by goyney** [comment]
All those were added.
