### ISSUE TITLE
Icon: Financial Icons

### ISSUE THREAD

**Issue by sethrubenstein** [Templarian/MaterialDesign#194]
Paypal, Visa, Amex, etc...

**Comment by Templarian** [comment]
Sorry, the PayPal icon does not work for an monotone font. I recommend using a SVG or vector format for their logo (with a optional fallback png if on the web). It's really annoying, but I don't want to modify their logo since they have really specific terms of use around it. :frowning: 

The Credit Card logos have too much detail. At the moment only icons visible at 24x24 will be supported. This was a community decision between the contributors.
