### ISSUE TITLE
touch-app, flare, grain

### ISSUE THREAD

**Issue by r1si** [Templarian/MaterialDesign#2071]
Hi! 
I found  some icon that there is in google library but not in this library
here the link:
can you add ?

- [ ] https://material.io/icons/#ic_leak_add (see #1694)
- [ ] https://material.io/icons/#ic_leak_remove (see #1694)
- [x] https://material.io/icons/#ic_photo_size_select_large (See #3724)
- [ ] https://material.io/icons/#ic_touch_app
- [ ] https://material.io/icons/#ic_hdr_off (See #2004)
- [ ] https://material.io/icons/#ic_hdr_on (See #2004)

If you want I can do a pull request!

**Comment by CoDEmanX** [comment]
Grain is also missing

https://material.io/tools/icons/?search=grain&icon=grain&style=baseline

**Comment by goyney** [comment]
There's a bunch of requests in this issue, so let's clean them up:
 - `leak-add` and `leak-remove` will be handled in #1694 
 - `photo-size-select-large` was added in #3724 as `image-size-select-*`
 - `hdr` and `hdr-off` will be handled in #2004 

---

The `touch-app` icon is an interesting request, because we already have a set of `gesture-*` icons, and `gesture-tap` is very similar. I suggest we add it as `gesture-tap-hold`.

![image](https://user-images.githubusercontent.com/1015040/48990162-58148f00-f0fb-11e8-8964-c3f6a47f258f.png)

And the remaining two pointed out by @CoDEmanX:
![image](https://user-images.githubusercontent.com/1015040/48990203-87c39700-f0fb-11e8-8da8-4debf4350095.png)![image](https://user-images.githubusercontent.com/1015040/48990214-8f833b80-f0fb-11e8-9017-40115c4a6bb0.png)

[stock.zip](https://github.com/Templarian/MaterialDesign/files/2613898/stock.zip)

**Comment by Templarian** [comment]
Added these 3. Will close the other issues as I add them.
