### ISSUE TITLE
Lavalamp

### ISSUE THREAD

**Issue by Jonasvdp** [Templarian/MaterialDesign#2075]
Thanks!

**Comment by GreenTurtwig** [comment]
![puush-linux 2017-06-09 at 12 44 59](https://user-images.githubusercontent.com/15905797/26974091-af902a8a-4d11-11e7-94f3-dfefddffcb81.png)
![puush-linux 2017-06-09 at 12 46 18](https://user-images.githubusercontent.com/15905797/26974101-b5a6a250-4d11-11e7-911b-65495e75343a.png)
[lava-lamp.zip](https://github.com/Templarian/MaterialDesign/files/1063932/lava-lamp.zip)

Left this around for a while. :-/
Also tagging this with the `Home Assistant` label, since it's a lighting applicance.

**Comment by Templarian** [comment]
This is a nice "generic lighting" for odd light appliances. Marking as high priority for the next release.

**Comment by GreenTurtwig** [comment]
@Templarian I'm going to be taking a look at a lot of other lighting/appliances as well. ;-)
Should be really helpful for the user or Home Assistant (myself included). :cat2:

**Comment by Templarian** [comment]
[![lava-lamp](https://materialdesignicons.com/icon/lava-lamp)](https://materialdesignicons.com/icon/lava-lamp)

**Comment by JamesCoyle** [comment]
Wow. Definitely nailed this one.

**Comment by GreenTurtwig** [comment]
Heh, thanks. <3
