### ISSUE TITLE
Delete Multiple (Delete All & Delete Selected) Icon

### ISSUE THREAD

**Issue by DOCbrink** [Templarian/MaterialDesign#2137]
In order to select multiple objects and allow to remove them in one click, I suggest to have an icon to show this action ("delete selected").
This icon can do a "delete all" action too. 
The idea is to show that the user can delete more than one object with this icon.
Something like this [http://www.iconeasy.com/icon/ico/System/Shimmer/Document%20Delete.ico](Icon) but with the trashbin.

**Comment by JamesCoyle** [comment]
I would maybe have a think about your UI in general and perhaps consider changing the UI when multiple items are selected. If you look at the way apps like Google Keep or Inbox handle this, they change the title bar to show items are being selected and show new icons which relate to all of the selected icons instead of individual icons. Use the UI context itself rather than relying on the user being able to interpret the meaning of the icon.

**Comment by MrGrigri** [comment]
I would agree with @JamesCoyle and that you need to rethink your UI. However, wouldn't any of these icons work?

![delete-sweep](https://materialdesignicons.com/icon/delete-sweep) ![delete-forever](https://materialdesignicons.com/icon/delete-forever)

**Comment by PeterShaggyNoble** [comment]
Closing for now due to lack of response.
