### ISSUE TITLE
Candelabrum (antique)

### ISSUE THREAD

**Issue by sukhrobik** [Templarian/MaterialDesign#2160]
![antiques](https://user-images.githubusercontent.com/6409461/27196929-638c6a36-51da-11e7-9d0c-85fffb966bbb.png)

**Comment by shroudedcode** [comment]
@sukhrobik There's no real way to represent `antique` in icon form (same goes for other adjectives), adding `glower` icon could still be considered.

**Comment by Xenomorph99** [comment]
Let's use the colloquial `candelabra` instead of `candelabrum` for these icons.

> The word _candelabra_ became popularly used from the early 1800s. Since that time, however, the term has changed from the traditional ‘candelabrum’ as singular and ‘candelabra’ as the plural to the now more common singular of _candelabra_ and the plural _candelabras_.

Here's the reference: https://www.macmillandictionaryblog.com/candelabra

I included `candelabra-flame` as a variant using the flame shape from [candle](https://materialdesignicons.com/icon/candle).

![candelabra](https://user-images.githubusercontent.com/1837101/95635213-02c09d00-0a49-11eb-9bdd-d7ea0798c597.png)
![candelabra-flame](https://user-images.githubusercontent.com/1837101/95635210-02280680-0a49-11eb-8160-0e027aa58d90.png)

[candelabra.zip](https://github.com/Templarian/MaterialDesign/files/5357789/candelabra.zip)

**Comment by temaprint** [comment]
few icons (
look here
https://icons8.com/icons/set/candelabrum
<img src="https://img.icons8.com/doodle/48/000000/menorah--v1.png"/>
