### ISSUE TITLE
Pivot Table

### ISSUE THREAD

**Issue by Arbitrode** [Templarian/MaterialDesign#2161]
Need an icon for pivot table to change from flat table to pivot table, then maybe another for 'edit pivot table'.

**Comment by PeterShaggyNoble** [comment]
[Reference](https://icons8.com/icon/46316/pivot-table) from Icons8.

**Comment by JamesCoyle** [comment]
Need to get some workable ideas for this one. Should probably be based on one of our existing table icons.

**Comment by steodor** [comment]
Starting from @JamesCoyle's point on keeping consistency with the existing table icons, i tried something but i'm not sold on the arrows (hence 2 versions in which the second one has much better arrows but break the 2dp spacing rule of the guidelines). The body of the table can also be left filled instead of cut out, but not sure that the idea of column/row would be as clear.
![image](https://user-images.githubusercontent.com/4397338/107616762-59d4b980-6c57-11eb-97cf-4b4ab13c1f3b.png)![image](https://user-images.githubusercontent.com/4397338/107616769-5c371380-6c57-11eb-8adb-2f16b0df2a7e.png)
[table-pivot.zip](https://github.com/Templarian/MaterialDesign/files/5963932/table-pivot.zip)

**Comment by steodor** [comment]
Hmm, actually it's not that bad without the cutout. Not sure which is better though, the one with equal distance row/column or symmetric arrow shape? Personally i think the last one looks better.
![image](https://user-images.githubusercontent.com/4397338/107702237-a0133280-6cc2-11eb-9f38-dd383d225bb8.png)![image](https://user-images.githubusercontent.com/4397338/107702242-a43f5000-6cc2-11eb-9b48-480ecf3808ad.png)
[table-pivot-3-4.zip](https://github.com/Templarian/MaterialDesign/files/5968597/table-pivot-3-4.zip)

**Comment by steodor** [comment]
Ok, this is the best i've got, i started from `table-row` this time and the result is much better:
![image](https://user-images.githubusercontent.com/4397338/107738050-99aaa800-6d0e-11eb-92d2-965b9cf989c9.png)
[table-pivot.zip](https://github.com/Templarian/MaterialDesign/files/5970076/table-pivot.zip)

**Comment by goyney** [comment]
[![table-pivot](https://materialdesignicons.com/icon/table-pivot)](https://materialdesignicons.com/icon/table-pivot)
