### ISSUE TITLE
[CRITICAL] Exporting Icons/Bundles/Anything Throws Error

### ISSUE THREAD

**Issue by dintendocoltd** [Templarian/MaterialDesign#2181]
When exporting an icon into a png file, the image cannot be downloaded and the server responds with an error:

<code>Fatal error: Class 'Imagick' not found in /home/templarian/webapps/materialdesignicons/api/endpoints.php on line 1656</code>

URL: https://materialdesignicons.com/api/download/icon/png/598B7931-3DF8-4CFA-A6E6-80550CA31372/256/FFFFFF/1/000000/0/0/0/creation

This may have been caused by the Imagick module being removed.

**Comment by Templarian** [comment]
Yep, noticed this last night during testing, but haven't had a second to reinstall imagick on the server. My host kind of messed things up with their little "migration".

Fixed a few other smaller issues, but this I can resolve tonight.

**Comment by Templarian** [comment]
Just got home, looking into this now, but it could be a bit until this is resolved. Need to see why the current install broke during the migration. Hopefully just reinstalling fixes this.

**Comment by Templarian** [comment]
By the way, rebuilt and installed imgick, but it's not behaving correctly. Reaching out to support to see what could be going on. 32bit -> 64bit server caused this to break I believe. Also the PHP version update was incompatible with the extension version.

Fixed those, but the extension doesn't load. I think it's something on their end.

**Comment by JelleBlaauw** [comment]
Could you please give an update? This is kind of blocking for me at the moment.

**Comment by Templarian** [comment]
@JelleBlaauw No status update at the moment, the PHP extension is setup, but isn't being recognized by the new environment. Support ticket is opened, but no status update.

**Comment by btripp** [comment]
Glad to see that it is being worked on. Love the site @Templarian Keep up the good work!

**Comment by Templarian** [comment]
Very busy at the office today, and my host is unfortunately not responding to tickets it would appear. Hopefully tonight if they don't fix the issue I can try some other ideas (kind of out of ideas, it really should be working).

**Comment by Templarian** [comment]
Finally got an update on the ticket (no progress yet), they think it should be working also and are investigating the issue on the box.

**Comment by MrGrigri** [comment]
Just out of curiosity, who is your host with? I'll make sure not to use them. :wink:

**Comment by dintendocoltd** [comment]
@MrGrigri According to the DNS records, the server is hosted with webfaction.com.

**Comment by Templarian** [comment]
Updated the PHP version, which took me testing some of the larger API endpoints.

Please let me know if you notice any issues (there are a lot of third party libraries that I'm not sure if they support 5.6, but the site loads fine right now and the endpoints I hit seem fine so far). Working on the new site, so really happy this seems to work. Going to try and use the new site for the next build webfont release.

_Sorry for the delay getting this all up._ If it helps the new site will be on Digital Ocean (where the rest of my servers instances are and will run on a larger server). Due to how much bandwidth this site takes it's pretty affordable on the current host, but will help with the more complex download options.

(Had to send my new Surface Pro in for a replacement Tuesday after getting rid of my Surface Pro 4 great timing to have these server issues come up 😆).

**Comment by JamesCoyle** [comment]
Good to hear you're making progress on this. Server issues are a nightmare.

DigitalOcean is awesome but cost me a bit more than I'd like for minimal use though. Switched over to SiteGround for fixed rate hosting but would probably switch back to DigitalOcean once I get going and need more flexibility. It was all a bit beyond my understanding at the time but seemed incredibly robust and way more feature rich than other hosting options.

**Comment by JelleBlaauw** [comment]
Thanks for resolving this issue!
