### ISSUE TITLE
Vacuum cleaner

### ISSUE THREAD

**Issue by Chappie112** [Templarian/MaterialDesign#2217]
A simple vacuum cleaner icon

**Comment by vcantu** [comment]
Here's what I came up with
![vacuum-demo](https://user-images.githubusercontent.com/13156162/27998575-5a47c4f8-64c6-11e7-9bed-84eb5b8b9bf4.png)
[vacuum_svg.zip](https://github.com/Templarian/MaterialDesign/files/1134160/vacuum_svg.zip)

**Comment by Chappie112** [comment]
Thanks a lot, looks awesome!

**Comment by GreenTurtwig** [comment]
Personally, I would have no idea what it is without context. I feel a "canister" style vacuum would be better as well as it would have slightly more detail, making it more recognisable.

**Comment by MrGrigri** [comment]
I believe that the bag is the wrong shape and that the stem is too thick. Also, there is plenty of space left over, try to utilize that.

**Comment by Templarian** [comment]
Agreed with the above, may need to think of a different style/type of vacuum.

**Comment by vcantu** [comment]
How's this?
![vacuum-demo](https://user-images.githubusercontent.com/13156162/28048136-cf168296-65a3-11e7-868d-f48e81888605.png)
[vacuum_cannister_svgs.zip](https://github.com/Templarian/MaterialDesign/files/1137556/vacuum_cannister_svgs.zip)

**Comment by JapanYoshi** [comment]
@vcantu Can you follow the guidelines? Strokes are tapered, not rounded, and counter strokes are 2px.

**Comment by vcantu** [comment]
@JapanYoshi Is this what you meant?
![vacuum-fixed](https://user-images.githubusercontent.com/13156162/28048557-9d2f866c-65a6-11e7-83a2-0370158c0d4e.png)

**Comment by i00** [comment]
This does not appear to have been released yet?! ... also I would like a stick vac also like @vcantu proposed in his first response.

**Comment by Templarian** [comment]
The hose needs to be "cleaned" up a little bit. Maybe more geometric.

**Comment by Templarian** [comment]
@i00 Not sure on the design for the canister vacuum yet. Maybe something more modern looking. Not like the dyson ball, but something that uses a round canister. Bag vacuums are old school and may not be as recognized (don't worry I feel old right now saying that also).

**Comment by juchong** [comment]
My specific use-case is controlling a shop vacuum using a smart switch. Something like this would clearly show that the vacuum is meant to be used by a human rather than the robo-vacuum icons currently in the library. I'd recommend making the hose a bit thinner and calling it good!

**Comment by Templarian** [comment]
@juchong Added the `Home Assistant` label so it might be more eyes.

**Comment by vcantu** [comment]
I can work on updating these, but would want to know which variants to draw.
Which of these is most like what we want?

![Screen Shot 2021-02-01 at 4 25 20 PM](https://user-images.githubusercontent.com/13156162/106520148-50568f00-64aa-11eb-9997-19b5a3a5dea4.png)

**Comment by MGHollander** [comment]
> I can work on updating these, but would want to know which variants to draw.
> Which of these is most like what we want?

I like all of them :-D, but the fourth one (left to right, top to bottom) the most.

**Comment by juchong** [comment]
Sorry for the late reply! I must have missed the notification @vcantu! 

I suggest adding both of these since they fulfill slightly different roles. This vacuum is meant to represent a vacuum you'd find in a garage:
<img width="156" alt="image" src="https://user-images.githubusercontent.com/342107/111678037-37a1fe80-87f6-11eb-93b3-77a978847dde.png">

This icon is meant to represent a standard home vacuum: 
<img width="175" alt="image" src="https://user-images.githubusercontent.com/342107/111678154-5b654480-87f6-11eb-85e5-e08afb9d14cf.png">

**Comment by jhein05** [comment]
I have no qualification to add my opinion here, but I'll do it anyway. Haha. I do feel that most of the suggested examples are to detailed and that the icon should me more generic in order to represent most of the vacuums out there. I would do a normal/generic icon and a handheld/battery, because those two are the major types and different enough to warrant two different icons. There is already an issue for a handheld one here: #6026 

For the generic one, I think this could be a good example:
https://www.gettyimages.com/detail/illustration/vacuum-icon-flat-graphic-design-royalty-free-illustration/489124046

**Comment by goyney** [comment]
[![vacuum](https://materialdesignicons.com/icon/vacuum)](https://materialdesignicons.com/icon/vacuum)[![vacuum-outline](https://materialdesignicons.com/icon/vacuum-outline)](https://materialdesignicons.com/icon/vacuum-outline)
