### ISSUE TITLE
phone-location

### ISSUE THREAD

**Issue by kiernann** [Templarian/MaterialDesign#2238]
Something like `account-location` but with `phone` substituted for `account` within the box.

Mockup: 
![phone-location](https://user-images.githubusercontent.com/18021678/28188358-e2505730-67ef-11e7-88ee-309711914fda.png)

Or, replace the box with a circle to more closely match Google's [Find My Device](https://play.google.com/store/apps/details?id=com.google.android.apps.adm&hl=en) icon:

![find-my-device](https://user-images.githubusercontent.com/18021678/28188382-0063fb14-67f0-11e7-9761-b553905cb782.png)

**Comment by k5cents** [comment]
Or, if somebody were able to pull the icon used by Google Play Services when Find My Device locates said device: 

![fmd_noti](https://user-images.githubusercontent.com/18021678/28188556-8d024ada-67f0-11e7-89ad-af2b2eb96256.png)

**Comment by augustin32** [comment]
![phone-location24](https://user-images.githubusercontent.com/14167196/28218877-9b0eb3a2-68c2-11e7-9e06-5da45e196cd8.png)
![phone-location36](https://user-images.githubusercontent.com/14167196/28218880-9cbdcf4e-68c2-11e7-98ca-de70904aab0b.png)
![phone-location48](https://user-images.githubusercontent.com/14167196/28218883-9eeff558-68c2-11e7-8073-ac1fb4a68d9d.png)

[phone-location.zip](https://github.com/Templarian/MaterialDesign/files/1148892/phone-location.zip)

**Comment by JamesCoyle** [comment]
I think we should stick to square TBH. It's best we keep to a standard and a circular icon restricts the available space for the inner icon.

**Comment by PeterShaggyNoble** [comment]
Here's the SVG Google use as a map pin:

https://ssl.gstatic.com/android/fmd/static/be8632f979265f2940ae4c912e56d9ac/images/avatar-phone.svg

**Comment by steodor** [comment]
@kiernann @PeterShaggyNoble how's this for a start? Based off existing location marker and phone icons:
![image](https://user-images.githubusercontent.com/4397338/108431597-c1889700-724b-11eb-8116-7b794f3778b2.png)
[phone-location.zip](https://github.com/Templarian/MaterialDesign/files/6006366/phone-location.zip)

**Comment by PeterShaggyNoble** [comment]
We have since added `map-marker` as a modifier (e.g. `bus-marker`) so I think using that in conjunction with `cellphone` as the base icon to give us `cellphone-marker` might be the best approach here.

**Comment by steodor** [comment]
@PeterShaggyNoble first of all thank you for your time! I understand what you're saying, and while i agree that `cellphone-marker` would be a good addition to the exiting `cellphone-*` range, i don't think it would be the best fit here because it reverses meaning. That icon would tell me that a location is visible / stored / accesible on my cellphone, not that my cellphone is at some location.

Thanks for giving me a hint about the naming though (i didn't pay enough attention initially, sorry), so keeping in line with the rest of the library i guess `map-marker-cellphone` would be appropriate for placing phones on a map.

Also i fixed the cellphone shape to bring it closer to the one used in `monitor-cellphone`, which looks much better. It's just 1dp narrower to allow for centering without having subpixel antialiasing making its edges blurry at native resolution. What do you think?
![image](https://user-images.githubusercontent.com/4397338/108474325-e276d980-7297-11eb-8a15-c531ae8614bf.png)
[map-marker-cellphone.zip](https://github.com/Templarian/MaterialDesign/files/6008436/map-marker-cellphone.zip)
