### ISSUE TITLE
Waterfall & Pond

### ISSUE THREAD

**Issue by coogle** [Templarian/MaterialDesign#2249]
Hello,

It would be wonderful to have a Waterfall and/or Pond glyph for Home Assistant!

**Comment by augustin32** [comment]
![waterfall24](https://user-images.githubusercontent.com/14167196/28290897-f538076c-6b50-11e7-8ac0-03733c38325c.png)
![waterfall36](https://user-images.githubusercontent.com/14167196/28290901-f73f3b5c-6b50-11e7-940a-5edd6a0e7f2d.png)
![waterfall48](https://user-images.githubusercontent.com/14167196/28290905-f98b6b92-6b50-11e7-973d-609d33ee32eb.png)

[waterfall.zip](https://github.com/Templarian/MaterialDesign/files/1154065/waterfall.zip)

**Comment by coogle** [comment]
There are a few decent ones here, but I don't know if they can be borrowed?

https://www.shareicon.net/tag/waterfall

https://www.shareicon.net/natural-landscape-river-water-nature-waterfall-776412

**Comment by MrGrigri** [comment]
A waterfall is very detailed and will be very difficult to represent in the Material Design pattern. @augustin32, I believe that your implementation does not reflect waterfall at all.

**Comment by augustin32** [comment]
@MrGrigri Well...i see this, but it's hard to do a waterfall in a 24px grid

**Comment by JamesCoyle** [comment]
Not sure if this is gonna be doable but someone may be able to come up with something.

**Comment by steodor** [comment]
@JamesCoyle sorry i'm late :) so, i started with the proposed icon, but took our existing `wave` as reference and since it had square linecaps, i went with that all the way. They can be tweaked of course but the second one looks ok i guess?
![image](https://user-images.githubusercontent.com/4397338/108433519-cb5fc980-724e-11eb-9204-fe395b71efdd.png)![image](https://user-images.githubusercontent.com/4397338/108433523-cdc22380-724e-11eb-98ba-33c82d500791.png)
[waterfall.zip](https://github.com/Templarian/MaterialDesign/files/6006448/waterfall.zip)

**Comment by steodor** [comment]
And about the `pond`, i found this [noun project](https://thenounproject.com/search/?q=pond&i=2777127) idea that would be doable, of course using our existing `wave`:
![image](https://user-images.githubusercontent.com/4397338/108435448-221ad280-7252-11eb-9394-53724077bcfb.png)
[pond.zip](https://github.com/Templarian/MaterialDesign/files/6006543/pond.zip)

**Comment by Pmoshbr** [comment]
A news about this icon request?? will be implemented...

**Comment by goyney** [comment]
I've added `waterfall`.
[![waterfall](https://materialdesignicons.com/icon/waterfall)](https://materialdesignicons.com/icon/waterfall)

`pond` is too hard and too ambiguous. How to differentiate lake? Ocean? Sea? Just use `waves` and it should work contextually.
