### ISSUE TITLE
Change icon padding for Android L style

### ISSUE THREAD

**Issue by QuadFlask** [Templarian/MaterialDesign#227]
Which I downloaded from [http://materialdesignicons.com/](http://materialdesignicons.com/) by `Download Package` - `Android 5.x` have small padding.
I think Android package have to match padding(?) like google's material icons.
24x24 icon should using space 18x18 rather than 22x22.

I love your icons, Thanks!

**Comment by Templarian** [comment]
It is just that one icon (qrcode)? Or are there others.

**Comment by QuadFlask** [comment]
I suggest all of icons. Because Android L's icon guide line what you said 'space 18x18 rather than 22x22'. to match google's look and feel. Is it hard to change? I think just changing packaging is end.

**Comment by Templarian** [comment]
@QuadFlask Yea, the rest are styled to the Android L size. It is just that one icon that is 22x22 since it doesn't look like a QR code at the smaller size.

Contributors what do you think?

![image](https://cloud.githubusercontent.com/assets/338885/6733030/80b1c2fc-ce1d-11e4-9a81-10df820c06bd.png) vs ![image](https://cloud.githubusercontent.com/assets/338885/6733033/8576bbbc-ce1d-11e4-8de3-9f896d34240a.png)

**Comment by Templarian** [comment]
The vote was 4v0. Swapped it for the smaller one.

http://materialdesignicons.com/icon/qrcode
