### ISSUE TITLE
Add note about using Material Icons in Vue

### ISSUE THREAD

**Issue by robcresswell** [Templarian/MaterialDesign#2281]
Hi!

I put up a small library a few days ago ([Vue Material Design Icons](https://www.npmjs.com/package/vue-material-design-icons "vue-material-design-icons on NPM")), which is simply a wrapper of the SVG icons as Vue single-file-components. It's really unopinionated about how you use them (a lot of other options register everything immediately as a global component), but offers some suggestions, optional CSS, in the README. It also has some simple accessibility via ARIA and semantic elements.

2 questions:

1. I've put a very explicit credit in the README, as well as using MaterialDesign as a git submodule  so the link is clear; is this enough for you to be happy with me using your library?

2. Could / should I add a note to your documentation about how people can easily use the icons in their vue project by using my library? I think its useful, but I'm obviously very biased as the author.

Thanks for your time

**Comment by Templarian** [comment]
@robcresswell This is exactly why we supply the new `mdi-svg` repo so that cool projects like this can exist. The new site will give documentation on various options for each framework.

https://github.com/Templarian/MaterialDesign-Site/tree/master/src/content

This is the new site's documentation, preview it here: http://dev.materialdesignicons.com/getting-started/angularjs (this is not the latest code, still working locally a lot, will try and update more, but feel free to pull request a `getting-started-vue.md` file).

We're going to be pushing third party integration on the new site (I personally can't support more than Angular/AngularJS/Webfont/Bootstrap integration, too much work outside of this project).

Thanks!

**Comment by Templarian** [comment]
If you want to document it on the current site make a quick pull request to the file below...

https://github.com/Templarian/MaterialDesign/blob/master/site/getting-started.savvy (after the react section).

**Comment by robcresswell** [comment]
Great! I hadn't noticed that, I'll update my library to use the compressed paths, and put up a PR to document it.

**Comment by robcresswell** [comment]
I'll submit a PR for the other repo too, later this evening
