### ISSUE TITLE
Compress (Vice / Winzip style icon)

### ISSUE THREAD

**Issue by velasarius** [Templarian/MaterialDesign#2305]
Vice or Compress type icon similar to WinZip's icon. I was trying to express a 'packaged data' or 'data in the process of being packaged' symbol, nothing to do with file compression per se.

**Comment by MrGrigri** [comment]
Would `arrow-collapse` not work?

![arrow-collapse](https://materialdesignicons.com/icon/arrow-collapse)

**Comment by velasarius** [comment]
That icon relates to more to View, I need an icon that relates more to Data.

**Comment by MrGrigri** [comment]
Here are my attempts. Since it's relative to data, I'm using the `database` icon.

![data-compress](https://user-images.githubusercontent.com/4528551/28895883-672e9fa0-7797-11e7-89a2-8a342c36cf09.png) ![data-uncompress](https://user-images.githubusercontent.com/4528551/28895884-6732fc62-7797-11e7-8828-f0745c893fc1.png)

[data-compress.zip](https://github.com/Templarian/MaterialDesign/files/1195362/data-compress.zip)

**Comment by JamesCoyle** [comment]
Looks ok at 24x24 but not a fan of the larger versions.  :/

**Comment by JamesCoyle** [comment]
We have 
[![](https://materialdesignicons.com/icon/zip-box)](https://materialdesignicons.com/icon/zip-box)

The beauty of MDI is that icons can be used in multiple ways so `arrow-compress` could work for both views and data.

**Comment by velasarius** [comment]
Thanks for your suggestions, I ended up going with the DNA icon to symbolize data control, filtering, etc. I know there are other icons that directly apply to filtering and data control, but as this is a user document, I needed something that could also go beyond the specific meaning. thanks again

**Comment by JamesCoyle** [comment]
To the community: Would it be worth looking into ways of showing this? I feel like we could at least do with a better icon to represent zip.

**Comment by PeterShaggyNoble** [comment]
`arrow-collapse-horizontal` and `arrow-collapse-vertical` have since been added which do a better job at representing what's being asked here.

I agree with @JamesCoyle that we need a better representation of a zip file than `zip-box` but let's continue that discussion in the more recently active #2825.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
