### ISSUE TITLE
Developer tools icon

### ISSUE THREAD

**Issue by paullryan** [Templarian/MaterialDesign#2334]
An icon to denote developer tools, to be used for things like toggling developer tools on and off.

I've created the following as a reference (using google's icons as a baseline).
![debug](https://user-images.githubusercontent.com/3146164/29472207-31fa2054-8410-11e7-8014-456144c4af75.png)
<img width="24" alt="debug 2x" src="https://user-images.githubusercontent.com/3146164/29472208-31fa5b50-8410-11e7-9b01-8089e332bd55.png">
![debug 3x](https://user-images.githubusercontent.com/3146164/29472209-320070b2-8410-11e7-98e0-4a338d276fe6.png)

**Comment by buutqn** [comment]
I'm not sure, but i think you should provide an SVG file inside a zip file...

**Comment by JamesCoyle** [comment]
We generally use one of the code icons such as:
[![](https://materialdesignicons.com/icon/code-tags)](https://materialdesignicons.com/icon/code-tags)

**Comment by GreenTurtwig** [comment]
Yeah, the `bug` icon is used to represent "debug" rather than "dev tools", I see where you going with the icon though as some IDEs do use a beetle with a crosshair on it rather than just a plain beetle icon. I agree with @JamesCoyle `code-tags` is a better fit to represent "dev tools".
[![](https://materialdesignicons.com/icon/bug)](https://materialdesignicons.com/icon/bug)

**Comment by Templarian** [comment]
Closing as too niche. Will reopen if there is more discussion / examples.
