### ISSUE TITLE
Import SmartVISU icons

### ISSUE THREAD

**Issue by lolouk44** [Templarian/MaterialDesign#2352]
I'm switching over from SmartVISU to home-assistant.
Home-assistant pulls its icons from mdi, but many home automation related icons are missing.
Any way we could import those from SmartVISU?
See list of icons [here](http://docu.smartvisu.de/2.8/index.php?page=design/design_icons)
I've attached the svgs.
[SmartVISU_Icons.zip](https://github.com/Templarian/MaterialDesign/files/1254736/SmartVISU_Icons.zip)

**Comment by MrGrigri** [comment]
These do not conform to the MD standards.

**Comment by Templarian** [comment]
This is going to be too niche / similar icons or requests might exist.

**Comment by lolouk44** [comment]
Sorry if I sound difficult, this is my first post / request. can you point me in the right direction so that I know what's not conform, what needs changing and then I can see if a similar request is present before submitting new requests in the future?
Thanks

**Comment by GreenTurtwig** [comment]
The icons can't be added because they don't follow the Material Design guidelines: https://material.io/guidelines/style/icons.html#icons-system-icons

Individual issues will need to be opened for each icon that you would like to be added to the set, then hopefully someone will come up with a design following the guidelines.

Meanwhile if you want to use the SmartVISU icons in Home Assistant while you wait, you can give entities an `entity_picture` with with the URL poitning to the location of a SmartVISU icon. There is more info here: https://home-assistant.io/docs/configuration/customizing-devices/
I actually use Home Assistant myself, it's an amazing example of open source.

**Comment by lolouk44** [comment]
Thanks @GreenTurtwig for your detailed help and guidance, much appreciated :)

**Comment by GreenTurtwig** [comment]
No problem. 🐱
