### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by rvoltolini** [Templarian/MaterialDesign#2383]
![world_time_zones-512](https://user-images.githubusercontent.com/30928235/30031131-a446d73e-9166-11e7-80bc-833a1a8d20af.png)
![maps-timezone-icon](https://user-images.githubusercontent.com/30928235/30031132-a44e3696-9166-11e7-8518-a1368bef20c7.png)

**Comment by augustin32** [comment]
What about this?
![timezone24](https://user-images.githubusercontent.com/14167196/30076881-056243ec-9283-11e7-8252-7830347211be.png)
![timezone36](https://user-images.githubusercontent.com/14167196/30076883-07025aca-9283-11e7-8b42-6d7d1f83f337.png)
![timezone48](https://user-images.githubusercontent.com/14167196/30076888-0aa29762-9283-11e7-856d-fa752dc8d04c.png)
[timezone.zip](https://github.com/Templarian/MaterialDesign/files/1278514/timezone.zip)

**Comment by rvoltolini** [comment]
It's better than my suggestions, especially at lower resolution

**Comment by MrGrigri** [comment]
I like it.

@augustin32 as a side note, it will help if you use one of the [templates](https://github.com/Templarian/MaterialDesign/tree/master/templates/icon) created for this pack. That will help in creating the different variants of the icon.

**Comment by GreenTurtwig** [comment]
Is there any reason why the map isn't based on the `map` icon currently in the set and instead larger with pointed corners (no idea why Google decided to give their map icon rounded corners...)?
Also it might be worth removing the empty space around the clock, like `calendar-clock` and `timetable`, and see how that turns out. :cat2:

**Comment by augustin32** [comment]
@MrGrigri i use one of the templates, and when i open the svg it is at 24x24 pixel size (i work affinity designer).

**Comment by augustin32** [comment]
![timezone24](https://user-images.githubusercontent.com/14167196/30112374-d1c46e06-9319-11e7-919c-7f48d7d998f8.png)
![timezone36](https://user-images.githubusercontent.com/14167196/30112378-d4593eb2-9319-11e7-9545-d81cd6ef6ae5.png)
![timezone48](https://user-images.githubusercontent.com/14167196/30112382-d78661b4-9319-11e7-8c85-2c978121e581.png)
![timezone-variant24](https://user-images.githubusercontent.com/14167196/30112603-a16945b4-931a-11e7-8c58-00031ad69b0c.png)
![timezone-variant36](https://user-images.githubusercontent.com/14167196/30112607-a47cee7c-931a-11e7-8217-34966d423311.png)
![timezone-variant48](https://user-images.githubusercontent.com/14167196/30112613-a6b29534-931a-11e7-8f7f-e7d96a8f46ba.png)
![timezone-filled24](https://user-images.githubusercontent.com/14167196/30112614-a99f8e28-931a-11e7-8f43-e3e1b50060ae.png)
![timezone-filled36](https://user-images.githubusercontent.com/14167196/30112617-aac00fb2-931a-11e7-9e8b-005371c20eea.png)
![timezone-filled48](https://user-images.githubusercontent.com/14167196/30112623-ae51f51e-931a-11e7-880b-06b3ed1d8b55.png)
[timezone.zip](https://github.com/Templarian/MaterialDesign/files/1281094/timezone.zip)

**Comment by augustin32** [comment]
Also, i corrected the original map icon, because it has some weird corners
![image](https://user-images.githubusercontent.com/14167196/30112752-184ef16a-931b-11e7-817f-9bd2b1acb159.png)
![image](https://user-images.githubusercontent.com/14167196/30112766-240f3dca-931b-11e7-893d-24c993b0efc9.png)
[map-corrected.zip](https://github.com/Templarian/MaterialDesign/files/1281097/map-corrected.zip)

**Comment by MrGrigri** [comment]
@augustin32 that's weird because when I opened it up in Illustrator, it was around 100 pixels. Idk, looks good though. I believe that the last one is the best.

**Comment by rvoltolini** [comment]
any prevision?

**Comment by CoDEmanX** [comment]
The only other way I see would be some grid:

![image](https://user-images.githubusercontent.com/1309249/38772430-9bf01058-4036-11e8-952d-ecb981deaf09.png)

[timezone2.zip](https://github.com/Templarian/MaterialDesign/files/1911068/timezone2.zip)

There's very little space, otherwise some of the grid lines could be irregular like real time zone borders, but that's not really possible here... 

![timezone2b](https://user-images.githubusercontent.com/1309249/38772501-9b9c5cb8-4038-11e8-8b12-546321682b98.png)

**Comment by rvoltolini** [comment]
![cake](https://user-images.githubusercontent.com/30928235/45116531-64ef9b00-b129-11e8-9337-7358dcf3da29.png)
One year!
hahahahahahahaha

**Comment by PeterShaggyNoble** [comment]
@rvoltolini, we know expect to see you posting cake to all open issues on their anniversaries! 😆

**Comment by rvoltolini** [comment]
@PeterShaggyNoble only in my issues! :-P

**Comment by Templarian** [comment]
[![map-clock](https://materialdesignicons.com/icon/map-clock)](https://materialdesignicons.com/icon/map-clock) [![map-clock-outline](https://materialdesignicons.com/icon/map-clock-outline)](https://materialdesignicons.com/icon/map-clock-outline)
