### ISSUE TITLE
Public CDN - Documentation & more

### ISSUE THREAD

**Issue by tomap** [Templarian/MaterialDesign#2394]
Hi,

I saw that you have at least two CDN setup.
One is mentioned here #2061 
https://cdn.materialdesignicons.com/1.8.36/
and another here:
https://cdnjs.com/libraries/MaterialDesign-Webfont

There are 3 issues with those:
- none is mentioned in the documentation/readme. Could be mentionned in the getting started guide here https://materialdesignicons.com/getting-started
- the one on CDNJS is linked to this repo https://github.com/Templarian/MaterialDesign-Webfont which has very few stars and fork, which in turn makes this project poorly ranked on CDN JS when you search for "material design icons": https://cdnjs.com/ Maybe it could be "linked" to this repo instead?
- in the CSS, you reference ../fonts/...?v=2.0.46 which is redundant with the folder name https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/2.0.46/css/materialdesignicons.css You could skip ?v=2.0...

Regards,

ThomasP.

**Comment by Templarian** [comment]
The CDN is the same build as provided through `npm` and `bower`. You can edit the `getting-started` page by clicking the button at the top right. 'Edit on GitHub' (new site is the same way).

I never setup the `cdnjs` one. Someone else must have. Right now I'm seeing about 7TB per month.

The new site that is being coded right now will expand on the documentation (been swamped, hopefully will have time this winter to wrap it up). https://github.com/Templarian/MaterialDesign-Site

I'm going to be pushing the use of the SVG's over the webfont in the future, so not going to put too much stress.

You can edit any of the documentation pages below (might quickly pull these into the current site while since the docs do need to be expanded on).
https://github.com/Templarian/MaterialDesign-Site/tree/master/src/content

**Comment by Templarian** [comment]
For manageability on my half it's easier to have the repos split up. We also have the SVG repo for third party applications/libraries.

https://github.com/Templarian/MaterialDesign-SVG

**Comment by goyney** [comment]
Closing as the new site already has much improved documentation and we're not likely to update the current site with this information with the new site on the horizon.
