### ISSUE TITLE
How to attribute License in Android app?

### ISSUE THREAD

**Issue by ursusursus** [Templarian/MaterialDesign#2521]
Hi guys, I want some advice regarding how to bundle the license concerning icons I use from you. 

Is comment above the .svg file okay? Does the license have to be readable from the app´s ui by app´s user? If so then how? i.e. how should I refer to an icon (by name? by actually displaying the icon?)

**Comment by Templarian** [comment]
Licenses files only exist in the code repo not the UI/app. You can put the license file anywhere, but tbh it's not even needed if it's not an open source app (since who would know).

We'll work on covering this in more detail in the new site once this page is written:
https://github.com/Templarian/MaterialDesign-Site/issues/2

**Comment by ursusursus** [comment]
Thanks.

Btw there is a precedence nowadays for apps to include the list of opensource code libraries in the actual apps ui. So you think this is just a paying tribute to authors, not a obligation stemming from the license?

**Comment by Templarian** [comment]
Depends on if a project is attribution / non-attribution. The license we have doesn't require it, but there is nothing to stop people from adding attribution on a about page.

I think some devs do this because they use a lot of open source to make their apps.

Good point we'll try to clarify this on the new site.

**Comment by ursusursus** [comment]
How would i attribute an icon in the about page, i.e. how should I refer to it?

**Comment by JamesCoyle** [comment]
You could just put something like "Icons provided by Material Design Icons" and link to the site.

**Comment by ursusursus** [comment]
Well, not all of them are 😄
