### ISSUE TITLE
Why aren't mapped icons from this set to the original Material Design icons?

### ISSUE THREAD

**Issue by xgebi** [Templarian/MaterialDesign#2545]
Why in original there's 'chat-bubble' but this project has it as 'message'?

P.S.: Sorry for hositility but year ago I hoped that I could avoid this particular project forever.

**Comment by JamesCoyle** [comment]
This project was here first and we went with a more natural noun/verb based naming system instead of Google's naming based on implementation specifics. The Google release came afterwards and changing our naming convention would have broken existing implementations. Our naming system allows icons to be more general purpose.

We do provide SVGs for all icons so if you would rather use Google's official set you could use inline SVG for any icons you need from our set.

**Comment by PeterShaggyNoble** [comment]
As @JamesCoyle mentioned, this library predates the official release of the stock icons by about 4 months so @Templarian based the naming convention off FontAwesome instead.

If you are using the webfont, it's fairly straightforward to edit the CSS to change the class names to match the ones Google use.

**Comment by xgebi** [comment]
So no good reason for not following official Material Design guidelines :(

**Comment by JamesCoyle** [comment]
There are no guidelines for icon naming in the material guidelines. 

This is a completely separate project and it's up to the user which icon set to go with. Don't like our naming system? Don't use our iconset.

**Comment by xgebi** [comment]
With all due respect I think that by releasing official Material Design icons designers at Google gave a good naming guidelines.

I wish I didn't have to but a lot of fools think that you are official and that would mean quitting my job which is otherwise decent.

**Comment by PeterShaggyNoble** [comment]
As we've mentioned multiple times already, this project pre-dates the stock icons by 4 months meaning there were *no* naming conventions to work with (there are still no naming *guidelines* - Google name their icons with ligatures in mind) so Templarian came up with his own convention and guidelines, influenced FontAwesome's.

A lot of the stock icons have been aliased with their Google names and there's a tonne of work being put into adding more aliases, all to help those making the transition to more easily find the icons they need.

Both James and I have offered solutions to try to help with whatever issue it is you're having but, unless you provide the specifics of the issue so that we can try to offer a solution more particular to your situation, I don't know what you expect to come of this conversation.

**Comment by xgebi** [comment]
Frankly speaking I didn't expect sunk cost fallacy and "go away". I expected something along the lines "we are working on it" or "we missed this one".

**Comment by PeterShaggyNoble** [comment]
At which point were you told to "go away"? Your question as to why our naming scheme differs from Google's was answered multiple times, you were provided with 2 solutions and you offered further assistance upon providing specifics, which you have not done.

Nothing constructive can come of this conversation so I'm recommending it be locked/deleted.
