### ISSUE TITLE
Lingerie Icon

### ISSUE THREAD

**Issue by BrunoGiubilei** [Templarian/MaterialDesign#2546]
I need a bra or other think like something this to my app

**Comment by kmohl** [comment]
Couldn't resist the challenge :)
![lingerie-outline](https://user-images.githubusercontent.com/24955518/31987740-0ce26244-b96d-11e7-8f34-52bcb87ea614.png)
[lingerie-outline.zip](https://github.com/Templarian/MaterialDesign/files/1413768/lingerie-outline.zip)

**Comment by BrunoGiubilei** [comment]
tks @kmohl for your time! but i looking for another think, much more material, less real image.

**Comment by JamesCoyle** [comment]
@kmohl Have you had a read of the material guidelines yet? Your icons aren't really capturing that material style.

https://material.io/guidelines/style/icons.html#icons-system-icons

**Comment by kmohl** [comment]
@BrunoGiubilei Sure, it's your call. These icons from Google's own material set look prety much like the real thing:

1. https://material.io/icons/#ic_fingerprint
2. https://material.io/icons/#ic_radio
3. https://material.io/icons/#ic_weekend
4. https://material.io/icons/#ic_pets
5. https://material.io/icons/#ic_content_cut
6. https://material.io/icons/#ic_format_paint
7. https://material.io/icons/#ic_directions_bike

@JamesCoyle Thanks, I'm familiar with the guidelines. And that's why I'd like you to elaborate how exactly my icons are so different and don't "capture that material style"?

**Comment by kmohl** [comment]
Ok @JamesCoyle you were right. @BrunoGiubilei How does it look now?

![lingerie](https://user-images.githubusercontent.com/24955518/32094895-9ec70bac-bb01-11e7-913b-9a2176d998d8.png)
[lingerie.zip](https://github.com/Templarian/MaterialDesign/files/1421293/lingerie.zip)

**Comment by kmohl** [comment]
Here's another take.
![lingerie-2](https://user-images.githubusercontent.com/24955518/32099879-6d4f8e8a-bb12-11e7-8ee0-fb627bfd09b6.png)
[lingerie-2.zip](https://github.com/Templarian/MaterialDesign/files/1421714/lingerie-2.zip)

**Comment by kmohl** [comment]
Hi, here's the updated design.
![lingerie-outline](https://user-images.githubusercontent.com/24955518/67868533-67326700-fb2c-11e9-87d6-ca19fa068392.png)
[lingerie-outline.zip](https://github.com/Templarian/MaterialDesign/files/3789526/lingerie-outline.zip)

**Comment by Templarian** [comment]
YEah, can't think of another way to design this within the guidelines. This might be the closest we can get.

**Comment by goyney** [comment]
[![lingerie](https://materialdesignicons.com/icon/lingerie)](https://materialdesignicons.com/icon/lingerie)
