### ISSUE TITLE
Phone hardware buttons

### ISSUE THREAD

**Issue by irplus-remote** [Templarian/MaterialDesign#2588]
Hi, i use this icon in my app as a drawable, as MDI do not offer something like this. It is to customize the function of the hardware volume buttons

This is an icon to represent the hardware-buttons (volume+/volume-) of a phone. This could be also extended to a 3-button version when power is to be shown too

![image](https://user-images.githubusercontent.com/14196521/32483039-8fced520-c39a-11e7-8263-a3158ef18cd5.png)

![ic_action_settings_cell](https://user-images.githubusercontent.com/14196521/32483028-846b87a0-c39a-11e7-9bbb-994453b6467f.png)

I hope this can be added in a future version :)

**Comment by steodor** [comment]
Hi, here's my take on it, starting from the existing `cellphone` icon. They bend a few MD guidelines so i doubt they are library material, but you can use the paths directly from the attached zip file if they're good enough for you. I moved the phone to the left and cut it so that it's clear it's a phone but the focus is not quite on it, and then i used both volume and power buttons and separated them from the phone one at a time to indicate which buttons exactly you want to draw focus on:
![image](https://user-images.githubusercontent.com/4397338/110308201-82f32a80-8008-11eb-9a8d-83faa2ba7c52.png)![image](https://user-images.githubusercontent.com/4397338/110308211-85ee1b00-8008-11eb-9bf7-dd8f3e1dbb80.png)
[cellphone-buttons.zip](https://github.com/Templarian/MaterialDesign/files/6100601/cellphone-buttons.zip)

**Comment by goyney** [comment]
I’m honestly not a fan. There’s general power and volume icons. Why would those not work in this case?

The problem with the proposed icons is that every phone is different and these feel like they’re trying to be specific to a device, even though I know they’re not.

**Comment by irplus-remote** [comment]
I use the proposed icon to map specific application functions to each hardware button , which happen to be volume+, volume- and power. So it must be one single icon which means "map hardware buttons to something different" 

I understand that not all phones have the buttons on the same place, but to be honest, 99% of androids do. Either on the right or on the left.

**Comment by steodor** [comment]
@goyney I understand that these icons are not library material, it was just an attempt :) i agree that they are weird the way i made them, but @irplus-remote has a point as well in that the semantics of this icon would be different than the generic power and volume icons. So they should be depicted in a different manner, i just don't have a good idea yet. Also, making 2 icons was unnecessary in this scenario, so let's try with 2 floating buttons:
![image](https://user-images.githubusercontent.com/4397338/110343052-c3689d80-8034-11eb-9248-12fab579a575.png)
[cellphone-hardware-buttons.zip](https://github.com/Templarian/MaterialDesign/files/6102411/cellphone-hardware-buttons.zip)
I still feel this is weird, but maybe a bit better than the first ones?

**Comment by steodor** [comment]
Looking back i see the proposed buttons are a lot smaller, so here's another try:
![image](https://user-images.githubusercontent.com/4397338/110343625-5b668700-8035-11eb-88c2-140787b4dc25.png)
[cellphone-buttons-small.zip](https://github.com/Templarian/MaterialDesign/files/6102449/cellphone-buttons-small.zip)

**Comment by goyney** [comment]
The attempts are there, but these don't really work. Cutting off the side of the phone doesn't really work. All phones have their hardware buttons in different locations. I feel these are trying to be overly specific.

For your use case, you can use the `volume(-plus|-minus)` icons to depict a mapping and the phone owner will know exactly what you're talking about. Due to the niche use case with a more standardized way to handle it, we're going to pass on these.

Thank you for your suggestion.
