### ISSUE TITLE
Download specific icons as webfont

### ISSUE THREAD

**Issue by Errvald** [Templarian/MaterialDesign#262]
I don't see the option to make a custom download. 

The number of the icons keeps growing so I think it would be nice to be able to select which icons we want to download as webfont.

**Comment by Templarian** [comment]
This is coded in the backend. I just don't have a UI built out exposing the functionality.

There are a few issues to resolve before development is started. For now using the whole icon set [small if the browser supports woff2] should be fine.

**Comment by w3l** [comment]
+1

Got the font-files down to 2-4 KB after editing the font in FontForge. But it was a pain in the ass, would love to see it on the site!

**Comment by Templarian** [comment]
@w3l Google is working to optimize their woff2 conversion software. It's a bug in that currently, that does not exist in the FontForge implementation. Once it is fixed I'll use the most up to date.

Right now the entire font build process is ran in node to keep the process as simple as possible. The 2-4kb savings was nice, but I want to keep the build chain as simple as possible since it takes 25 seconds to build the download package at the moment from the database from scratch.

Subselection is still in the works for now you can use FontIcons.com which has support for `v1.1.34`.

**Comment by w3l** [comment]
Well, the savings was 58KB-1194KB depending on font-type, the fonts was 2-4KB big after removing unused icons... (If that was unclear ;-)) But thanks for the suggestion, didn't know fonticons.com had support for Material Design Icons... Gonna check it out...

**Comment by dougamos** [comment]
@Templarian is there a place where we can see your Gruntfile for building?

**Comment by Templarian** [comment]
@dougamos It's mainly just the stock `grunt-webfont`.

```javascript
module.exports = function(grunt) {

  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    webfont: {
      everything: {
        src: ['icons/access-point.svg', 'icons/access-point-network.svg', ...'],
        dest: 'build',
        options: {
            engine: 'node',
            types: 'eot,woff2,woff,ttf,svg',
            font: 'Material Design Icons',
            hashes: false,
            template: 'template.css',
            autoHint: false,
            normalize: true
        }
      }
    },
    sass: {
      expanded: {
        options: {                       // Target options
          style: 'expanded'
        },
        files: {
          'build/materialdesignicons.css': 'build/materialdesignicons.scss'
        }
      },
      compressed: {
        options: {                       // Target options
          style: 'compressed'
        },
        files: {
          'build/materialdesignicons.min.css': 'build/materialdesignicons.scss'
        }
      }
    }

  });
  
  grunt.loadNpmTasks('grunt-webfont');
  grunt.loadNpmTasks('grunt-contrib-sass');

  grunt.registerTask('build.font', ['webfont', 'sass']);

};
```

**Comment by dougamos** [comment]
@Templarian thanks for this, I've changed my Gruntfile to closer match yours but icons are having issues converting:

```
grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    webfont: {
      everything: {
        src: '... MaterialDesign/icons/svg/*.svg',
        dest: 'fonts',
        destCss: 'css',
        options: {
          templateOptions: {
            baseClass: 'icon',
            classPrefix: 'icon-',
          },
          htmlDemoFilename: 'preview',
          destHtml: '.',
          engine: 'node',
          types: 'eot,woff2,woff,ttf,svg',
          autoHint: false,
          normalize: true,
          hashes: false,
        },
      }
    }
  });
```

Output (ttf file) is as follows:

<img width="396" alt="screen shot 2016-01-08 at 07 14 52" src="https://cloud.githubusercontent.com/assets/1301464/12192762/6c68a1cc-b5d9-11e5-84fc-0367dba44314.png">

OS: Mac OS X 10.11.1 (also tried ubuntu 14.04)
node: v5.3.0
grunt: v0.4.5
grunt-webfont 1.1.0

**Comment by Templarian** [comment]
I build mine in a node/linux environment on my CentOS server. You **can't** use the SVG files in the repo they won't work (there is a warning about that). Eventually I need to add an option to create custom fonts (very CPU intensive), or allow a mass download.

https://materialdesignicons.com/ Right click any icon and select the "SVG Webfont" option. This is due to limitations in the SVG to Font conversion. I've written a ton of code to make sure the path data always works and is minimum as possible.

To make things easy I've zipped v1.4.57 [here for download](http://1drv.ms/1UBkfhT).
