### ISSUE TITLE
List of currently released icons?

### ISSUE THREAD

**Issue by adambiggs** [Templarian/MaterialDesign#2654]
After lots of head scratching, I discovered that many of the icons listed on [materialdesignicons.com](https://materialdesignicons.com) haven't actually been released yet...

Is there a way to filter that list by icons that are currently able to be used? Or maybe that site should only display icons that are part of the latest release.

**Comment by PeterShaggyNoble** [comment]
All the icons included in the current release are listed in the preview.html file bundled with the webfont, which can also be [accessed on the CDN](https://cdn.materialdesignicons.com/2.0.46/).

As well as that, you can use the [history page](https://materialdesignicons.com/history) or [the sandbox](https://petershaggynoble.github.io/MDI-Sandbox/?section=soon) to see which icons were added since the last release.

**Comment by Templarian** [comment]
The new website will be able to filter by version release and latest icons. The current site lacks that functionality.

http://cdn.materialdesignicons.com/2.0.46/meta.json Contains all the meta data for the release also, but not very friendly to look at.

**Comment by Templarian** [comment]
Closing this issue since it will be resolved in the new site.
