### ISSUE TITLE
Loading Issues

### ISSUE THREAD

**Issue by sgangadhar02** [Templarian/MaterialDesign#2656]
Link: 

https://github.com/vuetifyjs/vuetify/issues/2702#issuecomment-348743896

**Comment by sgangadhar02** [comment]
@PeterShaggyNoble When you load the first time, web fonts loads, then the checkbox comes.

**Comment by PeterShaggyNoble** [comment]
How are you loading the font into your page?

**Comment by sgangadhar02** [comment]
@PeterShaggyNoble Please find the attachment. On refresh of view, web fonts load first on a slow network or medium network. Is there any way to fix this?

<img width="1680" alt="load" src="https://user-images.githubusercontent.com/16475764/33568547-c6b78524-d94c-11e7-8f70-0bd05166af5f.png">

**Comment by JamesCoyle** [comment]
Well the fonts are likely cached. Not really sure how this relates to MDI though.

**Comment by MrGrigri** [comment]
I do not believe this is related to MDI. Like @JamesCoyle stated, fonts cache themselves unless the cache is turned off or there is a network issue when initially loading the fonts. The native way browser handle font loading varies and there are some opinions out there on the interwebs. I for one, steer clear of web fonts for icons because of this exact issue. I opt for SVGs. 

P.S. there is an option to disable caching when debugging. If that is checked, and you are on a slow network, then that could be your problem.

![image](https://user-images.githubusercontent.com/4528551/33576365-c74352c0-d8fc-11e7-9796-8b39b0edd11a.png)

**Comment by Templarian** [comment]
Closing this issue, looks like the above comments come to the same solution (which is correct as far as I know).

Just disable cache if you need to debug the loading. Generally webfonts cache with a long expiration since they rarely ever change between page loads.
