### ISSUE TITLE
add text and font icons

### ISSUE THREAD

**Issue by noctivityinc** [Templarian/MaterialDesign#267]
More editor related fonts dealing with adding new text and selecting fonts
- [ ] format-font
- [ ] format-text-plus

**Comment by CoDEmanX** [comment]
So text formatting icons? Google has a lot of them (for word processing applications).

**Comment by CoDEmanX** [comment]
@noctivityinc: can you please re-evaluate this request? There a few new icons in MDI, which may suite your need, like

https://materialdesignicons.com/icon/format-title
https://materialdesignicons.com/icon/cursor-text
https://materialdesignicons.com/icon/textbox

We also have the following related request: #714 

Otherwise, please provide example pictograms.

**Comment by PeterShaggyNoble** [comment]
`format-font` is now available and, seeing as there has been no feedback on `format-text-plus` (`format-size` should do the job), I'm going to close this out.

@noctivityinc, if `format-size` doesn't suit your needs, please provide an example of what you *are* looking for an we'll revisit this issue.
