### ISSUE TITLE
All Microsoft Paint toolbar icons

### ISSUE THREAD

**Issue by gagandeep-s** [Templarian/MaterialDesign#2716]

**Comment by GreenTurtwig** [comment]
I assume these:
![](https://user-images.githubusercontent.com/15905797/34664450-e1ac8704-f453-11e7-9730-24e3aea34e2a.png)

We have:
- `paste`
- `cut`
- `copy`
- `select`
- `crop`
- `rotate-right-variant`
- `pencil`
- `format-color-fill`
- `format-text`
- `eraser`
- `eyedropper-variant`
- `magnify`
- `brush`

**Comment by goyney** [comment]
It looks like all the icons from the Paint interface have been added or are already included in the library. Closing.

**Comment by PeterShaggyNoble** [comment]
@gagandeep-s, if there are any icons you're still missing then please create a new issue for each one.

**Comment by CoDEmanX** [comment]
How do we call photo-size-select-small? Or has it yet to be added?

**Comment by goyney** [comment]
Which icon is that? The resize icon?

[![resize](https://materialdesignicons.com/icon/resize)](https://materialdesignicons.com/icon/resize)[![move-resize-variant](https://materialdesignicons.com/icon/move-resize-variant)](https://materialdesignicons.com/icon/move-resize-variant)

**Comment by goyney** [comment]
Sorry, I'm not sure I follow how those 3 icons are Paint related. I mean, I do, because they are formatting type icons, but none of those exist in that screen shot. I'm going to create a new issue for `photo-size-select`. If you can find good examples of the other two, please open new issues for each so we can get them added.
