### ISSUE TITLE
Steam Icon -box

### ISSUE THREAD

**Issue by thakyZ** [Templarian/MaterialDesign#2720]
I would like to see a box icon for Steam, being either the current or the upcoming new icon for this icon set. My website has social icons at the bottom and currently looks a little weird with Steam being out of place.

![screenshot](https://wesgu.is-a-good-waifu.com/6aa082.png)

**Comment by thakyZ** [comment]
I am currently working to contribute such icon with the current steam logo

**Comment by thakyZ** [comment]
I have created the icon in just a few seconds, but I am not sure I downloaded the right SVG style. (I downloaded SVG Optimized)

![steam-box](https://dl.dropboxusercontent.com/s/lmopvc9a07ryqtd/2018-01-03_06-35-05.svg)

**Comment by MrGrigri** [comment]
@thakyZ, thanks for this contribution. This might be a bit difficult because of its size. Typically, with brand icons, they don't follow the overall guidelines and are just copied or recreated. Also, since it's a brand icon, we try to find a resource or guidelines for that brans specifically. The style you are probably looking for is the following. 

![image](https://user-images.githubusercontent.com/4528551/34530267-d3ddac16-f06b-11e7-9fec-371a9ccc1030.png)

**Comment by thakyZ** [comment]
You are right, as I now see looking at the icon on my taskbar.
I have now done the following
Please do note, I am using your current steam icon off your website since I thought it would be more fitting to be more consistent.
![screenshot](https://owo.sh/bc321f.png)
![svg](https://dl.dropboxusercontent.com/s/cn7iio34o0a0dzf/2018-01-03_09-14-08.svg)

**Comment by MrGrigri** [comment]
We need the svg file.

**Comment by thakyZ** [comment]
Oh sorry, I didn't think Github wouldn't save it as an SVG to their CDN.
https://dl.dropboxusercontent.com/s/cn7iio34o0a0dzf/2018-01-03_09-14-08.svg

**Comment by Templarian** [comment]
[steam-box](https://materialdesignicons.com/icon/steam-box)](https://materialdesignicons.com/icon/steam-box)
