### ISSUE TITLE
Missing unicodes for some icons in the cheatsheet

### ISSUE THREAD

**Issue by oliviergaucher** [Templarian/MaterialDesign#2758]
Using the cheatsheet at following URL to get list of icons with their names and unicodes:
https://materialdesignicons.com/cheatsheet

Unicodes are missing for some of the icons, could you add them?
database-search
eye-plus
eye-plus-outline
file-question
folder-network
function-variant
home-alert
image-plus
phone-rotate-landscape
phone-rotate-portrait
reminder
security-account
thermostat-box
tractor
vector-ellipse

Thank you very much.

**Comment by Templarian** [comment]
That cheatsheet was one of the failed project ideas I had a while back, forgot it was still online (those pages lag so much because they lack any cache system).

https://cdn.materialdesignicons.com/2.1.19/ Is the better solution, with the new site we'll need to figure out a way to rework it for people that may have used that page.

Closing this issue out as the current site isn't getting fixes. All work is going into the new site. https://github.com/Templarian/MaterialDesign-Site

**Comment by oliviergaucher** [comment]
Using the cdn page now, thanks a lot!

**Comment by PeterShaggyNoble** [comment]
Note that all the icons you mention are scheduled for the next release and, as such, have not yet been assigned codepoints and they are not included in the `preview.html` file used on the CDN.
