### ISSUE TITLE
Build with node-sass v3.0.0 doesn't show icons

### ISSUE THREAD

**Issue by jgoux** [Templarian/MaterialDesign#279]
Hello,
I updated node-sass to the upcoming v3.0.0.
The scss files are compiled without any error, but then all the icons aren't displayed, there is just the content included in the css for each icon character, like "xf10c", "xf20c"...
If I revert to node-sass v2.x, everything is fine.
I couldn't find where this is coming from. :/

Thanks for all the good work. :+1:

**Comment by Templarian** [comment]
I'll try and debug this. Thanks for filing an issue.

**Comment by Templarian** [comment]
Tested this with various changes, trying to find a solution that fixes it in all build tools. That `v3.0.0-beta.5` actually fixes a bug that has been in SASS for a very long time. I just need to find a work around that works in previous version at the same time.

I'll debug it some more this weekend. If you're curious what the bug is, SASS dislike backslashes (`\`) before variables.

**Comment by Templarian** [comment]
Wrote a fix that works in v3 and v2 of node-sass. Need to test this with the ruby sass compiler, then I'll include it in the next release.

**Comment by jgoux** [comment]
Awesome ! Thanks a lot :+1:

**Comment by Templarian** [comment]
Resolved in the `v1.0.62-beta` release.
