### ISSUE TITLE
Finance-Outline

### ISSUE THREAD

**Issue by RushanB** [Templarian/MaterialDesign#2817]

**Comment by PeterShaggyNoble** [comment]
Are you looking for something like Google's `bid landscape`, `graph options` or `pie chart outlined` icons?

![bid landscape](https://user-images.githubusercontent.com/15157491/36252687-5269c298-123d-11e8-9d27-d44f532d857f.png) ![graph options](https://user-images.githubusercontent.com/15157491/36252810-c359cd68-123d-11e8-8fff-663c44a5a19c.png) [![pie chart outlined](https://user-images.githubusercontent.com/15157491/36252852-e1c8a01c-123d-11e8-954c-d480a9b271dc.png)](https://material.io/icons/#ic_pie_chart_outlined)

**Comment by RushanB** [comment]
Hi Peter, I am looking for something closer to this glyph. An outlined version so I can use it in the tab bar. Also If its not to much to ask, could I get a home icon outlined as well - I was only able to find the filled version.

![combo_chart](https://user-images.githubusercontent.com/16970644/36254904-dc2572b6-121a-11e8-9818-d9b4319c54d8.png)

**Comment by PeterShaggyNoble** [comment]
So you're looking for an `outline` variant of the [`finance`](https://materialdesgnicons.com/icon/finance)? Due to the small size of the individual elements in that icon, I doubt it will be possible to outline them but I'll leave this open for one of the icon designers to confirm (or deny) that.

[`home-outline`](https://materialdesgnicons.com/icon/home-outline) already exists.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
