### ISSUE TITLE
Toaster

### ISSUE THREAD

**Issue by shayshtern** [Templarian/MaterialDesign#2820]
what about a smart Toaster?!
  like:
   icon: mdi:toaster!!
who can create an icon for that?

**Comment by PeterShaggyNoble** [comment]
A "smart" *toaster*?! What the what?! The world's gone mad! 😆

**Comment by shayshtern** [comment]
yea why not?! turn on and off,
forget it on can cause bad things... :cold_sweat:

**Comment by JapanYoshi** [comment]
This really depends on whether a ‘smart toaster’ really exists. *And for the love of God I hope it doesn't.*

**Comment by shayshtern** [comment]
HAHA COOL !!BUT I just use Sonoff regular on my Toaster. so not that smart but ok for now.

**Comment by JapanYoshi** [comment]
Oh, fuck you, Silicon Valley smart-[noun] startups...

**Comment by MrGrigri** [comment]
Here is my attempt.

[![toaster](https://user-images.githubusercontent.com/4528551/52226891-630e3d00-286b-11e9-9920-12c4e2ce0756.png)](https://github.com/Templarian/MaterialDesign/files/2829214/toaster.zip)

**Comment by PeterShaggyNoble** [comment]
I think it might work better if the toast were a rectangle. Or maybe without the toast at all?

**Comment by goyney** [comment]
@PeterShaggyNoble @MrGrigri What about this?

![image](https://user-images.githubusercontent.com/1015040/62506774-e7685b00-b7cf-11e9-9158-90c33a1bd698.png)
[toaster.svg.zip](https://github.com/Templarian/MaterialDesign/files/3470088/toaster.svg.zip)

**Comment by MrGrigri** [comment]
I don't think there is anything wrong with my contribution.

**Comment by goyney** [comment]
[![toaster](https://materialdesignicons.com/icon/toaster)](https://materialdesignicons.com/icon/toaster)

**Comment by JapanYoshi** [comment]
I do like the bread-shaped bread better, instead of the circle.

**Comment by CoDEmanX** [comment]
It's not really recognizable at native size and makes it more noisy, eventhough it looks nice at larger scales.

Maybe it could be tweaked to be a rounded rectangle rather than an ellipse?

![grafik](https://user-images.githubusercontent.com/1309249/62690758-93c36080-b9cd-11e9-85db-ac751c327af1.png)

![grafik](https://user-images.githubusercontent.com/1309249/62690827-bb1a2d80-b9cd-11e9-97fb-0a9952254287.png)

![grafik](https://user-images.githubusercontent.com/1309249/62690861-ca00e000-b9cd-11e9-9857-2c9dde34bf37.png)

3dp radius (2nd) looks good to me.
