### ISSUE TITLE
Icon for archive/compress/zip/rar/7z 

### ISSUE THREAD

**Issue by astalegale** [Templarian/MaterialDesign#2825]
Hi,

i wonder if is possible to have an icon to correctly identify an archive.
Actually i'm using the package-down, but it doesn't fit correctly my needs.

Thanks for help!
Alex

**Comment by GreenTurtwig** [comment]
We already have:
[![](https://materialdesignicons.com/icon/zip-box)](https://materialdesignicons.com/icon/zip-box)

**Comment by astalegale** [comment]
I've already seen that, but it's more a zip for clothes, not for represent a file, is not really clear for the user.

**Comment by Templarian** [comment]
@astalegale Do you have an example of what you are thinking for this icon (images can be copy and pasted into the comment area).

**Comment by PeterShaggyNoble** [comment]
I think this has come up before but, of course, searching for "zip" isn't much use! #2305 was the closest I could find.

**Comment by GreenTurtwig** [comment]
@astalegale `zip-box` is the icon Google use on Chrome OS and Google Drive, it's best to stick with that.

**Comment by PeterShaggyNoble** [comment]
See also #1093

**Comment by goyney** [comment]
The `zip-box` icon is the official Google ZIP-file format icon used across their products. It is very recognizable into its meaning. I fail to see another way to represent a ZIP file archive short of putting the file extension in the icon, which would lead to many icons that all share the same meaning with unnecessary distinction.

We're going to close this issue again since it has stagnated and we currently have a solution. However, if you come up with any other ideas or alternatives on how to indicate a file archived, please comment here. Thanks.
