### ISSUE TITLE
eye-settings

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2828]
![image](https://user-images.githubusercontent.com/4528551/36495773-99496d3e-16f3-11e8-8568-9bceab185063.png) ![image](https://user-images.githubusercontent.com/4528551/36495619-14e58d16-16f3-11e8-8b9a-7c3dc46431ad.png) ![image](https://user-images.githubusercontent.com/4528551/36495813-b94f38f2-16f3-11e8-98b9-323c4123a092.png) ![image](https://user-images.githubusercontent.com/4528551/36495660-389a01ba-16f3-11e8-98f6-0e921fc58126.png)

[eye-settings.zip](https://github.com/Templarian/MaterialDesign/files/1745099/eye-settings.zip)

**Comment by MrGrigri** [comment]
The variants could be omitted if not desired.

**Comment by Templarian** [comment]
[![eye-settings](https://materialdesignicons.com/icon/eye-settings)](https://materialdesignicons.com/icon/eye-settings) [![eye-settings-outline](https://materialdesignicons.com/icon/eye-settings-outline)](https://materialdesignicons.com/icon/eye-settings-outline)

Since we don't add `cog` modifiers as settings.
