### ISSUE TITLE
https://materialdesignicons.com/ is not working

### ISSUE THREAD

**Issue by andrii85** [Templarian/MaterialDesign#2869]
Your website and CDN are not working

![image](https://user-images.githubusercontent.com/11927676/36937163-cc9f4254-1f17-11e8-93f9-df58afd48138.png)

**Comment by Templarian** [comment]
It's my host having issues, the box is fine as far as I can tell. Team just let me know a minute ago.

Nothing traffic wise out of the ordinary, so I have no idea.

**Comment by Templarian** [comment]
Update a ticket has been created with my hosting provider. Hopefully will hear back very shortly.

**Comment by Templarian** [comment]
The data center had a power outage in section of their building and it is being restored now.

**Comment by Templarian** [comment]
Back from running errands and everything is back online. Closing this issue.

Very stressful whenever things like this happens since they are so rare. The new site is relying much more on longer cache layers on the CDN, so we might be able to run it all through the CDN. Will be looking into this once we switch over production.

**Comment by Templarian** [comment]
If you want more details it was actually a failure in their cooling unit that knocked out power. Hopefully this never happens again. All of my hosts servers are back online at this time.
