### ISSUE TITLE
Google "style" icon...

### ISSUE THREAD

**Issue by DavidCRivera** [Templarian/MaterialDesign#2906]
I did a search for open issues, and couldn't find one for this, so apologies if it's a duplicate. I couldn't seem to find the 'style' icon that looks like a swatch book. It's a part of Google's official icons, but seems to be missing: https://material.io/icons/#ic_style

Any chance of getting this included?

Thanks!

**Comment by Templarian** [comment]
Lets add this as a `palette-swatch` or something and alias it as `style`. Since we use nouns for most icons.

**Comment by Templarian** [comment]
[![palette-swatch](https://materialdesignicons.com/icon/palette-swatch)](https://materialdesignicons.com/icon/palette-swatch)

Alias `style`.

**Comment by Radiergummi** [comment]
I just migrated our code base to MDI-icons, but while `palette-swatch` can already be found on the website, it's missing from the package. It'd be great if the site would show a note for icons that aren't implemented yet, or simply not include them.

**Comment by Templarian** [comment]
@Radiergummi This is coming in the new site under construction right now.

https://github.com/Templarian/MaterialDesign-Site Track progress here. Glad you like the set. 😄

**Comment by PeterShaggyNoble** [comment]
@Radiergummi, you can also track the progress of the next release [here](https://github.com/Templarian/MaterialDesign/milestone/14) & [here](https://github.com/Templarian/MaterialDesign/issues/2872) and view which icons have been added since the last release (v2.1.99 on the 4th of March, as of this writing) on the [history page](https://materialdesignicons.com/history).
