### ISSUE TITLE
Rubik's Cube (unsolved), Rubik's Cube (solved), & Rubik's Cube (turning a side)

### ISSUE THREAD

**Issue by mikechoch** [Templarian/MaterialDesign#2929]
3-D positioning to show top left and right side equally.
Solved version all tiles same color (black, grey, white)
Unsolved could be random placement of a color and its inverse.
Turning cube could have left or right side at a 45˚ rotation.
[rubix_cube.zip](https://github.com/Templarian/MaterialDesign/files/1823489/rubix_cube.zip)

**Comment by JapanYoshi** [comment]
There's no way this can be done with Material Design specs.

**Comment by mikechoch** [comment]
Did you look at the example I left in my ZIP folder?

**Comment by JapanYoshi** [comment]
1) Yes, I've seen it.
2) They're PNG files and not the source SVG files.
3) Your icon violates the requirement that dimensionality be kept at an extreme minimum.

**Comment by PeterShaggyNoble** [comment]
As Yoshi mentioned, the [Material Design guidelines](https://material.io/guidelines/style/icons.html#icons-system-icons) don't allow for perspectives (see "Best practices").

Although we have taken *some* liberties with that in the past, the problem here is that when you angle the Rubik's Cube to make 2-3 faces available it introduces too much detail to be fit in a 24*24 icon. The old `dice` icon was somehwat less detailed than this would need to be and, as you can see below, it didn't look too good. I think the best representation of a Rubik's Cube that you're going to get under the MD guidelines is the `apps` icon or one of the `cube-*` icons, which should work given the correct context.

![dice](https://user-images.githubusercontent.com/15157491/37653452-d791f450-2c36-11e8-8a52-7f9243a287c4.png)

You should note as well that all our icons are single-colour icons so, unfortunately, your suggestion for an unsolved cube would not have been viable either.

**Comment by mikechoch** [comment]
I know they are PNG, I was just giving an example of something I made in PS. I understand now why it does not meet design standards, I appreciate the explanation.
