### ISSUE TITLE
New/Write New Message / Pencil on Box Icon

### ISSUE THREAD

**Issue by Mancerrss** [Templarian/MaterialDesign#3022]
Do we already have this?
![capture](https://user-images.githubusercontent.com/20938829/38429706-c18583de-39f1-11e8-8cfc-79530f0e89bf.PNG)
If we still don't have it? Can we make it? If not, can you guys help me find it on our set, I'm really weak finding things and tags wouldn't really cut it on me

**Comment by Mancerrss** [comment]
Also I just noticed, so the website and the html file included in the glyph font has a big inconsistency. The website is so so outdated

Also can I get a help finding where the icon for this? 
![pin](https://user-images.githubusercontent.com/20938829/38433282-d334c6ca-39fc-11e8-8e7a-4936e007329e.PNG)

**Comment by PeterShaggyNoble** [comment]
Is `pencil-box-outline` close enough what you're looking for?

If you think you've found a problem with the webfont, please open a new issue and provide details. Note, though, that the webfont isn't automatically updated as each icon is added, rather it's updated with each release. You can see which icons have been added since the last release on the [history page](https://materialdesignicons.com/history) or in [the Sandbox](https://github.com/Templarian/MaterialDesign/issues/3020).

`pin-outline` has already been requested in #2419.

**Comment by GreenTurtwig** [comment]
Google uses a similar design in the Google Maps timeline alongside `checkbox-marked-circle-outline`:
![image](https://user-images.githubusercontent.com/15905797/38445248-a67f701a-39ea-11e8-8454-f3831b8dd07c.png)

We should probably get that added and add a `checkbox-edit-outline` like the request above.

**Comment by Mancerrss** [comment]
@PeterShaggyNoble Nah I really need it just like that.

@GreenTurtwig Yea but I need it in like a checkbox/square shape

**Comment by Mancerrss** [comment]
@PeterShaggyNoble Sandbox? I think you made a mistake linking on that?

How about the website, does every time someone contributes a new font, does it get auto added on there as well. As far as I've noticed it's more outdated than the webfont. Or does new icons only can be get on the GitHub

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/38459809-9b35457e-3aa6-11e8-93fa-c672942a502b.png)](https://github.com/Templarian/MaterialDesign/files/1886687/checkbox-edit-circle-outline.zip)[![](https://user-images.githubusercontent.com/15905797/38459798-6d0418e2-3aa6-11e8-9171-c2dcd20d1ccf.png)](https://github.com/Templarian/MaterialDesign/files/1886688/checkbox-edit-outline.zip)

I assume you're doing something with the Discord UI which is why `pencil-box-outline` wouldn't do you?

Whenever a new icon is added it'll show up on the website. Also yeah, @PeterShaggyNoble didn't link the sandbox correctly, here's the [link](https://petershaggynoble.github.io/MDI-Sandbox).

**Comment by PeterShaggyNoble** [comment]
Sorry, I meant `pencil-circle-outline` above, not `pencil-box-outline`.

Sandbox link updated.

**Comment by Templarian** [comment]
@Mancerrss The repo here is just a WIP directory. If you need SVG's they are versioned and published alongside the fonts. https://github.com/Templarian/MaterialDesign-SVG

**Comment by Templarian** [comment]
Can I just call these `square-edit-outline` and `circle-edit-outline`?

**Comment by Templarian** [comment]
[![square-edit-outline](https://materialdesignicons.com/icon/square-edit-outline)](https://materialdesignicons.com/icon/square-edit-outline) [![circle-edit-outline](https://materialdesignicons.com/icon/circle-edit-outline)](https://materialdesignicons.com/icon/circle-edit-outline)
