### ISSUE TITLE
IconJar Testing

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3028]
I do not have a Mac. So I need some help testing.

https://github.com/Templarian/MaterialDesign-IconJar

**Comment by Templarian** [comment]
Okay updated the file above. Looking for feedback.

**Comment by Templarian** [comment]
@GlennFernandes Oh, I didn't publish it to NPM yet. Someone can verify it works okay for them first.

We can modify the script to group them, that's why we wrote it as a simple script so we can automate all that.

**Comment by GlennFernandes** [comment]
The IconJar itself works without a hitch. 
I did notice some icons missing from the iconJar, these are just the ones i stumbled across, i'm not sure if there are more. I'm not sure if this is because of the script itself or because these are relatively new icons which haven't been added to the script yet.
- Hammer
- Axe
- Home-lock
- Home-lock-open

The grouping i did was based on the tags available on the materialdesignicons main website. I've attached a screenshot of the same.

![screen shot 2018-04-14 at 9 39 03 pm](https://user-images.githubusercontent.com/31320319/38770194-78a98282-402c-11e8-8192-fff2ca88b74d.png)

**Comment by Templarian** [comment]
I can update the script later today with these tags (might break your current one if I mess it up, so please backup first 😆).

@GlennFernandes Can you export your file really quick so I can double check the format? (zips can be dragged into comments and attached).

**Comment by Templarian** [comment]
@GlennFernandes Also the missing icons are due to this being built off `v2.2.43` new version is going out tomorrow (hence why I want to get this script finished).

**Comment by GlennFernandes** [comment]
@Templarian I'm uploading a partially complete group. Basically, I made the sets up till Shape, Ignore the last set called Material Design Icons. That's the initial iconJar set which was extracted from the repo file, which I was pulling icons out of and adding them to individual sets. I left it in there just so all icons would be there.

[material_design_icons.zip](https://github.com/Templarian/MaterialDesign/files/1910754/material_design_icons.zip)

**Comment by Templarian** [comment]
That's fine, I just want to make sure I have the JSON file format correct. They don't really have it documented so looking at samples makes it this easier. Will work on updating it shortly.

Thanks!
