### ISSUE TITLE
CryEngine 5

### ISSUE THREAD

**Issue by alexchicn** [Templarian/MaterialDesign#3141]
Add a new icon `ce5-solid` for CryEngine 5.*. Built it by the [official website](http://assets.crytek.com/asset-bank/action/browseItems?categoryId=152).

![bitmap](https://user-images.githubusercontent.com/2211006/39583459-bdf4d062-4f22-11e8-99bf-2c1464890ac3.jpg)

[ce5-solid.zip](https://github.com/Templarian/MaterialDesign/files/1971354/ce5-solid.zip)

**Comment by Templarian** [comment]
[![cryengine](https://materialdesignicons.com/icon/cryengine)](https://materialdesignicons.com/icon/cryengine)

Due to the height being so small I ended up going for a wider 22dp. Brands are being attributed to the shared contributor account. But we still count these so 4 more unique icons to become a contributor.
