### ISSUE TITLE
Update & Alias share(-outline)

### ISSUE THREAD

**Issue by Sunpay** [Templarian/MaterialDesign#3155]
Most email clients programs allow you to reply, reply all and forward an email
Material design icons have icons for reply and reply all BUT NOT forward 

Please consider adding an icon for forward that has similar theming to the ones used for reply and reply all so that all three icons could be used together without any of them looking out of place

**Comment by PeterShaggyNoble** [comment]
It's called `share` and there's also a `share-outline` variant. However, both sit one point higher than the `reply` icon so we should probably update them.

**Comment by goyney** [comment]
The `share` icons should be updated because they're not vertically centered, while the `reply` icons are, so we'll leave those alone.

![image](https://user-images.githubusercontent.com/1015040/53062913-63741e00-3490-11e9-995f-7672097debe2.png)![image](https://user-images.githubusercontent.com/1015040/53062927-70910d00-3490-11e9-90a8-fc4fbe2ef528.png)
Our current is the outline.

[share.zip](https://github.com/Templarian/MaterialDesign/files/2882825/share.zip)

**Comment by Templarian** [comment]
Updated. 😃
