### ISSUE TITLE
Requested icon - Folder Earth Open

### ISSUE THREAD

**Issue by shig2k1** [Templarian/MaterialDesign#3342]
[folder-earth-open.zip](https://github.com/Templarian/MaterialDesign/files/2223293/folder-earth-open.zip)

**Comment by goyney** [comment]
Thanks for the contribution. We've rejected "open" variants of the folder icon in the past.

Material guidelines state that icons should not try to appear dimensional. All of our folder icons are in a "closed" state to follow that guideline. We do have a `folder-open` icon, but that was a conscious exception because it is such a widely and commonly used UI element.

I'm going to close this issue.
