### ISSUE TITLE
T-Shirt Icon non-outlined

### ISSUE THREAD

**Issue by ziyafenn** [Templarian/MaterialDesign#3353]
Hey there. Would be great to have a non-outlined version of t-shirt icon (normal-neck version in my case)

Thanks in advance!

**Comment by MrGrigri** [comment]
This will be a breaking change I think. Because the current options are technically outlined versions so their names would change to `tshirt-crew-outline` and `tshirt-v-outline` with these two additions taking the non-outlined names. 

![image](https://user-images.githubusercontent.com/4528551/43408620-0b261ad4-93df-11e8-9696-c89043be4932.png) ![image](https://user-images.githubusercontent.com/4528551/43408668-28a17dce-93df-11e8-9c81-a3b0d2c203c7.png)

[tshirt.zip](https://github.com/Templarian/MaterialDesign/files/2241925/tshirt.zip)

**Comment by Templarian** [comment]
[![tshirt-v](https://materialdesignicons.com/icon/tshirt-v)](https://materialdesignicons.com/icon/tshirt-v) [![tshirt-crew](https://materialdesignicons.com/icon/tshirt-crew)](https://materialdesignicons.com/icon/tshirt-crew)
