### ISSUE TITLE
ruby on rails 

### ISSUE THREAD

**Issue by jmj4you** [Templarian/MaterialDesign#3393]
![image](https://user-images.githubusercontent.com/1086448/44017800-37b9ef9e-9ef7-11e8-89b5-3c7043897383.png)

**Comment by SarinManS** [comment]
This got a bit tricky since at smaller sizes the details of the icon isn't really clear

Sample 1
![image](https://user-images.githubusercontent.com/26505215/44024095-12a430a6-9f0c-11e8-8374-d024f9ce15a4.png)

Sample 2 - Edited to look better on smaller sizes
![image](https://user-images.githubusercontent.com/26505215/44025343-9a09dc14-9f0f-11e8-8347-c06d817f87d9.png)

**Comment by goyney** [comment]
Leaving this open since its for a programming language.

**Comment by Templarian** [comment]
[![language-ruby-on-rails](https://materialdesignicons.com/icon/language-ruby-on-rails)](https://materialdesignicons.com/icon/language-ruby-on-rails)

**Comment by goyney** [comment]
The Ruby icon doesn't include the R from any example I've ever seen. We may want to rethink this one.

**Comment by Templarian** [comment]
We can always redesign it in the future, just wanted to get one in the pack as a placeholder.
