### ISSUE TITLE
Farm Icon

### ISSUE THREAD

**Issue by dabielkabuto** [Templarian/MaterialDesign#347]
Will be thankful for a bin icon, a silo for feed (farms) icon.
- [ ] farm-silo
- [ ] ???? feeding bin

**Comment by Templarian** [comment]
I get the Silo icon, but do you have an example for a feed bin?

**Comment by dabielkabuto** [comment]
For example 
https://thenounproject.com/term/silo/62184/
or

https://www.iconfinder.com/icons/435000/compost_container_farm_metal_silo_tin_icon#size=128

**Comment by djensen47** [comment]
Can we add a tractor as well?

**Comment by GreenTurtwig** [comment]
Tractors are a great idea since I recently created a bunch of vehicle icons. I'll get right on that.

**Comment by PeterShaggyNoble** [comment]
Bumping as a reminder for @GreenTurtwig ;)

**Comment by GreenTurtwig** [comment]
Haha, thanks. 👍

**Comment by GreenTurtwig** [comment]
Here we go:
![image](https://user-images.githubusercontent.com/15905797/31620911-5ff51ed8-b290-11e7-809a-2e97e9c25629.png)
![image](https://user-images.githubusercontent.com/15905797/31620926-6a660fda-b290-11e7-8cf9-a375ec85a6bd.png)
[tractor.zip](https://github.com/Templarian/MaterialDesign/files/1388078/tractor.zip)

Increased the usual windscreen width from 1.5 to 2 since the cab is quite large. Has elements of the CLAAS ATOS range.

**Comment by Templarian** [comment]
[![tractor](https://materialdesignicons.com/icon/tractor)](https://materialdesignicons.com/icon/tractor)

**Comment by PeterShaggyNoble** [comment]
`silo` was added in #3474
