### ISSUE TITLE
Icon request guidelines

### ISSUE THREAD

**Issue by cvsguimaraes** [Templarian/MaterialDesign#351]
Currently there's no "out of scope requests"?! Icon requests will be accepted no matter what and be created in prior `+1` count(i.e popularity)?! What is the current workflow?!

I see a great future for this project, would be nice to provide some guidelines for icon requests and define how they are prioritized. Please share your thoughs @Templarian ...

I just wondered about it after reading about #348 :sweat_smile:

**Comment by Templarian** [comment]
Probably a good idea. There are no real out of scope requests. The only limitation is the small 24x24 region and the design rules that everything must be 2px width. I prioritize the icons in a very simple way, which ever ones I think would be most useful for the community. It's a very biased system, that's why I'm always looking for other contributors to help out.

The only way to get rejected right now is it for to be a obscure company logo (outside of the large social media companies).

**Comment by cvsguimaraes** [comment]
We can greatly increase the overall quality of the incoming icon requests by just asking them to provide at least one image/link as example of their request, as people seem to have difficulty to put in words what they really want; 

A simple edit on `README.md` would be enough for now, but I'll also try to give a hand on ambiguous requests if you don't mind.

Thanks!

**Comment by Templarian** [comment]
I take pull requests if you want to modify the wording. :smile: Or I can modify it later.

**Comment by Templarian** [comment]
I think the process so far works pretty well. They are relatively easy to manage and filter them out.

Adding the extra "policies" might work as a deterrent for some not use to GitHub. I'm going to close this issue and will reopen it if this becomes an issue.

Right now the largest issue is lack of designer contributors and not really the issues coming in.
