### ISSUE TITLE
Icon request: Blank icon

### ISSUE THREAD

**Issue by jacksonrayhamilton** [Templarian/MaterialDesign#352]
Sometimes we want to conditionally show an icon where an icon would otherwise occupy space. The icon's size might contribute to the width or height of a containing element. Thus, if you apply a `display: none` style to an icon, your layout may change. Sure, one could use any icon and apply `visibility: hidden` to it, but I think a more "semantic" approach to using a placeholder icon would be to actually have a placeholder icon.

Hence, I'd like an icon that has the same width and height as the other icons, but which is entirely invisible.

**Comment by Templarian** [comment]
Good idea, but instead of adding an actual icon I will probably just add another mdi-blank class that takes the first icon and sets the opacity: 0; on it.

The font generation tools I use in the background I believe throw an error if they can't parse the path data (aka blank would probably be an error).

**Comment by CoDEmanX** [comment]
Is there a chance you make your toolchain public? I would like to test if a blank SVG will actually cause an error and maybe fix it.

**Comment by Templarian** [comment]
The font creation portion will be public eventually it just uses the [grunt-webfont](https://github.com/sapegin/grunt-webfont) tool. Technically on every icon there is a "download .svg for grunt webfont" download option. That can be dropped right into the tool.

I think it will throw an error on blank .svg paths due to it thinking there is an error in the SVG file.

**Comment by CodingSamurai** [comment]
Did you ever get this added?

**Comment by Templarian** [comment]
Nah, it never did... but I'm adding it to the next release now that you reminded me I had forgot. :smile:

**Comment by Templarian** [comment]
Blank is now included in the `v1.7.12` release that is going out tomorrow.

Preview: https://cdn.materialdesignicons.com/1.7.12/

**Comment by jacksonrayhamilton** [comment]
Thanks for adding this!

**Comment by edward6d** [comment]
I don't know where is the right place to report this, but the `mdi-blank` icon is missing from https://pictogrammers.com/library/mdi/ listing, which I normally use for finding MD icons that suit my use case. 

Googling this problem and finding this issue was how I found out it even exists. 😅 It's very useful, helped me solve a problem I struggled for hours to fix. Thanks for implementing it!
