### ISSUE TITLE
account-briefcase

### ISSUE THREAD

**Issue by ugate** [Templarian/MaterialDesign#354]
How about a user account icon like the current ones, but with a briefcase instead of plus, check, etc?
- [ ] account-briefcase

**Comment by CoDEmanX** [comment]
Can you describe the purpose a bit? Do you want to distinguish private and business accounts?

**Comment by ugate** [comment]
@CoDEmanX exactly, business accounts...

**Comment by CoDEmanX** [comment]
There's a human with hardhat (account icon + helmet): https://materialdesignicons.com/icon/worker

Probably better than the account icon with a briefcase because of the very small details, as I tried here:

![account-business](https://cloud.githubusercontent.com/assets/1309249/8843369/e4e01a06-3107-11e5-98b9-41744fbef81f.png)

The briefcase can't be made much larger (2px spacing and stroke width) without impairing the legibility:

![account-business2](https://cloud.githubusercontent.com/assets/1309249/8843553/3e06e36a-310a-11e5-87e5-311cd66ae150.png)

**Comment by CoDEmanX** [comment]
Maybe a (bow-)tie could be made working. My experiment showed so far, that if an icon at 24px is legible, then the shape is inelegant at larger sizes and vice versa:

![account-tie-test_90dpi](https://cloud.githubusercontent.com/assets/1309249/8846752/ab1520d8-3129-11e5-92f3-cab630a471ca.png)

![account-tie-test_360dpi](https://cloud.githubusercontent.com/assets/1309249/8846753/ab15e9d2-3129-11e5-943a-c72d9f3a2e3a.png)

**Comment by goyney** [comment]
I don't like the little briefcase. I think I would rather see the briefcase have a user variant.

![image](https://user-images.githubusercontent.com/1015040/48747683-1048c000-ec42-11e8-9a91-43499f0a35c9.png)![image](https://user-images.githubusercontent.com/1015040/48747731-49813000-ec42-11e8-8ae3-9921275e1543.png)

[briefcase-user.zip](https://github.com/Templarian/MaterialDesign/files/2597809/briefcase-user.zip)

**Comment by goyney** [comment]
Combining ideas from @CoDEmanX and from @Tarilonte (from #2341), I put this together which may also serve this use case.

![image](https://user-images.githubusercontent.com/1015040/48815599-fc1dc500-ed0c-11e8-90de-ae5607340adc.png)

[user-tie.zip](https://github.com/Templarian/MaterialDesign/files/2602408/user-tie.zip)

**Comment by Templarian** [comment]
Added all three. `account-tie`, `briefcase-account`, and `briefcase-account-outline`.
