### ISSUE TITLE
Comparison icons

### ISSUE THREAD

**Issue by Bulforce** [Templarian/MaterialDesign#355]
Comparison icons like [=], [<], [>],  [=<], [>=], [<>], [!=] 

- [x] `code-equal` (already exists)
- [x] `code-less-than`
- [x] `code-great-than`
- [x] `code-greater-than-or-equal`
- [x] `code-less-than-or-equal`
- [x] `code-not-equal`
- [x] `code-not-equal-variant`

**Comment by CoDEmanX** [comment]
Should be easy to do, rather a question of scale. Not sure when to use these however if text could be equally used (very minor visual difference, as long as you don't use Comic Sans :laughing: )

**Comment by CoDEmanX** [comment]
@Bulforce: I missed the square brackets, do you mean comparison symbols in a box?

So `equal-box`, not `equal?`
https://materialdesignicons.com/icon/equal-box

**Comment by Bulforce** [comment]
the equal-box looks great, it would be nice to have all the operators like that one.

Possible usage is when building excel like web apps and those will be handy when defining filters for example.

**Comment by CoDEmanX** [comment]
I would actually change equal-box so the counter strokes are closer together:
![equal-box](https://cloud.githubusercontent.com/assets/1309249/9007715/5ca7d97e-3794-11e5-993f-e02016d86159.png) to ![equal-box2](https://cloud.githubusercontent.com/assets/1309249/9007729/85d3a256-3794-11e5-9991-9c8af6f68821.png)

@Templarian; do you want me to do all of them, or do you wanna do it yourself?

**Comment by CoDEmanX** [comment]
Not sure whether there should be 2 or 3 pixels between box border and symbol, comparison:

![equal-equal-box](https://cloud.githubusercontent.com/assets/1309249/9009136/5e0beff2-379f-11e5-9258-00d0bbdd5eb8.png) vs. ![equal-equal-box2](https://cloud.githubusercontent.com/assets/1309249/9009166/9f3cd2e8-379f-11e5-9798-ca83f325f2c2.png)

![greater-equal-box](https://cloud.githubusercontent.com/assets/1309249/9009138/654c1a76-379f-11e5-84f7-965a7740ffbc.png) vs. ![greater-equal-box2](https://cloud.githubusercontent.com/assets/1309249/9009139/6550da02-379f-11e5-9080-bb9d4e843a40.png) 

There's more space in this one because an exclamation mark is by far narrower, but not sure if the equal symbol should be made longer in this case:

![not-equal-box2](https://cloud.githubusercontent.com/assets/1309249/9009232/210d75c0-37a0-11e5-9707-8a57ed61046a.png) vs. ![not-equal-box](https://cloud.githubusercontent.com/assets/1309249/9009142/697c8e78-379f-11e5-827b-59abcc62eddc.png)

**Comment by Templarian** [comment]
I agree with all 4 icons. 2nd ones from the comment above. Spacing looks nicer with 3dp.

**Comment by CoDEmanX** [comment]
![unequal-box](https://cloud.githubusercontent.com/assets/1309249/9027732/f84c203c-3961-11e5-847c-0d51ddd4eabe.png) ![unequal-box2](https://cloud.githubusercontent.com/assets/1309249/9027733/f84fde0c-3961-11e5-94b1-2c463698cd79.png) ![not-equal-box](https://cloud.githubusercontent.com/assets/1309249/9027734/fb90c856-3961-11e5-9db9-c188bbd04fab.png) ![equal-equal-box](https://cloud.githubusercontent.com/assets/1309249/9027735/ff4a929c-3961-11e5-8e4b-493b81637497.png) ![greater-box](https://cloud.githubusercontent.com/assets/1309249/9027739/06c63058-3962-11e5-97c0-e555e4283a05.png) ![greater-equal-box](https://cloud.githubusercontent.com/assets/1309249/9027740/06c776ac-3962-11e5-9bbf-9bba90213fc3.png) ![less-equal-box](https://cloud.githubusercontent.com/assets/1309249/9027743/0b537bb2-3962-11e5-8d9b-9ab5e5648375.png) ![less-box](https://cloud.githubusercontent.com/assets/1309249/9027742/0b52b588-3962-11e5-996b-7b9a3a2ffcde.png)

https://www.dropbox.com/sh/46zd9pyvz76lpdu/AAA-K_akh75C7ICT1UHSVGPSa?dl=0

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/code-equal
etc..

Busy week with the family in town. Just getting to emails and trying to get a few icons in tonight.
