### ISSUE TITLE
Ticketmaster

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3588]
I've found myself in need of this recently. SVG of their logo can be found [here](https://developer.ticketmaster.com/support/branding-guide/) and their icon uses the `t` & `m`.

**Comment by Templarian** [comment]
Still not sure if this is one we can add. I don't really see it fitting nicely into the size.

**Comment by goyney** [comment]
[Ticketmaster's Brand Guidelines](https://blog.ticketmaster.com/brand-guidelines/) don't mention anything about a shortened version of their logo, but their favicon is just the t, so that's what I have here. We can decided whether or not this is worth adding from this point.

![image](https://user-images.githubusercontent.com/1015040/48974913-8333ab80-f033-11e8-940f-656ddad462cf.png)

[ticketmaster.zip](https://github.com/Templarian/MaterialDesign/files/2612787/ticketmaster.zip)

**Comment by PeterShaggyNoble** [comment]
That must be a recent update to their favicon; they *were* using `tm` when I created this issue.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
