### ISSUE TITLE
Icons for horoscope

### ISSUE THREAD

**Issue by Krahen** [Templarian/MaterialDesign#360]
- [ ] horoscope-pisces
- [ ] horoscope-aquarius
- [ ] horoscope-aries
- [ ] horoscope-taurus
- [ ] horoscope-gemini
- [ ] horoscope-cancer
- [ ] horoscope-leo
- [ ] horoscope-virgo
- [ ] horoscope-libra
- [ ] horoscope-scorpio
- [ ] horoscope-sagittarius
- [ ] horoscope-capricorn

**Comment by cvsguimaraes** [comment]
Please provide examples...

**Comment by Templarian** [comment]
I think people know what the 12 animals are.

**Comment by Krahen** [comment]
They could be as animals or by their symbol, for example Libra is pretty similar to omega icon.

**Comment by CoDEmanX** [comment]
Animals are pictorial and I suspect better understood than the more textual symbols. Problem with animals: too fine details for the 24 pixels grid...

**Comment by heymartinadams** [comment]
- [ ] aries: ♈️
- [ ] taurus: ♉️
- [ ] gemini: ♊️
- [ ] cancer: ♋️
- [ ] leo: ♌️
- [ ] virgo: ♍️
- [ ] libra: ♎️
- [ ] scorpio: ♏️
- [ ] sagittarius: ♐️
- [ ] capricorn: ♑️
- [ ] aquarius: ♒️
- [ ] pisces: ♓️

**Comment by JapanYoshi** [comment]
I suggest closing this. I don't so the purpose of having these icons in Material Design.

**Comment by JamesCoyle** [comment]
While horoscopes are utterly useless, they are often seen on dating profiles so might be useful to people.

**Comment by heymartinadams** [comment]
Whether you believe in something or not shouldn’t be a criterion to having icons. For example, if you happen to be an atheist, it doesn’t follow that there shouldn’t be any Christian or Buddhist icons.

**Comment by JapanYoshi** [comment]
I don't believe in the Horoscope, but that has nothing to do with thether MDI's scope includes these or not.

**Comment by MrGrigri** [comment]
I actually had all of these done but didn't put them here because it was closed. 

![horoscope-aquarius](https://user-images.githubusercontent.com/4528551/41322654-5d2c26a4-6e67-11e8-8ec0-e5f047356c89.png) ![horoscope-aries](https://user-images.githubusercontent.com/4528551/41322662-69934cd8-6e67-11e8-9114-15a0c2337b54.png) ![horoscope-cancer](https://user-images.githubusercontent.com/4528551/41322668-7984d4ea-6e67-11e8-984d-2dcbd0fb05ed.png) ![horoscope-capricorn](https://user-images.githubusercontent.com/4528551/41322678-847ba324-6e67-11e8-94a3-ebe237b11649.png) ![horoscope-gemini](https://user-images.githubusercontent.com/4528551/41322632-40dfac32-6e67-11e8-8efd-e9fe828d9e6b.png) ![horoscope-leo](https://user-images.githubusercontent.com/4528551/41322737-e65fbe90-6e67-11e8-8e4b-5585e40b20e7.png) ![horoscope-libra](https://user-images.githubusercontent.com/4528551/41322757-00ff2ae2-6e68-11e8-841b-65b10ea85578.png) ![horoscope-pisces](https://user-images.githubusercontent.com/4528551/41322786-29ee29e4-6e68-11e8-9ba9-6d0761f1986a.png) ![horoscope-sagittarius](https://user-images.githubusercontent.com/4528551/41322861-8aa8d090-6e68-11e8-8056-4b0d229c9286.png) ![horoscope-scorpio](https://user-images.githubusercontent.com/4528551/41322880-a38c6a04-6e68-11e8-8868-97d4db366f22.png) ![horoscope-taurus](https://user-images.githubusercontent.com/4528551/41322934-e26b0e56-6e68-11e8-8a2d-e75c81979abf.png) ![horoscope-virgo](https://user-images.githubusercontent.com/4528551/41322967-fbd6c7ea-6e68-11e8-899a-376c50a806bb.png)

[horoscopes.zip](https://github.com/Templarian/MaterialDesign/files/2096156/horoscopes.zip)

**Comment by goyney** [comment]
Excellent! Thanks @MrGrigri, these will be useful in the MDI Wingdings project I am working on.

**Comment by Templarian** [comment]
Added all 12. http://dev.materialdesignicons.com/history
