### ISSUE TITLE
mdi-account-details does not show

### ISSUE THREAD

**Issue by musicformellons** [Templarian/MaterialDesign#3619]
Referencing other icons works fine, but when I reference 'mdi-account-details' it does not show up... What's wrong?

**Comment by Templarian** [comment]
It was added in `v1.6.50` which is ancient like multiple years old at this point. So probably a typo? 🤷‍♂️.

I really doubt you have a version that old, so really not sure why it wouldn't render. Seems fine in the CDN preview.

https://cdn.materialdesignicons.com/2.8.94/

**Comment by musicformellons** [comment]
Odd... It is no typo...

**Comment by Templarian** [comment]
What version of the webfont?

**Comment by musicformellons** [comment]
I am actually using it via quasar-framework, so issue might be there... Will try in their repo.

**Comment by Templarian** [comment]
Check the CSS panel in your dev tools and see if anything is overriding the `::before` class in some way.

Since it renders in the CDN's preview in various browsers I'm going to close this issue out. Definitely let me know if you find out what it is or can't solve it and I'll reopen this issue. Please make a small codepen/jsfiddle to better debug this.
