### ISSUE TITLE
  Icon file-document-box-multiple-outline did not added in mdi package

### ISSUE THREAD

**Issue by KashaevaD** [Templarian/MaterialDesign#3637]
This icon **file-document-box-multiple-outline** did not exist in `/node_modules/mdi/css/materialdesignicons.css`
Version of mdi: 2.2.43.

But I founded  **file-document-box-multiple-outline** in [site](https://materialdesignicons.com/) and [materialdesignicons.css](http://cdn.materialdesignicons.com/2.8.94/css/materialdesignicons.css)
![screenshot from 2018-10-19 10-59-16](https://user-images.githubusercontent.com/25029796/47205278-1c650780-d38e-11e8-90af-86a13a101acd.png)

_Why I can not find it in mdi package?_

**Comment by PeterShaggyNoble** [comment]
> Version of mdi: 2.2.43

You will need to update your files to the latest version of MDI - `file-document-box-multiple-outline` was added in v2.7.94, the current version is v2.8.94 and the next version (v3.0.39) is scheduled for release soon.

Note that there have been a few breaking changes since v2.2.43 was released, which you can check on [the history page](http://dev.materialdesignicons.com/history).
