### ISSUE TITLE
gate-clock

### ISSUE THREAD

**Issue by chrisdaloa** [Templarian/MaterialDesign#3638]
A combined icon gate+timer to assign to temporized gates in home assistant :)

**Comment by MrGrigri** [comment]
Do you have any suggestions for this?

**Comment by MrGrigri** [comment]
Would a `gate-clock` work?

![image](https://user-images.githubusercontent.com/4528551/47260341-f49d9e80-d476-11e8-9bd1-92b333e093e0.png)

[Asset 6.zip](https://github.com/Templarian/MaterialDesign/files/2498528/Asset.6.zip)

**Comment by chrisdaloa** [comment]
Great, it works yet?

**Comment by MrGrigri** [comment]
This is an 'unreleased draft'. If accepted by the community a milestone will be added and in that version, it'll be released.

**Comment by chrisdaloa** [comment]
It would be great! Thank you

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.

**Comment by goyney** [comment]
Reopening as it looks like this was closed by accident. The contribution has not been added to the library yet.

**Comment by goyney** [comment]
I apologize in advance. There seems to have been some miscommunication revolving around this issue that all started because GitHub had some internal error which was causing this specific issue to 404.

Additionally, there was some internal discussion back about a week ago with the contribution team where it was ruled this icon was deemed too niche to be added to the library. Unfortunately, when the issue was closed, that decision was not relayed to you here and so I mistakenly reopened it.

Because of the uniqueness of the situation, we had another small discussion about what to do this morning in regards to this issue and the consensus amongst the contributors retained that the icon is still too niche and we do not wish to add it to the library at this time. I'm, therefore, going to re-close this issue and mark it as rejected for now.

If you have other suggestions for how to supplement your use case with an icon or wish to provide more information that may help us reevaluate this in the future, feel free to add more here or to create a new issue.

Once again, we all sincerely apologize for the confusion and thank you for your suggestion.
