### ISSUE TITLE
War icon

### ISSUE THREAD

**Issue by AdiCovaci** [Templarian/MaterialDesign#365]
Like an icon suggesting armed confilct, for wars, could be useful in a news app
- [ ] bullets
- [x] swords
- [x] gun
- [ ] tank
- [x] bomb
- [ ] soldier

**Comment by Templarian** [comment]
I made a list of icons above that could probably fill that. If you have an example image that could help also.

**Comment by CoDEmanX** [comment]
The best I got so far:
![tank](https://cloud.githubusercontent.com/assets/1309249/8860090/ac77930e-3181-11e5-8e2c-51e38103b669.png) https://www.dropbox.com/s/x5y1m97d8h804fd/tank.svg?dl=0

2px spacing will make it looked like two detached things, thus I used 1px only. I guess the shape could be simplified even more...

**Comment by SLembas** [comment]
Tried myself.

![tank-24](https://cloud.githubusercontent.com/assets/5235533/12538556/1ddfdade-c2e5-11e5-859e-8bc0beba3906.png)
![tank-48](https://cloud.githubusercontent.com/assets/5235533/12538555/1ddc0a4e-c2e5-11e5-9d04-57118ce6b608.png)
![tank-192](https://cloud.githubusercontent.com/assets/5235533/12538554/1ddbacb6-c2e5-11e5-9f4c-56b2ac5405b1.png)

**Comment by CoDEmanX** [comment]
I like your approach. Can you make it a bit taller though?

**Comment by SLembas** [comment]
Updated. That's all I can do to keep it minimalistic: http://slembas.esy.es/tank.svg

![tank](https://cloud.githubusercontent.com/assets/5235533/12539134/67df84d6-c2f4-11e5-9e4d-97dca3acae6b.png)

**Comment by SLembas** [comment]
Oh, got another idea for tracks: http://slembas.esy.es/tank2.svg

![tank2](https://cloud.githubusercontent.com/assets/5235533/12539239/9ec948a4-c2f6-11e5-9542-e5df26211fd9.png)

**Comment by goyney** [comment]
Since @SLembas links are dead, I recreated their two tank variations here:
![image](https://user-images.githubusercontent.com/1015040/48816116-e90bf480-ed0e-11e8-8a0e-decd6e5ac37f.png)![image](https://user-images.githubusercontent.com/1015040/48816129-f0330280-ed0e-11e8-943f-fa69bb7d5e53.png)

[tanks.zip](https://github.com/Templarian/MaterialDesign/files/2602446/tanks.zip)

---

I also created some ammunition.
![image](https://user-images.githubusercontent.com/1015040/48816149-09d44a00-ed0f-11e8-8e52-becff837932c.png)![image](https://user-images.githubusercontent.com/1015040/48816165-15277580-ed0f-11e8-9fa3-6be7ca632a92.png)

[ammunition.zip](https://github.com/Templarian/MaterialDesign/files/2602447/ammunition.zip)

**Comment by goyney** [comment]
I almost feel like `worker` could double for a solider.

**Comment by JamesCoyle** [comment]
I prefer `tank` as the alt version feels too detailed IMO. The angled shoulder on the bullet might look better if it slopes more.

![image](https://user-images.githubusercontent.com/10384436/48832977-4f762e80-ed72-11e8-92a5-893d25c5554c.png)

**Comment by Templarian** [comment]
Added `tank`, `bullet`, and `ammunition`.
