### ISSUE TITLE
Checkbox marked outline

### ISSUE THREAD

**Issue by wayferer** [Templarian/MaterialDesign#3677]
To clarify I'd like the checkmark to be enclosed within the box where the current one breaks out of the corner.

**Comment by wayferer** [comment]
Here's an initial attempt 
![check-outline](https://user-images.githubusercontent.com/1575559/48073934-624f0780-e1a5-11e8-85ec-0c34c315cf60.png)

**Comment by MrGrigri** [comment]
These are kind of a mouthfull: `checkbox-marked-outline-variant`, `checkbox-multiple-marked-outline-variant`, `checkbox-marked-circle-outline-variant`, and `checkbox-multiple-marked-circle-outline-variant`. I figured since we are doing the checkbox, we should do them all. I labeled these as variants, but @Templarian, you can name them what you want. I do believe we should keep both.

![checkbox-marked-outline-variant](https://user-images.githubusercontent.com/4528551/48075464-91af4580-e1a0-11e8-8a4c-1e47eafb791e.png) ![checkbox-multiple-marked-outline-variant](https://user-images.githubusercontent.com/4528551/48075493-9d9b0780-e1a0-11e8-9f1a-8b519cfe80e1.png) ![checkbox-marked-circle-outline-variant](https://user-images.githubusercontent.com/4528551/48075525-abe92380-e1a0-11e8-94b6-db3bf27ce4fa.png) ![checkbox-multiple-marked-circle-outline-variant](https://user-images.githubusercontent.com/4528551/48075551-b99ea900-e1a0-11e8-884f-3db86317a49a.png)

[checkbox-outline.zip](https://github.com/Templarian/MaterialDesign/files/2553872/checkbox-outline.zip)

**Comment by JamesCoyle** [comment]
Would this be better as a `check-square` and `check-square-outline` icon to match these:
[![](https://materialdesignicons.com/icon/check-circle)](https://materialdesignicons.com/icon/check-circle)[![](https://materialdesignicons.com/icon/check-circle-outline)](https://materialdesignicons.com/icon/check-circle-outline)

**Comment by MrGrigri** [comment]
Are you talking about size? As the box is only 18x18 and the circle is 20x20.

**Comment by JamesCoyle** [comment]
We are missing `check-box` and `check-box-outline` so might be worth adding those instead of more `checkbox-marked` variants.

**Comment by wayferer** [comment]
Thanks for the quick response to this. Maybe it can follow the circle naming scheme where there is check-circle/-outline as that wouldn't need any renaming?

**Comment by MrGrigri** [comment]
Ah, It now just clicked what you were talking about. That does make sense.

**Comment by Templarian** [comment]
Had to read that a couple times, but yea. That makes sense adding these as `check-*` type icons.

**Comment by Templarian** [comment]
Added the two. 😃
