### ISSUE TITLE
LIVE Icon

### ISSUE THREAD

**Issue by ofekashery** [Templarian/MaterialDesign#3679]

**Comment by MrGrigri** [comment]
Most live icons are handled by one of three ways: the word live, a recording circle, or a play button. We are trying not to add language specific text and we already have the other two. Is there an example or idea that you have?

**Comment by ofekashery** [comment]
Something like that:
![image](https://user-images.githubusercontent.com/16443111/48143176-e9d86b80-e2b6-11e8-8d95-25a8ac5d76c3.png)

**Comment by MrGrigri** [comment]
This is exactly what I was talking about. We don't want to add language specific text like 'like', 'ao vivo', 'en vivo', etc. 

You could just use the 'record' icon with text next to it saying 'live'.

**Comment by goyney** [comment]
I agree with MrGrigri. Icons are intended to be supplemental visual representations. That typically means they should aim to transcend language and be universal. In this case, we have icons that are commonly used with something being "Live," such as the `play` or `record`.

Going to close this due to language conflict.
