### ISSUE TITLE
scale-off

### ISSUE THREAD

**Issue by Yanovsky** [Templarian/MaterialDesign#3682]
We need an icon similar to this one. Also need the same, but crossed out for the "broken" scales
![group 20](https://user-images.githubusercontent.com/6930863/48255393-97658f00-e41d-11e8-90ed-38dac040ce55.png)

**Comment by goyney** [comment]
It's just going to look like a rectangle and not convey meaning. I would recommend using `scale` and we'll create a `scale-off` in this thread.

**Comment by MrGrigri** [comment]
The problem with this icon is it won't be recognizable. Would `scale` or `scale-bathroom` not work?

![scale](https://materialdesignicons.com/icon/scale) ![scale-bathroom](https://materialdesignicons.com/icon/scale-bathroom]

**Comment by MrGrigri** [comment]
We could add a scale off.

![image](https://user-images.githubusercontent.com/4528551/48274153-ef8d9880-e3ff-11e8-9c34-5ee128f0fe97.png)

[scale-off.zip](https://github.com/Templarian/MaterialDesign/files/2566602/scale-off.zip)

**Comment by Yanovsky** [comment]
I didn't understand why topic has renamed. 
I wrote we need actually POS Scale icon like on a attached picture.
Because our clients can't associating proposed icon with real device
Also I asked about crossed out for the "broken" scales

**Comment by Yanovsky** [comment]
[Here is link on example SVG file](https://drive.google.com/file/d/1qvyDAcZ9mt16QHGwibpOWl1_fWlKIPQp/view?usp=sharingl)

**Comment by goyney** [comment]
@Yanovsky The reason the topic was renamed because both myself and @MrGrigri indicated that your proposal will not translate well to an icon and because we already have to `scale` variants in the library that can fulfill your use case.

Icons are meant to be supplemental to the meaning you are trying to convey. Utilizing our already existing `scale`, and the newly provided `scale-off`, it should be clear in the context of its use that you are talking about a device used to measure the weight of something, even if the icon isn't an exact visual representation of the device you are using. 

Think of it this way, we have `printer`, which indicates a device which can output content on a piece of paper. The icon mostly represents an ink jet style printer. However, you see this icon used everywhere to indicate printing, even if the physical device is, say, a laser printer.

We'll add `scale-off` in this thread. If you can provide a better example of something that may be useable in an icon for your specific use case, please create a new thread with that information for consideration. Thanks!

**Comment by goyney** [comment]
[![scale-off](https://materialdesignicons.com/icon/scale-off)](https://materialdesignicons.com/icon/scale-off)
