### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by bmpitzen** [Templarian/MaterialDesign#3702]
Could we get an icon for Ruby? I see the Ruby on Rails icon but I would love just the plain Ruby logo.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48974893-11f3f880-f033-11e8-8850-5d9128b5dcf0.png)
[ruby.zip](https://github.com/Templarian/MaterialDesign/files/2612783/ruby.zip)

**Comment by bmpitzen** [comment]
Thanks @goyney it looks great! Any word on when this will deploy? @Templarian

**Comment by goyney** [comment]
@bmpitzen We're getting ready to release the `3.2.xx` version, and this is slated for the `3.8.xx` version as of right now. We really don't have a hard timeframe on when a release happens; it's up to @Templarian's schedule, but the Contributors have been working to make his job easier so releases can happen more frequently.

Regardless, when this issue is closed, you'll get a notification and that is when it will be added to the next release. Sorry I cannot provide any more information than that at this time.

**Comment by Templarian** [comment]
[![ruby](https://materialdesignicons.com/icon/ruby)](https://materialdesignicons.com/icon/ruby)

This will be in the next release. 😃
