### ISSUE TITLE
Download specific icons with Material colors

### ISSUE THREAD

**Issue by Madis0** [Templarian/MaterialDesign#371]
It is great to see that you can download only the icon size you want with the color you want under Advanced, but can you please add 3 buttons to select only the Material, original colors (black, gray, white)? 
Would be great for making mockups and not having to remember Hex codes.
- [x] custom color pallet selector
- [ ] export to sizes like on the official google icon site.
- [ ] Persisting the colors between exports will be implemented in this rework also.
- [ ] The `dp` selector will consist of `18dp`, `24dp`, `36dp`, `48dp`, `all`.

**Comment by Templarian** [comment]
Funny enough this is already there, but it isn't documented anywhere. Right click the textfield where the hex color is.

I have plans to completely replace the color picker with a pallet of Material Design [colors](http://www.google.com/design/spec/style/color.html#color-color-palette).

**Comment by pawelantczak** [comment]
In addition. 
It would be great, to have a possibility, to get all sizes of icons with custom color.
Thanks.

**Comment by ComeBurguburu** [comment]
It would be great to have a border-radius option
to have round icon like this
![Image](http://www.virginia.edu/cue/images/twitter-round-icon.png)

**Comment by Templarian** [comment]
I started coding a Material Design specific color picker. If anyone has any UX input I would be very open to hearing it.

There are 19 sections of colors (+ Black/White). Designing a color picker to make viewing all the colors and making selection as fast as possible will be key.

http://www.google.com/design/spec/style/color.html#color-color-palette

http://codepen.io/templarian/pen/jPyvpv Barely started it, but I'll be building it out here as I get free time this week.

**Comment by Templarian** [comment]
An update as I've started to work more on the color picker. The UX on the modal is getting a different layout. The advanced menu will open up instead of down showing the color swatches. There will be only 1 download button. If the advanced panel is opened download packages will export only the selected color.

http://codepen.io/templarian/pen/jPyvpv

In the demo above if you click on a color square a preview of the file naming will display... `account_lightGreen800_24dp.png` style for instance.

Following Google's lead I've deleted _grey600_ from the default package.

Please let me know any feedback on the above points. This is going to be the next enhancement to the site.

**Comment by Templarian** [comment]
The color picker is coded, reworking the backend calls for all the various download combinations.

Let me know what you think of the [color picker](http://codepen.io/templarian/pen/jPyvpv) widget.

Two new tasks were added to the main issue.

- Persisting the colors between exports will be implemented in this rework also.
- The `dp` selector will consist of `18dp`, `24dp`, `36dp`, `48dp`, `all`.
