### ISSUE TITLE
network-card

### ISSUE THREAD

**Issue by Shikareth** [Templarian/MaterialDesign#3725]
I'm working with ethernet cameras and it would be nice to have something like this for interface settings interface.

![network_card](https://user-images.githubusercontent.com/16690152/48889062-e7d4e780-ee34-11e8-8e97-a684968bce2b.png)

---

- [ ] Rename `gpu` => `expansion-card` (Breaking)
- [x] Add @MrGrigri's contribution as `expansion-card-variant`
- [ ] Alias both with `graphics-processing-unit`, `gpu`, `network-interface-card`, `nic`

**Comment by goyney** [comment]
Would `gpu` work?

[![gpu](https://materialdesignicons.com/icon/gpu)](https://materialdesignicons.com/icon/gpu)

**Comment by Shikareth** [comment]
Gpu icon won't work. 

I am in favor of RJ45 variant.

**Comment by MrGrigri** [comment]
I believe an RJ-45 wouldn't translate at such a small space within the card. Here is what I've come up with. This will work for various cards. However, I'm not sure on the name because it might cause confusion with the general `network-*` icons.

![image](https://user-images.githubusercontent.com/4528551/48960366-382d7180-ef29-11e8-9d13-e3b5b8fcbe1c.png)

---

[network-card.zip](https://github.com/Templarian/MaterialDesign/files/2611729/network-card.zip)

**Comment by goyney** [comment]
Honestly, I think both @MrGrigri's new icon and `gpu` are just too variations of a computer expansion card. I would suggest we rename `gpu` to something like `expansion-card`, make the new one a variant, and alias them appropriately.

**Comment by MrGrigri** [comment]
@goyney, I agree completely. Although, the only noticeable difference is the fan instead of a chipset on the GPU.

**Comment by goyney** [comment]
The variant was added:
[![expansion-card-variant](https://materialdesignicons.com/icon/expansion-card-variant)](https://materialdesignicons.com/icon/expansion-card-variant)

**Comment by goyney** [comment]
[![expansion-card](https://materialdesignicons.com/icon/expansion-card)](https://materialdesignicons.com/icon/expansion-card)
