### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by PaulWoitaschek** [Templarian/MaterialDesign#3734]
> materialdesignicons.com uses an invalid security certificate. The certificate expired on November 24, 2018, 10:38:10 PM GMT+1. The current time is November 25, 2018, 9:42 AM.

Expired yesterday

**Comment by Templarian** [comment]
Resolved, but keep this opened to figure out why the corn job stopped running. I might have messed up something on this box. I'm keeping this opened to figure out why it didn't run.

**Comment by Templarian** [comment]
Okay, when I migrated servers (upgraded ram, because traffic has gone up gradually), I somehow wiped out the cron tasks. Completely didn't see that before because I have it running in quiet mode. I'll double check next month to ensure the cert renews.

Always fun when this stuff happens while I'm asleep.
