### ISSUE TITLE
beaufort 0 -12

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3743]
please consider creating icons for beaufort windspeed 0 -12

hadn't asked if numeric went up to 12 ;-)

which would be fine also. Having weather-windy with a number up to 12 would be even better, but I daren't ask...
thanks for considering

**Comment by MrGrigri** [comment]
From what I can tell, there isn't a specific or regulated symbol for the beaufort measurement. Adding the numbers 1-12 with `weather-windy` will not work as the icons are only 24- x 24-pixels. We have decided to not go above 10 with numbers so that is also not going to work. Do you have any other suggestions?

**Comment by CoDEmanX** [comment]
There is probably a plethora of measurement or other systems using numbers, using varying scales and ranges. I don't see why specific icons would be useful to display particular values.You can use combinations of the 0-9 icons, or simply use text. Are there sensible use cases which require a single icon to show the full value? In smartphone apps perhaps, because you can have a single icon only in notifications? But then again, why not use text and write it in the notification instead of having different icons? If you really need it, then I bet you can program something for dynamic icons and generate them on-the-fly.

**Comment by goyney** [comment]
Agree with both @MrGrigri and @CoDEmanX. I don't think this is way too specific for us to add to this library.

**Comment by PeterShaggyNoble** [comment]
Agreed with the others. Closing.

@Mariusthvdb, if you can find a standardised set of icons for this anywhere please comment and we'll revisit this.
