### ISSUE TITLE
New Fire icons

### ISSUE THREAD

**Issue by Magaradja** [Templarian/MaterialDesign#3807]
What about some modifications of Fire icon? For example filled, outlined or with some symbols inside.

**Comment by PeterShaggyNoble** [comment]
Our current `fire` icon is Google's filled version. Here's their outline version:

[![fire-outline](https://user-images.githubusercontent.com/15157491/50960384-2bef7a80-14bd-11e9-9da6-34a9aae5487e.png)](https://material.io/tools/icons/?search=whatshot&icon=whatshot&style=outline)

**Comment by Magaradja** [comment]
Recently fire icon was changed. On https://materialdesignicons.com/ current version 
![image](https://user-images.githubusercontent.com/9250383/50964664-ea70c680-14e0-11e9-8bb3-e7d154897595.png)
So, it seems easy to make completely filled(without any holes).

**Comment by goyney** [comment]
That's not an outlined version, though. The stroke is too wide.

Honestly, I don't think we need another fire variation. What value would a filled version bring you? What's your use case?

**Comment by Magaradja** [comment]
I may not completely describe my use case. Now I have to use awful combination of icons to make result. I want to reduce their number a little. Finally, I'll create issue with zip files with icons, you decide to accept or disline. As I undestand, it is a correct way to suggest new icons.

**Comment by Templarian** [comment]
Not really a fan of the old fire icon we had (why it was replaced). Fine taking our new one and making an outline though.

**Comment by Magaradja** [comment]
New, 2dp version of outline icon. @PeterShaggyNoble, it'll be better
[fire-outline.zip](https://github.com/Templarian/MaterialDesign/files/2758417/fire-outline.zip)
?

**Comment by goyney** [comment]
Our current `fire` icon is an icon which does not have a logical "outline" variation because of the nature of its design. The best we could do is create an inversed version of it, but we don't have a precedent for doing that.

The other fire icons provided by @Magaradja reduces the stroke or fills the entire shape in a way in which, I feel, detracts from the meaning of the icon at native resolution.

That all being said, I still feel this issue should just be closed. I'll bring this up for discussion internally on the team before taking an action one way or another.

**Comment by Templarian** [comment]
Going to agree with this. We're probably best just closing this issue out as `fire-outline` would best be represented by simply using the current `fire` icon.
