### ISSUE TITLE
content-save-alert

### ISSUE THREAD

**Issue by MitchBerninger** [Templarian/MaterialDesign#3817]
I ended up making a save icon with an alert indicator for a project. Sharing here to extend what is currently available. Let me know if there are any issues that need to be fixed.

[content-save-alert.svg.zip](https://github.com/Templarian/MaterialDesign/files/2749824/content-save-alert.svg.zip)
[content-save-alert-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2749825/content-save-alert-outline.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Good idea for an icon, @MitchBerninger; thanks for the contributions.

However, could you update them to use a single path, please?

**Comment by MitchBerninger** [comment]
Hey @PeterShaggyNoble, attached are the updated versions of the icons. Fixes include converting the icons into a single compound path and maintaining the proper white space around the icons.

[content-save-alert.svg.zip](https://github.com/Templarian/MaterialDesign/files/2750880/content-save-alert.svg.zip)
[content-save-alert-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2750881/content-save-alert-outline.svg.zip)

**Comment by goyney** [comment]
Can you please generate previews for these? http://dev.materialdesignicons.com/contribute/github

**Comment by MitchBerninger** [comment]
Absolutely @goyney. I have noticed previews in other issues but did not know where to create them. Thanks for providing the link!

![image](https://user-images.githubusercontent.com/10249199/51060068-5411d300-15bc-11e9-9929-a5483ef4cec0.png)
![image](https://user-images.githubusercontent.com/10249199/51060091-76a3ec00-15bc-11e9-8e83-55917c73c0ad.png)

**Comment by MrGrigri** [comment]
I'm not such a fan of these. I feel like the outlined version -- since it lines up with the outline of the disk -- is a bad choice because it just breaks up the border. The other is lost sum what. The standard for alert style icons is to either have it centered in the object (`home-alert`) or to the right side (`disc-alert`).

[![home-alert](https://user-images.githubusercontent.com/4528551/51060651-a7305980-15ad-11e9-8d74-51b2a2729d80.png)](https://materialdesignicons.com/icon/home-alert) [![disc-alert](https://user-images.githubusercontent.com/4528551/51060542-4e60c100-15ad-11e9-84f7-e8db81262ffa.png)](https://materialdesignicons.com/icon/disc-alert)

**Comment by goyney** [comment]
To be fair, we do have a couple icons that do the whole line-up-with-the-outline thing:
[![network-strength-1-alert](https://materialdesignicons.com/icon/network-strength-1-alert)](https://materialdesignicons.com/icon/network-strength-1-alert)

**Comment by MrGrigri** [comment]
Yeah, I still don't like that one either. I still think we should just shrink the disk and place the exclamation on the right side.

**Comment by goyney** [comment]
Added! 💾
