### ISSUE TITLE
Search Modifiers

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3883]
![image](https://user-images.githubusercontent.com/1015040/52186400-2b64ae00-27f5-11e9-9a1f-6907bab61005.png)![image](https://user-images.githubusercontent.com/1015040/52186405-31f32580-27f5-11e9-9259-6f9bcdda93f8.png)
![image](https://user-images.githubusercontent.com/1015040/52186518-d1181d00-27f5-11e9-9a11-8043a605cb5f.png)

[search-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/2826269/search-modifiers.zip)

---

These should complement:
[![regex](https://materialdesignicons.com/icon/regex)](https://materialdesignicons.com/icon/regex)

**Comment by CoDEmanX** [comment]
Not a fan of using letters based on the initials of associated English words.

Furthermore I worry that the asterisk symbol is also not understood universally. The `.*` combination stands for regular expression pars pro toto rather than a concrete search pattern, therefore I don't think we are forced to use an asterisk here. On the other hand, an asterisk may also be known to the user as wildcard character - which is different to a regex. A "starts-with" regex would be more like `A.*` or `A\w+`. Perhaps it's just the use of different letters in the icons which does not feel right to me. Or the font even?

Couldn't we express this language neutral by using e.g. an A to represent text generally, and some strokes?

Something like:
![grafik](https://user-images.githubusercontent.com/1309249/53725871-2125e600-3e6d-11e9-86f4-780317915978.png)

![grafik](https://user-images.githubusercontent.com/1309249/53726327-04d67900-3e6e-11e9-89f9-968bfd85be61.png)

![grafik](https://user-images.githubusercontent.com/1309249/53726454-4109d980-3e6e-11e9-9035-8c071db2db2e.png)

From VS Code for find full words only: ![grafik](https://user-images.githubusercontent.com/1309249/53724898-38fc6a80-3e6b-11e9-83f0-bebf0d72279f.png)

**Comment by JamesCoyle** [comment]
Depending on the context wouldn't `^` and `$` work?

**Comment by CoDEmanX** [comment]
Only in the regex domain. There it means beginning/end of source text (or line if the multiline flag is set). I would say the meaning is different to "starts with" / "ends with", but it comes down to the same result.What do we actually want to express with these icons and in which context?

**Comment by goyney** [comment]
`^` and `$` would not work. I think @CoDEmanX may be on to something with his ideas.

**Comment by goyney** [comment]
@CoDEmanX I like your second option the best. Can you make one for ends-with and whole world in that style so you get credit for the three? :)

**Comment by JamesCoyle** [comment]
Well those characters have been used for css attribute selectors too. I think in a programming context they make sense but not so much in other contexts.

I'd be tempted to use something like `arrow-collapse-*` in more generic contexts.

**Comment by CoDEmanX** [comment]
`arrow-collapse-*` have a notion of motion to me, which doesn't really fit in my opinion.

I also thought about the second option a bit more and came to the conclusion that one might confuse the starts and ends with. With the letter moved to the left and the underline thingy with the vertical line on the right, there is just a bit of whitespace which stands for an arbitary amount of additional characters and is supposed to show that the A is the beginning of something. I think it would be better to have the letter centered and let the underline thingy show whether it's start (left-hand side) or end (right-hand side):

![grafik](https://user-images.githubusercontent.com/1309249/53771029-6be14580-3ee1-11e9-9454-8b264d539475.png)
![grafik](https://user-images.githubusercontent.com/1309249/53771051-7ac7f800-3ee1-11e9-83a5-3286bc72ef59.png)
![grafik](https://user-images.githubusercontent.com/1309249/53771059-86b3ba00-3ee1-11e9-8537-d832d066d8b9.png)

Another option would be:

![grafik](https://user-images.githubusercontent.com/1309249/53771104-aa770000-3ee1-11e9-88a9-f810f7144ab0.png)
![grafik](https://user-images.githubusercontent.com/1309249/53771051-7ac7f800-3ee1-11e9-83a5-3286bc72ef59.png)
![grafik](https://user-images.githubusercontent.com/1309249/53771117-b95db280-3ee1-11e9-9ac1-6b9dee8353c2.png)

Even more abstract is difficult because a single letter doesn't really work in this:

![grafik](https://user-images.githubusercontent.com/1309249/53771504-1c9c1480-3ee3-11e9-9951-5398d16d2bf9.png)

We could give up on margin so that the two letters don't get too tiny, but I don't find it as understandable as above options.

[search-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/2928696/search-modifiers.zip)

**Comment by goyney** [comment]
These three are my vote:

![image](https://user-images.githubusercontent.com/1015040/53851172-c8993a80-3f8b-11e9-84dc-939a399232aa.png)![image](https://user-images.githubusercontent.com/1015040/53851175-cb942b00-3f8b-11e9-8e96-248bbb4e2e65.png)
![image](https://user-images.githubusercontent.com/1015040/53851181-d18a0c00-3f8b-11e9-8d31-7c9c310c0224.png)

Thanks, @CoDEmanX!

**Comment by goyney** [comment]
[![format-letter-starts-with](https://materialdesignicons.com/icon/format-letter-starts-with)](https://materialdesignicons.com/icon/format-letter-starts-with)[![format-letter-ends-with](https://materialdesignicons.com/icon/format-letter-ends-with)](https://materialdesignicons.com/icon/format-letter-ends-with)
[![format-letter-matches](https://materialdesignicons.com/icon/format-letter-matches)](https://materialdesignicons.com/icon/format-letter-matches)
