### ISSUE TITLE
Tree outline

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#3931]
Hey,
I'd like to replace solid icons with outline ones in an app and need an outline variant of https://materialdesignicons.com/icon/tree for that. Thanks for all the other icons :+1: .

**Comment by CoDEmanX** [comment]
The leaves are 3 circles in the filled variant, but as 2dp circle outlines the top and left one don't overlap fully:

![grafik](https://user-images.githubusercontent.com/1309249/53235704-c503da80-3692-11e9-8e79-812c59318799.png)

I tweaked the inner radius a little from 5dp to 5.125 dp on both. This is the result:

![grafik](https://user-images.githubusercontent.com/1309249/53236770-5e33f080-3695-11e9-82e2-d4d3205d1455.png)

Also tried to emphasize the inner shape by making the inner radius of the right circle smaller, so that it barely touched the other two:

![grafik](https://user-images.githubusercontent.com/1309249/53236799-70ae2a00-3695-11e9-992c-43f1b1c5b2bb.png)

The third option would be to use a rounded counter shape, but it loses a lot in recognizability:

![grafik](https://user-images.githubusercontent.com/1309249/53236720-40ff2200-3695-11e9-9e5f-5d2d1104aa84.png)

Download: [tree-outline.zip](https://github.com/Templarian/MaterialDesign/files/2893517/tree-outline.zip)

**Comment by JapanYoshi** [comment]
I think we should leave the radii the same, but visually correct the intersections manually.

**Comment by CoDEmanX** [comment]
There is barely a difference, but okay. Here are three more variants using the original radii:

![grafik](https://user-images.githubusercontent.com/1309249/53716975-f6309780-3e56-11e9-8a26-86b2ee17b7fe.png)
![grafik](https://user-images.githubusercontent.com/1309249/53716981-047eb380-3e57-11e9-97d2-9e811191d8b9.png)
![grafik](https://user-images.githubusercontent.com/1309249/53716996-119ba280-3e57-11e9-8c0b-1a9fc29d143d.png)

And another idea, also using the original radii and visual corrections:

![grafik](https://user-images.githubusercontent.com/1309249/53718413-71944800-3e5b-11e9-9937-8d7378deb1b1.png)


[tree-outline.zip](https://github.com/Templarian/MaterialDesign/files/2924796/tree-outline.zip)

**Comment by Templarian** [comment]
Tree Outline 5.
