### ISSUE TITLE
folder-zip

### ISSUE THREAD

**Issue by opaquewarellc** [Templarian/MaterialDesign#3948]
I would like to request for a Zip File icon that is based from the standard Google FIle icon. 
Thx

**Comment by PeterShaggyNoble** [comment]
See also #1093, #1288, #2825, #2305 and many more I'm probably forgetting.

**Comment by goyney** [comment]
@PeterShaggyNoble I left this one open because on the latest issue (#2825), we said:

> if you come up with any other ideas or alternatives on how to indicate a file archived

This issue has an idea to work the zip icon we currently have into the file icons. I may actually take a stab at this one soon.

**Comment by goyney** [comment]
Let's add `zip-box-outline`, since we're missing it:

![image](https://user-images.githubusercontent.com/1015040/53689785-778b0b80-3d2b-11e9-91ca-0593c0ce5373.png)

---

For the issue, I don't think using `file` as the base makes sense, since a ZIP file is an archive of one or (usually) more files. Using `folder` seems like a better idea. Perhaps like this:

![image](https://user-images.githubusercontent.com/1015040/53689791-98536100-3d2b-11e9-895e-8bffff841880.png)![image](https://user-images.githubusercontent.com/1015040/53689794-9f7a6f00-3d2b-11e9-8e33-d8c7c6cc33e8.png)

[zip.zip](https://github.com/Templarian/MaterialDesign/files/2922666/zip.zip)

**Comment by goyney** [comment]
[![folder-zip](https://materialdesignicons.com/icon/folder-zip)](https://materialdesignicons.com/icon/folder-zip)[![folder-zip-outline](https://materialdesignicons.com/icon/folder-zip-outline)](https://materialdesignicons.com/icon/folder-zip-outline)
[![zip-box-outline](https://materialdesignicons.com/icon/zip-box-outline)](https://materialdesignicons.com/icon/zip-box-outline)
