### ISSUE TITLE
file-pdf-outline

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#3958]
file-pdf, but outlined

**Comment by goyney** [comment]
Related: https://github.com/Templarian/MaterialDesign/issues/3101

**Comment by PeterShaggyNoble** [comment]
I don't know that this one's going to be possible; the Acrobat logo would need to be reduced to keep it away from the file's outline, which would make it unrecognisable.

**Comment by CoDEmanX** [comment]
Even a text-based variant isn't really feasible unless you use a font even smaller than this:

![grafik](https://user-images.githubusercontent.com/1309249/53652279-cd3ab780-3c48-11e9-9c3a-530cc1165147.png)

... because it's already getting very close to the border of the filled document.

The F is too narrow and the D looks like an O:

![grafik](https://user-images.githubusercontent.com/1309249/53652617-a03ad480-3c49-11e9-95b9-5b283a57ad43.png)

[file-pdf-outline.zip](https://github.com/Templarian/MaterialDesign/files/2920321/file-pdf-outline.zip)

**Comment by goyney** [comment]
Our current `file-pdf` icon is off-center, so let's fix that first.

![image](https://user-images.githubusercontent.com/1015040/53689647-478e3900-3d28-11e9-9531-114dbe9c95e9.png)
Outline is our current.

---

![image](https://user-images.githubusercontent.com/1015040/53689663-8623f380-3d28-11e9-930a-3731d3158084.png)

It's really not much worse than the current `file-pdf` icon, to be quite honest.

[file-pdf.zip](https://github.com/Templarian/MaterialDesign/files/2922651/file-pdf.zip)

**Comment by Templarian** [comment]
[![file-pdf](https://materialdesignicons.com/icon/file-pdf)](https://materialdesignicons.com/icon/file-pdf)

Re-vectored to remove a lot of unnecessary point data also. Going to stick with the symbol since the letters get a bit crushed.
