### ISSUE TITLE
Official Flutter Package

### ISSUE THREAD

**Issue by MichaelPriebe** [Templarian/MaterialDesign#4125]
Wondering if you guys could create an official [Flutter](https://flutter.dev/) package. [One exists](https://pub.dartlang.org/packages/material_design_icons_flutter) but it takes some time for them to manually update it. Would like to see one that updates more frequently, or automatically.

**Comment by Templarian** [comment]
That is very interesting and terrifying. Flutter use the `534kb` ttf font and not the vector paths. No idea why they are doing that, it seems like it would be extremely heavy. Each release our webfonts get larger.

We require all of our first party packages to use the vector `@mdi/svg` or `@mdi/js` as a dependency (even if it's indirectly during compile time). Unfortunately I don't know flutter or dart to write/maintain a package.

We have to rely on the third parties to maintain these libraries. I would just open up a very nice issue asking if they can update their dependency.

**Comment by MichaelPriebe** [comment]
SVG is not supported (officially) yet. That is why it uses a font.

**Comment by Templarian** [comment]
Did a little research. Looks like wrapping `flutter_svg` to render icons might be an okay solution. Since it uses pretty low level API's to render the vectors it would work great from a performance standpoint.

Would have to be wrapped into a nice component like our other first party solutions. For now I think the existing project that uses the TTF is fine. Looks like they update pretty regularly. Not terribly far behind us.

Can dart import and use our `@mdi/js` package from NPM/github? Not sure how friendly dart is with JS packages or if they can import them.

**Comment by MichaelPriebe** [comment]
Ideally you want to use a font, exactly like how Flutters built in [Icons](https://docs.flutter.io/flutter/material/Icons-class.html) use so you can use them in the [Icon Widget](https://docs.flutter.io/flutter/widgets/Icon-class.html)

**Comment by Templarian** [comment]
That makes sense. Definitely would be a nice update on their part to support an SVG assets or in our case we always publish a single SVG vector path so our components can do `<Icon path={mdiAccount}/>` type.

If they had `woff2` it would cut down the size of the font a long. `TTF` is one of our heaviest files since it was never really created to be small/optimized for web.

Going to close this out for now as a first party component is outside of our scope.

**Comment by Templarian** [comment]
Just wrote up a quick first draft of a Third Party dev guide. Will expand it to give some guidelines.

https://dev.materialdesignicons.com/contribute/third-party

**Comment by Templarian** [comment]
@MichaelPriebe https://github.com/Templarian/MaterialDesign-Site/issues/85

I had forgot someone asked us to document flutter. I'm going to make a page with the above issue and some place holder text. Just wanted to let you know.
