### ISSUE TITLE
A webcomponent for MaterialDesignIcons

### ISSUE THREAD

**Issue by burawi** [Templarian/MaterialDesign#4128]
I created a package that uses MaterialDesignIcons in an es6 web-compoent:
Here is a link: [https://www.npmjs.com/package/mdi-component](https://www.npmjs.com/package/mdi-component).
I don't know if I can count this as a contribution. That's why I created a new issue.

**Comment by Templarian** [comment]
Marking this as a question, but I'm going to use this issue to track a spec for a first party web component. It's been on my mind for a while since my day job is web components and could use some help writing this.

Few things for it to be first party:
- Needs to be in TypeScript
- Feature parity with `@mdi/react`
- Jest test suite

Quick glance at the code, it looks like it imports all of the icons and will not tree-shake out the unused ones? Might be ideal to just assume `<icon name=""/></icon>` is for the webfont and `<icon path=""></icon>` is for the path data.

What do you think of that for a middle ground so ES6 compilation works, but would still let one use it native.

**Comment by Templarian** [comment]
Just got back from MS Build and short vacation. Going to be looking into this a bit and setting up a boilerplate repo. Looking around at various blog posts/tutorial to see how to best handle this.

**Comment by burawi** [comment]
Sorry for not answering, I've been working on a project last week (The one for which I created the package).
I'll try to work on it too next days.

**Comment by Templarian** [comment]
@burawi https://github.com/Templarian/MaterialDesign-Web-Component

Configured for TS + Rollup Build, and configured it for Jest unit testing. Please submit a PR to the `package.json` adding yourself as a contributor. We can work on making this similar to `@mdi/react`.

Hopefully the name is fine. `mdi-icon` and `mdi-stack` so it's easy for people going back and forth between react.

**Comment by Templarian** [comment]
If you can run the app you should see something like:

![image](https://user-images.githubusercontent.com/338885/57589559-39a82180-74ea-11e9-8b7a-0787dcbba30f.png)

I need to work on icon issues for the rest of the night, but will try to setup a GitHub Action to build/publish automatically to: https://templarian.github.io/@mdi/web-component/ after every change.

**Comment by Templarian** [comment]
No rush, I did add you as a collaborator to the repo, but don't feel obligated to work on it. Especially if you're solution works good for your uses.

Wanted to give you the ability to help out more directly if you were interested. Going to close this issue as the repo can track the progress.

Completion will be feature parity with `@mdi/react`.
