### ISSUE TITLE
Unsharp and pixelated icon after export in png format

### ISSUE THREAD

**Issue by makerlabs** [Templarian/MaterialDesign#4216]
Like in the topic when u customize your icon on https://materialdesignicons.com/ and export it as png the result icon is pixelated and unsharp.

**Comment by JapanYoshi** [comment]
What resolution are you exporting at?

**Comment by makerlabs** [comment]
at 24x24 but regardless of the resolution the effect is always the same 
https://imgur.com/VUpGQLA

**Comment by JapanYoshi** [comment]
That explains it. You're exporting an image at 24 pixels wide.

**Comment by goyney** [comment]
There is no bug here, that is what happens when you export a raster based image.

Vector based images (such as SVGs, which all of our icons are created in), use math to draw their lines instead of pixels. This allows them to look crisp.
![image](https://user-images.githubusercontent.com/1015040/60340839-b009c180-997a-11e9-92c4-773b4eb9a7c2.png)

Raster based images (such as JPG and PNG) use raw pixel data.
![image](https://user-images.githubusercontent.com/1015040/60340847-b5ffa280-997a-11e9-9768-3b37ac178a12.png)

I believe your screenshot is also exacerbating the pixelation because you are likely on a Retina or high DPI monitor. PNG images created for the web are at a resolution of 72dpi.

**Comment by makerlabs** [comment]
@JapanYoshi @goyney well I din't know u are using canvas to export your icons to png. Next time you should read about devicePixelRatio and how to save your image rather than talking about how raster and vector base image works... It was great talking to you bb.

**Comment by JapanYoshi** [comment]
This happens no matter how you export a vector image into 24px raster, idiot.

**Comment by Templarian** [comment]
Be nice @JapanYoshi, but they are right @makerlabs since you are not on a native 1:1 display you're going to see blurry images. If you are not using vectors it's often best to export at 2x the size since most run their displays at 200% scale or less.

In UI design we refer to 24x24 as device pixels. On a 200% scaled "retina" display this could be 48x48. Because of this vector is almost always preferred for icons due to their small size pixelation is most noticeable.
