### ISSUE TITLE
Humidifier

### ISSUE THREAD

**Issue by bieniu** [Templarian/MaterialDesign#4217]
I have:

- [X] Searched all issues to make sure there isn't a request for this icon.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Home Assistant

**Comment by goyney** [comment]
We could potentially modify Google's `air-purifier` for this:
![image](https://user-images.githubusercontent.com/1015040/60378189-c2244800-99ec-11e9-95e9-e4020f7d0e46.png)

Or, here's something a little more abstract:
![image](https://user-images.githubusercontent.com/1015040/60378191-cfd9cd80-99ec-11e9-8841-ea8e678a6d51.png)

[humidifiers.zip](https://github.com/Templarian/MaterialDesign/files/3341284/humidifiers.zip)

Waiting to through a milestone on this because I would like input from other collaborators on this specific issue.

**Comment by GreenTurtwig** [comment]
Definitely the first one. 👍

**Comment by bieniu** [comment]
The first one is great.

**Comment by MrGrigri** [comment]
Agreed, the first one is the best.

**Comment by goyney** [comment]
[![air-humidifier](https://materialdesignicons.com/icon/air-humidifier)](https://materialdesignicons.com/icon/air-humidifier)
