### ISSUE TITLE
Weather alert icons

### ISSUE THREAD

**Issue by Imbuzi** [Templarian/MaterialDesign#4224]
I have:

- [x] Searched all issues to make sure there isn't a request for this icon.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'm creating a weather forecast and alert card in Home Assistant (it based on Météo France weather forecasts, that also provides alerts for some weather conditions such as thunder, strong wind or things like that). The idea is to get an icon for each type of weather events (maybe based on Météo France ones). Some already exists (like heat wave, we can use thermometer), some doesn't.

Here you can find a picture of the weather card in HA, with a yellow alert for thunder.

![image](https://user-images.githubusercontent.com/20660653/60489673-312bc600-9ca5-11e9-888e-d0ee2192c038.png)

## Examples

Here's the list of the official Météo France icons.

![image](https://user-images.githubusercontent.com/20660653/60489900-be6f1a80-9ca5-11e9-98b4-1235957dd000.png)

For now, I'm using these combinations of icons in HA : 

Strong wind (vent-violent) : ?
Thunder (orages) : Maybe an adaptation of mdi:weather-lightning, with a "!" on the right, like mdi:thermometer-alert
Rain/flood (pluie/innondations) : ?
Flood (innondation) : ?
Waves/submersion (vagues/submersion) : ?
Extreme cold temp. (grand froid) : Maybe an adaptation of mdi:thermometer-alert with a snowflake on the top left
Heat wave (canicule) : mdi:thermometer-alert
Snowslide (avalanche) : ?
Snow/ice (neige/verglas) : Maybe there is something to do with the mdi:snowflake ...

I'd really like to have a "!" on every icon, it would be easier for the user to differenciate this icons that are for weather alerts, and the ones that are for weather forecasts only

## More info

For now, I don't know how can I create my custom icons to submit to this repo. I've used Photoshop for a long time, but not to create SVG. If I can help by making icon examples in JPG, and then someone can help me transform it to SVG, it would be very nice !

**Comment by goyney** [comment]
Some of these are kinda niche and very uncommon. Let's see what we can do to satisfy this request:

- Strong wind (vent-violent): Use [`weather-windy`](https://materialdesignicons.com/icon/weather-windy)
- Thunder (orages): See new contribution further down
- Rain/flood (pluie/innondations): [`weather-pouring`](https://materialdesignicons.com/icon/weather-pouring) is likely your best bet
- Flood (innondation): See new contribution further down
- Waves/submersion (vagues/submersion): See new contribution further down
- Extreme cold temp. (grand froid): See new contribution further down
- Heat wave (canicule): [`thermometer-alert`](https://materialdesignicons.com/icon/thermometer-alert) or [`weather-sunny-alert`](https://materialdesignicons.com/icon/weather-sunny-alert)
- Snowslide (avalanche): I think this is too niche
- Snow/ice (neige/verglas): [`snowflake`](https://materialdesignicons.com/icon/snowflake) or [`snowflake-variant`](https://materialdesignicons.com/icon/snowflake-variant)

---

Here are some new potential contributions:

![image](https://user-images.githubusercontent.com/1015040/60523169-465e2000-9cb8-11e9-9324-05ab67a17f2c.png)![image](https://user-images.githubusercontent.com/1015040/60523211-58d85980-9cb8-11e9-9ae9-58071d6d5c1d.png)
![image](https://user-images.githubusercontent.com/1015040/60523236-6261c180-9cb8-11e9-9f80-00faf5e77293.png)![image](https://user-images.githubusercontent.com/1015040/60523261-68f03900-9cb8-11e9-8be0-c97b0b43b403.png)
![image](https://user-images.githubusercontent.com/1015040/60523282-73aace00-9cb8-11e9-9222-cad23e86d9dd.png)

[weathery.zip](https://github.com/Templarian/MaterialDesign/files/3350712/weathery.zip)

---

I'm not sure about `home-flood`. I think the rest are fine.

**Aliases To Add**:

- [ ] `snowflake-alert` -> `cold-alert`
- [ ] `waves` -> `ocean`, `lake`, `flood`
- [ ] `flash-alert` -> `lightning-alert`
- [ ] `flash-outline-alert` -> `lightning-outline-alert`

**Comment by JamesCoyle** [comment]
What would home flood look like without the door?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/60530495-defb9c80-9cc6-11e9-9698-21f2240ddb18.png)
[home-flood-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/3351077/home-flood-variant.svg.zip)

**Comment by Templarian** [comment]
Looks like an arrow. 🤔

**Comment by Templarian** [comment]
Added the 5 and updated `waves`.

**Comment by goyney** [comment]
Aliases added.

**Comment by Mariusthvdb** [comment]
is it allowed to get back on this please, or do I need to re-enter an new issue.

Since some of the icons are left open really, and probably rather easy to fulfill? 
As seen on the http://meteoalarm.eu/legend.inc.php?lang=en_UK&s=1&d= legend, the _coastal event_ isn't the same as mdi:waves nor are the _temp high_ and _temp low_ alerts, while these could easily be made and aren't true niche icons, on the contrary I would say...
`Forest-fire` would be great if added, and certainly would have added value above mdi:fire, or camp-fire for that matter. 

Only ones that could somewhat be considered niche would be avalanche and rain-flood, though these 2 are happening too often unfortunately and would be of real help to the frontend.

So please reconsider adding dedicated icons for:

coastal-event  (heavy waves, not the plain ones available.)
high-temp-alert  (thermometer alert with up arrow)
low-temp-alert (thermometer alert with down arrow)
forest-fire (combine pine-tree and fire)
avalanche
rain-flood (combine rainy and wave )

above would be states for suggestion for icons if reconsidered, though the icons shown on the link speak for them selves, and are really close to the material design icons, if adapted in a few spots as I hope.

Avalanche would need some work, but is dangerous and important enough, and unfortunately frequent enough to not have a dedicated icon....

thanks for considering!
