### ISSUE TITLE
restore-alert

### ISSUE THREAD

**Issue by rickx** [Templarian/MaterialDesign#4247]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/1685369/61203257-25e78a00-a6ea-11e9-9080-c37863d9e04c.png)

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[factory-reset.zip](https://github.com/Templarian/MaterialDesign/files/3391387/factory-reset.zip)

**Comment by goyney** [comment]
Nice first contribution! You're definitely on the right track, but there are a few things we'll need to address. Let's go through those and make this ready-to-add.

1. You'll notice that the circle and exclamation point in your contribution is "off-grid," meaning it doesn't line up directly on a grid line. We always try to keep shapes on the grid because the look sharper at native (24x24) resolution.
2. The counter-clockwise circle with the arrow matches an icon we already have, `restore`. Let's use this as the base icon. This also puts the circle on the grid.
3. Material guidelines want all lines to be no wider than 2dp, unless absolutely needed, so let's shrink down the exclamation point and center it within the circle.

Making those changes we get:

![image](https://user-images.githubusercontent.com/1015040/61232488-651ed680-a6fc-11e9-92d3-72303dfca1f7.png)
[restore-alert.svg.zip](https://github.com/Templarian/MaterialDesign/files/3393248/restore-alert.svg.zip)

Notice how much crispier the exclamation point looks in the center of the icon at native resolution. That's the goal.

Again, nice work! We'll assign this icon to the global Contributor account until you reach a total of 5 icons added. When that happens, let us know and we'll reassign these to you. 😄

**Comment by goyney** [comment]
Might as well mirror it and add `reload-alert` as well.

![image](https://user-images.githubusercontent.com/1015040/61233105-c6937500-a6fd-11e9-85c3-243cccdc29fa.png)
[reload-alert.svg.zip](https://github.com/Templarian/MaterialDesign/files/3393281/reload-alert.svg.zip)

**Comment by rickx** [comment]
Dear gogney,
thanks first of all. Actually I got the circle from "lock-reset" and didn't change it at all, but I get what you mean. I'd just like to add 2 quick things:
1. is one supposed to work on the bitmap and then go to svg? I worked on the svg directly.
2. I'd like it to maintain the factory-reset name or at least as alias. That's what I was seeking in the first place. Restore - for how I intend it - is the action which brings a system forward, adding things and settings which are not like they should be YET. So restore or restore-alert would be my name of choice for the mirrored one.

**Comment by JamesCoyle** [comment]
Always work in SVG. You need to make sure everything lines up with the 24dp grid though so when the SVG is rendered it appears crisp and pixel aligned. You should be working on a 24x24 canvas/viewbox and most (if not all) of the points should land on whole numbers. 

We will be going with the names @goyney  used as we are basing these icons on ones we already have so these are just alert variants of those existing icons. We will however add `factory-reset` as an alias.

**Comment by goyney** [comment]
[![restore-alert](https://materialdesignicons.com/icon/restore-alert)](https://materialdesignicons.com/icon/restore-alert)[![reload-alert](https://materialdesignicons.com/icon/reload-alert)](https://materialdesignicons.com/icon/reload-alert)
