### ISSUE TITLE
Improvement on the site design

### ISSUE THREAD

**Issue by gytdau** [Templarian/MaterialDesign#426]
I was going to originally try to fork and pull, but you don't keep your website files in this repository, so here's the changes I'd like to suggest:

In `.icons button.icon`, make `border-radius: 60px;` so that it's a circle. Circles are pretty, and they also fit the style of the icons. 

In `icons button.label-orange`, remove the `border` and add a `background-color: #EEE`. This makes, instead of an orange border, a light grey background. I think this is better because the color orange kind of competes with your attention, like it's a warning. You can then also remove all of that keyframe fluff with the orange borders.

In the end, it produces something like this:
![screenshot_2](https://cloud.githubusercontent.com/assets/8823299/8124174/1aa9d0f4-10cf-11e5-9319-a4f243ce3e59.png)
It's much easier on the eyes.

**Comment by Templarian** [comment]
The orange border fades out after 10 seconds. That was actually added earlier today. It seems like circles are only used for people or flyout overlays of icons.

I still really want to keep the emphasis on the community icons. Because really if user wants the stock icons they can just use the official [site](https://www.google.com/design/icons/). It's really the main purpose of the site and way to get more contributors for their icons to feel like an addition.

From someone else's feedback earlier I even lowered the orange down to 0.2 alpha so it is barely visible.

Thanks for the feedback and making the images. I'll keep it in mind if others suggest something similar.
