### ISSUE TITLE
folder-key-outline

### ISSUE THREAD

**Issue by trondulseth** [Templarian/MaterialDesign#4267]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

There is a **folder-key** icon.

I would like a **folder-key-outline** icon.

Also would be helpful with **folder-key-plus** and **folder-key-minus**  
(similar to *key-plus* and *key-minus*).

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/61802338-46a49380-adfe-11e9-86a9-910eea4f5a77.png)
[folder-key-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3427296/folder-key-outline.svg.zip)

Plus and Minus versions of the folder with a key is going to be too much for a small space.

**Comment by trondulseth** [comment]
First of all - thank you for maybe the quickest reply to an issue I have posted ever 🥇 

> Plus and Minus versions of the folder with a key is going to be too much for a small space.

Would it not be possible to move the folder down a pixel or two, and have the plus and minus sign up to the right?

**Comment by goyney** [comment]
The `plus` and `minus` modifiers go in the bottom right corner, typically in a cutout. In some cases, such as `folder`, they're incorporated into the icon itself because they don't work as a cutout. In this case, the `key` modifier and the `plus`/`minus` modifiers would need to share the same space. Unfortunately, there is not enough space for both and because `folder` already is a very large icon, there is not really space elsewhere for them either.

**Comment by goyney** [comment]
[![folder-key-outline](https://materialdesignicons.com/icon/folder-key-outline)](https://materialdesignicons.com/icon/folder-key-outline)
