### ISSUE TITLE
Wall-sconce-variant-down 

### ISSUE THREAD

**Issue by Tamadite** [Templarian/MaterialDesign#4294]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
The existing "Wall-sconce-variant" rotated 180 degrees and so pointing down.

## Examples
![wall-sconce-variant-down](https://user-images.githubusercontent.com/30261982/62417437-46eb2d00-b64f-11e9-9081-216f80fd3842.png)

**Comment by goyney** [comment]
**Couple of things to do here:**
- [ ] Rename `wall-sconce-variant` to `wall-sconce-round-variant`
- [ ] Update `wall-sconce-round-variant` because it is off grid
- [ ] Add `wall-sconce-round`
- [ ] Add `wall-sconce-flat-variant`

---
![image](https://user-images.githubusercontent.com/1015040/62736731-1105ca00-b9fc-11e9-82c8-a97ee7c094b4.png)
![image](https://user-images.githubusercontent.com/1015040/62736664-e61b7600-b9fb-11e9-8953-5cd971096c03.png)
![image](https://user-images.githubusercontent.com/1015040/62736688-f59abf00-b9fb-11e9-8a58-f25974885661.png)

**Comment by PeterShaggyNoble** [comment]
Do we really need the `-variant` when the base icon can be simply rotated to suit?

**Comment by goyney** [comment]
> Do we really need the `-variant` when the base icon can be simply rotated to suit?

Can't rotate icons easily in Home Assistant, so I think it's okay to add those variants.

**Comment by goyney** [comment]
[![wall-sconce-flat](https://materialdesignicons.com/icon/wall-sconce-flat)](https://materialdesignicons.com/icon/wall-sconce-flat)[![wall-sconce-flat-variant](https://materialdesignicons.com/icon/wall-sconce-flat-variant)](https://materialdesignicons.com/icon/wall-sconce-flat-variant)

[![wall-sconce-round](https://materialdesignicons.com/icon/wall-sconce-round)](https://materialdesignicons.com/icon/wall-sconce-round)[![wall-sconce-round-variant](https://materialdesignicons.com/icon/wall-sconce-round-variant)](https://materialdesignicons.com/icon/wall-sconce-round-variant)

Note: `wall-sconce-round` replaced `periscope`. `wall-sconce-flat-variant` replaced `pocket`. Both in the v5.0 release.
