### ISSUE TITLE
Heat pump-icon

### ISSUE THREAD

**Issue by mycortex** [Templarian/MaterialDesign#4389]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To use in Home Assistant.
Would be nice to have the possibility to have different icons for different AC type. In this case a Heat Pump-icon, in order to not have to use "Heat pump"-text in front of the entity name. Now I use the `air-conditioner` icon on all my AC-types.

## Examples

Found some pictures on Google:
![image](https://user-images.githubusercontent.com/48593936/64180944-ecb7d480-ce65-11e9-97bb-d970d27c60d1.png)

**Comment by goyney** [comment]
Heat pumps look like air conditioning condensers which looks like boxes. I'm not sure this is going to really work as an icon. Even your examples are just rectangles, which won't look like much at native size. Would none of our other icons, maybe `radiator-disabled` suit your use case?

**Comment by Mariusthvdb** [comment]
maybe OP is looking for something like this

![Schermafbeelding 2019-09-12 om 09 45 44](https://user-images.githubusercontent.com/33354141/64764353-2eb9d800-d542-11e9-98a5-816dfb338abc.png)

of course mdi:air-conditioner 
![Schermafbeelding 2019-09-12 om 09 46 50](https://user-images.githubusercontent.com/33354141/64764423-4e510080-d542-11e9-8df7-ab79c0596023.png) could be made into a heat-pump using H/P instead of A/C ;-)

**Comment by mycortex** [comment]
No, not really. But thanks for the tip :)

**Comment by goyney** [comment]
[![hvac](https://materialdesignicons.com/icon/hvac)](https://materialdesignicons.com/icon/hvac)
