### ISSUE TITLE
re: #4353 "NULL" as a symbol

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#4392]
WRT not adding the text-based NULL icons, I'd say that the word "NULL" is recognizable to anyone who has ever used an English-based programming language (which, and this is true, is the vast majority of them). 
We already have lots of icons for "symbolic" words and abbreviations, like H1~H6, HDR, IP, LQ/MQ/HQ, AM/FM, 2FA, sin, log, etc.

In addition, I'd say that the symbols that are meant to stand for "NULL" are either misleading or not well known enough.
* Ø (the current "null" icons) is the official ISO symbol, but it is more well known as "empty set", or plain simple looks like a 0, which is not what null is. We also need to make a "not null" icon, which doesn't play well with the slash that's already there.
* The suggesed circle icon and slashed circle icon suffer from the same problem.

Therefore, I think the text-based NULL icons merit inclusion.
#4353

**Comment by goyney** [comment]
I'll echo my original comment in #4353. We try really hard not to add icons that are nothing but letters for concepts which can be depicted in another way. "null," for example, has a standardized graphic representation which is already included in this library.

The other examples provided were added because it was extremely hard, or impossible, to add a visual representation in any other way. I am still of the opinion that this is not an appropriate icon to add at this time and that this issue is actually a duplicate because we already have a `null` icon.

**Comment by Templarian** [comment]
If we could increase the size of null to expand the full width. It's too small with the standard font. [NULL]

It might not be that bad of an icon to add. The `-off` is unnecessary.

**Comment by JapanYoshi** [comment]
> If we could increase the size of null to expand the full width. It's too small with the standard font.
The icon I gave is smaller than the standard font. I tried the easy way and it didn't fit.

> The -off is unnecessary.
Keep in mind that we want a “not null” icon.

**Comment by Templarian** [comment]
Closing this out as it doesn't seem doable within the constraints.
