### ISSUE TITLE
GIF with box background

### ISSUE THREAD

**Issue by ursusursus** [Templarian/MaterialDesign#4441]
Hi, I'd like variant of the GIF icon, inverted, something alike PDF icon, which is inverted in a box

Without it its very float-y and weak

**Comment by goyney** [comment]
Please ***do not*** remove our issue template when requesting new icons. If you followed the bullet points in that template, [you would have found this issue](https://github.com/Templarian/MaterialDesign/issues/1383#issuecomment-520660010), in which we said we will not being adding this variant because it does not work.

**Comment by ursusursus** [comment]
Sorry for removing the template, but I dont get the last message in the thread. What solution os it reffering to, the google text only one?

Is there going to be no boxed version at all?
