### ISSUE TITLE
battery-heart

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4528]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

There are multiple usages.
- Optimized for low battery usage.
- Power save mode.
- The battery needs to be repaired.

## Examples

![battery](https://user-images.githubusercontent.com/6717356/67161809-e07ccd80-f366-11e9-9086-9d2fc51f321a.png)
![battery 2](https://user-images.githubusercontent.com/6717356/67161902-a7912880-f367-11e9-9ac5-fbf3021b189e.png)
![battery 3](https://user-images.githubusercontent.com/6717356/67161823-e5418180-f366-11e9-8493-77aa4a27eb50.png)

**Comment by MrGrigri** [comment]
I'm not sure if `battery-heart-outline` is going to work because of the spacing and the 2-px spacing rules. But here are the three: `battery-heart`, `battery-heart-variant`, and `battery-heart-outline`.

![battery-heart](https://user-images.githubusercontent.com/4528551/67215229-5cfec300-f3de-11e9-9f4b-14058bc97f95.png) ![battery-heart-variant](https://user-images.githubusercontent.com/4528551/67215233-5ec88680-f3de-11e9-9bcd-fdafb9642dee.png) ![battery-heart-outline](https://user-images.githubusercontent.com/4528551/67215317-7d2e8200-f3de-11e9-8c25-e2127bf0f6ef.png)

---

[battery-heart.zip](https://github.com/Templarian/MaterialDesign/files/3751396/battery-heart.zip)

**Comment by goyney** [comment]
[![battery-heart](https://materialdesignicons.com/icon/battery-heart)](https://materialdesignicons.com/icon/battery-heart)[![battery-heart-outline](https://materialdesignicons.com/icon/battery-heart-outline)](https://materialdesignicons.com/icon/battery-heart-outline)
[![battery-heart-variant](https://materialdesignicons.com/icon/battery-heart-variant)](https://materialdesignicons.com/icon/battery-heart-variant)
