### ISSUE TITLE
FontAwesome style helper classes

### ISSUE THREAD

**Issue by gytdau** [Templarian/MaterialDesign#460]
The Font Awesome style helper classes are useful.
See http://fortawesome.github.io/Font-Awesome/examples/
I think they should also be included in the CSS.
Here are the helper classes I could find:
`fa-1x fa-2x etc`, `fa-fw`, `fa-ul and fa-li`, `fa-border`, `fa-spin and fa-pulse`, `fa-rotate-90 etc`, and the `fa-stack` set.

**Comment by Templarian** [comment]
[v1.1.70](https://cdn.materialdesignicons.com/1.1.70/) did not include these changes. I expect to have them in for the next release (no I do not know when that will be :smile:).

**Comment by egeland** [comment]
Looking at version `1.4.57` and can't see a `mdi-stack`, but can use the `mdi-2x`, etc size modifiers..

Any idea if/when a `fa-stack`-like feature will be included?

**Comment by Templarian** [comment]
We're not supporting `fa-stack` functionality at the moment and `mdi-2x` is not included also.

`.mdi-24px`, `.mdi-36px`, `.mdi-48px` are included (48px being like a 2x).

It has been discussed a few times and it seems like a feature that probably won't come to mdi since there are so few use cases for it in this icon pack.

**Comment by gytdau** [comment]
Feel free to close this issue :+1:
