### ISSUE TITLE
String lights

### ISSUE THREAD

**Issue by davejblair** [Templarian/MaterialDesign#4623]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

![image](https://user-images.githubusercontent.com/338885/69305182-a06c6d00-0be8-11ea-830b-ddb2783d4eac.png)
![image](https://user-images.githubusercontent.com/338885/69305204-b5490080-0be8-11ea-8c69-d740f3b85fca.png)

**Comment by Templarian** [comment]
@davejblair Edited your issue to include some examples. If you have others feel free to paste the images in above. Or if you're looking for a different design than Christmas lights let us know.

**Comment by davejblair** [comment]
many thanks!

**Comment by Templarian** [comment]
@davejblair Think you accidentally closed this. Still on our todo list. Hopefully will see a design for this one of these days that fits the pack.

**Comment by goyney** [comment]
This one is a little more difficult to do because of the complexity required to convey the icon's meaning. I had to drop the lights to 1.5dp and break the 2dp buffer.

![image](https://user-images.githubusercontent.com/1015040/70015402-3b4f3a80-154b-11ea-9c6c-1fe416e05da5.png)![image](https://user-images.githubusercontent.com/1015040/70015413-41451b80-154b-11ea-9c26-93c3aa502abf.png)

Additionally, a "on" version (with light bursts) is pretty much impossible. A filled version doesn't really work either. Therefore, I've at least created an "off" version. Knowing this will be used primarily in Home Assistant (I know I will use it there!), HASS colors the icons when the switch is on, so that should be enough.

[string-lights.zip](https://github.com/Templarian/MaterialDesign/files/3914228/string-lights.zip)

**Comment by goyney** [comment]
[![string-lights](https://materialdesignicons.com/icon/string-lights)](https://materialdesignicons.com/icon/string-lights)[![string-lights-off](https://materialdesignicons.com/icon/string-lights-off)](https://materialdesignicons.com/icon/string-lights-off)
