### ISSUE TITLE
kitchen design

### ISSUE THREAD

**Issue by molinaga** [Templarian/MaterialDesign#4739]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by molinaga** [comment]
![image](https://user-images.githubusercontent.com/59885526/72362711-a0a55800-36c1-11ea-9d9f-107408a91721.png)

![image](https://user-images.githubusercontent.com/59885526/72362760-badf3600-36c1-11ea-93e5-80ae37f3a60b.png)

**Comment by goyney** [comment]
We already have several kitchen appliances as individual icons. Due to the limited space we have, having more than one appliance in the same icon is impossible to do while maintaining Material guidelines and discernibility. Unfortunately, we are going to have to reject this request. Thank you for your suggestion!
