### ISSUE TITLE
laundry-room

### ISSUE THREAD

**Issue by molinaga** [Templarian/MaterialDesign#4740]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by molinaga** [comment]
![image](https://user-images.githubusercontent.com/59885526/72362994-0b569380-36c2-11ea-97cc-fa9522029eb2.png)

![image](https://user-images.githubusercontent.com/59885526/72363008-13aece80-36c2-11ea-92ae-83db55a16768.png)

**Comment by molinaga** [comment]
![image](https://user-images.githubusercontent.com/59885526/72363031-1dd0cd00-36c2-11ea-8196-bfc4600e9421.png)

**Comment by goyney** [comment]
Same as #4739.

We already have several laundry appliances as individual icons, and other things such as hangars. Due to the limited space we have, having more than one appliance in the same icon is impossible to do while maintaining Material guidelines and discernibility. Unfortunately, we are going to have to reject this request. Thank you for your suggestion!
