### ISSUE TITLE
Female and male

### ISSUE THREAD

**Issue by xesun** [Templarian/MaterialDesign#475]
Female and male icon

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/human-male-female

This icon is called `wc` in the official pack.

**Comment by eithe** [comment]
Sorry to open this, but why did you change the name from the official pack? I don't see any reason to do so?

**Comment by REJack** [comment]
Maybe the most people look for ``human``/``male`` or ``female`` so the ``wc`` icon wouldn't show.

**Comment by eithe** [comment]
yeah, but Google decided to name it wc for a reason.

**Comment by REJack** [comment]
Templarian talked about to add aliases to the icons, so the original name can used too.

**Comment by Templarian** [comment]
@eithe Google has some legacy naming that opts for shortness rather than description. It was decided early on to go with more readable names for all the icons. As @REJack explained a little the naming is also used to add associations to the other icons. `human-` for instance lets the user know the icon includes a human representation in it.

This is most noticeable with icons that require modifiers. `-circle`, `-box` for instance that before lacked these descriptors. As we add hundreds of more community icons having these descriptive names will help us better uniquely identify the icons.

I'm not sure how well `wc` translates also. I had to look up WC to figure out what it actually meant.

**Comment by Templarian** [comment]
With that said, an alias does need to be added to `wc` for that icon.

**Comment by eithe** [comment]
Thanks, yes, an alias is enough. Then people looking for the wc icon (like
me) doesn't have to search the closed issues list here to find it.

**Comment by REJack** [comment]
@Templarian WC's are Toilets or Bathrooms a other name for this is ``00``. i would say its more an European name :smile:

**Comment by CoDEmanX** [comment]
How about a text version?

![wc](https://cloud.githubusercontent.com/assets/1309249/12405461/ac0b0ec8-be44-11e5-8e75-593ed3074d9f.png) https://www.dropbox.com/s/yugvuh973ju7oz7/wc.svg?dl=0

**Comment by Templarian** [comment]
Added an alias for WC (not adding a text version as I'm trying to only add text to icons when it is 100% required).
