### ISSUE TITLE
palette-swatch-outline

### ISSUE THREAD

**Issue by MohammadKhrram** [Templarian/MaterialDesign#4760]
I need the following icon:

<b>palette-swatch-outline</b>

Please design specified icon
Thanks...

**Comment by JamesCoyle** [comment]
**Please do not remove our issue template.** In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.

**Comment by MohammadKhrram** [comment]
Please design specified icon
Thanks...
