### ISSUE TITLE
Make store-outline

### ISSUE THREAD

**Issue by MohammadKhrram** [Templarian/MaterialDesign#4767]
I need the following icon:

store-outline

Please design specified icon
Thanks...

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.

**Comment by CoDEmanX** [comment]
Added stock icon to the system.

**Comment by MohammadKhrram** [comment]
thanks sooooo much

**Comment by JamesCoyle** [comment]
Please make sure future requests use our issue template or your issue will be closed immediately.
