### ISSUE TITLE
Make bookmark-check-outline

### ISSUE THREAD

**Issue by MohammadKhrram** [Templarian/MaterialDesign#4780]
I need the following icon:

bookmark-check-outline

Please design specified icon
Thanks...

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
