### ISSUE TITLE
account-arrow-swap

### ISSUE THREAD

**Issue by sergiocarlotto** [Templarian/MaterialDesign#4792]
Good morning, follow these two suggestions of icons.
I will use it to replace attributes in an account.

I have:

- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2835460/73455039-13fbca80-434e-11ea-8fcf-4ac3f99fe247.png)
![image](https://user-images.githubusercontent.com/2835460/73455175-4c9ba400-434e-11ea-9791-6d158cfc07bf.png)

## Zip Download

[account-arrow-swap.zip](https://github.com/Templarian/MaterialDesign/files/4134235/account-arrow-swap.zip)

**Comment by MrGrigri** [comment]
Would `account-switch` not suffice?

![account-switch](https://materialdesignicons.com/icon/account-switch)

**Comment by sergiocarlotto** [comment]
In this case the account is not replaced, the functionality in this case is to replace attributes of an account.

**Comment by MrGrigri** [comment]
From a UX perspective, if it's not the account that is being swapped, then the account icon shouldn't be used at all and instead, one of the `swap` icons should be used.

**Comment by CoDEmanX** [comment]
I agree that a variant for the described purpose seems like bad UX.

About the icons themselves: I think the circular cutout doesn't work for this modifier, the gap at the top to the person silhouette is too narrow.

On a different note, should we update `account-switch` to use a similar silhouette as in e.g. `account-multiple-minus` (but the second person moved further to the right) so that we can add an outline variant?

![grafik](https://user-images.githubusercontent.com/1309249/73502936-e43ed800-43ca-11ea-93c2-c87d093d366d.png) ![grafik](https://user-images.githubusercontent.com/1309249/73502726-34696a80-43ca-11ea-9864-4d88d9b2080a.png)

[account-switch-outline.zip](https://github.com/Templarian/MaterialDesign/files/4136999/account-switch-outline.zip)

**Comment by goyney** [comment]
`account-switch` updated and `account-switch-outline` added.

[![account-switch-outline](https://materialdesignicons.com/icon/account-switch-outline)](https://materialdesignicons.com/icon/account-switch-outline)

Note: `account-switch-outline` replaced `square-inc-box` in the v5.0 release.

We won't be adding the original proposal and recommend using `account-switch` or another generic swap icon for your use case.
