### ISSUE TITLE
Email off

### ISSUE THREAD

**Issue by wkeizer** [Templarian/MaterialDesign#4830]
Can you add an email off variant? So an email icon with a strikethrough like many other '-off' variants.

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
