### ISSUE TITLE
Credit-card cryptogramme Icon

### ISSUE THREAD

**Issue by Camillecc** [Templarian/MaterialDesign#4850]
Hi, 
I look for it but I could find a icon with the back of credit card indicating the cvc (or cryptogramme) element. 
It's usually designed by a circle with 3 number of the top-right of the card. 
Thank you for your attention and your work.

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
