### ISSUE TITLE
Table variants to represent different types of data

### ISSUE THREAD

**Issue by TheWilks** [Templarian/MaterialDesign#4879]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Table variants to represent different types of data so user know that some data requires a specific level of access permissions 

## Examples

![Capture](https://user-images.githubusercontent.com/6516828/74344542-cb470700-4d7a-11ea-9857-0a9d81f167c7.PNG)

Looking for variants that follow the mdi-table-eye pattern...
- mdi-earth
- mdi-shield
- mdi-shield-half-full
- mdi-lock
- mdi-eye-off

_Note: there are many icons in the mdi-lock, mdi-shield and mdi-eye family that could be useful_

**Comment by CoDEmanX** [comment]
What we already have and what we could add:

- [x] table
- [ ] table-account
- [ ] table-alert
- [ ] table-arrow (share?)
- [ ] ~table-bluetooth~ (does not make sense)
- [ ] ~table-bold~ (does not apply)
- [x] table-border
- [ ] table-box
- [ ] table-cancel
- [ ] table-check
- [ ] table-circle
- [ ] table-clock (there is `timetable` with a slightly different base icon)
- [ ] table-cog
- [x] table-column-width
- [ ] table-download
- [ ] table-earth
- [x] table-edit
- [ ] table-export
- [x] table-eye
- [ ] table-eye-off
- [ ] table-heart
- [ ] table-home
- [ ] table-import
- [ ] table-key
- [ ] table-link
- [ ] table-lock
- [ ] table-message (commented table?)
- [ ] table-minus
- [ ] table-multiple
- [ ] table-network
- [ ] table-off
- [ ] table-outline
- [ ] table-phone?
- [ ] table-plus
- [ ] table-question
- [ ] table-refresh
- [x] table-remove
- [x] table-row-height
- [x] table-search
- [x] table-settings
- [ ] table-shield(-half-full)
- [ ] table-star
- [ ] table-sync
- [ ] ~table-thick~ (does not apply)
- [ ] table-upload

**Comment by Templarian** [comment]
A lot of these would be very useful to have and are pretty quick wins. 👍

**Comment by Templarian** [comment]
To save time, tick these off as you add them and leave a comment.

- `table-refresh` / `table-sync` were added.

**Comment by goyney** [comment]
- `box`, `circle`, and `outline` don't really make sense here.
- We don't have modifiers for `earth`, `home`, `link`, `shield`.
- `question` and `phone` are meh.

The rest are all added.

**Comment by goyney** [comment]
Going to close this one since most have been added. If there are other variant needed, please open an issue for each one. Thanks for the suggestion.

**Comment by TheWilks** [comment]
Sorry I am fairly new to this project. What does “ We don't have modifiers for earth, home, link, shield.” mean. These are some of the variants I was looking for. I have no issues contributing to this project just need to read up on how to do so.

**Comment by goyney** [comment]
An icon modifier is a small symbol, usually cut out of the icon in the corner, that slightly changes the meaning of an icon. Examples are plus, minus, remove, etc.

There needs to be a very compelling reason for us to add a new modifier because it opens the floodgates for adding it to every other icon, and most of the time, they're superfluous. 

We've had discussions about `earth` in the past and currently (#4573) and we're probably going to deny it again because it loses meaning and is hard to convey detail as a modifier. Additionally, we've rejected many `link`s in the past as well for similar reason, though a few have gotten through where they made absolute sense.

If you really have a strong use case for any of those, please feel free to open up a new issue for each one and explain your case. If we don't feel the idea works as an icon, we often can help find alternative icons that can meet your needs. Remember, that icons are supposed to be contextual, not literal.

**Comment by TheWilks** [comment]
Awesome. Thanks for the additional explanation it’s helpful for future requests.
