### ISSUE TITLE
bell-(minus | remove | cancel)-outline

### ISSUE THREAD

**Issue by gdang** [Templarian/MaterialDesign#4881]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I use some of the bell-* icons to represent alarms in my monitoring app.

**bell-remove**: Alarms that are considered "nuisance" are automatically removed by the server but are still required to be displayed client-side.
**bell(-minus | -cancel)**: Users can manually disable alarms for maintenance reasons. Once done, they put the alarms back in service (thus bell-plus is adequate).

## Examples

Can be based on [`bell-plus`](https://materialdesignicons.com/icon/bell-plus) or [`bell-check`](https://materialdesignicons.com/icon/bell-check). I don't know if it can be applied here, but the flask-* icons look neat.

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/74360196-eccce080-4dc4-11ea-9740-ea8167fabe8f.png)

[bell.zip](https://github.com/Templarian/MaterialDesign/files/4193786/bell.zip)

The cancel icons use a slightly larger cutout (13dp diameter vs 12dp otherwise).

I think we should replace the existing `bell-plus` icons:

![grafik](https://user-images.githubusercontent.com/1309249/74360252-053cfb00-4dc5-11ea-809b-ae2c4f6de38a.png)

The circular cutout works better for the minus IMO.

Not a fan of my alert variant, I think it's better to keep the existing ones:

![grafik](https://user-images.githubusercontent.com/1309249/74360315-1c7be880-4dc5-11ea-9376-350dcdbf4395.png)

**Comment by gdang** [comment]
I like your bell-alert variant. It'll compliment well with [`account-alert`](https://materialdesignicons.com/icon/account-alert) for displaying alarms that require acknowledgement/confirmation.

**Comment by Templarian** [comment]
I don't really like how our current bell has the plus inside. It makes it look medical (not exactly sure why). If everyone else is fine with it we could replace it.

The `bell-alert` is weird also, it can _almost_ be confused with the clapper inside.

**Comment by CoDEmanX** [comment]
Good point about the clapper. I need to check how we position the exclamation mark on the right side in other icons, maybe has to be moved to the border. A littler bigger gap should help.

**Comment by goyney** [comment]
All added and updated.
