### ISSUE TITLE
decagram-multiple 

### ISSUE THREAD

**Issue by julienreszka** [Templarian/MaterialDesign#4882]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I use decagram as a placeholder for a brand. I wish I could have an icon to represent multiple brands.

## Examples

Include any example images so we know what the icon should look like.

https://petershaggynoble.github.io/MDI-Sandbox/?icon=decagram

**Comment by CoDEmanX** [comment]
Does it represent a specific brand, or is it a placeholder kind of thing? Wouldn't `account-star` work?

**Comment by julienreszka** [comment]
@CoDEmanX it's a placeholder kind of thing.

**Comment by julienreszka** [comment]
![decagram-multiple](https://user-images.githubusercontent.com/8984570/74382880-7218bb00-4dee-11ea-8565-1cb1862051d3.png)
Something like this maybe

**Comment by goyney** [comment]
This won't work for multiple reasons. Firstly, our `decagram` already breaks into the buffer area by 1dp on all sides, meaning we have to shrink the icon down considerably to do a multiple variant. At native resolution, this hurts to recognizability of the shape. Additionally, because of the awkwardness of the shape, a shift with the 2dp cutout in place doesn't leave much of the "copy." I don't feel this works and don't think this is worth adding.

![image](https://user-images.githubusercontent.com/1015040/76044497-94eb4a80-5f28-11ea-9105-4247506ca62b.png)

**Comment by julienreszka** [comment]
ok thank you for taking the time to consider it
