### ISSUE TITLE
Current, voltage and power

### ISSUE THREAD

**Issue by pmmivv** [Templarian/MaterialDesign#4892]
## Usage

Use in some electrical icon .

## Examples

![image](https://user-images.githubusercontent.com/10779588/74592164-86d79780-5016-11ea-9200-1ff453297e56.png)
![image](https://user-images.githubusercontent.com/10779588/74592168-96ef7700-5016-11ea-80a1-4ce607e639a8.png)
![image](https://user-images.githubusercontent.com/10779588/74592177-b25a8200-5016-11ea-849f-ccef6e352769.png)

**Comment by goyney** [comment]
So, a few things here. You selectively removed a portion of the issue template (which is already grounds for an immediate closure), specifically the areas talking about SEARCHING. If you would have done that, you would have [found an issue pertaining to voltage](https://github.com/Templarian/MaterialDesign/issues/2813), which was closed because we have `alpha-v-circle-outline`, which fits your example. We also have `alpha-a-circle-outline` which fits the amperage. We also have [an open issue dealing with stuff like sine waves](https://github.com/Templarian/MaterialDesign/issues/4346), which hits your others. Therefore, it's quite obvious those portions of the issue template were removed intentionally to sidestep that your request is not unique.
