### ISSUE TITLE
Arcade Game / Pinball Machine / Retro Joystick icons needed

### ISSUE THREAD

**Issue by peterhirschberg** [Templarian/MaterialDesign#4910]
# Some ideas:
- An arcade game
- A pinball machine
- A retro joystick (like an Atari 2600 style)

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
