### ISSUE TITLE
calculator-variant-outline

### ISSUE THREAD

**Issue by KasaP-AndroDev** [Templarian/MaterialDesign#4912]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Use this icon in android app for calculate some operator.
I need Vector Drawable (.xml)

**Comment by MrGrigri** [comment]
I do not believe this will work due to spacing. MD has a 2-pixel wide guideline that is already being broken on this icon. There are two options, allow for a smaller sign, or allow for a smaller border. Neither of which looks good or follow MD guidelines.

Option A

![image](https://user-images.githubusercontent.com/4528551/75180839-3b01ae00-56fa-11ea-8d80-6f4792016359.png)

Option B

![image](https://user-images.githubusercontent.com/4528551/75180886-510f6e80-56fa-11ea-88c7-2eed788badb5.png)

**Comment by KasaP-AndroDev** [comment]
thanks sooo much <b>MrGrigri</b>

**Comment by goyney** [comment]
Unfortunately, these do not work within Material's guidelines. We're going to reject this request. Thank you for the suggestion.
