### ISSUE TITLE
Heater icon

### ISSUE THREAD

**Issue by KonradLindblad** [Templarian/MaterialDesign#4918]
I am opening a request for an icon that represents a car heater, it kinda works for anything that uses both ventilation and heating though.
In my car it also works to cool the car (icon changes color to blue), so it has a dual purpose i guess. :)

![Image of Auxiliary heating in Mercedes Me app](https://i.imgur.com/B98NpCY.png)

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
