### ISSUE TITLE
Upload audio icon

### ISSUE THREAD

**Issue by azimbialiev** [Templarian/MaterialDesign#4938]
It would be nice to have an icon like this in mdi icons collection

https://www.iconfinder.com/icons/670294/arrow_music_note_song_upload_icon

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
