### ISSUE TITLE
Icon for Amazon echo dot v3

### ISSUE THREAD

**Issue by andilge** [Templarian/MaterialDesign#4939]
Hi all,

I'd really love to see an icon for amazon echo dot v3
https://icdn7.digitaltrends.com/image/amazon-echo-dot-2018-3rd-gen-review-6-720x720.jpg

All the best

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
