### ISSUE TITLE
Tattoo icon

### ISSUE THREAD

**Issue by outshot** [Templarian/MaterialDesign#4957]
A standard icon to indicate the user / candidate have a tattoo.
This is for a modeling app.

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
