### ISSUE TITLE
business_center

### ISSUE THREAD

**Issue by unm4sk1g** [Templarian/MaterialDesign#4972]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It's already part of material.io icons, why not add it here as well?

## Examples

![image](https://user-images.githubusercontent.com/26198899/76622822-93c2aa80-6532-11ea-88d3-4a81559971a5.png)

https://material.io/resources/icons/?icon=business_center&style=filled

Thanks.

**Comment by goyney** [comment]
Looks like a `briefcase` variant.

**Comment by unm4sk1g** [comment]
Is it already inside the font or? If not, do you have in plans to add it?

**Comment by holtalanm** [comment]
running into this, too.  we chose material design icons because it was supposed to be a superset of the official material icons, but this icon was chosen by our design team, and it is no where to be found within mdi.

**Comment by goyney** [comment]
> running into this, too. we chose material design icons because it was supposed to be a superset of the official material icons, but this icon was chosen by our design team, and it is no where to be found within mdi.

Not sure where you got the impression that we are a superset of the official icon set by Google. We're a community-driven icon collection that builds icons that follow Material guidelines. We add official Google icons where they make sense, based on feedback from the community. This issue is asking for this icon to be included, which we are considering adding as `briefcase-variant`. Please remember that we're all volunteering our time here and a lot of lives have been turned upside-down based on the current global situation. Once we have more information about this specific request, it'll be expressed in this issue.

**Comment by goyney** [comment]
[![briefcase-variant](https://materialdesignicons.com/icon/briefcase-variant)](https://materialdesignicons.com/icon/briefcase-variant)[![briefcase-variant-outline](https://materialdesignicons.com/icon/briefcase-variant-outline)](https://materialdesignicons.com/icon/briefcase-variant-outline)
