### ISSUE TITLE
chart-scatter-plot (contribution)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#498]
As found on FontAwesome's [issue tracker](https://github.com/FortAwesome/Font-Awesome/issues/2243), a chart icon for scatter plots can be handy along the other common types of charts:

![chart-scatter-plot](https://cloud.githubusercontent.com/assets/1309249/8664757/bdf430ea-29db-11e5-97f0-a38f56f085af.png) https://www.dropbox.com/s/lgmc5uicry8yk33/chart-scatter_plot.svg?dl=0

The depicted features resemble the line from chart-line. I'm not sure if this could be misleading, but I find it nicer than randomly scattered data points. Plus it's hard to adhere to the 2dp spacing guideline for randomly placed dots without creating a visual mess.

**Comment by Templarian** [comment]
I think that will be as close as you get without it just looking like a bunch of dots.

Shoot me an email with your preferred contact at austin at templarian com. I can't add you to the system right now since I have it a bit broken, but I can add your icons and assign them all over to your contributor account once I get everything fixed.
