### ISSUE TITLE
Water pump (closed circuit)

### ISSUE THREAD

**Issue by antonverburg** [Templarian/MaterialDesign#4987]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![pump](https://user-images.githubusercontent.com/47820045/77559307-53f9ac80-6ebc-11ea-8d55-77811d1c161e.png)

## Zip Download
[pump.zip](https://github.com/Templarian/MaterialDesign/files/4382055/pump.zip)

**Comment by Templarian** [comment]
@antonverburg Line needs to be 2px width. Nice icon to have.

**Comment by antonverburg** [comment]
Is this better?
![pump2](https://user-images.githubusercontent.com/47820045/77580117-ba41f780-6edb-11ea-8381-0132e9f7811d.png)

**Comment by antonverburg** [comment]
Here is the zip for 2nd try,
[pump.zip](https://github.com/Templarian/MaterialDesign/files/4383267/pump.zip)

**Comment by Templarian** [comment]
[![pump](https://materialdesignicons.com/icon/pump)](https://materialdesignicons.com/icon/pump)

Since `water-pump` exists and this can be used for either water, air, or anything I'll leave this generically called `pump`. Also tweaked the vector to remove the rounded ends.

Let me know when you have 5 icons so I can transfer this to a contributor account.
