### ISSUE TITLE
Need outline version of mdi-view-carousel

### ISSUE THREAD

**Issue by mishanwavenet** [Templarian/MaterialDesign#5010]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue.

**Comment by tgrelka** [comment]
![view-carousel-outline](https://user-images.githubusercontent.com/22134144/79699567-91214680-8290-11ea-811c-abe9d84ea0a8.png)
Google already has added this to their material design icons set, but it hasn't made it's way into the MDI repo yet. I've created this variant, because personally I fell like this goes with the `outline`-style better, it's less heavy.
Source: [view-carousel-outline.zip](https://github.com/Templarian/MaterialDesign/files/4500223/view-carousel-outline.zip)

**Comment by mishanwavenet** [comment]
Thank you so much.
