### ISSUE TITLE
Dome Light

### ISSUE THREAD

**Issue by kmlucy** [Templarian/MaterialDesign#5028]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

These style lights are ubiquitous in apartments, and there isn't an icon that matches up well. `ceiling-light` is probably the closest, but it indicates a hanging light, which these are not.

## Examples

![image](https://user-images.githubusercontent.com/13952475/78895511-ff6a3b80-7a3c-11ea-8ac9-13f7d2de8b45.png)

**Comment by tgrelka** [comment]
![dome-light](https://user-images.githubusercontent.com/22134144/79699356-6aaedb80-828f-11ea-8d33-c0796dddf030.png)
Something like that? I think the proportions would need to be adjusted for a filled version, that's why I'm just posting an `-outline` version right now.
Source files: [dome-light.zip](https://github.com/Templarian/MaterialDesign/files/4500185/dome-light.zip)

**Comment by Templarian** [comment]
Actually kind of like that in context I think it would work nicely. Weird we added a `globe-light` before a simple `dome-light`, which is a way more common light fixture.

@tgrelka We don't need `-outline` / `filled` for these. It would be best represented by the outline in all cases.

**Comment by tgrelka** [comment]
Yes, I agree! I don't think anything filled would work for this, I've tried and nothing looked right.

**Comment by Templarian** [comment]
Added! Assigned to you: https://dev.materialdesignicons.com/history
