### ISSUE TITLE
 Request to add sports icons, more specifically actions involving basketball

### ISSUE THREAD

**Issue by williancm812** [Templarian/MaterialDesign#5039]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by JamesCoyle** [comment]
In order to deal with incoming requests efficiently we ask that you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
