### ISSUE TITLE
Ice Cube

### ISSUE THREAD

**Issue by ProofofNatalie** [Templarian/MaterialDesign#5049]
It would be great to have an ice cube icon. Maybe a rounded-corner cube with a snow-scruffs on the corner? Thanks for considering it :)

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
