### ISSUE TITLE
Stonehenge

### ISSUE THREAD

**Issue by baalgar** [Templarian/MaterialDesign#5066]
Something like the following:

https://www.iconfinder.com/icons/317026/britons_cultures_england_landmark_stone_stonehenge_tourism_icon

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
