### ISSUE TITLE
icon request: view grid

### ISSUE THREAD

**Issue by iftekhar-ahmed** [Templarian/MaterialDesign#513]
Could we have a 'view grid' icon just like the 'view list' icon? I couldn't find that. Thanks.

**Comment by CoDEmanX** [comment]
What about [view-module](https://materialdesignicons.com/icon/view-module)?

Google has an additional view icon btw., [view-comfy](http://www.google.com/design/icons/#ic_view_comfy).

**Comment by iftekhar-ahmed** [comment]
[view-module](https://materialdesignicons.com/icon/view-module) or [view-comfy](http://www.google.com/design/icons/#ic_view_comfy) are not exactly what I am looking for. The one below is what it should look like 

![view_grid_snap](https://cloud.githubusercontent.com/assets/6437678/8821702/83f583e2-3081-11e5-9728-b5385898da39.png) 

Surprising I didn't find that icon anywhere in the web!

**Comment by CoDEmanX** [comment]
I see. Perhaps because it could be confused with MS Windows logo?

Anyway, here's a straightforward icon based on view-dashboard:

![view-grid](https://cloud.githubusercontent.com/assets/1309249/8829901/8c5e1c34-3099-11e5-8124-18c42aee68f7.png)

Or should the spacing / size of the rectangles be different?

**Comment by iftekhar-ahmed** [comment]
Well, from the outlook I should say it's okay. Can you share 24 dp png version of the original icon?

**Comment by CoDEmanX** [comment]
Here you go:

Preview | Icon name
--- | ---
![view-grid](https://cloud.githubusercontent.com/assets/1309249/8829901/8c5e1c34-3099-11e5-8124-18c42aee68f7.png) | view-grid (new)
![ic_dashboard_24px](https://cloud.githubusercontent.com/assets/1309249/8830896/1e593a9c-309f-11e5-8774-fea8fef2889f.png) | view-dashboard
![view-module](https://cloud.githubusercontent.com/assets/1309249/8830962/956953e2-309f-11e5-8048-1e64c35ed587.png) | view-module
![ic_view_comfy_24px](https://cloud.githubusercontent.com/assets/1309249/8830963/9569ef6e-309f-11e5-814b-b97ac46d80ee.png) | view-comfy (not yet in MDI)
![view-list](https://cloud.githubusercontent.com/assets/1309249/8831022/dc37ac56-309f-11e5-8185-e2b50e7116d4.png) | view-list

**Comment by iftekhar-ahmed** [comment]
I can't see the view-grid icon in MDI yet. Need a larger resolution of that. Can you share a 128*128 png version? Thanks in advance.

**Comment by CoDEmanX** [comment]
I just created it, you and Austin need to approve before it can land in MDI.

It can't be rendered fully sharp at 128x128, because 128 is not a multiple of 24. Here's a slightly blurry rendering anyway:

![view-grid_128px](https://cloud.githubusercontent.com/assets/1309249/8832068/10f513f0-30a7-11e5-906e-9cc079e7ab27.png)

**Comment by iftekhar-ahmed** [comment]
No problem with that, and for the matter of fact, it still looks sharp at 128x128. You can go ahead and put it in MDI (or is there any standard approval process?) once @Templarian approves. Thanks again for your effort.

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/view-grid
