### ISSUE TITLE
external-thermometer

### ISSUE THREAD

**Issue by markappa** [Templarian/MaterialDesign#5149]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

This icon should be used in contrast to the home-thermometer, where you have weather stations measuring both temperatures: internal and external.

## Examples

![IMG_20200511_135709](https://user-images.githubusercontent.com/15861685/81559410-a0774980-938f-11ea-80f1-74ca78677105.png)

**Comment by goyney** [comment]
**Please DO NOT remove our issue template.**

---

This icon won't work without shrinking down our house because it pushed both sides out of the boundary.

![image](https://user-images.githubusercontent.com/1015040/81562922-99d2dd00-9363-11ea-9ea8-f7b228365401.png)

I also don't feel this is needed. We have icons for internal temperature, anything else could be contextually assumed to be something else.

**Comment by Templarian** [comment]
I'm not sure this is really needed. It kind of reads house temperature which is kind of the opposite.

Maybe a Sun + thermometer?

**Comment by goyney** [comment]
Sun + thermometer would work. I like that idea.

**Comment by goyney** [comment]
Not really a fan of either of these.

![image](https://user-images.githubusercontent.com/1015040/81764684-179c0300-94a0-11ea-9c63-a77850e5563f.png)![image](https://user-images.githubusercontent.com/1015040/81764703-22569800-94a0-11ea-86fc-8dd820ba58dd.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/4619466/Archive.zip)

**Comment by goyney** [comment]
[![sun-thermometer](https://materialdesignicons.com/icon/sun-thermometer)](https://materialdesignicons.com/icon/sun-thermometer)
