### ISSUE TITLE
Stories like icons, 

### ISSUE THREAD

**Issue by tonystark-cyber** [Templarian/MaterialDesign#5150]
I would like to have an icon that looks like whatsapp, instagram,facebook, STORIES NOT LOGO.

e.g. https://bit.ly/2zv4IkV

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
