### ISSUE TITLE
Old rocket icon

### ISSUE THREAD

**Issue by Baswazz** [Templarian/MaterialDesign#5151]
Would be nice if the old Rocket icon can be re-added as for example rocket-variant.
Our company prefers the old one over the new.

![Artboard 1](https://user-images.githubusercontent.com/1690629/81657986-a6753500-9438-11ea-8dd2-356c259eb782.png)

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
