### ISSUE TITLE
Old rocket icon

### ISSUE THREAD

**Issue by Baswazz** [Templarian/MaterialDesign#5152]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
It's an icon we use in our systems on various places.
We discovered it has replaced by another rocket icon. It would be nice if the old Rocket icon can be re-added as for example rocket-variant.
Our company prefers the old one over the new.

## Examples
Below the example of the old rocket icon (mdi-rocket):
![Artboard 1](https://user-images.githubusercontent.com/1690629/81693150-c9670f80-945f-11ea-8e63-303a1a7adf60.png)

**Comment by goyney** [comment]
The old rocket was removed and replaced because it is not very Material. The new rocket is an official Google icon. We're not likely to add it back.

You can use an older version of `@mdi/js` to get the glyph if you'd like to use it.

**Comment by Baswazz** [comment]
@goyney Thank you for your quick reply. The problem with using an older version is that if we need a specific icon which has been added after we are not able to use that one.

**Comment by Templarian** [comment]
@Baswazz Since `@mdi/js` is just path data you can actually just grab any icon from an old version.

`const mdiRocketOld = 'M20 22L16.14 20.45C16.84 18.92 17.34 17.34 17.65 15.73L20 22M7.86 20.45L4 22L6.35 15.73C6.66 17.34 7.16 18.92 7.86 20.45M12 2C12 2 17 4 17 12C17 15.1 16.25 17.75 15.33 19.83C15 20.55 14.29 21 13.5 21H10.5C9.71 21 9 20.55 8.67 19.83C7.76 17.75 7 15.1 7 12C7 4 12 2 12 2M12 12C13.1 12 14 11.1 14 10C14 8.9 13.1 8 12 8C10.9 8 10 8.9 10 10C10 11.1 10.9 12 12 12Z';`

But I also think we might be able to make a rocket launch icon to match the current style in a launch... 🚀

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/81765615-4b782800-94a2-11ea-8f1e-04839825e25b.png)![image](https://user-images.githubusercontent.com/1015040/81765672-75c9e580-94a2-11ea-8a9e-a62499be230d.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/4619545/Archive.zip)

**Comment by Templarian** [comment]
@goyney You think it's proportionally too large diagonal. Maybe it's correct though?

**Comment by goyney** [comment]
Both of these have been added.
