### ISSUE TITLE
file-find-replace

### ISSUE THREAD

**Issue by massivemadness** [Templarian/MaterialDesign#5163]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Could be used to represent ability to replace all found results in text

## Examples

Just combine existing `file` and `find-replace` icons please  🙏 Thank you!

![R-ULISicEYo](https://user-images.githubusercontent.com/7825871/82153353-99f54000-986f-11ea-933a-73a81f6ddb7f.jpg)

**Comment by goyney** [comment]
There's several issues with this.

First, because of the small nature of the search glass, we must stay on grid here to prevent blurring. Because of that, the arrow heads cannot be equally positioned on the sync circle.

![image](https://user-images.githubusercontent.com/1015040/82276496-70154980-9953-11ea-8211-385bd8863356.png)

Second is that this just doesn't work in the outline version.

![image](https://user-images.githubusercontent.com/1015040/82276516-7e636580-9953-11ea-8c88-35258350ed14.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/4647840/Archive.zip)

**Comment by massivemadness** [comment]
@goyney Thank you, exactly what I was looking for!

**Comment by JamesCoyle** [comment]
Can the arrowheads be shrunk to 3x3 rather than 4x4?

**Comment by goyney** [comment]
They're barely identifiable at native resolution at 4x4, so I would say no.

**Comment by goyney** [comment]
Since this doesn't work at native resolution, we're not going to add them.

You may also consider `file-replace` for this use case.
