### ISSUE TITLE
whole slide imaging icon

### ISSUE THREAD

**Issue by ayayassine** [Templarian/MaterialDesign#5178]
![WSI](https://user-images.githubusercontent.com/65758093/82645458-9240ed00-9c1b-11ea-90b6-ac97f3249c27.png)

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
