### ISSUE TITLE
icon request: reminder

### ISSUE THREAD

**Issue by wkeizer** [Templarian/MaterialDesign#518]
Google Keep has a 'delay' or 'remind me' function with an icon of a finger with a string around it. I could really use this icon. It would be a nice addition to MDI, I think.

**Comment by CoDEmanX** [comment]
From Google Keep:
![screenshot_2015-07-22-17-38-07](https://cloud.githubusercontent.com/assets/1309249/8830165/13666f82-309b-11e5-98b7-bd5371d5674d.png)

From Google Now:
![screenshot_2015-07-22-17-38-38](https://cloud.githubusercontent.com/assets/1309249/8830166/1367e95c-309b-11e5-9688-c3ce33023469.png)

The other two icons I included in the shots seem to be missing, too (magic wand / alternative version of light bulb).

**Comment by CoDEmanX** [comment]
Re-created it based on thumbs-up icon and the reference screenshot:

![reminder](https://cloud.githubusercontent.com/assets/1309249/8851228/5a2ef714-314e-11e5-90e9-d5f4fed50e10.png) https://www.dropbox.com/s/2d029wjavx11eod/reminder.svg?dl=0

@Templarian: No idea how to make it production-ready. If I combine the two arcs of the knot with the rest in InkScape, the arcs turn into paths with irregularly placed points. Or is it acceptable as it is? Is there a chance someone could see a small gap between the arcs and the hand?

**Comment by Templarian** [comment]
The upload system only allows a single `<path d="M ... Z">` tag to be present, but don't worry I can fix it. I actually switch between illustrator and Expression Design (I do all the final exports from Expression Design since it gives the best point data).

**Comment by CoDEmanX** [comment]
Well, it can't stay an arc then, because the hand is filled with no border, and the rest is no fill with contour for the arc strokes. So both arcs need to be converted to regular paths I guess.

The magic wand does exist, it's called `auto-fix` - could use some additional tags :unamused:

What about the light bulb? Same problem as with the reminder arcs, otherwise easy to recreate.

**Comment by CoDEmanX** [comment]
Expression Design seems to have some flaws, and I can't edit an individual path point numerically...

I managed to create the knot in InkScape without arc though, looks like a accidentally used *combine* instead of *union* before.

What I noticed: A perfect circle doesn't seem to work around the finger tip. Google's version a better noticeable notch. I'm not sure how to correct this in my version properly (i.e. not lowering the path width of 1.25px and maintaining a round appearance). Maybe you can have a look:

https://www.dropbox.com/s/492h72ifu6us63a/reminder_production.svg?dl=0

**Comment by CoDEmanX** [comment]
Actually, my icons appears to be correct. There's barely a notch you could see in Google's original icon, even if viewed on a high density screen. Rendered at larger sizes, it will become more apparent.

**Comment by PeterShaggyNoble** [comment]
Here's the SVG from Google Keep. As usual, the original and a version compressed with SVGOMG are included.

[reminder.zip](https://github.com/Templarian/MaterialDesign/files/1411089/reminder.zip)

**Comment by PeterShaggyNoble** [comment]
Google's [extended icon set](https://petershaggynoble.github.io/MDI-Sandbox/extended/) includes this at 2 different sizes.

[![reminder](https://user-images.githubusercontent.com/15157491/33128785-952972f4-cf85-11e7-8c5b-94c38ec097c7.png) ![image](https://user-images.githubusercontent.com/15157491/33129005-70ff42f4-cf86-11e7-80ec-6c7077bcfab4.png)](https://github.com/Templarian/MaterialDesign/files/1496051/reminder.zip)

**Comment by Templarian** [comment]
[![reminder](https://materialdesignicons.com/icon/reminder)](https://materialdesignicons.com/icon/reminder)
