### ISSUE TITLE
DokuWiki Contributions: Text wrapping, headline level, tank

### ISSUE THREAD

**Issue by splitbrain** [Templarian/MaterialDesign#519]
the DokuWiki project is currently evaluating to add an IconFont (https://github.com/splitbrain/dokuwiki/issues/1204) and this one seems our best candidate so far. However a couple of icons are still missing to cover our usecases.

I'd like to contribute a couple of files I made. There are probably more to come. You can find them here: https://github.com/splitbrain/material-icons/tree/master/material-icons

- [x] `format-float-left`
- [x] `format-float-center`
- [x] `format-float-right`
- [x] `format-float-none`
- [x] `format-wrap-tight`
- [x] `format-wrap-top-bottom`
- [x] `format-wrap-square`
- [x] `format-wrap-inline`
- [ ] `tank`
- [x] `format-header-increase`
- [x] `format-header-decrease`
- [x] `format-header-equal`

**Comment by Templarian** [comment]
The naming will change for a few of them, but they all look like good additions to the pack.

**Comment by splitbrain** [comment]
awesome :-)

**Comment by Templarian** [comment]
The contributor system is disabled while I'm making updates over the next few weeks to it.

Since you have 5+ icons I can add you as a contributor. I'll attach these icons to your account. If not I'll just upload them to my account, but I really prefer people to get credit on the site.

- email (will delete it from the comment once it is added to the system, same location your reset password will be sent to once the system is back online)
- Name (first [last] or company)
- 100x100 picture png of you or company logo (images can be pasted into github comments).
- Sentence about you (bio)
- Website url (optional)

Example: https://materialdesignicons.com/contributor/Austin-Andrews

**Comment by splitbrain** [comment]
* andi@splitbrain.org
* Andreas Gohr
* http://www.gravatar.com/avatar/b6b4d7dbe3fb7cf61b68e36cd80f8698.jpg?s=100
* Web, Wiki and Open Source enthusiast from Berlin, Germany
* http://www.splitbrain.org

**Comment by CoDEmanX** [comment]
What's the purpose of the header icons? They seem really specific, and a bit to text-heavy for my taste. Maybe there's a more metaphorical way to express the meaning...

The align icons: is their purpose to position content blocks inside the main content?
(`float: ...` in CSS). Because for general text alignment, there are icons already (e.g. http://www.google.com/design/icons/#ic_format_align_left).

The tank could use some shape tweaking, so that the primitives used don't shine through as much. Furthermore, I would let the barrel point ahead, not up.

**Comment by Templarian** [comment]
@CoDEmanX Feel free to tweak them, I tweak the contributor icons all the time. Many go through a few small tweaks before being added.

It looks the alignment icons are exactly that. Text wrapping like in word (that is what I meant by the icon names will probably change).

**Comment by splitbrain** [comment]
The header icons are used in DokuWiki to insert headlines relative to the current level. When you're editing a text you often want to insert a sub section for example. For that you would need to know at which level your current text currently is (eg. H3) and then insert the appropriate level (H4). With these buttons you can simply say enter a subsection headline. Or enter a same level headline. Or a higher order headline. All without counting. Regarding the style, I oriented it on the existing header buttons.

And yes, the alignment buttons are for aligning objects within texts, eg. images.

I'm happy about any tweaks you can do. I'm not a designer by trade.

**Comment by Templarian** [comment]
https://materialdesignicons.com/contributor/Andreas-Gohr

Added a few of them (assigned them to your account, but made them a bit different to fit the style better).

**Comment by splitbrain** [comment]
Sorry. But the alignment icons do not work the way you changed them anymore. To clarify: the have to symbolize aligning an image to the left, center, right or no align. The way you changed them they do not represent that at all.

**Comment by Templarian** [comment]
Oh you're right. I clicked on the first one and assumed they were text wrapping. That's what @CoDEmanX meant by `float` alignment. Will add those shortly.

- [ ] format-object-float-left
- [ ] format-object-float-center
- [ ] format-object-float-right
- [ ] format-object-float-none
- [ ] tank

**Comment by CoDEmanX** [comment]
I think this can be fixed by adding two additional icons, with the triangle on the left or right respectively, with 3 strokes on the opposing side.

Not sure about the headline icons with chevrons pointing up or down... Left and right seems more natural, see Wikipedia Syntax example (sub-headlines are visually more indented than their parents) and icon button to press to create the subsequent headline:

```
= Headline 1 =  [H>]
== Headline 1.1 ==  [H>]
=== Headline 1.1.1 ===  [H=]
=== Headline 1.1.2 ===  [H<]
== Headline 1.2 ==  [H=]
== Headline 1.3 ==  [H<]
= Headline 2 =
```
H+ and H- might also work...

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/format-header-increase
https://materialdesignicons.com/icon/format-header-decrease
https://materialdesignicons.com/icon/format-header-equal

**Comment by Templarian** [comment]
Yea, I think you're on the right path @CoDEmanX , but I'm going to agree rectangles might be best. I only used a triangle since it showed off `tight` word wrapping best. I'll create these 4 and add them.

**Comment by Templarian** [comment]
I messed around making the tank look a little more like a tank, but not sure on that one. The current one kind of looks like an observatory at first glance.

**Comment by CoDEmanX** [comment]
I thought of an observatory too! :smile: 

Maybe it's better to use rectangles for all of them except `tight`, and use a circle for this particular one?

Some tests on spacing how and to place the rect:

`center`:
![format-object-center-square1](https://cloud.githubusercontent.com/assets/1309249/8844048/e707b5e2-3110-11e5-8a0e-3c581fca33a8.png)
![format-object-center-square2](https://cloud.githubusercontent.com/assets/1309249/8844049/e70854de-3110-11e5-8de3-29b28803201f.png)
![format-object-center-square3](https://cloud.githubusercontent.com/assets/1309249/8844050/e70b0bfc-3110-11e5-84d1-8895b86f56de.png)
![format-object-center-square4](https://cloud.githubusercontent.com/assets/1309249/8844047/e705a310-3110-11e5-8c1b-ddc89e19ef10.png)

`left`:
![format-object-left-square3](https://cloud.githubusercontent.com/assets/1309249/8844056/f535dfcc-3110-11e5-8619-201becbfdd54.png)
![format-object-left-square2](https://cloud.githubusercontent.com/assets/1309249/8844054/f52f4306-3110-11e5-879b-4025091e0bcb.png)
![format-object-left-square1](https://cloud.githubusercontent.com/assets/1309249/8844055/f533e8ac-3110-11e5-9f19-3a318882aba7.png)
![format-object-left-square4](https://cloud.githubusercontent.com/assets/1309249/8844107/8e47b46a-3111-11e5-9db6-f54a352948b9.png)


`right`:
![format-object-right-square1](https://cloud.githubusercontent.com/assets/1309249/8844064/1279d3c2-3111-11e5-866a-39c319c278b9.png)
![format-object-right-square2](https://cloud.githubusercontent.com/assets/1309249/8844066/12825416-3111-11e5-8bec-589425198fd1.png)
![format-object-right-square3](https://cloud.githubusercontent.com/assets/1309249/8844065/1280ee8c-3111-11e5-9345-fa0d6ea4bc27.png)
![format-object-right-square4](https://cloud.githubusercontent.com/assets/1309249/8844108/91e4231a-3111-11e5-8242-c1efbd4757c2.png)

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/format-wrap-inline
https://materialdesignicons.com/icon/format-wrap-square
https://materialdesignicons.com/icon/format-wrap-tight
https://materialdesignicons.com/icon/format-wrap-top-bottom
https://materialdesignicons.com/icon/format-float-none
https://materialdesignicons.com/icon/format-float-left
https://materialdesignicons.com/icon/format-float-center
https://materialdesignicons.com/icon/format-float-right

Renamed them a bit.

**Comment by Templarian** [comment]
Tried at the tank... ended up making an observatory. Not 100% set on it though.

![observatory](https://cloud.githubusercontent.com/assets/338885/8844715/bb848ea0-30dd-11e5-86df-c7c2a4eb8d89.png) ![observatoryx2](https://cloud.githubusercontent.com/assets/338885/8844716/bd7dd1d0-30dd-11e5-9b7a-7066599b20c5.png)

**Comment by splitbrain** [comment]
Looks like a robot with one of these toilet cleaning thingies on his head ;-) But really I'm for observatories over tanks anytime :-)

The alignment icons are perfect now. Thanks.

**Comment by Templarian** [comment]
oberverate!

Okay. If you really need a tank icon open another issue and we'll get it added. For now I'm going to close out this issue.

**Comment by splitbrain** [comment]
Yeah, I don't need the tank. It was more of an attempt to implement #365

**Comment by splitbrain** [comment]
Yeah, I don't need the tank. It was more of an attempt to implement #365

**Comment by CoDEmanX** [comment]
We could use a Dalek icon as well :zap: :gun: :alien: !
![Imgur](http://i.imgur.com/rxKZe8Q.jpg?1)

:+1: for the new `format-wrap-*` names!

The new `format-float-*` icons are a little irregular, nonetheless much descriptive. Here's a slightly cleaner version of `format-float-right` vs. the original:
![format-float-right-variant](https://cloud.githubusercontent.com/assets/1309249/8844957/ec522bea-311a-11e5-9b16-cea75d9475b2.png)
![format-float-right](https://cloud.githubusercontent.com/assets/1309249/8844958/ec58f646-311a-11e5-826b-0d58096cc67a.png)
I'm undecided which I like better, because cleaner also means information loss.

The square is quite small. A lot of attention is drawn to the lines, although the square is the important thing here. In a cleaner version, the square is more prominent.

The float icons look really geared towards CSS formatting. Thinking desktop publishing however, one could change `format-float-center` to `format-float-both` (like CSS' `clear: both`), and use another icon as `format-float-center`:
![format-float-center](https://cloud.githubusercontent.com/assets/1309249/8844898/6966f99a-311a-11e5-93e4-6cd5f2158ad2.png)

**Comment by Templarian** [comment]
I went with the one with more information simply for the fact it stands out with what it would do when wrapped in text.

I agree with your second idea of renaming and adding that icon. I'll get that added shortly.
