### ISSUE TITLE
Park / playground

### ISSUE THREAD

**Issue by gregfenton** [Templarian/MaterialDesign#5243]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

"Park" or "playground" icons such as a slide, a swingset, a seesaw, playstructure, treehouse, soccer/football field, baseball diamond, etc.

## Examples

A [search for playground icons](https://www.google.com/search?q=playground+icons) reveals a ton of ideas.

**Comment by goyney** [comment]
We already have [`soccer-field`](https://materialdesignicons.com/icon/soccer-field).

I've created new issues for slide (#5397), seesaw (#5398), and baseball diamond (#5396).

We also have various icons of soccer, basket-, base-, and footballs.

I'm going to close this issue because it's far too broad to keep open and assume other ideas. If you have other specific icon requests, please open a new issue for each individual icon idea.

Thanks for your suggestions!

**Comment by gregfenton** [comment]
That's awesome @goyney!   Thank you muchly!!
