### ISSUE TITLE
washer-machine / tumble-dryer with lid/door open/closed

### ISSUE THREAD

**Issue by perozonp** [Templarian/MaterialDesign#5277]
I have:

- [x] Searched all [issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] Searched the [current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I want to indicate when my washer machine lid is open/closed (top-loader). Also want to indicate when my tumble-dryer door is open/closed (front-loader).

## Examples

Sorry, I don't have any example to load, probably using the original "washer-machine" and "tumble-dryer" adding the lid/door showing is open/closed. Probably won't be possible to use the entire original icon due to space/size, that's ok, as long as the final icon can be easily interpreted and a door/lid open/closed.

**Comment by goyney** [comment]
This is not something I feel we can accomplish. There is no universal open for washers and dryers due to the duality of styles each have (e.g. top-loading vs. front-loading). Additionally, our current icons use the full canvas space as it is. I don't think it's a good idea to create a new icon style to indicate open that is different than our current base icons. I would recommend that if you want to show some sort of state distinction, to use the `alert` variant to indicate something requires attention.
