### ISSUE TITLE
account-refresh

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#5335]
Hi,
I was in need of a "account-refresh" icon to express account reactivation (after suspension for example).
They are quite unusual (I could have done a classical version with refresh modifier, but I like them) What do you think ?

## Preview
![image](https://user-images.githubusercontent.com/6012554/87677550-2fcb1f80-c77a-11ea-90c6-10e17f475722.png)

## Zip Download

I struggle with making the outline version a single path, but here is the zip
[Archive.zip](https://github.com/Templarian/MaterialDesign/files/4931851/Archive.zip)

**Comment by Templarian** [comment]
Added. Actually kept your name just on the off chance we use the small refresh overlay also. But I did re-vector them so that the circles were on exact points. Try to not rotate circles.

You're up to 22 icons! 😃

**Comment by qnp** [comment]
Thanks for the rework of the vector shape. Can you tell me what tools do you use ? I struggled in vain with Illustrator + svgo to generate a single & clean path.

**Comment by Templarian** [comment]
@qnp Missed that message. Illustrator is actually great if you select all the paths and combine.

The issue is rotating circles themselves moves the point onto weird point values resulting in our optimization to round them to 2 decimal places. Just rotate the arrow part and then cut/combine.

Don't worry about running the SVG through any optimizations. The admin already runs SVGO + other fancy calculations to make it as small as possible. The key is to make sure any point that can be on an exact integer the better. We actually round anything close also. Like `.98` = `1`. and `.43` = `.5` within `.02`. This handles illustrators and other software from producing weird floating point values.
