### ISSUE TITLE
GS1 DataMatrix 

### ISSUE THREAD

**Issue by kbehboodi** [Templarian/MaterialDesign#5346]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

GS1 DataMatrix barcodes are one of the most globally accepted standards in supply chain, healthcare and lots of other industries. It would be great if we could have an icon to represent it.
[here's the link to GS1 DataMatrix guidline](https://www.gs1.org/standards/gs1-datamatrix-guideline/25#1-Introduction-to-GS1-DataMatrix+1-2-Technical-characteristics).
## Examples
![DM](https://user-images.githubusercontent.com/36262267/87869994-693d9e00-c9b9-11ea-9827-21b898e09b44.png)

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
So, it's like a QR code, but with a solid line on the left and right? Yeah, that seems worth adding.

`datamatrix` or data-matrix`?

**Comment by kbehboodi** [comment]
You almost got it right. Also the top and right of the square should be dotted dash lines. I created a sample for you.
![DM2](https://user-images.githubusercontent.com/36262267/87904318-45d72980-ca73-11ea-8455-a7684a7c8cb5.png)
About the name I personally prefer datamatrix so you could use the dash to separate actions from the icon base name. like datamatrix-scan or datamatrix-add. 
It would be great if you could create a set of actions for it just like your QRCode icon.

**Comment by kbehboodi** [comment]
By the way it is better that the scan icon be like the qrcode-scan with those 4 outer corners

**Comment by daavko** [comment]
Here's my attempt at creating a `datamatrix` icon. I also created a variant that uses normal cutouts instead of the cutouts that `qrcode` uses, not sure which one is better.

![image](https://user-images.githubusercontent.com/7669061/88081455-adc76600-cb80-11ea-8e06-f24dcdecf96f.png)

![image](https://user-images.githubusercontent.com/7669061/88081597-e5361280-cb80-11ea-8f3c-0ed5335c4378.png)

![image](https://user-images.githubusercontent.com/7669061/88081641-f97a0f80-cb80-11ea-863a-84ad0adbdd23.png)

![image](https://user-images.githubusercontent.com/7669061/88081688-0860c200-cb81-11ea-9e49-3be5fe4d1940.png)

![image](https://user-images.githubusercontent.com/7669061/88081739-1f9faf80-cb81-11ea-92e4-7ec0480f151c.png)

![image](https://user-images.githubusercontent.com/7669061/88081760-27f7ea80-cb81-11ea-8ae1-15f461991197.png)

![image](https://user-images.githubusercontent.com/7669061/88081805-380fca00-cb81-11ea-97bc-043b237d43a5.png)

![image](https://user-images.githubusercontent.com/7669061/88081847-46f67c80-cb81-11ea-94e7-1043e40ad2fc.png)

![image](https://user-images.githubusercontent.com/7669061/88081896-57a6f280-cb81-11ea-82e3-360887ae782f.png)

![image](https://user-images.githubusercontent.com/7669061/88081930-61305a80-cb81-11ea-887b-2775a63e4daa.png)

![image](https://user-images.githubusercontent.com/7669061/88082653-532f0980-cb82-11ea-9687-6ad794bbdf42.png)

[datamatrix.zip](https://github.com/Templarian/MaterialDesign/files/4954954/datamatrix.zip)

**Comment by goyney** [comment]
[![data-matrix](https://materialdesignicons.com/icon/data-matrix)](https://materialdesignicons.com/icon/data-matrix)[![data-matrix-scan](https://materialdesignicons.com/icon/data-matrix-scan)](https://materialdesignicons.com/icon/data-matrix-scan)
[![data-matrix-plus](https://materialdesignicons.com/icon/data-matrix-plus)](https://materialdesignicons.com/icon/data-matrix-plus)[![data-matrix-minus](https://materialdesignicons.com/icon/data-matrix-minus)](https://materialdesignicons.com/icon/data-matrix-minus)
[![data-matrix-remove](https://materialdesignicons.com/icon/data-matrix-remove)](https://materialdesignicons.com/icon/data-matrix-remove)[![data-matrix-edit](https://materialdesignicons.com/icon/data-matrix-edit)](https://materialdesignicons.com/icon/data-matrix-edit)
