### ISSUE TITLE
person with cap

### ISSUE THREAD

**Issue by syrynj** [Templarian/MaterialDesign#5349]
I like to request a pilot / taxidriver / ..... icon.
It should be the same style as 'account-hard-hat'
A guy with a cap is what I have in mind.
The name should also be similar like 'account-cap'.
This way it can represent a pilot, taxi driver, even a police officer.

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
