### ISSUE TITLE
Monitor with different screen ratios

### ISSUE THREAD

**Issue by CoreyVidal** [Templarian/MaterialDesign#5360]
I have:

- [✓] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [✓] Searched open issues to make sure there isn't a request for this icon.
- [✓] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/20746389/88422247-f026b800-cdb7-11ea-95ae-b948506fbc78.png)

![image](https://user-images.githubusercontent.com/20746389/88422302-0765a580-cdb8-11ea-8d8b-102150c172fe.png)

![image](https://user-images.githubusercontent.com/20746389/88422347-1a787580-cdb8-11ea-9dc5-3024815907ed.png)

![image](https://user-images.githubusercontent.com/20746389/88422418-3c71f800-cdb8-11ea-97ce-aa1f23611973.png)

![image](https://user-images.githubusercontent.com/20746389/88422492-590e3000-cdb8-11ea-8c55-d36d98411f13.png)

![image](https://user-images.githubusercontent.com/20746389/88422548-6f1bf080-cdb8-11ea-89ee-3e1b81753233.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[monitor-with-different-screen-ratios.zip](https://github.com/Templarian/MaterialDesign/files/4973659/monitor-with-different-screen-ratios.zip)

**Comment by goyney** [comment]
I like the idea. The 16:9 one is the best because the numbers are kept on the grid. We'll need to work on the 4:3 one to align them to the grid as well. Not sure we need the 16:10 one, but if so, we'll need to align that one as well.

**Comment by CoreyVidal** [comment]
I started with the numbers for 4:3 (and 16:10) aligned to the grid, however it then looks really weird. The numbers end up looking too high or too low in the frame. And if you adjust the screen/frame, it's then no longer the ratio it claims it is, haha.

**Comment by goyney** [comment]
As I stated, they'll need some work. 1dp lines are technically against Material guidelines, but we allow them in certain cases. I believe this is a good case to allow them, but they absolutely have to be on the grid. They're blurry at native resolution, so we have to adjust for that.

**Comment by Xenomorph99** [comment]
On closer inspection, our current [monitor](https://materialdesignicons.com/icon/monitor) icon is actually 22 dps wide as you can see here:

![monitor](https://user-images.githubusercontent.com/1837101/96914035-af474980-1461-11eb-8d4f-84f93b6a9b3e.png)

I don't think it makes sense to have different monitor shapes for 16:10 and 16:9 since the difference isn't noticeable at 24x24 dps. So, I added 16:10 and 16:9 to our existing monitor icon.

![monitor-size-16x10](https://user-images.githubusercontent.com/1837101/96914287-05b48800-1462-11eb-87f2-fdef3eab0299.png)
![monitor-size-16x9](https://user-images.githubusercontent.com/1837101/96914284-051bf180-1462-11eb-8002-83a7b35668a4.png)

Having an icon to represent smaller/older monitors would be useful, so I included one here both with and without 4:3.

![monitor-small](https://user-images.githubusercontent.com/1837101/96914452-43b1ac00-1462-11eb-8249-5d12b8609223.png)
![monitor-size-4x3](https://user-images.githubusercontent.com/1837101/96914451-43191580-1462-11eb-8a6c-6e031d221444.png)

[monitor-size.zip](https://github.com/Templarian/MaterialDesign/files/5424952/monitor-size.zip)

**Comment by goyney** [comment]
Not gonna add the numeric ones at this time. They break guidelines and aren't really needed.
[![monitor-small](https://materialdesignicons.com/icon/monitor-small)](https://materialdesignicons.com/icon/monitor-small)
