### ISSUE TITLE
pencil-ruler-outline

### ISSUE THREAD

**Issue by AlexandreALAIMO** [Templarian/MaterialDesign#5383]
Hi Material Design Icons team,

Outlined icons look awesome ! I'm looking for an outlined icon representing "design", I think a pencil-ruler-outline might be useful.

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
