### ISSUE TITLE
Footnote Icon

### ISSUE THREAD

**Issue by emilyb22** [Templarian/MaterialDesign#5386]
Could a footnote icon be made? Perhaps a note icon with a line above it or a note with a shoe or foot on it.

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
