### ISSUE TITLE
Related icons with variable size

### ISSUE THREAD

**Issue by Selada** [Templarian/MaterialDesign#5394]
Hi,

I've search for this issue and found a related one closed (#4384). I understand the need to comply with the restriction and design rules.

I'm using some related icons side by side in a vertical menu and noticed icons like [account-clock-outline](https://materialdesignicons.com/icon/account-clock-outline) and [account-cancel-outline](https://materialdesignicons.com/icon/account-cancel-outline) have different sizes, which makes them unusable next to each other.

Although the "person" in the icon has the same size, the detail on the left shoulder has different sizes (clock Vs. cancel), which makes them have different widths and fit differently in the space reserved for icons :-| Is it a normalization between related icons like these (normalizing the detail in the shoulder) something to considerable?

![imagem](https://user-images.githubusercontent.com/11150532/89054610-051fc000-d351-11ea-8824-aece9a494308.png)

Tks

**Comment by goyney** [comment]
In your specific example, the clock cannot be depicted at any smaller of a size, otherwise it no longer can be a clock. Also, because of the size of the clock, the entire account icon is actually shifted 1dp to the left to support fitting it in the available space. That's just the nature of how these icons are. If you're looking to have perfect alignments in your app, unfortunately that task will have to fall to you to adjust positioning as you see fit. But, the `cancel` and `clock` modifiers there are our standard modifiers and will be the same on all icons they are applied to.

**Comment by Templarian** [comment]
Closing this one out as explained above, it's a limitation of the overlay size. Always try to do a cutout, but it's not always possible.
