### ISSUE TITLE
Rename icons with sparkles modifier for uniformity

### ISSUE THREAD

**Issue by Simran-B** [Templarian/MaterialDesign#5400]
- ~~silverware-clean -> silverware-sparkles~~ - No rename, but we'll alias this one.
- [x] `sparkles` -> `shimmer`
- [x] `monitor-clean` -> `monitor-shimmer`
- [x] `television-clean` -> `television-shimmer`

**Comment by goyney** [comment]
I hate `sparkles`. I know we just added a base `sparkles` icon. I'd prefer we find a better name for these.

However, we cannot rename it `clean`, because there are other icons (like Google's `insights` icon`) that use the sparkles, or shimmer, or whatever, that does not mean clean, but means "magic."

That being said, we know this visual modifier can represent a few very different things: magic, stars, clean... Naming suggestions for something that hits all those without it being "stars" since they aren't literal stars?

🤔

**Comment by Templarian** [comment]
- `silverware-clean` is fine and _shouldn't_ be changed.
- `shimmer` works for the others. Agreed it is weird we called it `clean` on `monitor` and `television`.

**Comment by goyney** [comment]
Then let's rename `sparkles` to `shimmer` in v6 as well.

**Comment by Templarian** [comment]
@Simran-B Updated your comment with the list of tasks.

**Comment by goyney** [comment]
@Templarian Lol, I just did too, looks like my edit went in over yours. Sorry!

**Comment by goyney** [comment]
These have been renamed.
