### ISSUE TITLE
Diversify

### ISSUE THREAD

**Issue by Simran-B** [Templarian/MaterialDesign#5406]
We added a `consolidate` icon (#4236), so I thought we might want a `diversify` icon as well. 
There is already `arrow-decision`, which comes very close:

![image](https://user-images.githubusercontent.com/7819991/89391138-12013280-d708-11ea-990f-3f5a056523e5.png)

Not sure if we need another one. Would be nice to have one in a similar style to consolidate:

![image](https://user-images.githubusercontent.com/7819991/89391259-41b03a80-d708-11ea-9f6c-4c47dccb26e1.png)

## Preview

![image](https://user-images.githubusercontent.com/7819991/89391305-4ffe5680-d708-11ea-927d-ae2071349b4c.png) ![image](https://user-images.githubusercontent.com/7819991/89391334-5ab8eb80-d708-11ea-90f8-3f9104ca9f00.png)
![image](https://user-images.githubusercontent.com/7819991/89391354-63a9bd00-d708-11ea-9c6f-1ca8fd6a5568.png) ![image](https://user-images.githubusercontent.com/7819991/89391372-6c9a8e80-d708-11ea-9414-1fab113acac4.png)
![image](https://user-images.githubusercontent.com/7819991/89391396-77552380-d708-11ea-8d70-b7ee27b08477.png) ![image](https://user-images.githubusercontent.com/7819991/89395213-4f1bf380-d70d-11ea-9d3f-7f0356ad1716.png)
![image](https://user-images.githubusercontent.com/7819991/89396649-1aa93700-d70f-11ea-9ecf-b0d7ea713e59.png)

## Zip Download

[diversify.zip](https://github.com/Templarian/MaterialDesign/files/5027464/diversify.zip)

**Comment by Templarian** [comment]
Just need to think of some nice names for these. I think many would be good additions.

**Comment by goyney** [comment]
I went with the first one because it matches the style of `consolidate` the best.

[![diversify](https://materialdesignicons.com/icon/diversify)](https://materialdesignicons.com/icon/diversify)

Option 2's corners were too round to match.
I don't like the combined nature of 3 and 4, they remind me a little bit of the USB logo.
Option 5 feels more like a split... maybe? This one might be worth adding with a different name.
Option 6 is just `pan` with different arrows.
Option 7 feels too chaotic for a diverse split.

So... thoughts on names for this one?
![image](https://user-images.githubusercontent.com/1015040/131900679-7a3b554b-cdf1-441d-a9dc-ff1c3219ad5c.png)

`split-diverge`, `diverge`, etc?

**Comment by Simran-B** [comment]
Isn't it more like broadcast / multiplex?

**Comment by goyney** [comment]
[![multicast](https://materialdesignicons.com/icon/multicast)](https://materialdesignicons.com/icon/multicast)
