### ISSUE TITLE
Camera Rotation

### ISSUE THREAD

**Issue by nikhiladmin** [Templarian/MaterialDesign#5407]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon for change front and rear camera 

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@nikhiladmin Please fill out the issue template. Examples etc. I've pasted the template back into the issue.

**Comment by Simran-B** [comment]
We have the following icons:

![image](https://user-images.githubusercontent.com/7819991/89638317-e3bc5800-d8ab-11ea-858a-5e96dbe4be5c.png) ![image](https://user-images.githubusercontent.com/7819991/89638335-ec149300-d8ab-11ea-83ec-4e705d9d461b.png) ![image](https://user-images.githubusercontent.com/7819991/89638453-20884f00-d8ac-11ea-93f1-f3431e084f59.png)

I see a switch icon more often in apps however, and Google also has two in the official set:

![image](https://user-images.githubusercontent.com/7819991/89638584-5a595580-d8ac-11ea-8450-31a61b4365ac.png)

I think we should add those.

**Comment by goyney** [comment]
So, we're not going to add either of those because they're terrible. The first one doesn't use our standard arrows. The second one uses a 1dp line and is bad at native resolution.

Instead, I've used our `cached` to create `orbit-variant` for the first:
[![orbit-variant](https://materialdesignicons.com/icon/orbit-variant)](https://materialdesignicons.com/icon/orbit-variant)

And `camera-retake` to make a flip version of the second:
[![camera-flip](https://materialdesignicons.com/icon/camera-flip)](https://materialdesignicons.com/icon/camera-flip)[![camera-flip-outline](https://materialdesignicons.com/icon/camera-flip-outline)](https://materialdesignicons.com/icon/camera-flip-outline)

That should take care of this issue. Thanks for the suggestion!
