### ISSUE TITLE
numeric-negative-1 -> minus-one

### ISSUE THREAD

**Issue by truefusion** [Templarian/MaterialDesign#5408]
We have `plus-one`. Short, simple and intuitive. In order to get `minus-one` we need to use `numeric-negative-1`. That's not intuitive and not so short and simple. Please make `minus-one` an alias of `numeric-negative-1`.

Also, `plus-one` is bigger than the numeric icons. Resizing them to match would be useful.

**Comment by Templarian** [comment]
That `plus-one` is a legacy of Google's social media platform. The `plus-one` needs to be deprecate.

So, that leaves us will adding a new icon. `numeric-positive-one` to match `numeric-negative-one`.

Or we rename `numeric-negative-one` to `numeric-minus-one`. 🤔 

The aliases are only used in searching. They don't actually show up in code anywhere.

**Comment by JapanYoshi** [comment]
I think we should officially name the icons `numeric-positive-one` and `numeric-negative-one`, and make them searchable via `plus-one` and `minus-one`.

**Comment by truefusion** [comment]
If `plus-one` is to become deprecated to match the naming pattern of `numeric-{sign}-{number}`, then it would seem right to match the icon sizes, also. Really hoping that doesn't get overlooked. They look really odd next to each other as it is now.

I would also vote for `decrement` and `increment` as being aliases.

**Comment by goyney** [comment]
So, there's a couple things we can do here now, especially because this will cause a breaking change that won't make the pack until v6.

- Update `numeric-negative-1` (extend `minus` by 1dp to support plus variant)
- Added `numeric-positive-1`
- Aliased `numeric-negative-1` => `decrement`, `minus-one`
- Aliased `numeric-positive-1` => `increment`, `plus-one`
- Deprecate the existing `plus-one`, which will be removed in v6

We'll leave this issue open now until v6, when we fully remove the existing `plus-one`.

**Comment by Simran-B** [comment]
The official set has these as `exposure` icons:

![image](https://user-images.githubusercontent.com/7819991/89633900-c9cb4700-d8a4-11ea-8d1d-cc11b31bc54b.png)

**Comment by goyney** [comment]
We don't need multiple styles of numbers, IMO. We already have an alphanumeric set, so sticking with that seems more reasonable.

**Comment by goyney** [comment]
`plus-one` has now been removed.
