### ISSUE TITLE
Edit Border Icon

### ISSUE THREAD

**Issue by GrRivero** [Templarian/MaterialDesign#5415]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2970080/89765696-1f972d80-daf7-11ea-8907-9a4b1f95c283.png)

## Zip Download

[icon_editor_border_color_24px.zip](https://github.com/Templarian/MaterialDesign/files/5049813/icon_editor_border_color_24px.zip)

**Comment by goyney** [comment]
Thanks for the contribution. I've unchecked "Followed the material guidelines" because there are some minor issues you'll need to address before we can add this. Namely, you've have elements in the trim area and your elements are not aligned to the grid. See if you can make some adjustment so we can consider adding this!

**Comment by Templarian** [comment]
I don't think we should add this. The correct usage is overlaying `border-color` + `color-helper`.

**Comment by GrRivero** [comment]
> I don't think we should add this. The correct usage is overlaying `border-color` + `color-helper`.

I understand that to be able to represent an icon I have to load two and overlaying them by css?

I think it is easier to add a new icon to the library. 

If I adjust the icon will it be considered?
