### ISSUE TITLE
Flood Light

### ISSUE THREAD

**Issue by tbtgspence** [Templarian/MaterialDesign#5425]
A typical flood light you'd see installed on a house with two lights.

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.

**Comment by tbtgspence** [comment]
Strange.  I could swear when i created the issue that the body was blank.  Oh well, I resubmitted with the correct format.
