### ISSUE TITLE
Seasons

### ISSUE THREAD

**Issue by flixlix** [Templarian/MaterialDesign#5452]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I would like to have icons for different seasons of the year, like Summer and Winter

## Examples

Summer
![1266619-200](https://user-images.githubusercontent.com/61006057/91293336-c0d8e180-e78f-11ea-9b3e-44044cd03bb9.png)

Winter
![weather-snow-flake-512](https://user-images.githubusercontent.com/61006057/91293357-cafae000-e78f-11ea-852e-80436699fc2e.png)

Fall
![fall-season-1409576-1192669](https://user-images.githubusercontent.com/61006057/91293393-da7a2900-e78f-11ea-8449-499f00a3a98d.png)

Spring
![transferir](https://user-images.githubusercontent.com/61006057/91293486-fd0c4200-e78f-11ea-861f-be1fccd74864.png)  (I know this one already exists, I just didn't have any other ideas for the Spring season.)
![500_F_175212923_PoS8LrNqgXEgelK7eeyGRlyUOpsPOVJd](https://user-images.githubusercontent.com/61006057/91293446-eb2a9f00-e78f-11ea-8be2-6b277027b04b.jpg) An icon representing all seasons would also be awesome.

**Comment by JapanYoshi** [comment]
I'm quite sure flower, sun, leaf, and snowflake already exist.

**Comment by flixlix** [comment]
Yes, they do, but I would like to have an icon that represents all seasons.

**Comment by goyney** [comment]
This is going to be next to impossible to do within Material guidelines. It becomes difficult because there is no one clear (and simple) icon that can be used to represent each season and doing so in a fashion that all four fit in the same 24x24 canvas just isn't feasible. I mean, we barely we able to make it work for `calculator-variant`, and those are 4 simple mathematic symbols.

I'm afraid we're going to have to close this request. If someone wants to try and design something and prove me wrong, feel free to post it here and we can potentially reopen the issue to discuss it.

Thanks for your suggestion.
