### ISSUE TITLE
A.C. Cool ; A.C. Heat ; A.C. Off

### ISSUE THREAD

**Issue by ItamarVa** [Templarian/MaterialDesign#5477]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
We already have a few icons that solve this use case. We really can't make any other assumptions on what you might want because you didn't "Include any example images so we know what the icon should look like."

For example, here's a thermostat card in Home Assistant:

![Screen Shot 2020-09-08 at 9 01 59 PM](https://user-images.githubusercontent.com/1015040/92542366-8b63d780-f216-11ea-9a24-330c14f58250.png)

Give us some examples of what else you might like to see to depict these.

**Comment by goyney** [comment]
Closing because `Needs More Info` was added quite a while ago without further clarification.
