### ISSUE TITLE
new icon

### ISSUE THREAD

**Issue by frankiha** [Templarian/MaterialDesign#5479]
please create a "car in the garage" icon
thank you
![car](https://user-images.githubusercontent.com/53922329/92514641-9c95ef80-f1e8-11ea-8625-30fff5873d55.png)

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
