### ISSUE TITLE
krishna

### ISSUE THREAD

**Issue by keatshackon** [Templarian/MaterialDesign#5490]
I need a material ocon on krishna pic!
Please... make one!

**Comment by Templarian** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.

**Comment by Templarian** [comment]
A note also, that is way too detailed for a small 24x24 icon, so probably not possible. Might want to represent this with something more generic.
