### ISSUE TITLE
Wavy Icon

### ISSUE THREAD

**Issue by BanjoKaJoey** [Templarian/MaterialDesign#5581]
- I'd specifically be interested in a three wave icon, seems classic and I have a use case for it already. Something like the "approximately equal" icon from mathematics, except that has two waves and I think three would look better.
- "approximately equal" icon pictured here: https://www.rapidtables.com/math/symbols/Basic_Math_Symbols.html

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
