### ISSUE TITLE
Rounded chat bubble icon

### ISSUE THREAD

**Issue by naamapps** [Templarian/MaterialDesign#5590]
Hi,
It would be nice to have a rounded char bubble icon like in the image below.

![chat](https://user-images.githubusercontent.com/37176893/96699673-37145180-1397-11eb-8f35-89f9702cd07a.png)

Thanks

**Comment by Templarian** [comment]
Could you use `chat-outline`?

**Comment by Templarian** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
