### ISSUE TITLE
Front Yard Icons

### ISSUE THREAD

**Issue by brianm71** [Templarian/MaterialDesign#5594]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icons to represent the front yard area for use in home assistant.  For example, I have a "front yard" and "back yard" areas.  The other areas of the house (1st floor, second floor, etc..) are all represented by a fairly self-explanatory icon, but there really aren't any icons in this set to represent outside areas such as front yard, back yard, shed and garden.

Suggestion is for:
Front Yard

## Examples
A few examples:
https://thenounproject.com/term/front-yard/546171/ (front yard)
https://thenounproject.com/term/front-yard/199288/ (front yard)

**Comment by Templarian** [comment]
@brianm71 The template isn't optional. Can you fill it out.

**Comment by brianm71** [comment]
> 
> 
> @brianm71 The template isn't optional. Can you fill it out.

Done

**Comment by goyney** [comment]
We have some of these.

[![home](https://materialdesignicons.com/icon/home)](https://materialdesignicons.com/icon/home)[![grass](https://materialdesignicons.com/icon/grass)](https://materialdesignicons.com/icon/grass)
[![sprinkler-variant](https://materialdesignicons.com/icon/sprinkler-variant)](https://materialdesignicons.com/icon/sprinkler-variant)

Fence is being tracked here: https://github.com/Templarian/MaterialDesign/issues/6110

The one with the street in front of the house won't work due to [Material Guidelines](https://material.io/design/iconography/system-icons.html#system-icon-metrics) on perspective.
