### ISSUE TITLE
How to attribute credits to the icon designers or MDI in general?

### ISSUE THREAD

**Issue by PurpleProgrammer** [Templarian/MaterialDesign#5600]
Hello!

I know this might look like a "dumb" question, but I want to know how I should attribute credits to the icon designers.

To begin with, it is not really clear what the license really is. "Some icons are under the Apache 2.0 License, other under their respective licenses". This is not really clear. Which icons can be used without attribution under Apache 2.0 (like Google's icons) and which ones need to be attributed to their respective designers?

If attribution for some icons is mandatory, do I have to attribute each of the designers one by one, or is it enough to include a link pointing the the official Material Design Icons page?

As for the Apache 2.0 and the other licenses, do I have to include them in my "About" page, or do I only have to state that the icons are licensed under the Apache 2.0 License?

Thanks for your time in advance!

P.S.:
I would like to ask for the designers' opinion on how you would like your credentials being included in an attribution page. I really enjoy using open source code and the least I can do is give a shout out to the contributors. For example, would you like your full name being stated alongside with your dribble/twitter profile?

**Comment by Templarian** [comment]
Apache 2.0 license applies after `v5.6+`. The reason we have to legally say "some" is due to us including logos and brands (so be careful with how you use those).

No individual icon needs attribution (every is contributing to the pack, we just list the creators to encourage additions), the whole icon pack is licensed under Apache 2.0. This means you just have to include it in your source somewhere.

https://dev.materialdesignicons.com/license

**Comment by Templarian** [comment]
If you want to include a shoutout

Name: `Material Design Icons` URL: `https://materialdesignicons.com` Twitter: `@MaterialIcons`

**Comment by PurpleProgrammer** [comment]
Thanks @Templarian !!!
