### ISSUE TITLE
Shooting Star

### ISSUE THREAD

**Issue by melissakinsey** [Templarian/MaterialDesign#5602]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'd like to use this as a box icon in a PDF user guide. It would set off content that's useful or interesting, but not necessarily critical to performing a given task. Thanks, designers! 

## Examples

Include any example images so we know what the icon should look like.

![The More You Know](https://user-images.githubusercontent.com/18484470/97309742-6b24c200-1830-11eb-84ce-da0f86e5eec4.png)

**Comment by Xenomorph99** [comment]
It would be cool to add a shooting star to our icon library. However, we'd need to design our own version.

We can't use this exact star shape because it's a brand logo associated with NBC: https://en.wikipedia.org/wiki/The_More_You_Know_(TV_programming_block)

**Comment by Xenomorph99** [comment]
I included 3 options for us to look at.

- **Option A**: [star](https://materialdesignicons.com/icon/star) and [star-outline](https://materialdesignicons.com/icon/star-outline) with 1 dp on top and 0 dps on the right.
- **Option B**: An 18 dps wide star (instead of 20 dps) with 1 dp on top and 1 dp on the right.
- **Option C**: A 17 dps wide star shape (instead of 20 dps) with 2 dps on top and 2 dps on the right.

![star-shooting-a](https://user-images.githubusercontent.com/1837101/97725380-bbe82500-1a93-11eb-8305-cbae2a771327.png)
![star-shooting-b](https://user-images.githubusercontent.com/1837101/97725385-bc80bb80-1a93-11eb-8b5b-35d788737806.png)
![star-shooting-c](https://user-images.githubusercontent.com/1837101/97725386-bc80bb80-1a93-11eb-9e25-c54256c0b1ed.png)

![star-shooting-outline-a](https://user-images.githubusercontent.com/1837101/97725388-bc80bb80-1a93-11eb-89a5-bc995058546c.png)
![star-shooting-outline-b](https://user-images.githubusercontent.com/1837101/97725389-bd195200-1a93-11eb-97b3-86a4fb46fc57.png)
![star-shooting-outline-c](https://user-images.githubusercontent.com/1837101/97725392-bd195200-1a93-11eb-86b1-3c69b99ae094.png)

My recommendation is that we go with Option A because the outlined variants start to look a little strange when the star shape is less than 20 dps wide.

[star-shooting.zip](https://github.com/Templarian/MaterialDesign/files/5466076/star-shooting.zip)

**Comment by melissakinsey** [comment]
Understood about the trademark issue. Option B looks most like the logo to
me (but not enough like it to be an infringement). I’m not a designer,
though, so it’s your call. Thank you so much!

**Comment by UrsineRaven** [comment]
I also vote option B. I like that the lines shooting out seem to go to the edge of the nearest points of the star, yet not past them. It seems more aesthetically pleasing that way. That's just my uneducated-in-graphic-design 2¢ 😁.

**Comment by melissakinsey** [comment]
Hey, Ursine. (You have the best name ever, btw.) Did this icon get
finished? I don't see it in the database. Apologies—I just ran across this
email. I don't check it often enough.

Thanks!

Melissa

**Comment by goyney** [comment]
The "B" variants have been added.
