### ISSUE TITLE
New icons 

### ISSUE THREAD

**Issue by halfajobj** [Templarian/MaterialDesign#5604]
Hi there could you add in some icons for Holiday like sun and beach and countrys bank holidays etc

**Comment by GreenTurtwig** [comment]
Could you please fill out the template? It's required.

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
