### ISSUE TITLE
"Mail Sent" Icon

### ISSUE THREAD

**Issue by PurpleProgrammer** [Templarian/MaterialDesign#5606]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Indicating that a mail has been sent.

## Examples

Mail with some dash lanes on the left.

![Untitled](https://user-images.githubusercontent.com/24755259/97600373-a7634880-1a11-11eb-956a-42fb6f1185a7.png)

**Comment by Xenomorph99** [comment]
Since [email](https://materialdesignicons.com/icon/email) fills most of the 20x20 dps space, I used [email-mark-as-unread](https://materialdesignicons.com/icon/email-mark-as-unread) as the base for these new icons.

![email-fast](https://user-images.githubusercontent.com/1837101/97721497-1c289800-1a8f-11eb-9646-f1723ebc89bb.png)
![email-fast-outline](https://user-images.githubusercontent.com/1837101/97721496-1b900180-1a8f-11eb-9805-1542069c7bb9.png)

I also included an `-outline` version of [email-mark-as-unread](https://materialdesignicons.com/icon/email-mark-as-unread). It might make sense to change this icon's name to something more literal such as "email-envelope-open" or something like that since Google has changed theirs.

![email-mark-as-unread-outline](https://user-images.githubusercontent.com/1837101/97722051-cf918c80-1a8f-11eb-965f-b2f72c960486.png)

![mark-email-unread](https://user-images.githubusercontent.com/1837101/97722355-2d25d900-1a90-11eb-8059-d75acbb2b5f9.png)

[email-icons.zip](https://github.com/Templarian/MaterialDesign/files/5465906/email-icons.zip)

**Comment by martareg** [comment]
Proposal for icon requested by @harsimranmaan (#5794)

![sent-mat-design](https://user-images.githubusercontent.com/77104115/105628763-1c8ec000-5e3f-11eb-85be-9f180f333b30.png)

[sent-mat-design.zip](https://github.com/Templarian/MaterialDesign/files/5862072/sent-mat-design.zip)

**Comment by goyney** [comment]
[![email-fast](https://materialdesignicons.com/icon/email-fast)](https://materialdesignicons.com/icon/email-fast)[![email-fast-outline](https://materialdesignicons.com/icon/email-fast-outline)](https://materialdesignicons.com/icon/email-fast-outline)
