### ISSUE TITLE
Movie icons with modifiers

### ISSUE THREAD

**Issue by dpeter99** [Templarian/MaterialDesign#5616]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

These would be usefull for apps that manage watch lists, or that let the user add movies.

## Examples

Just the google ``movie`` icon with the modifiers like the already existing ``movie-search``

**Comment by Xenomorph99** [comment]
Here's our typical modifiers. I included `-play` and `-star` because they could relate to movies as well.

We already have [movie-edit](https://materialdesignicons.com/icon/movie-edit) and [movie-edit-outline](https://materialdesignicons.com/icon/movie-edit-outline) so I created `movie-open-edit` and `movie-open-edit-outline` to match.

![movie-plus](https://user-images.githubusercontent.com/1837101/98143050-de0fe780-1e85-11eb-80be-13a63e5540ef.png)
![movie-minus](https://user-images.githubusercontent.com/1837101/98143044-dd775100-1e85-11eb-93d0-67535fe231b4.png)
![movie-check](https://user-images.githubusercontent.com/1837101/98143041-dc462400-1e85-11eb-8991-27d7c79f1a7f.png)
![movie-remove](https://user-images.githubusercontent.com/1837101/98143052-de0fe780-1e85-11eb-8b8c-c5c46f5440fa.png)
![movie-cog](https://user-images.githubusercontent.com/1837101/98143043-dcdeba80-1e85-11eb-8a4c-34ac2495dfd1.png)
![movie-settings](https://user-images.githubusercontent.com/1837101/98143054-dea87e00-1e85-11eb-9f6d-f253eb87ff5f.png)
![movie-play](https://user-images.githubusercontent.com/1837101/98143048-dd775100-1e85-11eb-8ef5-fee15b0d5fef.png)
![movie-star](https://user-images.githubusercontent.com/1837101/98143057-dea87e00-1e85-11eb-9101-77fe7a2b77a9.png)
![movie-off](https://user-images.githubusercontent.com/1837101/98143046-dd775100-1e85-11eb-816b-bffd6bb3e313.png)

![movie-plus-outline](https://user-images.githubusercontent.com/1837101/98143147-f7b12f00-1e85-11eb-9ee1-63cc46f147e7.png)
![movie-minus-outline](https://user-images.githubusercontent.com/1837101/98143142-f7189880-1e85-11eb-9001-a1d91ef72fd4.png)
![movie-check-outline](https://user-images.githubusercontent.com/1837101/98143139-f5e76b80-1e85-11eb-8f04-72cd558a835e.png)
![movie-remove-outline](https://user-images.githubusercontent.com/1837101/98143148-f7b12f00-1e85-11eb-8275-d7ec6e7899cb.png)
![movie-cog-outline](https://user-images.githubusercontent.com/1837101/98143141-f6800200-1e85-11eb-9e3f-daea376f2d21.png)
![movie-settings-outline](https://user-images.githubusercontent.com/1837101/98143152-f849c580-1e85-11eb-8387-0619ef4cdd39.png)
![movie-play-outline](https://user-images.githubusercontent.com/1837101/98143146-f7189880-1e85-11eb-9e57-2651169add59.png)
![movie-star-outline](https://user-images.githubusercontent.com/1837101/98143153-f849c580-1e85-11eb-9be8-ad7138e95353.png)
![movie-off-outline](https://user-images.githubusercontent.com/1837101/98143145-f7189880-1e85-11eb-8efc-10ab5753bd6e.png)

![movie-open-plus](https://user-images.githubusercontent.com/1837101/98143623-8faf1880-1e86-11eb-9fd6-e9b10109d999.png)
![movie-open-minus](https://user-images.githubusercontent.com/1837101/98143619-8f168200-1e86-11eb-9d83-98677cf54cab.png)
![movie-open-check](https://user-images.githubusercontent.com/1837101/98143612-8de55500-1e86-11eb-95b5-d5a1dd27c1ed.png)
![movie-open-remove](https://user-images.githubusercontent.com/1837101/98143625-8faf1880-1e86-11eb-8aba-a43a3a0cb4c2.png)
![movie-open-cog](https://user-images.githubusercontent.com/1837101/98143615-8e7deb80-1e86-11eb-9276-248d6b827c1e.png)
![movie-open-settings](https://user-images.githubusercontent.com/1837101/98143627-9047af00-1e86-11eb-9fbd-eed86cf02fb0.png)
![movie-open-edit](https://user-images.githubusercontent.com/1837101/98143618-8e7deb80-1e86-11eb-9449-a3c5b9c5f1b2.png)
![movie-open-star](https://user-images.githubusercontent.com/1837101/98143628-9047af00-1e86-11eb-849c-2567fb126c3b.png)
![movie-open-play](https://user-images.githubusercontent.com/1837101/98143622-8f168200-1e86-11eb-89b2-0fde061ef233.png)
![movie-open-off](https://user-images.githubusercontent.com/1837101/98143620-8f168200-1e86-11eb-9c71-b75327371ab8.png)

![movie-open-plus-outline](https://user-images.githubusercontent.com/1837101/98143739-b53c2200-1e86-11eb-818c-42373dcbd981.png)
![movie-open-minus-outline](https://user-images.githubusercontent.com/1837101/98143733-b40af500-1e86-11eb-8cd1-eaaa3c886fad.png)
![movie-open-check-outline](https://user-images.githubusercontent.com/1837101/98143729-b3725e80-1e86-11eb-829a-97c5a05df75f.png)
![movie-open-remove-outline](https://user-images.githubusercontent.com/1837101/98143741-b53c2200-1e86-11eb-9a7a-ec5281ff247d.png)
![movie-open-cog-outline](https://user-images.githubusercontent.com/1837101/98143731-b3725e80-1e86-11eb-85ab-fb9834f84258.png)
![movie-open-settings-outline](https://user-images.githubusercontent.com/1837101/98143743-b53c2200-1e86-11eb-9a8b-63e827268f01.png)
![movie-open-edit-outline](https://user-images.githubusercontent.com/1837101/98143732-b40af500-1e86-11eb-8389-0e8d9f20342e.png)
![movie-open-play-outline](https://user-images.githubusercontent.com/1837101/98143737-b4a38b80-1e86-11eb-9580-b9b088237f5c.png)
![movie-open-star-outline](https://user-images.githubusercontent.com/1837101/98143744-b5d4b880-1e86-11eb-8109-718b8fe0003d.png)
![movie-open-off-outline](https://user-images.githubusercontent.com/1837101/98143735-b4a38b80-1e86-11eb-8904-f7a2ad860b59.png)

[movie-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5489470/movie-modifiers.zip)

**Comment by Xenomorph99** [comment]
Added

**Comment by Glandos** [comment]
Thanks! But this is puzzling: icons are visible on https://materialdesignicons.com/, but are neither in this repository, nor available in published extension.

Are they somewhere in limbos?

**Comment by goyney** [comment]
Yes, they are staged to be released in the 5.9 release. Sorry the milestone was not added.
