### ISSUE TITLE
Audio Inputs

### ISSUE THREAD

**Issue by iotemylabs** [Templarian/MaterialDesign#5625]
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

For audio inputs / output icons 

## Examples

Include any example images so we know what the icon should look like.

RCA (Red / White), 3.5" Stereo Jack (on headphones) 1/4" Jack (for guitars, etc.), XLR (for High End Audio and DMX Lighting, etc.)

**Comment by GreenTurtwig** [comment]
In the future could you please keep it to one icon per issue, thanks! 🐱 

We've already got `video-input-component` for three RCA connectors, though I've no idea why it's got a strip taken out of it, so that can be modified.
[![](https://materialdesignicons.com/icon/video-input-component)](https://materialdesignicons.com/icon/video-input-component)

Without the strip they're awfully long, so we should preferably reduce the height to 20dp, or keep the strip (not sure why).
![](https://user-images.githubusercontent.com/15905797/98416004-3c9bb800-2076-11eb-93e5-4e22530189d6.png)
![](https://user-images.githubusercontent.com/15905797/98416173-84224400-2076-11eb-80ff-0f6a471d836c.png)![](https://user-images.githubusercontent.com/15905797/98416131-72d93780-2076-11eb-9e19-10a755ebf05c.png)

Compromises will have to me made for the phone icons, the detail at the end of the connector will be lost at a small size and the 3.5" is essentially just a smaller version, so it makes sense to just use a single icon for all three sizes of connector. Can't decide on which insulation size is better.
![](https://user-images.githubusercontent.com/15905797/98417907-b8e3ca80-2079-11eb-93a1-8ccb7f98dc8f.png)![](https://user-images.githubusercontent.com/15905797/98417929-c9944080-2079-11eb-9c92-1c9fca11c865.png)


XLR is simple enough.
![](https://user-images.githubusercontent.com/15905797/98418254-622ac080-207a-11eb-9453-f3c4c8a02923.png)

Final note, that despite all these connectors having uses other than solely audio, it's their most common usage, so should append all with `audio-input`.

**Comment by goyney** [comment]
[![audio-input-rca](https://materialdesignicons.com/icon/audio-input-rca)](https://materialdesignicons.com/icon/audio-input-rca)[![audio-input-stereo-minijack](https://materialdesignicons.com/icon/audio-input-stereo-minijack)](https://materialdesignicons.com/icon/audio-input-stereo-minijack)[![audio-input-xlr](https://materialdesignicons.com/icon/audio-input-xlr)](https://materialdesignicons.com/icon/audio-input-xlr)
