### ISSUE TITLE
Bench icon

### ISSUE THREAD

**Issue by denisrom88** [Templarian/MaterialDesign#5641]
I am creating a large scale web map and I was kinda shocked there is no just simple bench icon in this library! :)
Can somebody create that?

**Comment by Templarian** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
