### ISSUE TITLE
fan-speed-auto

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#5663]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Indicating an automatic fan speed control (or an "away" level as it is used in my ventilation system).

## Preview

![grafik](https://user-images.githubusercontent.com/7279415/100269330-a8c35a80-2f56-11eb-8bae-ef639c7329bc.png)

## Zip Download

[fan-speed-auto.zip](https://github.com/Templarian/MaterialDesign/files/5598657/fan-speed-auto.zip)

**Comment by goyney** [comment]
The reason we used numbers for fan speeds instead of letters is because of localization issues. This falls into that same category.

_However_, "automatic" starts with "a" in most other languages after translation. We'll discuss this internally and make a decision if we are willing to add this variation.

**Comment by goyney** [comment]
We've decided we'll add this one. 😄

**Comment by goyney** [comment]
Added.
