### ISSUE TITLE
Floor lamp - on effect

### ISSUE THREAD

**Issue by benalla** [Templarian/MaterialDesign#5689]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I would like to have a 'floor-lamp-on'.
Same for 'ceiling-ligth-on'.

## Examples

Include any example images so we know what the icon should look like.

Thanks in advance

**Comment by goyney** [comment]
The light flares we've added to some icons don't indicate "on," but rather attention or direction. For example, `alarm-light` is to indicate flashing, while `wall-sconce-flat` is to indicate direction.

With these icons, direction is implied and the filled and outline versions, in addition to colorizing your icons, can help indicate on/off states if that is something your desire to do.

At this time, we're not interesting in adding a ton of light icons with rays because it is a slippery slope and most would not work, not work well, or over complicate an icon.

Thanks for your suggestion!
