### ISSUE TITLE
Something for Ambilight/ledstrip behing tv or monitor

### ISSUE THREAD

**Issue by Aasikki** [Templarian/MaterialDesign#5700]

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.

---

Additionally, this already exists as `television-ambient-light`.
