### ISSUE TITLE
Shutter middle state

### ISSUE THREAD

**Issue by katonage** [Templarian/MaterialDesign#5733]
I have: window-shutter-alert but I'd like it without the exclamation mark. To use it as the shutters middle position. 
In general, home automation scenario, windows, shutters and shades may have multiple positions than open and closed. (similar but maybe not that fine grained than battery icons are there) 
In my home somfy shades have a decent middle position I d like to depict. 

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Home automation entity state graphical representation 

Provide some context of how your icon could be used.

## Examples
window-shutter-alert without the exclamation mark 

Include any example images so we know what the icon should look like.

**Comment by Mariusthvdb** [comment]
+1 for this, to use while opening or closing, or as OP states, when stationary everywhere between 0% and 100%

thanks for considering

**Comment by Mariusthvdb** [comment]
> Your shutters are either open or closed

well, tbh, that's just the thing, as a shutter user open/closed are the 2 extremes in default states. Anything in between is the exception on those states, and are to be noted. The %age isn't so important, simply the fact they are neither fully openend nor closed is the important thing here.

Hence the fact we can now use the -alert variant. But, considering the fact an -alert icon is mostly used for situations which require immediate action, it is a bit over the top for this use.

Wont push any further, and understand what you're saying. Still, I do hope my thoughts make sense.

Goes without saying the addition of the icon would be much appreciated ;-)

thanks!

**Comment by JamesCoyle** [comment]
I think adding this would be fine. Just need to remove the alert from the alert variant.

**Comment by katonage** [comment]
> Your shutters are either open or closed,

I also think having middle state is also quite common. Somfy shades (a very popular brand) have a my position which means exactly a programmable middle state. Garage doors usually have sensors for being open or close. Everything between is the middle state. Etc. 
I'm not sure why this is a slippery slope, these icons can be relatively easily drawn from the open and closed variants. Naming is also trivial. 
Need has been expressed by multiple users.

**Comment by goyney** [comment]
It's a slippery slope because my front door can be partially open or closed. Same with my windows, my garage door, my gate... We're not going to offer "mid-ground" versions of everything that has an open and closed state. Again, icons are meant to be _contextual_, not literal. Just because we can easily add this doesn't mean it is the right thing to do. I stand firmly by my opinion that this is too niche, a slippery slope, and not worth adding.

**Comment by JamesCoyle** [comment]
I think there are valid use cases here that we should be catering to. A garage door that is not closed but not open enough for a vehicle to drive through cannot be represented by our open variant. For automated shutters like that we should have a state to represent that situation. We already have intermediate versions of these icons just with an alert modifier to indicate an issue with the mechanism occured and the shutter is stuck at that position or it's position is unknown so adding a version without that doesn't require any design work as it would with the window or door icons.

Of course with a window or door you don't need an intermediate state: if it's not closed it is definitely open letting in a breeze no matter how wide open it is. I definitely agree we shouldn't add those.

**Comment by goyney** [comment]
You're contradicting yourself though. Just because a garage door is not open enough for a car to get through doesn't mean its not open, letting in a breeze (or the occasional raccoon 🦝). Just because a shutter isn't open all the way doesn't mean it's not letting light in. These are the exact same as a door or a window. So if we're going to add these, what is so special about a door and a window that we don't add intermediate states to those? Especially since those are much harder, if not impossible, to create in a Material style.

**Comment by Mariusthvdb** [comment]
> Especially since those are much harder, if not impossible, to create in a Material style.

if that's (being hard) a valid reason not to add it, while at the same time you say:

> Just because we can easily add this doesn't mean it is the right thing to do

now that is contradicting yourself ;-)

But seriously, following your philosophy, we either have 0% open (closed) or 100% open for all other states. Calamities can use the -alert version (how to establish that is food for a whole separate discussion, but it would require some serious extra code in any system.)

While the main purpose for many users we see on eg Home Assistant for these shutter and garage door icons exactly **is** to check if it's anywhere between 0% and 100%. Regular windows are much less discussed concerning this specific issue.

It is still somewhat confusing really why you would want to forgo the wish of many users to illustrate their home situation best with the addition of a single extra, super functional en clarifying, icon.

_Especially_ since it is so easy, and almost present already. 

Sorry to push, while I promised I wouldn't.....

**Comment by JamesCoyle** [comment]
> You're contradicting yourself though. Just because a garage door is not open enough for a car to get through doesn't mean its not open

That's exactly my point. It's open but not open enough for it's primary purpose (if you consider the window shutter icon can also be a garage variant or represent a shop front with an entrance and isn't just acting like a blind). I'm arguing that shutters and garage doors when partially open serve a different purpose than when fully open. We currently have no icon to represent that partially open state.

**Comment by katonage** [comment]
![IMG_20210223_212954~2](https://user-images.githubusercontent.com/36854755/108925356-c038df00-763c-11eb-8ac8-6f442222ff89.jpg)
In my house I have a three button remote. The button's meaning is *full open, *full close *middle state. I use the middle state the most often, since full close makes complete darkness that feels like closed in a box. Sometimes it is nice in stormy winter nights, but summertime the middle state shuts out direct sunlight, but also lets light in conveniently. Most nights I use the middle state too, because it lets morning light in providing a natural wake up.
In this respect the middle state has a specific contextual meaning. 
And that function is not a custom diy stuff: somfy is one of the top 5 shutter brands in Europe and all of their stuff has the middle position option.

**Comment by Templarian** [comment]
I didn't read the thread, but I have that same remote for my condo's Somfy blinds. The middle button just pauses it when it's going down or up. Couldn't you just use a pause icon?

**Comment by Templarian** [comment]
`window-open-alert` or something possibly is missing.

**Comment by katonage** [comment]
> Slightly open window with a pause symbol. Not sure this really needs a specific icon.

Naturally I already have a replacement icon, but it would look much more nice and clean if there were a middle state icon for the middle state.

**Comment by GoTTi74** [comment]
Just to add my two cents. Although I think it would be neat to have different states for shutters, I understand the rationale of @goyney. Rather than making my point and arguing, I opted for creating the icons that I wanted myself and added them as custom icons to my HomeAssistant integration.

That being said, if you don't get what you want, why not helping yourself?

**Comment by katonage** [comment]
Of course life does not stops without this icon, but it seems there are a few guys seeing this a good avenue. - for the community... 

@GoTTi74 
If you happen to have the shutter-middle created, could you please share it?

**Comment by GoTTi74** [comment]
@katonage

Basically I found and followed this article. https://community.home-assistant.io/t/implement-some-custom-icons-ive-created/13884/49

If you open the shutter icons with a text editor, you can see the pattern of the Icon:
'M3 4H21V8H19V20H17V8H7V20H5V8H3V4M8 9H16V11H8V9M8 12H16V14H8V12M8 15H16V17H8V15M8 18H16V20H8V18Z'
Which is basically the 'frame' and the four dashes.

With the information from the SVG and the information from the HA community, you are able to create your own icon JS and integrate it in HA.

If not clear, I'm happy to explain more... not sure if I'm allowed to share this here... but we could continue the discussion in the HA community as it would relate to "how to integrate custom/own icons in HA".

**Comment by joshlawless** [comment]
I would like to see the suggested icon, too.  (Thankfully I read the contribution guidelines to see if my request existed already).  I agree that shutter / blinds states deserve a middle state, whereas the slippery slope argument that applies to doors and windows is not as relevant to these icons which generally apply to covers, for which positions are regularly set to a value between 0 and 100% (e.g., the Somfy or Bali autoview "home" position).

**Comment by GoTTi74** [comment]
> I would like to see the suggested icon, too. (Thankfully I read the contribution guidelines to see if my request existed already). I agree that shutter / blinds states deserve a middle state, whereas the slippery slope argument that applies to doors and windows is not as relevant to these icons which generally apply to covers, for which positions are regularly set to a value between 0 and 100% (e.g., the Somfy or Bali autoview "home" position).

Hey @joshlawless 

Although I'm with you, I don't have the time and patience to continue the discussion and that's why I decided to do it myself. Especially as this is an easy icon from an SVG point of view, the modification for a middle state icon is easily doable by everyone.

If you have a specific need (which platform you want to implement this), feel free to reach out and we might help you...

**Comment by pjator** [comment]
After reading this thread I am afraid to even propose what I would like to se. I have already solved to issue for myself.
I have a sunscript that based on temperature inside/outside and whether conditions sets the sun screens at preset values of 0, 25, 50, 75 or 100% So to increase the "wife approval factor" having an icon when you want to manually set this level in a specific room it can be difficult to understand what is half open and half closed since 25% versus 75% is just a definition if the blind is up or down at 100%. 

So I would like to add this comment that for window blinds and "sun management" it is a clear use case to be able to change icons in the intermediate steps while doors and windows don´t have the same clear function. I understand the slippery slope arguments that this would then give discussions on alot of components with variable settings. So I can fully understand if you don´t want to add more intermediate icons. 

But if you look at the picture below of my setup the icons is very suitable for intermediate steps. Now I have solved it with images instead of icons but my OCD brain hurts when since can have the same color change on these images as I have for the rest of the theme, or OK to be fair I would have to create one image for each theme which I will most likely do for the theme I have on my wall ipads. But on my phone I like to change theme from time to time and that would make these buttons bastards in my home assistant. 

I guess I could go to the Home Assistant team and complain that the icon function should be improved instead so it is easier to integrate local icons instead. But now I put my complaints here instead and hope the team will consider adding my 0%, 25%, 50%, 75% and 100% windows shutter icons since that would be very appreciated. 

Best regards

![shutter-setting](https://user-images.githubusercontent.com/79062433/120471552-21432200-c3a5-11eb-8da0-ef72850a3231.png)

**Comment by GoTTi74** [comment]
Hi @pjator 

Well written and I fully agree with your arguments.

Anyway, when you already "solved" it for yourself, why didn't you solved it with SVG icons?

This link https://community.home-assistant.io/t/implement-some-custom-icons-ive-created/13884/49 describes how you can implement your own icons. All you have to do is to create the file as described and add the data from the SVG file(s). 

Something like this:
```
	'shutter-open':
		'M3 4H21V8H19V20H17V8H7V20H5V8H3V4M8 9H16V11H8V9Z',
	'shutter-33':
		'M3 4H21V8H19V20H17V8H7V20H5V8H3V4M8 9H16V11H8V9M8 12H16V14H8V12M8',
	'shutter-66':
		'M3 4H21V8H19V20H17V8H7V20H5V8H3V4M8 9H16V11H8V9M8 12H16V14H8V12M8 15H16V17H8V15M8',
	'shutter-close':
		'M3 4H21V8H19V20H17V8H7V20H5V8H3V4M8 9H16V11H8V9M8 12H16V14H8V12M8 15H16V17H8V15M8 18H16V20H8V18Z',
```

If you look at the content of the shutter SVG file, it is really easy to make the two missing SVGs yourself.

**Comment by pjator** [comment]
Well to be honest I did not solve it that way because of my lack of knowledge. So thanks for pointing me in the right direction and I will redo my solution during the weekend based on your input.

Then I guess I can withdraw my request since there is a reasonable solution to go around this problem and I can agree the slippery slope guys wins this argument =)

Thanks @GoTTi74

**Comment by g-kiss** [comment]
See this: https://github.com/g-kiss/Home-Assistant-custom-shutter-icons

**Comment by pjator** [comment]
Thanks alot. @g-kiss will test it later this week.

**Comment by goyney** [comment]
We've once again decided to not add these variants. As previously stated, a cover item is either in an open or closed state at any given time, regardless of how far open or closed they are. Adding a mid-state also requires us to include `-alert` variants for every state across all icons we have that indicate cover and there just really isn't a need to do so.

Personally, I feel you are trying to convey too much information in a small icon. Remember that icons should be contextual and not used solely to indicate non-binary state.

If you wish to use these variants, especially in Home Assistant, it looks like there are other custom components that can help you achieve this, but this is not something we're interested in adding to the official library at this time.

Thank you all for your suggestions and constructive conversation regarding the matter.

**Comment by ideaweb** [comment]
But i dont get the argumentation. You decided not add these variants, but why such variants exists for wifi strength?

**Comment by goyney** [comment]
Because Wifi signal indication is an industry standard and is expected. This is a very niche case.
