### ISSUE TITLE
tag-price-down

### ISSUE THREAD

**Issue by erdemyilmaz06** [Templarian/MaterialDesign#5747]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![tag-price-down](https://user-images.githubusercontent.com/77012754/103673387-8fb6bc00-4f8e-11eb-923f-9492c3b50ffe.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[tag-price-down.zip](https://github.com/Templarian/MaterialDesign/files/5771469/tag-price-down.zip)

**Comment by goyney** [comment]
This doesn't convey "down" to me. It all depends on what you consider the orientation of the tag, portrait or landscape. I don't think the arrow should be inside the tag, but instead should use a cutout modifier. We have several arrow modifiers on other base icons. However, this specific icon, we have chosen to move the modifier to the left side of the icon due to its orientation.

![image](https://user-images.githubusercontent.com/1015040/104059171-7c883400-51ba-11eb-8221-3ec341861b5d.png)![image](https://user-images.githubusercontent.com/1015040/104059197-86aa3280-51ba-11eb-8834-e6210f483cfa.png)

**Comment by erdemyilmaz06** [comment]
The icons you uploaded do not represent a timeline. This icon is used for a textile has discounted price that changed between selected time period.
