### ISSUE TITLE
variable-add

### ISSUE THREAD

**Issue by clairecas** [Templarian/MaterialDesign#5749]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/9113137/103695896-65073c00-4f6b-11eb-8855-545b88493a6d.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[mdi-variable-add.svg.zip](https://github.com/Templarian/MaterialDesign/files/5772449/mdi-variable-add.svg.zip)

**Comment by goyney** [comment]
I understand the use case for this because of the variable-equals issue. However, I just don't know about the value we get for adding it. The `plus` is a standard modifier, but it's not being used in the standard modifier cutout. Doing so actually cuts away part of the "x".

![image](https://user-images.githubusercontent.com/1015040/104058632-ab51da80-51b9-11eb-832f-5a0152f0acac.png)

We also have several variants of `variable` and this modifier doesn't really work with them. 🤔 

I don't know.

**Comment by Templarian** [comment]
I'm kind of the same boat that these are probably too niche for the set.

**Comment by Templarian** [comment]
Closing this one out as too niche at this time.
