### ISSUE TITLE
script-text-play

### ISSUE THREAD

**Issue by clairecas** [Templarian/MaterialDesign#5752]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/9113137/103696188-f1b1fa00-4f6b-11eb-869f-dc70d8e71d2a.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[mdi-script-play.svg.zip](https://github.com/Templarian/MaterialDesign/files/5772464/mdi-script-play.svg.zip)

**Comment by Templarian** [comment]
This looks like a good addition 👍 

`script-text-play` for the name.

**Comment by clairecas** [comment]
awesome thanks

**Comment by goyney** [comment]
The cutout needs to be moved over, but otherwise it's good. Will get these added soon.

![image](https://user-images.githubusercontent.com/1015040/104057662-287c5000-51b8-11eb-8c87-039f75f228ed.png)![image](https://user-images.githubusercontent.com/1015040/104057642-20241500-51b8-11eb-82b3-5107ab632e7e.png)
