### ISSUE TITLE
LICENSE is quite unspecific: unclear licensing conditions and no copyright holders named

### ISSUE THREAD

**Issue by juliangilbey** [Templarian/MaterialDesign#5777]
The new license wording is:
```
# Icons: Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
Some of the icons are redistributed under the Apache 2.0 license. All other
icons are either redistributed under their respective licenses or are
distributed under the Apache 2.0 license.
```
This means that it is entirely unclear what the actual licensing conditions for any individual icon are, and there does not seem to be any way to find out this information.  The LICENSE file also does not specify who the copyright holders are.  We have a much older version of MaterialDesign in Debian, but without a clearer license, it will not be possible to update beyond v5.5.55.

Would it be possible to improve the LICENSE file?

Thanks!

**Comment by goyney** [comment]
We are discussing this internally. Our LICENSE was written with the help of legal counsel and worded this way intentionally due to the inclusion of several brand icons. I will update this issue when we know more.

**Comment by juliangilbey** [comment]
Oh wow, thank you so much!

**Comment by petergardfjall** [comment]
Any update on this?

**Comment by hoyce** [comment]
Any update on this issue? 

We have the same problem. We are interested in using this icon library but we cannot figure out which license correspond to which icon/icons.

It would be good if all icons have the same license or if you could hover an icon and clearly see its specific license.

**Comment by goyney** [comment]
We cannot release all icons under the same license because brands are the outliers.

All icons, as long as it isn't some company or product's logo, are released under Apache 2. Steer clear or brand icons, and you're good.

We're working internally on cataloging all brand icons we currently have with the intent on removing most. The others will have appropriate license information included in our v6 release. It's time consuming and we're all volunteers but we are definitely still working on it.

**Comment by hoyce** [comment]
Thanks for your quick response! I understand that you are all volunteers and I really appreciate your work. 
Although, it is important for us to fully understand the licensing due to the fact that we don't want to violate any license.

Looking forward to the v6 and keep up the good work!

**Comment by juliangilbey** [comment]
Thanks @goyney, that's very much appreciated!

Thinking about my Debian colleagues who are packaging this amazing font, it would be really helpful if you were able to have two separate fonts, one fully "free" and the other with restrictive licensing. But I realise that may well be too much work. Just a thought!

**Comment by goyney** [comment]
Honestly, if anything, this is just making a better case for use to completely remove all brand icons. There's still some pushback into do so by other contributors on that front, but we will have some renewed conversations about how we plan to tackle this in the coming days.

**Comment by goyney** [comment]
An update to this: We've deprecated all brand icons. They will be removed from this library in v8. Our license will then simply be Apache 2.0.

See the announcement here: https://github.com/Templarian/MaterialDesign/issues/6602

Because we have a plan that won't come to fruition for about a year, I'm going to close this one. Please follow the announcement for updates as we get closer to this change.
