### ISSUE TITLE
food-Outline

### ISSUE THREAD

**Issue by allanguintu** [Templarian/MaterialDesign#5811]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Use within food/restaurant/delivery services and other similar application.

## Examples

Just want and outlined version of the food icon as there are no outlined versions for the food icons in the library except for the foodapple icon.

**Comment by Xenomorph99** [comment]
You're correct, most of the [food & drink](https://materialdesignicons.com/tag/food-drink) icons in our library don't have an outlined equivalent.

Many of the [food & drink](https://materialdesignicons.com/tag/food-drink) icons have small details in order to communicate what they represent. Typically it's difficult or impossible to create outline version of icons with small details. If there's a specific one you had it mind we could spend time exploring it.

Check out this link for more information: [Material Design](https://material.io/design/iconography/system-icons.html#design-principles)

**Comment by goyney** [comment]
[![food](https://materialdesignicons.com/icon/food)](https://materialdesignicons.com/icon/food)[![food-off](https://materialdesignicons.com/icon/food-off)](https://materialdesignicons.com/icon/food-off)
[![food-outline](https://materialdesignicons.com/icon/food-outline)](https://materialdesignicons.com/icon/food-outline)[![food-off-outline](https://materialdesignicons.com/icon/food-off-outline)](https://materialdesignicons.com/icon/food-off-outline)
