### ISSUE TITLE
cargo-bike

### ISSUE THREAD

**Issue by Skywalker13** [Templarian/MaterialDesign#5832]
Hi

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It will be useful for some people like me to have a cargo-bike icon. There are already bicycles, but no cargo-bikes.

## Examples

From google:
![image](https://user-images.githubusercontent.com/397862/106636648-6b94cd80-6582-11eb-9eef-e03d082cc95e.png)

Thanks

**Comment by steodor** [comment]
Here, i gave it a shot :) not 100% satisfied but i ran out of ideas in order to make it legible at 24dp. I wonder if it's good enough though 😄 
![image](https://user-images.githubusercontent.com/4397338/107158322-ee0dfa80-6991-11eb-9bc1-cb4734c2b4d0.png)
[bike-cargo.zip](https://github.com/Templarian/MaterialDesign/files/5939877/bike-cargo.zip)

**Comment by Skywalker13** [comment]
Good start IMHO, thanks; most of time with cargo-bikes the front wheel is smaller.

For example:
![image](https://user-images.githubusercontent.com/397862/107251575-c754d000-6a34-11eb-830c-59f4c2d36f51.png)

**Comment by steodor** [comment]
The smaller front wheel bit helps quite a lot, thanks! Ok, here are another couple of tries:
![image](https://user-images.githubusercontent.com/4397338/107422625-f007c300-6b23-11eb-9c16-b9bdb18f157b.png)![image](https://user-images.githubusercontent.com/4397338/107422633-f1d18680-6b23-11eb-9e2d-e5a06dbebcae.png)
Yes, the only difference is the slanted cargo box top edge in the second one, not sure which one is better.
[bike-cargo-1-2.zip](https://github.com/Templarian/MaterialDesign/files/5954002/bike-cargo-1-2.zip)

**Comment by steodor** [comment]
And here are a couple more tries with the front wheel pushed to the right edge of the icon:
![image](https://user-images.githubusercontent.com/4397338/107424497-63aacf80-6b26-11eb-9442-c94d3a24d15a.png)![image](https://user-images.githubusercontent.com/4397338/107424502-65749300-6b26-11eb-8d30-1fb5f28dec11.png)
[bike-cargo-3-4.zip](https://github.com/Templarian/MaterialDesign/files/5954081/bike-cargo-3-4.zip)
Although honestly at this point i'm not sure whether i'm looking at a bike or a mini tractor :)

**Comment by Skywalker13** [comment]
My two cents:  
![image](https://user-images.githubusercontent.com/397862/107427196-6f47c780-6b21-11eb-87c5-49818f19979d.png)

**Comment by steodor** [comment]
Oh, not going all the way to the right with the cargo box is better. Unfortunately in 24dp there's not nearly enough width to fit all of it like you've drawn it, while maintaining the height just big enough in order to keep the icon at least barely legible. Or at least this is as far as my current skills can go on this one, if anyone else can improve on it, that would be great. Thanks!
![image](https://user-images.githubusercontent.com/4397338/107428909-f4d07500-6b2b-11eb-9636-8e2389d4ce9a.png)
[bike-cargo-5.zip](https://github.com/Templarian/MaterialDesign/files/5954270/bike-cargo-5.zip)

**Comment by Skywalker13** [comment]
Yeah, I like your last version

**Comment by goyney** [comment]
[![bicycle-cargo](https://materialdesignicons.com/icon/bicycle-cargo)](https://materialdesignicons.com/icon/bicycle-cargo)

Also, sidenote @steodor... Are you optimizing your SVGs before uploading them? Or what application are you using? I've had to recreate most of your submissions because they don't import properly. Just wondering so we can make sure you future submissions are easier to get in!

**Comment by steodor** [comment]
Hi @goyney, i'm using this little thing: https://yqnn.github.io/svg-path-editor/ because it allows me to be more precise and concise with my paths, although it lacks a lot of path manipulation functionality. Back when i made them they looked fine and the [github tools](https://dev.materialdesignicons.com/contribute/github) generated the images correctly, but now i see that the same paths don't appear at all. From what i could tell, it could be an issue with me usually ending path portions with Z instead of an actual command (i typically had multiple Z's) and/or with maybe not compacting the paths (the Minify output checkbox on that tool - when i used that, it appeared ok). Possibly something changed in the meantime which could explain the errors.

Can you confirm that if paths appear correctly in [github tools](https://dev.materialdesignicons.com/contribute/github), they should be good for importing as well? If not, you say "they don't import properly" - can you tell me where (in what software), so that i can check better next time? Thanks!

**Comment by goyney** [comment]
So, our preview generator doesn't do the optimization step; it just shows the raw path data you give it. When we import it into our library, it goes through an SVGO step to optimize and prepare for inclusion in the webfont. 

Unfortunately, this process doesn't have something the public can test with, but here's what happens when the path data you provided goes through that optimizer:
<img width="1094" alt="Screen Shot 2021-09-05 at 7 26 10 PM" src="https://user-images.githubusercontent.com/1015040/132145650-2c37390d-0a60-49ff-94b7-63e0d9f2b557.png">

We see it happen with variations from different applications that do unexpected things with the path data that doesn't translate well. I'm really not sure what we can do to make this easier and more consistent. Maybe @Templarian can chime in. I'm not sure what version of `svgo` we're using and/or if that could be updated or if that would even help. Maybe there is some other guidance we can give potential contributors to help side-step the issue. I'm not sure.

Honestly, it's not a huge deal. Maybe 15% of all icons that come in have to be remade by one of the core contributors before we add them, and sometimes it's as easy as opening them in Illustrator and resaving them (not in this case though unfortunately). I was just curious to make sure you were going through an extra step of optimizing your path data before uploading it (because that would be unnecessary 😄 ).

**Comment by steodor** [comment]
Thank you for the clarifications, indeed i see some H commands with at least very weird arguments, not sure how they ended up that way, sorry. As for better checking, since you mention using `svgo` for optimizing, i guess that if i verify my paths to load ok in something like https://jakearchibald.github.io/svgomg/ (which is based on svgo), then theoretically chances should be better for the import to run correctly. We'll have to see practically how it goes though :)

Just a thought: if the [github tool](https://dev.materialdesignicons.com/contribute/github) would run the optimizer step first, then generate the image from the optimized path (which should be displayed somewhere for copy/paste and/or downloadable as an svg file), that would ensure that all submissions are import-able by default. If there are any issues, they would be visible on the generated image and contributors could correct them before submitting. It would also greatly reduce (if not eliminate entirely) the amount of time you need to spend just correcting bugs in paths. How does that sound?
