### ISSUE TITLE
Outlined Icons! Please do Outlined version of the icons.

### ISSUE THREAD

**Issue by TarcisioMenezes** [Templarian/MaterialDesign#5833]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
I'd like to get outlined versions of some icons like floor-lamp, wall-sconce-flat, ceiling-light and pine-tree

P.S.: Why not having an outlined version for each icon? Outlined Icons are really useful. 

## Examples

Include any example images so we know what the icon should look like.
https://materialdesignicons.com/icon/lightbulb-outline
![lightbulb-outline](https://user-images.githubusercontent.com/12872368/106777667-cbcf5200-660a-11eb-9537-aa5e120929cc.png)

**Comment by goyney** [comment]
Any new icons we add, we typically add both unless an outlined version is impossible due to the design. Looking at the four you suggested, we might be able to outlined versions of each. However, you checked the box that says "only requested a single icon in this issue." Please open a separate issue for each individual icon request so we can evaluate each on its own merits.

Thank you!
