### ISSUE TITLE
Outlined version of pine-tree

### ISSUE THREAD

**Issue by TarcisioMenezes** [Templarian/MaterialDesign#5838]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
I'd like to get an outlined version of **pine-tree**.

![image](https://user-images.githubusercontent.com/12872368/106809813-c0435180-6631-11eb-8144-6549f3ecaef1.png)

## Examples

Example of an outlined icon:

![lightbulb-outline](https://user-images.githubusercontent.com/12872368/106777667-cbcf5200-660a-11eb-9537-aa5e120929cc.png)

https://materialdesignicons.com/icon/lightbulb-outline

**Comment by Xenomorph99** [comment]
Here's an idea. Not sure if I like it though.

![pine-tree-outline](https://user-images.githubusercontent.com/1837101/106829100-b4af5500-6648-11eb-8036-86d713fe0afa.png)

[pine-tree-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/5922448/pine-tree-outline.svg.zip)

**Comment by goyney** [comment]
Yeah, this one doesn't work as an outline.

**Comment by TarcisioMenezes** [comment]
I thik something like that would work. Just make all empty inside it.  :)

[image: image.png]

**Comment by Xenomorph99** [comment]
@TarcisioMenezes that's what I did in the icon I posted above just to see if it would work. Unfortunately we can't create outline versions that work of all our icons because of the guidelines we follow. Outline strokes need to be 2dps. Here's some more information: [Material Design: System Icons](https://material.io/design/iconography/system-icons.html#system-icon-metrics)

**Comment by steodor** [comment]
@Xenomorph99 i revisited that section of the material guidelines you linked to and got a few ideas you could try to apply (one and/or any combination of them) to your initial take on this icon. Please excuse my obvious lack of experience here, that's how i learn :) so, what about:
- using a 1.5dp thick outline (like their "paperclip" example)
- making stroke position `center` instead of `inside`, this way it would create more space in the middle
- setting `rounded` stroke corner type instead of straight (not a big fan of this, really) to keep the pointy ends from going too far to the sides, if needed

What do you think, anything worth testing?
