### ISSUE TITLE
home-floor-k 

### ISSUE THREAD

**Issue by liksvette** [Templarian/MaterialDesign#5892]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

There are a number of icons called home-floor-1, home-floor-2 etc. which I use in Home Assistant. There are also home-floor-b for Basement and home-floor-g for (I assume) Garage. I am requesting a home-floor-k for Kjeller (Norwegian), Källare (Swedish), Kælder (Danish), all words for basement
## Examples

home-floor-b should be a good example.

**Comment by Templarian** [comment]
@liksvette Pasted in the template above. Please fill out the Usage section above with more context... like what k means.

**Comment by liksvette** [comment]
Updated the template. Sorry for messing up.

**Comment by pbulteel** [comment]
I don't think there's a need for a "k" version if there's a version in English. Otherwise, wouldn't the whole thing be in <select language>? e.g piso-casa-s (home-floor-b in Spanish - sotano = basement)

I think localization like that isn't in scope for things that are common like a basement or window - otherwise we'd need a "ventana" icon and a "venster" icon - which would all be the same (a window in Spanish or Dutch/Flemish).

I can understand if a localised version of an icon would be so different as to make it not understandable to someone from a different country/language.

**Comment by JamesCoyle** [comment]
Unfortunately, as @pbulteel said, we can't add versions for every language. I don't really think we should even have the lettered versions we do have personally.
