### ISSUE TITLE
Shower off

### ISSUE THREAD

**Issue by flixlix** [Templarian/MaterialDesign#5901]
I would love to have an icon for shower off. The same idea as it was implemented in machine off, which is just a machine with a line crossed at a 45 degree angle.

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
