### ISSUE TITLE
Reverse Directional Icons

### ISSUE THREAD

**Issue by JamesDenby** [Templarian/MaterialDesign#5920]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I use a plethora of the icons available, but I find some are directional with no ability to select the opposite direction. This request covers all icons that face one direction, but could face two directions.

## Examples

Include any example images so we know what the icon should look like.
For example desk lamp (mdi:desk-lamp) faces to the right. In some use cases I would like it to face to the left. 
[https://iconify.design/icon-sets/mdi/desk-lamp.html](url)

Same with the outdoor lamp (mdi:outdoor-lamp). This one hangs to the right, but I would like it if it hung to the left as well.
[https://iconify.design/icon-sets/mdi/outdoor-lamp.html](url)

There are many others as well that could be offered in LEFT/RIGHT images.  mdi:air-horn, mdi:allergy, mdi:boom-gate, mdi:cart, and many, many others.

Thank you for reading.

**Comment by goyney** [comment]
This is something your application will need to implement. We don't want to arbitrarily add mirrored version of all icons because it becomes hard to maintain and explodes the size of the library unnecessarily.

Using the web font, you can use the `mdi-flip-h` and `mdi-flip-v` classes. Using something like [`@mdi/react`](https://www.npmjs.com/package/@mdi/react), you can use the `horizontal` or `vertical` props. Any other use of the icons will require you to determine how to do the flip yourself.
