### ISSUE TITLE
border-radius & margin & padding in css

### ISSUE THREAD

**Issue by xinnai** [Templarian/MaterialDesign#5932]
I need more css icons like border-radius(like  top-left corner, top-right corner , bottom-left corner and so on...)
Now I can only find `rounded-corner`, and margin or padding cannot be found.

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
