### ISSUE TITLE
coach-lamp : request modification to existing icon

### ISSUE THREAD

**Issue by skilletjohn** [Templarian/MaterialDesign#5936]
Request that the wall mount be removed from the existing coach-lamp icon and a vertical line (wire, chain) be add to make a hanging coach lamp style available.

Thanks for your consideration!
Home Assistant User

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.
