### ISSUE TITLE
Half-Dome Light

### ISSUE THREAD

**Issue by Warter21** [Templarian/MaterialDesign#5960]
![41OXgn4KABL _AC_SL1000_](https://user-images.githubusercontent.com/12511189/116862630-583ae200-ac05-11eb-9cf6-78d88ecdfdc7.jpg)

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.

---

As for your request, it already exists.

[![wall-sconce-round](https://materialdesignicons.com/icon/wall-sconce-round)](https://materialdesignicons.com/icon/wall-sconce-round)
