### ISSUE TITLE
Water, gas and electricity meters

### ISSUE THREAD

**Issue by HouseOnTheHill** [Templarian/MaterialDesign#5964]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To provide feedback on usage of utilities such as water, gas and electricity.

## Examples

![image](https://user-images.githubusercontent.com/65644386/117085270-a4fcf500-ad8c-11eb-924b-d9ca813713bb.png)

**Comment by goyney** [comment]
I know why these are being requested. Home Assistant's new Energy dashboard is giving people direct insights to their energy and environmental impact, so I want to be able to support that effort because I believe it's awesome.

However, there is way too much detail in each of these to be able to depict these in a small icon. However, I want to make sure we have other options available for these integrations.

We currently have 3 standalone icons for electricity, water, and gas:

[![flash](https://materialdesignicons.com/icon/flash)](https://materialdesignicons.com/icon/flash)[![water](https://materialdesignicons.com/icon/water)](https://materialdesignicons.com/icon/water)[![fire](https://materialdesignicons.com/icon/fire)](https://materialdesignicons.com/icon/fire)

We also already have `flash-circle`. I've added the other two:

[![flash-circle](https://materialdesignicons.com/icon/flash-circle)](https://materialdesignicons.com/icon/flash-circle)[![water-circle](https://materialdesignicons.com/icon/water-circle)](https://materialdesignicons.com/icon/water-circle)[![fire-circle](https://materialdesignicons.com/icon/fire-circle)](https://materialdesignicons.com/icon/fire-circle)

These feel a bit more contained and "appliance-like." Hopefully, the suit your needs.

Lastly, there is always `counter`.

[![counter](https://materialdesignicons.com/icon/counter)](https://materialdesignicons.com/icon/counter)

Anything else would be too complex for the small artboard we have to work with.

**Comment by goyney** [comment]
> Can we reduce the detail (a lot)?

I spent a good hour trying to make the `counter` work with the 3 icons above to no acceptable avail. If someone else would like to try and post here, we can reopen for further consideration.

> Or maybe a generic meter that can be used for all the utilities.

That would be the opposite of what this issue is about. A generic meter used for all three wouldn't differentiate between them at all. However, if you want to go that route, we do have `water-boiler`, which might suit your needs.

[![water-boiler](https://materialdesignicons.com/icon/water-boiler)](https://materialdesignicons.com/icon/water-boiler)

**Comment by goyney** [comment]
Google has added icons for gas and electric meters. We've added them.

[![meter-gas](https://materialdesignicons.com/icon/meter-gas)](https://materialdesignicons.com/icon/meter-gas)[![meter-gas-outline](https://materialdesignicons.com/icon/meter-gas-outline)](https://materialdesignicons.com/icon/meter-gas-outline)
[![meter-electric](https://materialdesignicons.com/icon/meter-electric)](https://materialdesignicons.com/icon/meter-electric)[![meter-electric-outline](https://materialdesignicons.com/icon/meter-electric-outline)](https://materialdesignicons.com/icon/meter-electric-outline)
