### ISSUE TITLE
JSON5

### ISSUE THREAD

**Issue by therselman** [Templarian/MaterialDesign#5991]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

JSON5 = JSON for Humans

The JSON5 Data Interchange Format (JSON5) is a superset of JSON that aims to alleviate some of the limitations of JSON by expanding its syntax to include some productions from ECMAScript 5.1.

## Example Icons

https://icon-icons.com/icon/file-type-json5/130501

## JSON5 Homepage

https://json5.org/

## JSON5 VS Code Extension

https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-json5

**Comment by goyney** [comment]
This is way too specific, IMO. At a high level, JSON5 is just JSON and we already can support that use case. Additionally, this can't be considered a brand icon because JSON5 itself doesn't have an identifiable logo in any official capacity. We're gonna say no to this for now. If JSON5 ever becomes branded, we may consider it then as it is related to development.

Thanks for your suggestion.
