### ISSUE TITLE
Icon Request - Top Hat

### ISSUE THREAD

**Issue by dlc3172** [Templarian/MaterialDesign#6018]
You know, like Abe Lincoln wore...

**Comment by Templarian** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.

**Comment by dlc3172** [comment]
I think a "top hat" is relatively self explanatory.
