### ISSUE TITLE
map marker with video camera

### ISSUE THREAD

**Issue by Siedlerchr** [Templarian/MaterialDesign#6023]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The icon will be used to show and to position the  camera position of an UAV.
This would be really cool to have!
## Examples

Similar to this, but with a video camera symbol
<img width="468" alt="grafik" src="https://user-images.githubusercontent.com/320228/121521229-18c99780-c9f4-11eb-8c66-a0c53ebe943a.png">

**Comment by Siedlerchr** [comment]
@erdemyilmaz06  Thanks for taking a look at this :) I think the top left under Yes would be fitting best as it's about a video camera of the uav.

**Comment by Simran-B** [comment]
The marker cannot be placed in the standard location in the bottom right because it would overlap the video camera too much. Even moving the camera up doesn't help all that much:

![image](https://user-images.githubusercontent.com/7819991/137166102-6af63928-c5d9-41dd-a49d-e8ffa250eb3b.png) ![image](https://user-images.githubusercontent.com/7819991/137166174-f8d4b13f-f160-4e4f-a930-8eaa5da91f0c.png)

Using the bottom left instead works:

![image](https://user-images.githubusercontent.com/7819991/137164473-de8489b7-37fc-4642-9951-6d41ec761625.png) ![image](https://user-images.githubusercontent.com/7819991/137165288-4b5613e1-29e4-49d6-a8c9-7aba0f24f235.png)

Camera works, even though the outline variant looks a little odd:

![image](https://user-images.githubusercontent.com/7819991/137165352-6b7830f1-2e78-4f24-ac3d-3d2141742363.png) ![image](https://user-images.githubusercontent.com/7819991/137165209-e325b03d-d848-4928-9d26-c5c6a9bae580.png)

CCTV doesn't really work IMO:

![image](https://user-images.githubusercontent.com/7819991/137166055-c535a802-766b-4ca4-b3b8-8443af891334.png)

[cam-marker.zip](https://github.com/Templarian/MaterialDesign/files/7339623/cam-marker.zip)

**Comment by goyney** [comment]
[![video-marker](https://materialdesignicons.com/icon/video-marker)](https://materialdesignicons.com/icon/video-marker)[![video-marker-outline](https://materialdesignicons.com/icon/video-marker-outline)](https://materialdesignicons.com/icon/video-marker-outline)
[![camera-marker](https://materialdesignicons.com/icon/camera-marker)](https://materialdesignicons.com/icon/camera-marker)[![camera-marker-outline](https://materialdesignicons.com/icon/camera-marker-outline)](https://materialdesignicons.com/icon/camera-marker-outline)
