### ISSUE TITLE
electric vehicles connectors

### ISSUE THREAD

**Issue by maidiries** [Templarian/MaterialDesign#6082]
Here all types:
https://www.mobilityhouse.com/int_en/knowledge-center/charging-cable-and-plug-types

Most important:
Type 1, Type 2, CHAdeMO, CCS and Tesla

**Comment by goyney** [comment]
First:

**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.

--

Second:

[These](https://materialdesignicons.com/icon/ev-plug-type1) [all](https://materialdesignicons.com/icon/ev-plug-type2) [already](https://materialdesignicons.com/icon/ev-plug-chademo) [exist](https://materialdesignicons.com/icon/ev-plug-ccs1). [Please](https://materialdesignicons.com/icon/ev-plug-ccs2) [search](https://materialdesignicons.com/icon/ev-plug-tesla).
