### ISSUE TITLE
tag-search and tag-search-outline

### ISSUE THREAD

**Issue by gdang** [Templarian/MaterialDesign#6132]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A button with the label `Search Tags` or a search box with the icon on the left side.

## Examples

Like the other `tag-*` icons but with a magnifying glass.

**Comment by goyney** [comment]
This one is going to very difficult to pull off because of the angles of both the magnifying glass and the tag. Here are some attempts.

Smaller than normal magnifying glass, inset. Don't think it works:
![image](https://user-images.githubusercontent.com/1015040/132067456-cb99524e-9793-45ad-837e-896f8a7ba3a9.png)![image](https://user-images.githubusercontent.com/1015040/132067471-04eb062d-e04d-4a8d-980d-6706a043eb1a.png)

Smaller than normal cut-out. It's okay, I suppose:
![image](https://user-images.githubusercontent.com/1015040/132067665-ea9700b2-00c1-4788-81b1-2322bcf19ecd.png)![image](https://user-images.githubusercontent.com/1015040/132067691-477415ec-be26-4c48-96e0-dff5e1070b07.png)

Some other ways I hate:
![image](https://user-images.githubusercontent.com/1015040/132067884-0cf4c1fc-7d6d-4dee-9e49-be75ce60bddb.png)![image](https://user-images.githubusercontent.com/1015040/132067898-e313decc-9fc1-4181-962d-b5dadd1625b6.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7108611/Archive.zip)

**Comment by gdang** [comment]
I like the second one. 👍

**Comment by goyney** [comment]
Added the second variant.
