### ISSUE TITLE
mdi-telegram disappeared

### ISSUE THREAD

**Issue by 4dcode** [Templarian/MaterialDesign#6178]
### What is your question?

Hi,

May I ask what the mdi-telegram icon suddenly has disappeared?
This will affect many apps/users/devs

Kind regards,

Martin

**Comment by Belzebuth68** [comment]
Linked to issue [5275](https://github.com/Templarian/MaterialDesign/issues/5275).
Brand icon are no longer supported, you need to use [SimpleIcons](https://simpleicons.org/) for that.

**Comment by 4dcode** [comment]
Really....
md-twitter
md-reddit
mdi-discord 

are still there ??

**Comment by goyney** [comment]
Yes. We're slowly working through brand icons and working on their fate in MDI.

Brand Icons are inherently NOT Material and likely shouldn't have been included in the first place. However, since the library started as a shadow of Google's own offering, it turned into a sort of slippery slope and now too many people rely on them. Brands also complicate our license, which has caused bigger issues for people.

We recommend using [Simple Icons](www.simpleicons.org) for brands moving forward, even for ones we currently have. They are dedicated only to brand icons, where we want our focus to be on system icons. We cannot guarantee any current brand icons will stay in this library in the future, so please make sure to watch our changelog, especially around major version releases.

And of course, simply just use Simple Icons for your brands and never worry about them again.

**Comment by 4dcode** [comment]
Ok thanks for your swift response. Issue can be closed.
