### ISSUE TITLE
Organize Icons into Categories

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#618]
Sort icons into categories similar to how the stock google icons organize their icons.

If anyone has any ideas of the best way to do this let me know. Right now we have tagging support, but most icons do not have tags assigned, it is a very manual process.

**Comment by CoDEmanX** [comment]
My recommendation: do not do it the Google way!

Identical icons appear under different names in multiple categories, and they also duplicate them in the icons repo. Total BS.

Mono-hierarchical categories won't really work without duplication, thus you should go for poly-hierarchies. It could be implemented like tags. Then loop through all categories and show all icons that have that category's tag (icons may appear in multiple categories).

These category tags should be completely separated from icon tags and aliases. I would also consider to add additional info to categories, like parent groups. Something like *Google > Action*, *Google > Device*, so that Google categories can be distinguished from let's say MDI categories. An MDI category could be *Circle*, another *Outline* etc. Maybe even go a step further and allow for something like *MDI > Geometric base shapes > Circle*.

How to display and make all that info available to the user is a different story... What would be awesome: a single search box, which queries icon names, alias and tags (like it is), but also suggest categories below the input field, which the user can click to display icons contained in that category instead. A graph that visulizes the category structure would be super helpful in a sidebar I guess.

**Comment by SolusSoftworks** [comment]
As a starting point, I'd suggest having some sort of variant system where similar icons are grouped together. For example all of the battery icons could be grouped into one 'super-icon' that when clicked on shows all of the variants. That would really reduce the number of icons to look through. 

Then, instead of the current tag system it would be nicer to have some sort of filter system. This would require a lot of thought so I won't go into too much detail at this point. My thought would be to have a sidebar containing lists of checkboxes to filter icons based on tags in a similar fashion to [PCPartPicker](http://uk.pcpartpicker.com/parts/cpu/). 

Some features which would be nice: the ability to show only google or community icons, ability to view only icons with square/circle variants, ability to show certain categories such as form elements/mobile UI/social networks something like: 

Filters
---
Search box

Author
--
- All
- Google
- Community 
- More link which shows individual contributors

Style
--
- All
- Circle
- Square

Category
---
- All
- Form elements
- Phone icons
- Social icons
- UI elements
- Game pieces
- Emoticons
- Arrows
- Transportation

Apologies for the poor formatting.
