### ISSUE TITLE
Icon Request: 360 image / Panorama variants

### ISSUE THREAD

**Issue by tmy-sr** [Templarian/MaterialDesign#6206]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

360 image, can be use for a form to upload 360 image data. 
and also a button to show 360 image. 

### Give us an example of what this icon might look like.

https://fonts.google.com/icons?icon.query=360
but please with [360]

**Comment by goyney** [comment]
We currently have `axis-z-rotate-counterclockwise` and `axis-z-rotate-clockwise`. Would either of those work?

[![axis-z-rotate-counterclockwise](https://materialdesignicons.com/icon/axis-z-rotate-counterclockwise)](https://materialdesignicons.com/icon/axis-z-rotate-counterclockwise)[![axis-z-rotate-clockwise](https://materialdesignicons.com/icon/axis-z-rotate-clockwise)](https://materialdesignicons.com/icon/axis-z-rotate-clockwise)

**Comment by goyney** [comment]
Actually, this issue gave me the opportunity to look at several Google icons that might fit your use case. So, I've added the one you requested, plus all of the following:

[![rotate-360](https://materialdesignicons.com/icon/rotate-360)](https://materialdesignicons.com/icon/rotate-360)[![panorama-outline](https://materialdesignicons.com/icon/panorama-outline)](https://materialdesignicons.com/icon/panorama-outline)

[![panorama-variant](https://materialdesignicons.com/icon/panorama-variant)](https://materialdesignicons.com/icon/panorama-variant)[![panorama-variant-outline](https://materialdesignicons.com/icon/panorama-variant-outline)](https://materialdesignicons.com/icon/panorama-variant-outline)

[![panorama-sphere](https://materialdesignicons.com/icon/panorama-sphere)](https://materialdesignicons.com/icon/panorama-sphere)[![panorama-sphere-outline](https://materialdesignicons.com/icon/panorama-sphere-outline)](https://materialdesignicons.com/icon/panorama-sphere-outline)

I've also opened https://github.com/Templarian/MaterialDesign/issues/6207 to complete the base `panorama` set with proper filled/outlined versions. That will happen in `v7` since it's a breaking change.
