### ISSUE TITLE
Poor rendering on Microsoft Edge/IE11

### ISSUE THREAD

**Issue by calebeaires** [Templarian/MaterialDesign#626]
Take a look at this comparative SVG rendering:

![captura-svg](https://cloud.githubusercontent.com/assets/794195/9428045/9bdabbfe-4971-11e5-802a-6bb1a76d6c1d.PNG)

Using md-icon on Material Angular 
https://material.angularjs.org/HEAD/#/

**Comment by CoDEmanX** [comment]
Looks like they were slightly scaled up? Make sure they are 24x24 pixels.

**Comment by Templarian** [comment]
I'm looking at the two Edge vs Chrome and they look exactly the same. I think you may have an issue in your CSS.

http://cdn.materialdesignicons.com/1.2.64/ Open in Chrome / Edge to compare.

Going to close this out assuming it is just a CSS issue.

**Comment by calebeaires** [comment]
Take a look on both browser side by side

![cap-4](https://cloud.githubusercontent.com/assets/794195/9429552/6a76fab2-49aa-11e5-87b2-75622f445ce2.PNG)

**Comment by Templarian** [comment]
You're right odd... I had to move my 4k displays back to 1:1 from 150%. I'm not sure how to fix that one since it's part of the font rendering engine ([read more](https://css-tricks.com/icon-fonts-vs-svg/)).

On high dpi displays which are becoming more common it will be fine. You can still always use inline SVG which will always render cleanly on 1:1.

![image](https://cloud.githubusercontent.com/assets/338885/9429592/3066eaee-499b-11e5-992f-be48ca3ccaa1.png)

**Comment by CoDEmanX** [comment]
You should try some of the font related CSS settings. I believe they are a little vendor specific, but maybe there's a way to favor legibility over performance.
Also make sure nothing scales the SVG, e.g. zoom property (ie only?! Can't remember... ), or rather font. I guess you should set font-size: 24px, instead of another unit like pt. Or might dp work too? Either way, it should be pixel-based.
Maybe there's a bug in edge (saw some posts about blurry text), or there's a problem that font sizes are converted to another internally used unit with insufficient precision...
