### ISSUE TITLE
file-document-remove

### ISSUE THREAD

**Issue by severinbeauvais** [Templarian/MaterialDesign#6261]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

This icon would be used alongside an action button to indicate to the user that they are removing/destroying something related to documents, for example, dissolving a company in a corporate registry.

### Give us an example of what this icon might look like.

SVG example:

![image](https://user-images.githubusercontent.com/10002889/138332119-1b95e9d9-b761-4dd9-a8e6-f19e1dc1302e.png)

**Comment by severinbeauvais** [comment]
Thanks for your comment.

The sample SVG icon shows that there is space if you add the X to bottom right of the file-document base icon.

**Comment by Simran-B** [comment]
![image](https://user-images.githubusercontent.com/7819991/139959838-a810d331-395f-459b-8438-8642ca9d4c0e.png) ![image](https://user-images.githubusercontent.com/7819991/139960031-aa028a10-cecb-4a56-a18b-e5804d2f636e.png)

I also included `file-` and `file-document-` icons with the new standard `plus`, `minus`, `remove`, `check`, and `alert` modifiers (the latter in two variants because I'm not sure about the placement on canvas). Do we want to update the existing icons?

[file-document.zip](https://github.com/Templarian/MaterialDesign/files/7464390/file-document.zip)

![image](https://user-images.githubusercontent.com/7819991/139962287-4d6981d5-a8bb-44c4-980c-ed612abc9281.png)
![image](https://user-images.githubusercontent.com/7819991/139962324-c0b92a15-8f02-414f-957c-b4506d19df3a.png)
![image](https://user-images.githubusercontent.com/7819991/139962368-b5f20db7-59fa-4f13-bba1-606f251bf9a4.png)
![image](https://user-images.githubusercontent.com/7819991/139962383-5aeb8287-dac0-42cf-8000-fa58cf2ab267.png)
![image](https://user-images.githubusercontent.com/7819991/139962420-183821c5-ae80-4afe-aec6-1d60d5350dfd.png)
![image](https://user-images.githubusercontent.com/7819991/139962446-3370329d-7d0a-43c0-b641-7591f0def142.png)
![image](https://user-images.githubusercontent.com/7819991/139962484-6c4ebb61-3611-4233-9c0a-0f6f4aff477d.png)
![image](https://user-images.githubusercontent.com/7819991/139962579-f1d4800c-922c-4650-a6e5-c72d5f90b71d.png)
![image](https://user-images.githubusercontent.com/7819991/139962648-88dbfba5-d37f-48ff-b245-624c4e808a90.png)
![image](https://user-images.githubusercontent.com/7819991/139962677-8ef6ed29-ed4a-4377-915c-921b9295463f.png)
![image](https://user-images.githubusercontent.com/7819991/139962696-1abbafa1-c6dc-42c6-8848-254399b2ef64.png)
![image](https://user-images.githubusercontent.com/7819991/139962719-658a4c27-0fa1-4048-9e5a-5f4943beb447.png)
![image](https://user-images.githubusercontent.com/7819991/139962769-d6092a5b-6eb2-4955-abea-7bee3af3156a.png)
![image](https://user-images.githubusercontent.com/7819991/139962797-5025013e-bef8-49f7-a845-2c9dfea4795b.png)
![image](https://user-images.githubusercontent.com/7819991/139962823-fdba032b-6f3a-49f8-9b40-49edf2667400.png)
![image](https://user-images.githubusercontent.com/7819991/139962840-289be0c6-f78f-4a17-91f3-728b3be00ae1.png)
![image](https://user-images.githubusercontent.com/7819991/139963258-17383106-2135-48bd-b3c0-8afb6d2cc3ac.png)
![image](https://user-images.githubusercontent.com/7819991/139963328-c12ee66a-8c7c-4813-8bdc-db1a597c7ea7.png)
![image](https://user-images.githubusercontent.com/7819991/139963519-56df4c80-c623-4014-97f0-d660d9a0aaa4.png)
![image](https://user-images.githubusercontent.com/7819991/139963543-19edc97c-9830-46c1-885e-2a2c7e877ac6.png)

**Comment by goyney** [comment]
Icons updated and added.
