### ISSUE TITLE
"Install Mobile" and "Install Desktop"

### ISSUE THREAD

**Issue by TomWyllie** [Templarian/MaterialDesign#6290]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In Chrome, navigating to a website that supports installation as a web app (for example [youtube](youtube.com)) displays an icon next to the "favourite" button in the URL bar which installs that page as a PWA. In the menu on Chrome mobile there is a button with the same functionality but a mobile version of the icon. I have found both of these icons as "install desktop" and "install mobile" on [Google's material icons](https://fonts.google.com/icons?selected=Material+Icons&icon.query=install) but could not find either icon, or even a suitable substitute, in this project. 

I'm already using many icons from this project to host a web app and would like to improve user engagement by directing them towards clicking these icons to installing the web app.

### Give us an example of what this icon might look like.

Google already has provided these icons, they just appear to be missing from this repo (unless I've missed them somehow?): [https://fonts.google.com/icons?selected=Material+Icons&icon.query=install](https://fonts.google.com/icons?selected=Material+Icons&icon.query=install)

**Comment by Templarian** [comment]
That's weird they use the `television` icon instead of `monitor` for the install on desktop icon. 🙃  We should probably use monitor instead.

We wait until someone requests an icon to add them. Not all of Google's icons get synced in.

**Comment by goyney** [comment]
Yeah, Google is kind of all over the place here, so they don't get credit for any of these. 😆 

They aren't using the base cellphone, so I've modified it to do so:
[![cellphone-arrow-down-variant](https://materialdesignicons.com/icon/cellphone-arrow-down-variant)](https://materialdesignicons.com/icon/cellphone-arrow-down-variant)

They are using `television` as the base, instead of `monitor`, so I've modified it to do so:
[![monitor-arrow-down-variant](https://materialdesignicons.com/icon/monitor-arrow-down-variant)](https://materialdesignicons.com/icon/monitor-arrow-down-variant)

We didn't have `monitor-arrow-down`, so I added it to match `cellphone-arrow-down` and kept naming appropriate between the two:
[![cellphone-arrow-down](https://materialdesignicons.com/icon/cellphone-arrow-down)](https://materialdesignicons.com/icon/cellphone-arrow-down)[![monitor-arrow-down](https://materialdesignicons.com/icon/monitor-arrow-down)](https://materialdesignicons.com/icon/monitor-arrow-down)
