### ISSUE TITLE
Add pets icon from material design icon set

### ISSUE THREAD

**Issue by japayne27** [Templarian/MaterialDesign#6329]
### What is your question?

Is it possible to add the pet icon from the official material design set?

The current "paw" icon is a "community" icon and different to the one in all the material design libraries for Figma and the official material design icons themselves. This library is great apart from this one issue!

I think just adding a "pets" icon and keeping the "paw" set would be fine?

Here's the difference between the two icons, Material pets icon in black, this library's paw icon in red:
![paw-vs-pets](https://user-images.githubusercontent.com/8763539/141834728-74d1a0e9-3ba6-4989-9277-b57587705175.png)

Link to the Material icon: https://fonts.google.com/icons?selected=Material%20Icons%3Apets%3A

**Comment by goyney** [comment]
There are a lot of icons from the Google set that we do not include because we have our own versions. Just because they are not a 1:1 match does not make them not Material. We are a community icon set that follows Material guidelines and Google happens to also make Material icons we sometimes include when requested.

That being said, we are not opposed to updating icons if there is good reason to. In this case, I don't really see a reason to change ours. However, I will give the other contributors opportunity to chime in and cast a vote before we decide to take action.

**Comment by Templarian** [comment]
This one I'm not really sure works as well with the circle toes. The spacing and shape was tweaked a bit I think to allow for outline to work.

**Comment by goyney** [comment]
Agreed. Good point on the outlined version.

Thanks for the suggestion, but we are going to keep our version.
