### ISSUE TITLE
Vue component package

### ISSUE THREAD

**Issue by Propaganistas** [Templarian/MaterialDesign#6334]
### What is your question?

Hi

Thank you for this vast icon library. I've been using it in numerous projects with great joy.

This is sort of a feature request, but in terms of the available package formats.

The `Vue` and `React` way for using the icons is currently put forward as importing the path data (from `@mdi/js`) and then inserting it using a dynamic binding. Here's a Vue example:

```vue
<template>
    <svg :path="mdiAbTesting" />
</template>

<script>
import { mdiAbTesting } from '@mdi/js'

export default {
    data() {
        return { mdiAbTesting }
    }
}
</script>
```

Of course this works just fine. Yet I find it rather cumbersome to define SVG paths as component properties.

I've stumbled upon a rather exciting, less boilerplating way in the [Heroicons](https://github.com/tailwindlabs/heroicons) library. Basically icons are provided as a native Vue/React component:

```vue
<template>
    <AbTestingIcon />
</template>

<script>
import { AbTestingIcon } from '@mdi/vue'

export default {
    components: { AbTestingIcon }
}
```

I have to admit, I absolutely love this way of working. All icons are directly accessible as a Vue component while everything remains tree-shakeable.

Now here's the question:

I've created a [repository ](https://github.com/Propaganistas/mdi-vue) implementing the very same principle for use in my projects (only for Vue, but I could extend it to React as well).
I would be happy to lift this to the mdi organization. Is this something you're interested in?

Open question, if not, no problem of course!

**Comment by goyney** [comment]
Nice work and creating something you find useful!

We purposely do not do this because our tools are meant to be universal to all our libraries. Material Design Icons isn't our only library of icons and instead of maintaining implementation details on every icon in each package, we export the raw path data and allow you to inject them directly into our library-specific packages.

This actually provides more flexibility. If we don't have an icon you need, you can hard-code any path data and continue to use our packages. For example:

```js
import Icon from '@mdi/react';

const mySpecialIcon = 'M...Z';

<Icon path={mySpecialIcon} />
```

Additionally, our tools work with other icon packs, such as [Simple Icons](https://simpleicons.org/). This allows the use of our library-specific packages and a wide variety of icon sources.

```js
import Icon from '@mdi/react';
import google from 'simple-icons/icons/google';

<Icon path={google.path} />
```

We appreciate the offer to hoist your work to first-party status, however we have carefully designed this as our approach and don't wish to add another way to do the same thing officially.

**Comment by Templarian** [comment]
@Propaganistas This exists for React... https://www.npmjs.com/package/mdi-react and this approach is very popular with their community. ❤️ It has nearly half the downloads of our `@mdi/react` component.

James wrote our `@mdi/react` equivalent for Vue. Just haven't had time to move it under `@mdi/*`. https://dev.materialdesignicons.com/getting-started/vuejs

**Comment by Propaganistas** [comment]
Hi @Templarian 

thanks for hopping in. Be careful though: the documentation you're referring to for Vue is not similar to the React reference.

mdi/react uses the approach put forward in this ticket: exporting every single icon as a self-container framework component. James' Vue repository provides a generic Icon component that still needs a path.

**Comment by Templarian** [comment]
@Propaganistas I was linking James' as a good starting point as it handles all accessibility concerns and I think Typescript for the general component. Yours would look like the third party `mdi-react`, but the same accessibility concerns apply.

A lot of work went into these components for accessibility.

**Comment by Propaganistas** [comment]
Just for further reference, I've cleaned up everything and made the repo self-updating to automatically stay on par with mdi releases.

https://github.com/Propaganistas/mdi-vue3/tree/master/dist

It's published on npm as `mdi-vue3`.
