### ISSUE TITLE
Add or Plus Icon

### ISSUE THREAD

**Issue by alexsalas** [Templarian/MaterialDesign#637]

**Comment by Templarian** [comment]
These already exist stock google icons.

[![plus](https://materialdesignicons.com/icon/plus)](https://materialdesignicons.com/icon/plus) [![plus-box](https://materialdesignicons.com/icon/plus-box)](https://materialdesignicons.com/icon/plus-box) [![plus-circle](https://materialdesignicons.com/icon/plus-circle)](https://materialdesignicons.com/icon/plus-circle) etc... (there are a few variations)

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/plus
plus many more variants... what exactly are you looking for?

**Comment by alexsalas** [comment]
Thank you. :+1:  Yes, It is.

**Comment by Templarian** [comment]
@alexsalas UX question to improve the site (currently doing a recode for some enhancements).

What steps did you perform to try and find the icon prior to opening the issue?

**Comment by alexsalas** [comment]
We need a tool  to write and find faster. I need  walk with my eyes.

**Comment by Templarian** [comment]
Is the search too slow? https://materialdesignicons.com/ I've been thinking of trying to optimize it a bit, it's mostly due to the SVG rendering calls. Will definitely look into it (it was faster when the site only had a couple hundred icons.

I'll work on getting the rendering faster after these next changes go out.
