### ISSUE TITLE
Material Design Icon not working in CSS pseudo code

### ISSUE THREAD

**Issue by conradreisch** [Templarian/MaterialDesign#6390]
### Where are you experiencing this bug?

@mdi/font

### What is the issue you are experiencing?

I have trouble to use @mdi/font in a react app with typescript and sass.

Situation:
- created an empty react app with npx
- removed unnecessary content (test, css files, etc.)
- installed @mdi/font
- installed sass and imported @mdi/font

Behaviour:
- using mdi in className is working
- using mdi in css pseudo code is not working (see [git repo with issue](https://github.com/conradreisch/mdi-font-issue))

Can someone please provide me with advice on how to get the pseudo code working?

**Comment by conradreisch** [comment]
Btw.. I'm using node 16

Here is also a screenshot from Firefox:
![mdi-font-issue](https://user-images.githubusercontent.com/40696850/147827776-9f0c33b5-d935-4f01-a90a-b09c4198ad66.png)

**Comment by Templarian** [comment]
@conradreisch You're using 6.5.95, so the `\F140` codepoint isn't defined. Since you're importing `@mdi/font` you can use the variables also. From: https://github.com/Templarian/MaterialDesign-Webfont/blob/master/scss/_variables.scss#L1590

https://pictogrammers.github.io/@mdi/font/6.5.95/ -> `F0140` is the correct codepoint.

Please let me know if that fixes your issue.

**Comment by conradreisch** [comment]
@Templarian Thanks a lot for the quick reply. I was actually looking up the font today. However, I use an older theme and I did not recognize the addtional "0".
That fixes my issue. Have a great start into 2022!
