### ISSUE TITLE
Add PDF file icons without brand logo

### ISSUE THREAD

**Issue by ypresto** [Templarian/MaterialDesign#6399]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

PDF icons are removed and replaced in #5797 as it was containing brand logo.
But removed icons have consistent with other file icons like word file, and still we need it.
Also, replaced box icon has smaller outline than original brand logo one.

So I created new replacement icons consistent with other icons.

![MDI PDF File Icons](https://user-images.githubusercontent.com/400558/148478037-77f8089b-350b-4f35-888e-c2611f4854e7.png)

I noticed that icons are removed when upgrading npm package.
Adding these icons with the same file names as original removed icons can help other people upgrade seamlessly.

Related: #6185

### Share a preview of your contribution.

![file-pdf](https://user-images.githubusercontent.com/400558/148476805-4cb74d62-f9a0-4eda-8e13-a79c3147040b.png)

![file-pdf-outline](https://user-images.githubusercontent.com/400558/148476772-38ecdda7-b97a-4fb7-a3f8-8e8686079c9b.png)

![file-pdf-box](https://user-images.githubusercontent.com/400558/148475667-0cca0e5e-5f12-42ad-972d-4cf2d739a61d.png)

![file-pdf-box-outline](https://user-images.githubusercontent.com/400558/148476835-64647abb-e3e9-403e-a6c6-630928a53c79.png)

### Upload the icon source.

[file-pdf-ypresto.zip](https://github.com/Templarian/MaterialDesign/files/7825695/file-pdf-ypresto.zip)

**Comment by goyney** [comment]
The PDF does not fit within the `file` base, so that will not work. The letters are complex enough; they must remain on the grid. The shrinking to make it fit within the `file` icon isn't acceptable, and the outline variation is obviously not as well.

Trying to fit it within `file-box-outline` also does not work, however [there was a proposal](https://github.com/Templarian/MaterialDesign/issues/6181) to expand all out `file-box` icons to be able to fit other 3 letter extensions. The general consensus, however, was that we don't need these types of icons so no official decision was made there.

`file-pdf-box` exists for a reason. If we expand the box size in #6181, an outline version will appear as well. As it stands, there's nothing to do in this request.

Thanks for your suggestion.

**Comment by ypresto** [comment]
> They must remain on the grid. The shrinking to make it fit within the file icon isn't acceptable

No, I did not shrink nor change pixel alignment from original `file-pdf-box` icon. I just copied path of "PDF" letters from it. For a reference, below preview shows how "PDF" letters are aligned on the pixels in the original icon.

![image](https://user-images.githubusercontent.com/400558/152440049-aac73cd8-ab86-4e5a-b862-2fc4d7cf518a.png)

But obviously it does not fit to `file-*-outline` without a notch in border.
