### ISSUE TITLE
Irrigation icons

### ISSUE THREAD

**Issue by Eckart0** [Templarian/MaterialDesign#6427]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I have the need for irrigation and gardening icons: Sprinklers on/off, irrigation working/off, plants dry/wet, lawnmower parking/mowing
I didn't find icons about that.
Regards, Eckart

### Give us an example of what this icon might look like.

I Don't have good ideas

**Comment by goyney** [comment]
Sprinklers:
- We have `sprinkler`, `sprinkler-variant`, and `sprinkler-fire`. #5881 exists for adding off variants.

Irrigation:
- This seems to be very similar to sprinklers. However, we have things like `water-pump`.

Plants:
- We have several `flower` icons as well as `sprout`.  Adding specific wet/dry variations to these seems a bit niche.
- We have plenty of `water` related icons, including `watering-can`.

Lawnmower:
- We have `mower`, `mower-bag`, and `robot-mower`.

All-in-all, we have many irrigation, agricultural-type icons. Since we have many cases covered, I'm going to close this. If there are specific icons we are missing, please open a new request, one per icon, with examples of what you need and what it might look like.

Thanks for the suggestions.
