### ISSUE TITLE
Ramp for brightness

### ISSUE THREAD

**Issue by Ynjxsjmh** [Templarian/MaterialDesign#6433]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [x] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

There are three circle like and four sun like icons for brightness as circled in picture below.

For circle like icons, from left to like, they look like 100% circle, 75% circle, 25% circle.

For sun like icons, from left to right, they look like 25% dark, no dark, 50% dark. The last is 100% dark but with white in middle.

![image](https://user-images.githubusercontent.com/40143136/150679837-f5ac8f5d-df3a-42c2-b3e1-f791aed319c7.png)

Here I request three icons:

- 50% of the circle
- 75% dark
- 100% dark follows the first three.

### Give us an example of what this icon might look like.

For 50% of the circle:

![image](https://user-images.githubusercontent.com/40143136/150679920-ad22d493-b21e-4573-a348-b702c7e9ffef.png)

For 75% dark:

![image](https://user-images.githubusercontent.com/40143136/150679582-d8ea0f3d-570e-4b6f-a063-da887019509d.png)

For 100% dark:

![image](https://user-images.githubusercontent.com/40143136/150679539-32be595b-fdfb-489b-bf6c-e0278e94d9b7.png)

**Comment by goyney** [comment]
I think there's a little bit of a misunderstanding of what these brightness icons actually represent.

- `brightness-1` is completely dark.
- `brightness-4` is 50%.
- `brightness-7` is completely bright.

---

Now, let's look at the three icons you're requesting and how we can fulfill those:

- 50% of the circle. We already have this as `circle-half`. You'll need to apply a horizontal flip to it to have it match your example.
- 75% of an octagram. We already have this as `brightness-4`. You'll also need to apply a horizontal flip to have it match your example.
- 100% dark. Just to be clear here, this would actually mean 100% bright, and that's indicated by using `brightness-7`. If you are looking for just a simple octagram, we also have that as `octgram`, but if you need it to match the other brightness' orientation, you'll need to rotate the icon 12.5%.

---

In terms of new icons, we're not going to add a rotated or flipped variant of `circle-half` or `octagram`, so those will be on you to transform. The flipped 75% is an interesting use case, but because of the numeric naming scheme, adding an additional step would be a major breaking change for a niche use case that I don't think we want to get into. Since you need to transform the other two, I'd just do that as well.

I hope this write-up helps why we're going to reject this request at this time. We do appreciate your suggestion though!
