### ISSUE TITLE
Temperatire outside home

### ISSUE THREAD

**Issue by nunoladeiro** [Templarian/MaterialDesign#6484]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

The same as "home-thermometer" but with a thermometer outside the house, representing the temperature outside.

### Give us an example of what this icon might look like.

The same as "home-thermometer" but with a thermometer outside the house.

**Comment by boehan** [comment]
Maybe `sun-thermometer` already fits your needs. Otherwise here are some suggestions (not sure about the naming though).
![grafik](https://user-images.githubusercontent.com/7279415/157085405-509b912b-c6dd-4ccf-89f2-60de72f1ecda.png)
![grafik](https://user-images.githubusercontent.com/7279415/157085445-8e9aa934-668b-46e4-88fb-3f191e24aafb.png)
![grafik](https://user-images.githubusercontent.com/7279415/157088205-8586fad6-324d-4dd4-8e58-f3f8033dbc5f.png)

However, this also made me rethink the `home-thermometer` icons, since the small thermometer looks more like a upside-down keyhole and I think the thermometer should be in the primary focus...
![grafik](https://user-images.githubusercontent.com/7279415/157089461-2ac042d8-f633-4885-a68b-32c8da629290.png)
![grafik](https://user-images.githubusercontent.com/7279415/157088951-28ec2de3-7b50-4280-899c-34470a22aa60.png)

BTW, I used the thermometer symbol from `sun-thermometer`, which has some issues with alignment. I will open an extra issue on that and correct it here if the icons are considered worth adding.

**Comment by goyney** [comment]
The idea of the home/thermometer combo was rejected here: https://github.com/Templarian/MaterialDesign/issues/5149#issuecomment-627131193

This is a duplicate issue of that one, and so we're going to close this for the same reasons.

**Comment by nunoladeiro** [comment]
Well, if you ask me, I really love all of them even if for e the temperature-outdoor will better serve my porpose.
