### ISSUE TITLE
Icon for Google Apps Script

### ISSUE THREAD

**Issue by MichelHazuky** [Templarian/MaterialDesign#6529]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Anyone interested in creating an icon for Google Apps Script?

### Give us an example of what this icon might look like.

https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_Apps_Script.svg/512px-Google_Apps_Script.svg.png

**Comment by goyney** [comment]
This would be borderline a brand icon, if not actually a brand icon. It's very niche too because it doesn't represent a script like our `script` icons do.
[![script-text](https://materialdesignicons.com/icon/script-text)](https://materialdesignicons.com/icon/script-text)

It's also very similar to `palette-swatch-variant`.
[![palette-swatch-variant](https://materialdesignicons.com/icon/palette-swatch-variant)](https://materialdesignicons.com/icon/palette-swatch-variant)

**Comment by Templarian** [comment]
Making this one as a brand. There are generic icons that work nicer for "scripts" or "swatch".
