### ISSUE TITLE
Phillips Hue Dimmer & Tap Switch Icon

### ISSUE THREAD

**Issue by oneseventhree** [Templarian/MaterialDesign#6551]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Home Assistant. A 4 button icon would do the trick and a circle with 3 smaller circles like the examples below.

### Give us an example of what this icon might look like.

Dimmer switch: https://thenounproject.com/icon/phillips-hue-dimmer-switch-2731264/
Tap switch: https://thenounproject.com/icon/hue-tap-250708/

**Comment by goyney** [comment]
The four up might be doable, but the other one is very device specific and we don't add device specific icons.

**Comment by nagyrobi** [comment]
Also see https://github.com/arallsopp/hass-hue-icons

**Comment by goyney** [comment]
We're going to pass on these because they are vendor and device specific, which we generally steer away from. There are more generic icons that can be used.

You may also look at @nagyrobi's suggestion. There are a few icon libraries with device specific icons available and installable via HACS inside Home Assistant that can be used side-by-side with the official MDI set.

Thanks for the suggestion.
