### ISSUE TITLE
Rename `text-to-speech` to `microphone-message`

### ISSUE THREAD

**Issue by nagyrobi** [Templarian/MaterialDesign#6555]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

![tts](https://user-images.githubusercontent.com/1550668/164617071-f83f02b5-07dd-45a1-ac19-d9d1847a66c1.png) ![ttsoff](https://user-images.githubusercontent.com/1550668/164618483-3728d6bb-a9c4-4dc7-b46f-b652d4c53c58.png)

This icon is incorrectly named as `text-to-speech`. It should be named `speech-to-text`.

_speech-to-text_ marks the technology needed to capture audio and recognize the speech transforming it in written text.
_text-to-speech_ marks the reverse of this, is technology needed to transform written text to audible speech

When representing these, a good approach is to look at the interface which is closest to the users. For _speech-to-text_ this is a microphone, as usually the user speaks into a microphone in order for the speech to be recognized by a system. For _text-to-speech_ this is a speaker, as the text transformed to speech is usually played out via speakers. 

So the icon above representing a microphone with a bubble is more appropriate for `speech-to-text`.

For `text-to-speech` I suggest to create a version based on `speaker-wireless`, where the waves on the right are replaced by the bubble fom `cellphone-message`, something like below:

![kép](https://user-images.githubusercontent.com/1550668/164619688-082e6e70-a36d-4db1-a84d-3f2d9ea97335.png)
(no need for an _off_ version imho)

Tag should also be `tts`.

Use case is for a Home Automation system where the speaker icons associated to media players change based on what the player does. Playing out a TTS message via speakers looks very strange (and concerning) while showing a microphone...

**Comment by goyney** [comment]
Thanks for the feedback. This really isn't a bug though, but a request to rename an existing icon. (Just for further reference. :smile:)

That being said, I think the icon is named too literal to begin with. I would prefer to see the current `text-to-speech` icons renamed to something more generic, such as `microphone-message` (following a pattern we begun with `cellphone-message`). We can then add new `speaker-message(-off)` icons.

Because an icon rename is a breaking change, this won't happen until v7, which is a few releases away. I'm going to repurpose this issue to handle the icon rename of `text-to-speech` and I opened a new issue to track adding the speaker: #6557.

**Comment by goyney** [comment]
In this issue, we will rename:
- [ ] `text-to-speech` ➜ `microphone-message`
- [ ] `text-to-speech-off` ➜ `microphone-message-off`

**Comment by nagyrobi** [comment]
Thank you.

**Comment by goyney** [comment]
Completed.
