### ISSUE TITLE
Drop with numbers for humidity level

### ISSUE THREAD

**Issue by pico1881** [Templarian/MaterialDesign#6630]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I want to use those icon for setting humidity level in  Home Assistant card

### Give us an example of what this icon might look like.

Existing water-outline icon with numbers 1, 2, 3, similar to the fan Speed icons

**Comment by goyney** [comment]
The reason the fan icon uses the numeric 1, 2, and 3 is to avoid a language issue with Low, Medium, and High, which are standard fan operating speeds.

I have personally have 2 standalone humidifiers and a whole home humidifier, and each of them set their levels in percentages ranging from 15 to 50 percent. That being said, this seems to be a very niche use cases because we cannot solve all scenarios like we can with the very standardized fan icons.

Because we cannot solve this use case universally, I don't feel we should add these.

**Comment by goyney** [comment]
We're going to pass on these at this time. Thanks for the suggestion.
