### ISSUE TITLE
Eyedropper icons have modifiers in non-standard location

### ISSUE THREAD

**Issue by daavko** [Templarian/MaterialDesign#6660]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

From what I understand, icon modifiers (`-plus`, `-remove`, etc.) are primarily put on the bottom right of the icon, unless there's a good reason to put them elsewhere. With the eyedropper icon, there is plenty of space on the bottom right, but the modifiers are all in the top left corner. Is this intended?

Example of what I mean (`plus` in the top left corner, but plenty of space in the bottom right):
![eyedropper-plus](https://user-images.githubusercontent.com/7669061/174785256-41d50e48-842c-4d47-978f-5c9cdbf161b4.png)

**Comment by daavko** [comment]
Noticed the same issue in `pen` and `pencil` icons. `pen` has a protruding part that might interfere with modifiers in the bottom right, but `pencil` has plenty of space.

**Comment by goyney** [comment]
These all are intentional, namely because of the issue `pen` has. Breaking that with the circular cutout makes it less clear that it is a pen. Pencil follows suit since the two are interchangeable. Eyedropper follows because of it's angular orientation. We don't wish to change these at this time. Thanks for the note though.
