### ISSUE TITLE
Icon for Clipping (Scissors)

### ISSUE THREAD

**Issue by lachlanjc** [Templarian/MaterialDesign#668]

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/content-cut ?

**Comment by lachlanjc** [comment]
Oh thanks! I had searched for `scissors` and `clip` but didn't find that. Maybe we can add some keywords?

**Comment by Templarian** [comment]
- [ ] add alias `scissors` `clip` to content-cut 

Details: Almost done re-coding the alias UI for the icon platform. Aliases no longer need to be unique also, so we will be able label various icons with similar names in the search results.

**Comment by lachlanjc** [comment]
👍

**Comment by Templarian** [comment]
Done. :smile:

**Comment by CoDEmanX** [comment]
> Aliases no longer need to be unique also, so we will be able label various icons with similar names in the search results.

You mean different icons can have the very same alias? Isn't that confusing? And a problem if you want to refer to an icon by its alias in CSS or similar?

**Comment by Templarian** [comment]
Aliases are not exported in CSS so it's fine. Think of aliases as more of alternative names to just help searching.

**Comment by CoDEmanX** [comment]
I see. So what's the difference between aliases and tags then?

**Comment by Templarian** [comment]
Tags are groupings of icons. They don't affect the searching.

Eventually I'll introduce the subset feature that will allow more category grouping of icons (social, brand, WYSIWYG editor, etc...).

**Comment by CoDEmanX** [comment]
I see. So poly-hierarchal groups via tags as icon "categories", and aliases like search "tags" ("alias" is a bit confusing, because they don't identify an individual icon). How do you feel about renaming them?

Tags > Categories
Aliases > Tags

It would be nice to have a view of all icons grouped by category (icons may appear more than once if they have more than one category / tag), similar to how Google does it, or FontAwesome.

**Comment by lachlanjc** [comment]
👍
