### ISSUE TITLE
Release version for icon

### ISSUE THREAD

**Issue by andrejsharapov** [Templarian/MaterialDesign#6692]
### What is your question?

It seems to me that in the details of the icon, the site is missing the version in which the icon was released. `Released in v6.1.95` or `Not released / Uncoming release`.

![image](https://user-images.githubusercontent.com/44722574/177977097-44df2da1-5b8f-4433-bd39-8c9a69e07128.png)
Some icons have already been added to the library only on the site (Uncoming release...). In this case, they will not be displayed to the user during install and this may raise a number of questions. For example, https://github.com/Templarian/MaterialDesign/issues/6680 icon has already been added, but I can't use it in my projects.

**Comment by goyney** [comment]
We're not making changes to the old site at this time [since a new site is in development](https://github.com/Templarian/MaterialDesign/issues/5161).

That being said, I still took a look at the told code to see if this would be quick to add just because we do occasionally get questions asking about icons that have not yet been released. However, it is not a trivial change, and in the structure of the old site, would likely add even more lag to an already slow site. Therefore, we're not going to do it.

**Comment by andrejsharapov** [comment]
Ok. :smile: Thx!
