### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Azbolg** [Templarian/MaterialDesign#6957]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Missing a discord icon

### Give us an example of what this icon might look like.

https://logos-world.net/wp-content/uploads/2020/12/Discord-Logo.png

**Comment by mririgoyen** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: https://pictogrammers.com/docs/library/mdi/guides/brand-icons/
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by Polda18** [comment]
With utmost respect, I would actually like to use a Discord icon on our Minecraft server wiki, powered by Wiki.js using this library for link icons. Discord icon is missing for some reason, not sure why. Wiki.js actually uses 3 libraries, where Discord icon can be found in Font Awesome v5 library, but this is the only thing I'd be using from it, and sadly I can't combine two libraries, I have to choose. I really like MDI icons, they're modern, and they look great. If I could add a custom icon, I would do that. However that's not possible. I had to find a similar looking icon of a gamepad (because Discord brand logo does kinda look like a gamepad). But it's not the same. Decision to not accept brand logo submissions anymore kinda restricts users.
