### ISSUE TITLE
Tilting window open/close

### ISSUE THREAD

**Issue by martinmoravek** [Templarian/MaterialDesign#7064]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

for displaying opened/closed tilting window

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/14981833/230732341-d8075ecf-e16e-4b52-9e11-31adf0cb24a6.png)
![image](https://user-images.githubusercontent.com/14981833/230732364-0213a90c-3481-4012-82cb-3fec47641190.png)

**Comment by MrGrigri** [comment]
Because of the rules for Material Design, we cannot design an icon with that type of perspective. We do have `window-open` and `window-closed`. I'm going to suggest this be closed.

![window-open](https://user-images.githubusercontent.com/4528551/231002373-6b25adad-a1c7-40c0-a59f-8fe34a01e8da.png) ![window-closed](https://user-images.githubusercontent.com/4528551/231002511-c27307d6-0d8f-4447-9585-88a3e85d700d.png)

**Comment by mririgoyen** [comment]
We cannot add icons the show perspective. This has been suggested and requested multiple times in the past. I'm sorry we are unable to fulfill this request in this library.

**Comment by caco3** [comment]
This is a pity since AFAIK the windows as shown here are only used in the US, but there are many more countries in the world, eg. in Europe who have other window types.
