### ISSUE TITLE
Bower packages not in-sync with website?

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#711]
I've noticed that the font files I get through bower differ from the display on the website. For instance, the Google+ logo is still the old one, whereas the website shows a new one.

**Comment by Templarian** [comment]
There is a short quality control time between releases. It just happens that Google replaced their logo right after the last release. The next release should be within about a week.

Usually isn't not too big of an issue since it's new icons, but yea, little annoying since they replaced their own logo. I'll close this issue once the new release it out.

**Comment by derwaldgeist** [comment]
Thanks for this info!
