### ISSUE TITLE
Do not mix OFL and other licenses

### ISSUE THREAD

**Issue by davelab6** [Templarian/MaterialDesign#779]
This is not legal advice:

The SIL OFL says, emphasis mine,

> 5) The Font Software, modified or unmodified, in part or in whole, must be distributed entirely under this license, and **must not be distributed under any other license.**

I suggest that this means that one can not mix OFL licensed work with work available under any other license, including CC-BY, into a single 'combined' work, such mixing icons under various licensed into a single font file.

Since this project starts with CC-BY licensed works from Google, I recommend using CC-BY; however, that doesn't have copyleft, so CC-BY-SA is probably the most similar to the OFL.

**Comment by adrientetar** [comment]
cc @n7s

**Comment by Templarian** [comment]
This came about due to Google changing their license 9'ish months ago. Yea, I've been kind of unsure how this adopts well into SIL since it has two licenses.

You'll have to agree to the to both licenses while using the icon pack for now. I will eventually be distributing the icons in two separate icon packs. One without the stock icons included.

This will be solved shortly after #644 is completed.

**Comment by davelab6** [comment]
For TruFont, since we include some individual SVG icons from Google, and some icons that you personally drew (AFAIK), do you agree that we can be specific that the G SVGs are CC-BY and your SVGs are OFL?

**Comment by Templarian** [comment]
That is a 100% correct. Sorry for the confusion. I have a laundry list of things I need to do, but *eventually* making a nice license explanation page will be one of my tasks.

**Comment by davelab6** [comment]
Thanks for confirming! Great project, good luck!! :)
