### ISSUE TITLE
New icon: cash register

### ISSUE THREAD

**Issue by fredericoregateiro** [Templarian/MaterialDesign#850]
Something like this:
![Icon of cash register](http://icons.iconarchive.com/icons/icons8/ios7/512/Ecommerce-Cash-Register-icon.png)

**Comment by CoDEmanX** [comment]
It would need to be more like in these examples:

![cash-register-128](https://cloud.githubusercontent.com/assets/1309249/11281808/959b5a2a-8efc-11e5-9d36-9e48333762c1.png)
![1368373925905577011cash-register](https://cloud.githubusercontent.com/assets/1309249/11281809/959bc636-8efc-11e5-833c-ff940be460d0.jpg)

but I doubt it's possible to make it legible at 24px...

**Comment by TheManuz** [comment]
Much time has passed, but I've done it, mostly because i needed this!
![cash_register_24px](https://cloud.githubusercontent.com/assets/2032334/15360451/ea4e82f0-1d0d-11e6-9362-a3312cf469b2.png)
[Cash_register_24px.svg.zip](https://github.com/Templarian/MaterialDesign/files/270577/Cash_register_24px.svg.zip)

**Comment by Templarian** [comment]
@TheManuz Once you hit 5 icons I'll create a contributor account. Until then assigning to the shared contributor account. Trying to get through the large backlog as we cut down the issues.

[![cash-register](https://materialdesignicons.com/icon/cash-register)](https://materialdesignicons.com/icon/cash-register)
