### ISSUE TITLE
Request: surprise/random/shuffle

### ISSUE THREAD

**Issue by passsy** [Templarian/MaterialDesign#866]
I want an icon which triggers an action and shows a random entry from my database.

But I have no idea how it could look like

**Comment by Templarian** [comment]
Maybe one of the `dice-*` icons or `reload`. Not entirely sure, which would be best.

**Comment by CoDEmanX** [comment]
What kind of entry does it fetch? A tip of the day? A product on sale? A random dating partner?

I wouldn't use an icon like our shuffle icon, because a click doesn't trigger a shuffle/randomization as primary action. If it gives you random user profiles for instance, don't use any icon that represents a dead object. Otherwise dice* icons are fine. I would prefer the reload icon however.

If it's actually a random hint, you may use a light bulb icon - so something that symbolizes the **what**, not the **how**.

**Comment by passsy** [comment]
@CoDEmanX great ideas, thank you so much!

It's a random dish from a menu of a restaurant. I should have mentioned that. It should be used when the user (me) is too lazy to choose something for lunch.
I think I'll go with the [dice](https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/dice.svg) 

I was also thinking about a magic wand

**Comment by CoDEmanX** [comment]
Probably too specific for MDI, but maybe you want use this anyway:
![auto-meal](https://cloud.githubusercontent.com/assets/1309249/11408296/6e77288c-93b8-11e5-9030-364ea4c2d06a.png) ![auto-meal_96px](https://cloud.githubusercontent.com/assets/1309249/11408297/6e8d8898-93b8-11e5-91e0-5bfe92be4a43.png) https://www.dropbox.com/s/c5m84nep8dyn9fw/auto-meal.svg?dl=0
