### ISSUE TITLE
 Icon sms

### ISSUE THREAD

**Issue by amfp** [Templarian/MaterialDesign#912]
Icon representing the SMS

**Comment by CoDEmanX** [comment]
There are several icons that stand for text-based messages, such as https://materialdesignicons.com/icon/message-text. Do you want to distinguish between SMS and other messaging systems?

**Comment by amfp** [comment]
thanks!

**Comment by CoDEmanX** [comment]
Maybe like this?

![message-text](https://cloud.githubusercontent.com/assets/1309249/11915923/7008888c-a6bc-11e5-93f3-66f58dd2d1bc.png)
![message-sms-outline](https://cloud.githubusercontent.com/assets/1309249/11915924/70138c5a-a6bc-11e5-9e93-039c516e20d0.png)

The outline version isn't all that great, because the text cannot be centered properly. It's less apparent in the filled version.

**Comment by amfp** [comment]
Perfect! wonderful!
Thank you!

**Comment by Templarian** [comment]
Yea, I think just the filled version should be added. Wish there was a way to represent this without the text, but can't think of anything.

**Comment by samlemarnais** [comment]
That could be a phone with this a bubble poping out from it?

**Comment by PeterShaggyNoble** [comment]
Google use `message-processing` for [`sms`](https://material.io/icons/#ic_sms).

[![message-processing](https://user-images.githubusercontent.com/15157491/35511527-302fff36-04f4-11e8-879e-d6dd01349bd8.png)](https://materialdesignicons.com/icon/message-processing)

**Comment by CoDEmanX** [comment]
Do we really need a specific SMS icon? We have plenty of message icon variants.

**Comment by JamesCoyle** [comment]
Most apps just add the text `SMS` under the `send` or `message` icon. Gonna close this unless someone can come up with something better.
