### ISSUE TITLE
404 icon

### ISSUE THREAD

**Issue by Muhammadmateen** [Templarian/MaterialDesign#917]
need 404 icon for bad request?

**Comment by CoDEmanX** [comment]
400 is bad request, 404 is not found. Either way, why don't you use one of the alert  or close icons?

**Comment by Templarian** [comment]
There hasn't been any new information for a while. Closing issue, please reopen if this icon is still needed.

**Comment by epelc** [comment]
@Templarian Can you reopen? I think a `404 not found` type icon would be useful.

**Comment by Templarian** [comment]
@epelc Do you have an example of what this would be? This was mostly closed out because we didn't have any information what the icon would look like (we really don't like to include text/numbers, so it would need to be a symbol).

**Comment by epelc** [comment]
@Templarian Sorry, I thought it was closed because of the confusion between 400 and 404. I don't really know what one would look like(especially given the no text/numbers rule). I couldn't find one after some searching either. Never mind my request unless someone can figure out what this might look like.

BTW thanks for the quick response! You are really on top of this project.
