### ISSUE TITLE
Google Adwords icon

### ISSUE THREAD

**Issue by garethrbrown** [Templarian/MaterialDesign#919]
https://www.google.com/search?q=adwords+logo&%7Bgoogle:acceptedSuggestion%7Doq=adwords+logo&aqs=chrome..69i57.2991j0j7&sourceid=chrome&ie=UTF-8

**Comment by CoDEmanX** [comment]
It doesn't have a very recognizable silhouette... I can only think of a counter stroke to make it two distinct areas to convey the "fold" in the original logo, but not sure if they allowed this kind of modification.

**Comment by PeterShaggyNoble** [comment]
There's an official AdWords icon in Google's "GMP Icons" font:

![gmp adwords](https://user-images.githubusercontent.com/15157491/38263192-4d5f0eda-3767-11e8-8a0a-8dc107397b56.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48988573-3a8ff700-f0f4-11e8-9c99-4d8d5332830f.png)
[google-adwords.zip](https://github.com/Templarian/MaterialDesign/files/2613807/google-adwords.zip)

**Comment by Templarian** [comment]
[![google-adwords](https://materialdesignicons.com/icon/google-adwords)](https://materialdesignicons.com/icon/google-adwords)

**Comment by JamesCoyle** [comment]
Should this have really been added as Adwords is no longer a thing? Maybe we should replace it with the Google Ads logo.

![image](https://user-images.githubusercontent.com/10384436/49439960-582b2380-f7ba-11e8-865b-ba1da193fd2b.png)

**Comment by CoDEmanX** [comment]
I re-created the shapes based on the SVG found on Wikipedia, which was apparently traced because there are quite a lot vertices. Do they even allow monochrome versions of their logo?

![grafik](https://user-images.githubusercontent.com/1309249/53646160-c86f0700-3c3a-11e9-870f-69f8078112d3.png)
![grafik](https://user-images.githubusercontent.com/1309249/53646963-c312bc00-3c3c-11e9-8c21-f3f669fb0a21.png)
![grafik](https://user-images.githubusercontent.com/1309249/53646984-d02fab00-3c3c-11e9-8b89-150c2d45e2d8.png)
![grafik](https://user-images.githubusercontent.com/1309249/53647020-e0478a80-3c3c-11e9-9f62-abdbf50b7b18.png)

[google-ads.zip](https://github.com/Templarian/MaterialDesign/files/2919954/google-ads.zip)
