### ISSUE TITLE
Laptop icon names mixed up

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#971]
Current name | Needs to be renamed to
:--|:--
laptop-windows | laptop-chromebook
laptop-chromebook | laptop-mac
laptop-mac | laptop-windows

**Comment by Templarian** [comment]
Fixed. Since there is already a generic `laptop` icon. I made the `laptop-windows` a Surface Pro. :confused: 

[![laptop-windows](https://materialdesignicons.com/icon/laptop-windows)](https://materialdesignicons.com/icon/laptop-windows) [![laptop](https://materialdesignicons.com/icon/laptop)](https://materialdesignicons.com/icon/laptop)
