### ISSUE TITLE
material gauge for appbar

### ISSUE THREAD

**Issue by ChetOrton** [Templarian/MaterialDesign#974]
I would like a series of perhaps 11 icons to represent from 0-100% in 10% increments on the app bar (action bar/toolbar). I'm thinking of something very simple. It would have a hand, like the hand on an analog clock. It wouldn't be a full circle, just a quarter circle. The hand would sweep up in a clockwise direction from totally horizontal (0%) to totally vertical (100%). Maybe add a few tick marks on the arc's path, like on an analog clock that has tick marks instead of numbers.

**Comment by Templarian** [comment]
This is probably too niche of an icon set to justify 11 new icons.

Probably best to use the standard https://materialdesignicons.com/icon/gauge icon with some other indicator.

**Comment by ChetOrton** [comment]
That gauge’s position is static. That is, it doesn’t communicate any value. t want a general-purpose gauge to communicate a changing measurement of something, sort of like the battery icons that show how much of a charge you’ve got. Only more general-purpose. I would replace the icon on the app bar as the value changed from 0% to 10% to 20% etc.

**Comment by Templarian** [comment]
I get the purpose, but it's a little too specific. Not every icon idea, even if it makes sense in some very specific scenarios can be added. Still trying to keep a majority of the icons as generalized as possible. This means many times representing a set of icons with a single icon.

I've broke this exception for only a few scenarios (dice for instance). The rest are due to them being included in the stock icon pack provided by Google.
