### ISSUE TITLE
WiFi icon status

### ISSUE THREAD

**Issue by Imp5pa** [Templarian/MaterialDesign#996]
Create lollipop WiFi statuses

**Comment by CoDEmanX** [comment]
Can you add a picture? Just wanna make sure we talk about the system icons for WiFi signal...

**Comment by Imp5pa** [comment]
<img src=http://img.djpw.cz/jkd.png>

**Comment by CoDEmanX** [comment]
Alright. The problem here with most of them is, that they use transparency (displayed as grey). Transparency / multiple colors are not supported in (web) fonts, at least as far as I know.

Those icons are not listed on Google's icon site, most certainly because they are not monochrome / opaque. They exist in their icon repository however.

I tried to overcome this with these icons: https://github.com/Templarian/MaterialDesign/issues/827#issuecomment-155913927

**Comment by not7CD** [comment]
I would definitely push outline version. Since we lack good options here.

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #586.
